"""
Seeker (Pre-A1) level data — topics 16-30
"""

SEEKER_TOPICS_16_30 = [
    {
        "id": "wild-animals",
        "name": "Động Vật Hoang Dã",
        "emoji": "🦁",
        "color": "amber",
        "words": [
            {"word": "lion", "meaning": "sư tử", "emoji": "🦁", "class": "n", "examples": [{"en": "The lion is very big.", "vi": "Con sư tử rất to."}, {"en": "A lion roars loudly.", "vi": "Sư tử gầm to lắm."}]},
            {"word": "tiger", "meaning": "hổ", "emoji": "🐯", "class": "n", "examples": [{"en": "The tiger has stripes.", "vi": "Con hổ có những sọc vằn."}, {"en": "Tigers are orange and black.", "vi": "Hổ màu cam và đen."}]},
            {"word": "elephant", "meaning": "voi", "emoji": "🐘", "class": "n", "examples": [{"en": "The elephant is very big.", "vi": "Con voi rất to."}, {"en": "Elephants have long noses.", "vi": "Voi có vòi rất dài."}]},
            {"word": "monkey", "meaning": "khỉ", "emoji": "🐒", "class": "n", "examples": [{"en": "The monkey climbs trees.", "vi": "Con khỉ leo cây."}, {"en": "Monkeys eat bananas.", "vi": "Khỉ ăn chuối."}]},
            {"word": "bear", "meaning": "gấu", "emoji": "🐻", "class": "n", "examples": [{"en": "The bear is brown.", "vi": "Con gấu màu nâu."}, {"en": "Bears like honey.", "vi": "Gấu thích mật ong."}]},
            {"word": "giraffe", "meaning": "hươu cao cổ", "emoji": "🦒", "class": "n", "examples": [{"en": "The giraffe has a long neck.", "vi": "Hươu cao cổ có cái cổ dài."}, {"en": "Giraffes eat leaves.", "vi": "Hươu cao cổ ăn lá cây."}]},
            {"word": "zebra", "meaning": "ngựa vằn", "emoji": "🦓", "class": "n", "examples": [{"en": "The zebra has black and white stripes.", "vi": "Ngựa vằn có sọc đen và trắng."}, {"en": "Zebras run very fast.", "vi": "Ngựa vằn chạy rất nhanh."}]},
            {"word": "crocodile", "meaning": "cá sấu", "emoji": "🐊", "class": "n", "examples": [{"en": "The crocodile is in the river.", "vi": "Con cá sấu ở trong sông."}, {"en": "Crocodiles have sharp teeth.", "vi": "Cá sấu có răng sắc nhọn."}]},
            {"word": "snake", "meaning": "rắn", "emoji": "🐍", "class": "n", "examples": [{"en": "The snake is long.", "vi": "Con rắn rất dài."}, {"en": "Some snakes are dangerous.", "vi": "Một số con rắn nguy hiểm."}]},
            {"word": "wolf", "meaning": "sói", "emoji": "🐺", "class": "n", "examples": [{"en": "The wolf howls at night.", "vi": "Con sói tru vào ban đêm."}, {"en": "Wolves live in the forest.", "vi": "Sói sống trong rừng."}]},
            {"word": "fox", "meaning": "cáo", "emoji": "🦊", "class": "n", "examples": [{"en": "The fox is orange.", "vi": "Con cáo màu cam."}, {"en": "The fox is clever.", "vi": "Con cáo rất ranh mãnh."}]},
            {"word": "deer", "meaning": "hươu", "emoji": "🦌", "class": "n", "examples": [{"en": "The deer runs in the forest.", "vi": "Con hươu chạy trong rừng."}, {"en": "Deer eat grass.", "vi": "Hươu ăn cỏ."}]},
            {"word": "panda", "meaning": "gấu trúc", "emoji": "🐼", "class": "n", "examples": [{"en": "The panda is black and white.", "vi": "Con gấu trúc màu đen và trắng."}, {"en": "Pandas eat bamboo.", "vi": "Gấu trúc ăn tre."}]},
            {"word": "koala", "meaning": "gấu koala", "emoji": "🐨", "class": "n", "examples": [{"en": "The koala sleeps on a tree.", "vi": "Con koala ngủ trên cây."}, {"en": "Koalas eat leaves.", "vi": "Koala ăn lá cây."}]},
            {"word": "penguin", "meaning": "chim cánh cụt", "emoji": "🐧", "class": "n", "examples": [{"en": "The penguin is black and white.", "vi": "Chim cánh cụt màu đen và trắng."}, {"en": "Penguins swim in the sea.", "vi": "Chim cánh cụt bơi trong biển."}]},
        ]
    },
    {
        "id": "sea-creatures",
        "name": "Sinh Vật Biển",
        "emoji": "🌊",
        "color": "blue",
        "words": [
            {"word": "shark", "meaning": "cá mập", "emoji": "🦈", "class": "n", "examples": [{"en": "The shark is in the sea.", "vi": "Cá mập ở trong biển."}, {"en": "Sharks swim very fast.", "vi": "Cá mập bơi rất nhanh."}]},
            {"word": "whale", "meaning": "cá voi", "emoji": "🐋", "class": "n", "examples": [{"en": "The whale is very big.", "vi": "Con cá voi rất to."}, {"en": "Whales live in the ocean.", "vi": "Cá voi sống ở đại dương."}]},
            {"word": "dolphin", "meaning": "cá heo", "emoji": "🐬", "class": "n", "examples": [{"en": "Dolphins are very smart.", "vi": "Cá heo rất thông minh."}, {"en": "I see a dolphin jump.", "vi": "Tôi thấy cá heo nhảy lên."}]},
            {"word": "crab", "meaning": "cua", "emoji": "🦀", "class": "n", "examples": [{"en": "The crab has big claws.", "vi": "Con cua có càng to."}, {"en": "Crabs walk sideways.", "vi": "Cua bò ngang."}]},
            {"word": "turtle", "meaning": "rùa biển", "emoji": "🐢", "class": "n", "examples": [{"en": "The turtle swims slowly.", "vi": "Con rùa bơi chậm chậm."}, {"en": "Turtles have hard shells.", "vi": "Rùa có mai cứng."}]},
            {"word": "jellyfish", "meaning": "sứa", "emoji": "🪼", "class": "n", "examples": [{"en": "The jellyfish is in the sea.", "vi": "Con sứa ở trong biển."}, {"en": "Jellyfish can sting.", "vi": "Sứa có thể đốt."}]},
            {"word": "octopus", "meaning": "bạch tuộc", "emoji": "🐙", "class": "n", "examples": [{"en": "The octopus has eight arms.", "vi": "Con bạch tuộc có tám xúc tu."}, {"en": "Octopus can change color.", "vi": "Bạch tuộc có thể đổi màu."}]},
            {"word": "lobster", "meaning": "tôm hùm", "emoji": "🦞", "class": "n", "examples": [{"en": "The lobster is red.", "vi": "Con tôm hùm màu đỏ."}, {"en": "Lobsters live in the sea.", "vi": "Tôm hùm sống dưới biển."}]},
            {"word": "starfish", "meaning": "sao biển", "emoji": "⭐", "class": "n", "examples": [{"en": "The starfish has five arms.", "vi": "Con sao biển có năm cánh."}, {"en": "Starfish live on the sea floor.", "vi": "Sao biển sống dưới đáy biển."}]},
            {"word": "seal", "meaning": "hải cẩu", "emoji": "🦭", "class": "n", "examples": [{"en": "The seal can swim well.", "vi": "Hải cẩu bơi rất giỏi."}, {"en": "Seals live near the sea.", "vi": "Hải cẩu sống gần biển."}]},
            {"word": "shrimp", "meaning": "tôm", "emoji": "🦐", "class": "n", "examples": [{"en": "I eat shrimp for dinner.", "vi": "Tôi ăn tôm vào bữa tối."}, {"en": "The shrimp is pink.", "vi": "Con tôm màu hồng."}]},
            {"word": "squid", "meaning": "mực", "emoji": "🦑", "class": "n", "examples": [{"en": "The squid has ten arms.", "vi": "Con mực có mười xúc tu."}, {"en": "I eat fried squid.", "vi": "Tôi ăn mực chiên."}]},
            {"word": "clam", "meaning": "nghêu/sò", "emoji": "🐚", "class": "n", "examples": [{"en": "I find a clam at the beach.", "vi": "Tôi tìm thấy con nghêu ở bãi biển."}, {"en": "Clams live in the sand.", "vi": "Nghêu sống trong cát."}]},
            {"word": "seahorse", "meaning": "cá ngựa", "emoji": "🐠", "class": "n", "examples": [{"en": "The seahorse is small.", "vi": "Cá ngựa rất nhỏ."}, {"en": "Seahorses swim slowly.", "vi": "Cá ngựa bơi chậm."}]},
            {"word": "eel", "meaning": "lươn", "emoji": "🐍", "class": "n", "examples": [{"en": "The eel is long.", "vi": "Con lươn rất dài."}, {"en": "Eels live in the water.", "vi": "Lươn sống dưới nước."}]},
        ]
    },
    {
        "id": "toys-games",
        "name": "Đồ Chơi",
        "emoji": "🧸",
        "color": "pink",
        "words": [
            {"word": "ball", "meaning": "quả bóng", "emoji": "⚽", "class": "n", "examples": [{"en": "I kick the ball.", "vi": "Tôi đá quả bóng."}, {"en": "The ball is round.", "vi": "Quả bóng có hình tròn."}]},
            {"word": "doll", "meaning": "búp bê", "emoji": "🪆", "class": "n", "examples": [{"en": "I have a pretty doll.", "vi": "Tôi có một con búp bê đẹp."}, {"en": "My doll has long hair.", "vi": "Con búp bê của tôi có tóc dài."}]},
            {"word": "kite", "meaning": "diều", "emoji": "🪁", "class": "n", "examples": [{"en": "I fly my kite.", "vi": "Tôi thả diều."}, {"en": "The kite flies high.", "vi": "Con diều bay cao."}]},
            {"word": "puzzle", "meaning": "trò chơi xếp hình", "emoji": "🧩", "class": "n", "examples": [{"en": "I do a puzzle.", "vi": "Tôi chơi xếp hình."}, {"en": "The puzzle has many pieces.", "vi": "Trò chơi xếp hình có nhiều mảnh."}]},
            {"word": "block", "meaning": "khối xây dựng", "emoji": "🧱", "class": "n", "examples": [{"en": "I build with blocks.", "vi": "Tôi xây bằng khối."}, {"en": "The blocks are colorful.", "vi": "Các khối rất nhiều màu sắc."}]},
            {"word": "teddy", "meaning": "gấu bông", "emoji": "🧸", "class": "n", "examples": [{"en": "I hug my teddy.", "vi": "Tôi ôm con gấu bông."}, {"en": "My teddy is soft.", "vi": "Con gấu bông của tôi rất mềm."}]},
            {"word": "marble", "meaning": "bi thủy tinh", "emoji": "🔮", "class": "n", "examples": [{"en": "I play with marbles.", "vi": "Tôi chơi bi."}, {"en": "The marble is round.", "vi": "Viên bi có hình tròn."}]},
            {"word": "drum", "meaning": "trống", "emoji": "🥁", "class": "n", "examples": [{"en": "I play the drum.", "vi": "Tôi đánh trống."}, {"en": "The drum is loud.", "vi": "Tiếng trống rất to."}]},
            {"word": "robot", "meaning": "rô bốt", "emoji": "🤖", "class": "n", "examples": [{"en": "I play with my robot.", "vi": "Tôi chơi với rô bốt."}, {"en": "My robot can walk.", "vi": "Rô bốt của tôi có thể đi."}]},
            {"word": "yo-yo", "meaning": "yo-yo", "emoji": "🪀", "class": "n", "examples": [{"en": "I play with my yo-yo.", "vi": "Tôi chơi yo-yo."}, {"en": "The yo-yo goes up and down.", "vi": "Yo-yo đi lên đi xuống."}]},
            {"word": "sticker", "meaning": "nhãn dán", "emoji": "🏷️", "class": "n", "examples": [{"en": "I put a star sticker on my book.", "vi": "Tôi dán nhãn ngôi sao lên sách."}, {"en": "I love my star stickers.", "vi": "Tôi thích các nhãn dán ngôi sao."}]},
            {"word": "clay", "meaning": "đất nặn", "emoji": "🪣", "class": "n", "examples": [{"en": "I make a cat with clay.", "vi": "Tôi nặn con mèo bằng đất nặn."}, {"en": "Clay is soft.", "vi": "Đất nặn rất mềm."}]},
            {"word": "whistle", "meaning": "còi", "emoji": "🎵", "class": "n", "examples": [{"en": "The teacher blows the whistle.", "vi": "Giáo viên thổi còi."}, {"en": "I have a red whistle.", "vi": "Tôi có một cái còi đỏ."}]},
            {"word": "frisbee", "meaning": "đĩa ném", "emoji": "🥏", "class": "n", "examples": [{"en": "I throw the frisbee.", "vi": "Tôi ném đĩa frisbee."}, {"en": "We play frisbee in the park.", "vi": "Chúng tôi chơi frisbee trong công viên."}]},
            {"word": "spinner", "meaning": "con quay", "emoji": "🌀", "class": "n", "examples": [{"en": "I spin my spinner.", "vi": "Tôi quay con quay."}, {"en": "The spinner goes round and round.", "vi": "Con quay quay tròn mãi."}]},
        ]
    },
    {
        "id": "basic-actions",
        "name": "Hành Động",
        "emoji": "🏃",
        "color": "orange",
        "words": [
            {"word": "run", "meaning": "chạy", "emoji": "🏃", "class": "v", "examples": [{"en": "I run in the park.", "vi": "Tôi chạy trong công viên."}, {"en": "Run fast!", "vi": "Chạy nhanh lên!"}]},
            {"word": "jump", "meaning": "nhảy", "emoji": "🦘", "class": "v", "examples": [{"en": "I jump over the puddle.", "vi": "Tôi nhảy qua vũng nước."}, {"en": "Jump high!", "vi": "Nhảy cao lên!"}]},
            {"word": "walk", "meaning": "đi bộ", "emoji": "🚶", "class": "v", "examples": [{"en": "I walk to school.", "vi": "Tôi đi bộ đến trường."}, {"en": "Walk slowly.", "vi": "Đi chậm thôi."}]},
            {"word": "eat", "meaning": "ăn", "emoji": "🍽️", "class": "v", "examples": [{"en": "I eat rice.", "vi": "Tôi ăn cơm."}, {"en": "Eat your food.", "vi": "Ăn thức ăn đi nào."}]},
            {"word": "drink", "meaning": "uống", "emoji": "🥤", "class": "v", "examples": [{"en": "I drink water.", "vi": "Tôi uống nước."}, {"en": "Drink your milk.", "vi": "Uống sữa đi nào."}]},
            {"word": "sleep", "meaning": "ngủ", "emoji": "😴", "class": "v", "examples": [{"en": "I sleep at night.", "vi": "Tôi ngủ vào ban đêm."}, {"en": "Sleep now.", "vi": "Ngủ đi."}]},
            {"word": "play", "meaning": "chơi", "emoji": "🎮", "class": "v", "examples": [{"en": "I play with my toys.", "vi": "Tôi chơi với đồ chơi."}, {"en": "Let's play together.", "vi": "Cùng chơi nào!"}]},
            {"word": "draw", "meaning": "vẽ", "emoji": "✏️", "class": "v", "examples": [{"en": "I draw a cat.", "vi": "Tôi vẽ một con mèo."}, {"en": "Draw a big circle.", "vi": "Hãy vẽ một hình tròn to."}]},
            {"word": "sing", "meaning": "hát", "emoji": "🎤", "class": "v", "examples": [{"en": "I sing a song.", "vi": "Tôi hát một bài hát."}, {"en": "Let's sing together.", "vi": "Cùng hát nào!"}]},
            {"word": "dance", "meaning": "nhảy múa", "emoji": "💃", "class": "v", "examples": [{"en": "I dance to the music.", "vi": "Tôi nhảy theo nhạc."}, {"en": "She dances very well.", "vi": "Cô ấy nhảy rất giỏi."}]},
            {"word": "swim", "meaning": "bơi", "emoji": "🏊", "class": "v", "examples": [{"en": "I swim in the pool.", "vi": "Tôi bơi trong hồ bơi."}, {"en": "Fish swim in water.", "vi": "Cá bơi trong nước."}]},
            {"word": "kick", "meaning": "đá", "emoji": "🦶", "class": "v", "examples": [{"en": "I kick the ball.", "vi": "Tôi đá quả bóng."}, {"en": "Kick it hard!", "vi": "Đá mạnh vào!"}]},
            {"word": "throw", "meaning": "ném", "emoji": "🤾", "class": "v", "examples": [{"en": "I throw the ball.", "vi": "Tôi ném quả bóng."}, {"en": "Throw it to me!", "vi": "Ném cho tôi đi!"}]},
            {"word": "look", "meaning": "nhìn", "emoji": "👀", "class": "v", "examples": [{"en": "Look at the bird!", "vi": "Nhìn con chim kìa!"}, {"en": "I look out the window.", "vi": "Tôi nhìn ra ngoài cửa sổ."}]},
            {"word": "open", "meaning": "mở", "emoji": "🔓", "class": "v", "examples": [{"en": "Open the door please.", "vi": "Mở cửa ra đi."}, {"en": "I open my bag.", "vi": "Tôi mở cặp ra."}]},
        ]
    },
    {
        "id": "greetings-manners",
        "name": "Chào Hỏi & Lễ Phép",
        "emoji": "🤝",
        "color": "green",
        "words": [
            {"word": "hello", "meaning": "xin chào", "emoji": "👋", "examples": [{"en": "Hello! My name is Lan.", "vi": "Xin chào! Tên tôi là Lan."}, {"en": "Hello, teacher!", "vi": "Xin chào thầy/cô!"}]},
            {"word": "bye", "meaning": "tạm biệt", "emoji": "👋", "examples": [{"en": "Bye! See you tomorrow.", "vi": "Tạm biệt! Hẹn gặp lại nhé."}, {"en": "Bye bye, grandma!", "vi": "Tạm biệt bà!"}]},
            {"word": "please", "meaning": "làm ơn", "emoji": "🙏", "examples": [{"en": "Water please.", "vi": "Cho tôi nước, làm ơn."}, {"en": "Please sit down.", "vi": "Làm ơn ngồi xuống."}]},
            {"word": "sorry", "meaning": "xin lỗi", "emoji": "😔", "examples": [{"en": "Sorry, I am late.", "vi": "Xin lỗi, tôi đến muộn."}, {"en": "I am sorry.", "vi": "Tôi xin lỗi."}]},
            {"word": "welcome", "meaning": "không có gì / chào mừng", "emoji": "🎉", "examples": [{"en": "You are welcome.", "vi": "Không có gì."}, {"en": "Welcome to my home!", "vi": "Chào mừng đến nhà tôi!"}]},
            {"word": "yes", "meaning": "có / vâng", "emoji": "✅", "class": "adv", "examples": [{"en": "Yes, I can do it.", "vi": "Vâng, tôi làm được."}, {"en": "Yes, that is right.", "vi": "Đúng vậy."}]},
            {"word": "no", "meaning": "không", "emoji": "❌", "class": "adv", "examples": [{"en": "No, I do not want that.", "vi": "Không, tôi không muốn."}, {"en": "No, thank you.", "vi": "Không, cảm ơn."}]},
            {"word": "help", "meaning": "giúp đỡ", "emoji": "🆘", "class": "v", "examples": [{"en": "Help me please.", "vi": "Làm ơn giúp tôi với."}, {"en": "I help my mum.", "vi": "Tôi giúp mẹ."}]},
            {"word": "thank", "meaning": "cảm ơn", "emoji": "🙏", "examples": [{"en": "Thank you very much.", "vi": "Cảm ơn rất nhiều."}, {"en": "Thank you for the gift.", "vi": "Cảm ơn vì món quà."}]},
            {"word": "name", "meaning": "tên", "emoji": "🏷️", "class": "n", "examples": [{"en": "My name is Lan.", "vi": "Tên tôi là Lan."}, {"en": "What is your name?", "vi": "Tên bạn là gì?"}]},
            {"word": "meet", "meaning": "gặp gỡ", "emoji": "🤝", "class": "v", "examples": [{"en": "Nice to meet you.", "vi": "Rất vui được gặp bạn."}, {"en": "I meet my friends.", "vi": "Tôi gặp các bạn."}]},
            {"word": "nice", "meaning": "tốt/dễ thương", "emoji": "😊", "class": "adj", "examples": [{"en": "You are very nice.", "vi": "Bạn rất tốt bụng."}, {"en": "Have a nice day!", "vi": "Chúc bạn một ngày tốt lành!"}]},
            {"word": "here", "meaning": "ở đây", "emoji": "📍", "class": "adv", "examples": [{"en": "Come here please.", "vi": "Lại đây đi."}, {"en": "I am here.", "vi": "Tôi ở đây."}]},
            {"word": "give", "meaning": "cho/tặng", "emoji": "🎁", "class": "v", "examples": [{"en": "Give me the book.", "vi": "Đưa sách cho tôi."}, {"en": "I give her a gift.", "vi": "Tôi tặng cô ấy một món quà."}]},
            {"word": "wait", "meaning": "chờ đợi", "emoji": "⏳", "class": "v", "examples": [{"en": "Wait for me!", "vi": "Chờ tôi với!"}, {"en": "Please wait here.", "vi": "Làm ơn chờ ở đây."}]},
        ]
    },
    {
        "id": "daily-routines",
        "name": "Sinh Hoạt Hàng Ngày",
        "emoji": "🌅",
        "color": "yellow",
        "words": [
            {"word": "wake", "meaning": "thức dậy", "emoji": "⏰", "class": "v", "examples": [{"en": "I wake up at seven.", "vi": "Tôi thức dậy lúc bảy giờ."}, {"en": "Wake up, it is morning!", "vi": "Dậy đi, trời sáng rồi!"}]},
            {"word": "wash", "meaning": "rửa/tắm", "emoji": "🚿", "class": "v", "examples": [{"en": "I wash my hands.", "vi": "Tôi rửa tay."}, {"en": "Wash your face.", "vi": "Rửa mặt đi."}]},
            {"word": "brush", "meaning": "chải/đánh", "emoji": "🪥", "class": "v", "examples": [{"en": "I brush my teeth.", "vi": "Tôi đánh răng."}, {"en": "Brush your hair.", "vi": "Chải tóc đi."}]},
            {"word": "wear", "meaning": "mặc/đeo", "emoji": "👕", "class": "v", "examples": [{"en": "I wear my school uniform.", "vi": "Tôi mặc đồng phục đi học."}, {"en": "Wear your jacket.", "vi": "Mặc áo khoác vào."}]},
            {"word": "morning", "meaning": "buổi sáng", "emoji": "🌅", "class": "n", "examples": [{"en": "Good morning!", "vi": "Chào buổi sáng!"}, {"en": "I eat breakfast in the morning.", "vi": "Tôi ăn sáng vào buổi sáng."}]},
            {"word": "school", "meaning": "trường học", "emoji": "🏫", "class": "n", "examples": [{"en": "I go to school every day.", "vi": "Tôi đi học mỗi ngày."}, {"en": "I love my school.", "vi": "Tôi yêu trường tôi."}]},
            {"word": "lunch", "meaning": "bữa trưa", "emoji": "🍱", "class": "n", "examples": [{"en": "I eat lunch at noon.", "vi": "Tôi ăn trưa vào buổi trưa."}, {"en": "I bring lunch to school.", "vi": "Tôi mang cơm hộp đi học."}]},
            {"word": "rest", "meaning": "nghỉ ngơi", "emoji": "💤", "class": "v", "examples": [{"en": "I rest after school.", "vi": "Tôi nghỉ ngơi sau khi học."}, {"en": "Rest now.", "vi": "Nghỉ ngơi đi."}]},
            {"word": "bath", "meaning": "tắm", "emoji": "🛁", "class": "n", "examples": [{"en": "I take a bath every day.", "vi": "Tôi tắm mỗi ngày."}, {"en": "The bath is warm.", "vi": "Nước tắm ấm."}]},
            {"word": "dinner", "meaning": "bữa tối", "emoji": "🍲", "class": "n", "examples": [{"en": "We eat dinner together.", "vi": "Chúng tôi ăn tối cùng nhau."}, {"en": "Dinner is my favorite meal.", "vi": "Bữa tối là bữa ăn tôi thích nhất."}]},
            {"word": "night", "meaning": "buổi tối/đêm", "emoji": "🌙", "class": "n", "examples": [{"en": "Good night!", "vi": "Chúc ngủ ngon!"}, {"en": "Stars come out at night.", "vi": "Sao xuất hiện vào ban đêm."}]},
            {"word": "study", "meaning": "học/học bài", "emoji": "📖", "class": "v", "examples": [{"en": "I study every day.", "vi": "Tôi học bài mỗi ngày."}, {"en": "I study after dinner.", "vi": "Tôi học bài sau bữa tối."}]},
            {"word": "cook", "meaning": "nấu ăn", "emoji": "🍳", "class": "v", "examples": [{"en": "Mum cooks dinner.", "vi": "Mẹ nấu bữa tối."}, {"en": "I cook rice.", "vi": "Tôi nấu cơm."}]},
            {"word": "come", "meaning": "đến/về", "emoji": "🏃", "class": "v", "examples": [{"en": "I come home at five.", "vi": "Tôi về nhà lúc năm giờ."}, {"en": "Come here!", "vi": "Lại đây!"}]},
            {"word": "go", "meaning": "đi", "emoji": "🚶", "class": "v", "examples": [{"en": "I go to school.", "vi": "Tôi đi học."}, {"en": "Go now!", "vi": "Đi thôi!"}]},
        ]
    },
    {
        "id": "simple-adjectives",
        "name": "Tính Từ Cơ Bản",
        "emoji": "✨",
        "color": "purple",
        "words": [
            {"word": "big", "meaning": "to/lớn", "emoji": "🐘", "class": "adj", "examples": [{"en": "The elephant is big.", "vi": "Con voi rất to."}, {"en": "I want a big piece.", "vi": "Tôi muốn một miếng to."}]},
            {"word": "small", "meaning": "nhỏ", "emoji": "🐭", "class": "adj", "examples": [{"en": "The mouse is small.", "vi": "Con chuột rất nhỏ."}, {"en": "I have a small bag.", "vi": "Tôi có một cái túi nhỏ."}]},
            {"word": "tall", "meaning": "cao", "emoji": "🦒", "class": "adj", "examples": [{"en": "The giraffe is tall.", "vi": "Hươu cao cổ rất cao."}, {"en": "My dad is tall.", "vi": "Bố tôi rất cao."}]},
            {"word": "short", "meaning": "thấp/ngắn", "emoji": "🐢", "class": "adj", "examples": [{"en": "She is short.", "vi": "Cô ấy rất thấp."}, {"en": "The pencil is short.", "vi": "Cây bút chì ngắn."}]},
            {"word": "long", "meaning": "dài", "emoji": "🐍", "class": "adj", "examples": [{"en": "The snake is long.", "vi": "Con rắn rất dài."}, {"en": "She has long hair.", "vi": "Cô ấy có tóc dài."}]},
            {"word": "new", "meaning": "mới", "emoji": "✨", "class": "adj", "examples": [{"en": "I have new shoes.", "vi": "Tôi có đôi giày mới."}, {"en": "This is a new book.", "vi": "Đây là quyển sách mới."}]},
            {"word": "old", "meaning": "cũ/già", "emoji": "👴", "class": "adj", "examples": [{"en": "That is an old book.", "vi": "Đó là quyển sách cũ."}, {"en": "My grandpa is old.", "vi": "Ông tôi đã già."}]},
            {"word": "fast", "meaning": "nhanh", "emoji": "🐆", "class": "adj", "examples": [{"en": "The cheetah is fast.", "vi": "Con báo rất nhanh."}, {"en": "Run fast!", "vi": "Chạy nhanh lên!"}]},
            {"word": "slow", "meaning": "chậm", "emoji": "🐌", "class": "adj", "examples": [{"en": "The snail is slow.", "vi": "Con ốc sên rất chậm."}, {"en": "Walk slowly.", "vi": "Đi chậm thôi."}]},
            {"word": "clean", "meaning": "sạch", "emoji": "✨", "class": "adj", "examples": [{"en": "My hands are clean.", "vi": "Tay tôi sạch rồi."}, {"en": "Keep your room clean.", "vi": "Giữ phòng sạch sẽ nhé."}]},
            {"word": "dirty", "meaning": "bẩn", "emoji": "🤢", "class": "adj", "examples": [{"en": "My shoes are dirty.", "vi": "Giày tôi bẩn rồi."}, {"en": "Wash your dirty hands.", "vi": "Rửa tay bẩn đi."}]},
            {"word": "soft", "meaning": "mềm", "emoji": "🧸", "class": "adj", "examples": [{"en": "The teddy is soft.", "vi": "Gấu bông rất mềm."}, {"en": "The bed is soft.", "vi": "Chiếc giường mềm lắm."}]},
            {"word": "hard", "meaning": "cứng", "emoji": "🪨", "class": "adj", "examples": [{"en": "The rock is hard.", "vi": "Hòn đá rất cứng."}, {"en": "This bread is hard.", "vi": "Cái bánh mì này cứng quá."}]},
            {"word": "sweet", "meaning": "ngọt", "emoji": "🍬", "class": "adj", "examples": [{"en": "The cake is sweet.", "vi": "Cái bánh rất ngọt."}, {"en": "I like sweet things.", "vi": "Tôi thích đồ ngọt."}]},
            {"word": "sour", "meaning": "chua", "emoji": "🍋", "class": "adj", "examples": [{"en": "The lemon is sour.", "vi": "Quả chanh rất chua."}, {"en": "That is too sour.", "vi": "Cái đó chua quá."}]},
        ]
    },
    {
        "id": "jobs-basic",
        "name": "Nghề Nghiệp",
        "emoji": "👷",
        "color": "amber",
        "words": [
            {"word": "doctor", "meaning": "bác sĩ", "emoji": "👨‍⚕️", "class": "n", "examples": [{"en": "The doctor helps sick people.", "vi": "Bác sĩ giúp người bệnh."}, {"en": "I want to be a doctor.", "vi": "Tôi muốn làm bác sĩ."}]},
            {"word": "vet", "meaning": "bác sĩ thú y", "emoji": "🐾", "class": "n", "examples": [{"en": "The vet helps sick animals.", "vi": "Bác sĩ thú y chữa bệnh cho động vật."}, {"en": "My dog sees the vet.", "vi": "Chó của tôi đến gặp bác sĩ thú y."}]},
            {"word": "police", "meaning": "cảnh sát", "emoji": "👮", "class": "n", "examples": [{"en": "The police keeps us safe.", "vi": "Cảnh sát bảo vệ chúng ta."}, {"en": "I see a police officer.", "vi": "Tôi thấy một cảnh sát."}]},
            {"word": "driver", "meaning": "tài xế", "emoji": "🚗", "class": "n", "examples": [{"en": "The driver drives the bus.", "vi": "Tài xế lái xe buýt."}, {"en": "My dad is a good driver.", "vi": "Bố tôi là một tài xế giỏi."}]},
            {"word": "chef", "meaning": "đầu bếp", "emoji": "👨‍🍳", "class": "n", "examples": [{"en": "The chef cooks good food.", "vi": "Đầu bếp nấu món ăn ngon."}, {"en": "I want to be a chef.", "vi": "Tôi muốn làm đầu bếp."}]},
            {"word": "farmer", "meaning": "nông dân", "emoji": "🧑‍🌾", "class": "n", "examples": [{"en": "The farmer grows rice.", "vi": "Nông dân trồng lúa."}, {"en": "Farmers work in the field.", "vi": "Nông dân làm việc trên đồng."}]},
            {"word": "nurse", "meaning": "y tá", "emoji": "👩‍⚕️", "class": "n", "examples": [{"en": "The nurse is very kind.", "vi": "Y tá rất tốt bụng."}, {"en": "The nurse gives me medicine.", "vi": "Y tá cho tôi thuốc."}]},
            {"word": "pilot", "meaning": "phi công", "emoji": "👨‍✈️", "class": "n", "examples": [{"en": "The pilot flies the plane.", "vi": "Phi công lái máy bay."}, {"en": "I want to be a pilot.", "vi": "Tôi muốn làm phi công."}]},
            {"word": "builder", "meaning": "thợ xây", "emoji": "👷", "class": "n", "examples": [{"en": "The builder makes houses.", "vi": "Thợ xây xây nhà."}, {"en": "I see builders at work.", "vi": "Tôi thấy thợ xây đang làm việc."}]},
            {"word": "artist", "meaning": "nghệ sĩ/họa sĩ", "emoji": "🎨", "class": "n", "examples": [{"en": "The artist draws pictures.", "vi": "Họa sĩ vẽ tranh."}, {"en": "She is a great artist.", "vi": "Cô ấy là một họa sĩ giỏi."}]},
            {"word": "singer", "meaning": "ca sĩ", "emoji": "🎤", "class": "n", "examples": [{"en": "The singer has a good voice.", "vi": "Ca sĩ có giọng hát hay."}, {"en": "I want to be a singer.", "vi": "Tôi muốn làm ca sĩ."}]},
            {"word": "soldier", "meaning": "người lính", "emoji": "💂", "class": "n", "examples": [{"en": "The soldier is brave.", "vi": "Người lính rất dũng cảm."}, {"en": "Soldiers protect our country.", "vi": "Người lính bảo vệ đất nước."}]},
            {"word": "baker", "meaning": "thợ làm bánh", "emoji": "🥖", "class": "n", "examples": [{"en": "The baker makes bread.", "vi": "Thợ làm bánh làm bánh mì."}, {"en": "The baker wakes up early.", "vi": "Thợ làm bánh thức dậy rất sớm."}]},
            {"word": "firefighter", "meaning": "lính cứu hỏa", "emoji": "🧯", "class": "n", "examples": [{"en": "The firefighter puts out fires.", "vi": "Lính cứu hỏa dập tắt lửa."}, {"en": "Firefighters are very brave.", "vi": "Lính cứu hỏa rất dũng cảm."}]},
            {"word": "sailor", "meaning": "thủy thủ", "emoji": "⚓", "class": "n", "examples": [{"en": "The sailor is on the ship.", "vi": "Thủy thủ ở trên tàu."}, {"en": "Sailors sail on the sea.", "vi": "Thủy thủ đi biển."}]},
        ]
    },
    {
        "id": "farm-basics",
        "name": "Nông Trại",
        "emoji": "🚜",
        "color": "green",
        "words": [
            {"word": "sheep", "meaning": "cừu", "emoji": "🐑", "class": "n", "examples": [{"en": "The sheep has white wool.", "vi": "Con cừu có bộ lông trắng."}, {"en": "I count sheep.", "vi": "Tôi đếm cừu."}]},
            {"word": "goat", "meaning": "dê", "emoji": "🐐", "class": "n", "examples": [{"en": "The goat eats grass.", "vi": "Con dê ăn cỏ."}, {"en": "Goats climb well.", "vi": "Dê leo trèo giỏi lắm."}]},
            {"word": "chicken", "meaning": "gà", "emoji": "🐔", "class": "n", "examples": [{"en": "The chicken lays eggs.", "vi": "Con gà đẻ trứng."}, {"en": "I see chickens on the farm.", "vi": "Tôi thấy gà trên nông trại."}]},
            {"word": "turkey", "meaning": "gà tây", "emoji": "🦃", "class": "n", "examples": [{"en": "The turkey is big.", "vi": "Con gà tây rất to."}, {"en": "Turkeys live on farms.", "vi": "Gà tây sống ở nông trại."}]},
            {"word": "donkey", "meaning": "lừa", "emoji": "🫏", "class": "n", "examples": [{"en": "The donkey carries things.", "vi": "Con lừa chở đồ."}, {"en": "Donkeys say hee-haw.", "vi": "Lừa kêu hí hí."}]},
            {"word": "rooster", "meaning": "gà trống", "emoji": "🐓", "class": "n", "examples": [{"en": "The rooster crows in the morning.", "vi": "Gà trống gáy vào buổi sáng."}, {"en": "I hear the rooster crow.", "vi": "Tôi nghe tiếng gà gáy."}]},
            {"word": "barn", "meaning": "chuồng trại", "emoji": "🏚️", "class": "n", "examples": [{"en": "The animals sleep in the barn.", "vi": "Các con vật ngủ trong chuồng."}, {"en": "The barn is red.", "vi": "Chuồng trại màu đỏ."}]},
            {"word": "field", "meaning": "cánh đồng", "emoji": "🌾", "class": "n", "examples": [{"en": "The farmer works in the field.", "vi": "Nông dân làm việc trên cánh đồng."}, {"en": "The field is green.", "vi": "Cánh đồng màu xanh."}]},
            {"word": "fence", "meaning": "hàng rào", "emoji": "🚧", "class": "n", "examples": [{"en": "There is a fence around the farm.", "vi": "Có hàng rào quanh nông trại."}, {"en": "The fence is white.", "vi": "Hàng rào màu trắng."}]},
            {"word": "tractor", "meaning": "máy cày", "emoji": "🚜", "class": "n", "examples": [{"en": "The farmer drives the tractor.", "vi": "Nông dân lái máy cày."}, {"en": "The tractor is yellow.", "vi": "Máy cày màu vàng."}]},
            {"word": "hay", "meaning": "rơm/cỏ khô", "emoji": "🌾", "class": "n", "examples": [{"en": "The horse eats hay.", "vi": "Con ngựa ăn rơm."}, {"en": "Hay is dry grass.", "vi": "Rơm là cỏ khô."}]},
            {"word": "crop", "meaning": "hoa màu", "emoji": "🌽", "class": "n", "examples": [{"en": "The farmer grows crops.", "vi": "Nông dân trồng hoa màu."}, {"en": "Rice is a crop.", "vi": "Lúa là một loại hoa màu."}]},
            {"word": "stable", "meaning": "chuồng ngựa", "emoji": "🐴", "class": "n", "examples": [{"en": "The horse lives in the stable.", "vi": "Con ngựa sống trong chuồng ngựa."}, {"en": "I visit the stable.", "vi": "Tôi đến thăm chuồng ngựa."}]},
            {"word": "feed", "meaning": "thức ăn/cho ăn", "emoji": "🌿", "class": "n", "examples": [{"en": "I give feed to the chickens.", "vi": "Tôi cho gà ăn thức ăn."}, {"en": "The animals need feed.", "vi": "Các con vật cần thức ăn."}]},
            {"word": "seed", "meaning": "hạt giống", "emoji": "🌱", "class": "n", "examples": [{"en": "I plant a seed.", "vi": "Tôi trồng một hạt giống."}, {"en": "Seeds grow into plants.", "vi": "Hạt giống mọc thành cây."}]},
        ]
    },
    {
        "id": "nature-basics",
        "name": "Thiên Nhiên",
        "emoji": "🌿",
        "color": "green",
        "words": [
            {"word": "tree", "meaning": "cây", "emoji": "🌳", "class": "n", "examples": [{"en": "The tree is tall.", "vi": "Cây rất cao."}, {"en": "Birds live in trees.", "vi": "Chim sống trên cây."}]},
            {"word": "flower", "meaning": "hoa", "emoji": "🌸", "class": "n", "examples": [{"en": "The flower is pink.", "vi": "Bông hoa màu hồng."}, {"en": "I pick a flower for mum.", "vi": "Tôi hái một bông hoa tặng mẹ."}]},
            {"word": "grass", "meaning": "cỏ", "emoji": "🌿", "class": "n", "examples": [{"en": "The grass is green.", "vi": "Cỏ màu xanh lá."}, {"en": "I sit on the grass.", "vi": "Tôi ngồi trên cỏ."}]},
            {"word": "leaf", "meaning": "lá cây", "emoji": "🍃", "class": "n", "examples": [{"en": "The leaf is green.", "vi": "Chiếc lá màu xanh."}, {"en": "I find a big leaf.", "vi": "Tôi tìm thấy một chiếc lá to."}]},
            {"word": "rock", "meaning": "hòn đá", "emoji": "🪨", "class": "n", "examples": [{"en": "I sit on a big rock.", "vi": "Tôi ngồi trên hòn đá to."}, {"en": "The rock is hard.", "vi": "Hòn đá rất cứng."}]},
            {"word": "river", "meaning": "sông", "emoji": "🌊", "class": "n", "examples": [{"en": "The river is long.", "vi": "Con sông rất dài."}, {"en": "Fish swim in the river.", "vi": "Cá bơi trong sông."}]},
            {"word": "lake", "meaning": "hồ", "emoji": "🏞️", "class": "n", "examples": [{"en": "The lake is blue.", "vi": "Hồ nước màu xanh."}, {"en": "We swim in the lake.", "vi": "Chúng tôi bơi trong hồ."}]},
            {"word": "hill", "meaning": "đồi", "emoji": "⛰️", "class": "n", "examples": [{"en": "I climb the hill.", "vi": "Tôi leo lên đồi."}, {"en": "The hill is green.", "vi": "Đồi màu xanh."}]},
            {"word": "sky", "meaning": "bầu trời", "emoji": "🌤️", "class": "n", "examples": [{"en": "The sky is blue.", "vi": "Bầu trời màu xanh."}, {"en": "I look at the sky.", "vi": "Tôi nhìn lên bầu trời."}]},
            {"word": "sand", "meaning": "cát", "emoji": "🏖️", "class": "n", "examples": [{"en": "I play in the sand.", "vi": "Tôi chơi trên cát."}, {"en": "Sand is soft.", "vi": "Cát mềm mại."}]},
            {"word": "beach", "meaning": "bãi biển", "emoji": "🏝️", "class": "n", "examples": [{"en": "I play at the beach.", "vi": "Tôi chơi ở bãi biển."}, {"en": "The beach has white sand.", "vi": "Bãi biển có cát trắng."}]},
            {"word": "forest", "meaning": "rừng", "emoji": "🌲", "class": "n", "examples": [{"en": "Animals live in the forest.", "vi": "Động vật sống trong rừng."}, {"en": "The forest is dark.", "vi": "Rừng tối và rậm."}]},
            {"word": "mountain", "meaning": "núi", "emoji": "🏔️", "class": "n", "examples": [{"en": "The mountain is very high.", "vi": "Núi rất cao."}, {"en": "I see snow on the mountain.", "vi": "Tôi thấy tuyết trên núi."}]},
            {"word": "path", "meaning": "con đường/lối đi", "emoji": "🛤️", "class": "n", "examples": [{"en": "I walk on the path.", "vi": "Tôi đi trên con đường."}, {"en": "The path goes to the river.", "vi": "Con đường dẫn đến sông."}]},
            {"word": "bush", "meaning": "bụi cây", "emoji": "🌿", "class": "n", "examples": [{"en": "The rabbit hides in the bush.", "vi": "Con thỏ ẩn trong bụi cây."}, {"en": "There are flowers on the bush.", "vi": "Có hoa trên bụi cây."}]},
        ]
    },
    {
        "id": "simple-sports",
        "name": "Thể Thao",
        "emoji": "⚽",
        "color": "green",
        "words": [
            {"word": "football", "meaning": "bóng đá", "emoji": "⚽", "class": "n", "examples": [{"en": "I play football.", "vi": "Tôi chơi bóng đá."}, {"en": "Football is my favorite sport.", "vi": "Bóng đá là môn thể thao yêu thích của tôi."}]},
            {"word": "basketball", "meaning": "bóng rổ", "emoji": "🏀", "class": "n", "examples": [{"en": "I play basketball.", "vi": "Tôi chơi bóng rổ."}, {"en": "Basketball is fun.", "vi": "Bóng rổ rất vui."}]},
            {"word": "tennis", "meaning": "quần vợt", "emoji": "🎾", "class": "n", "examples": [{"en": "I play tennis.", "vi": "Tôi chơi quần vợt."}, {"en": "Tennis needs a racket.", "vi": "Chơi quần vợt cần cây vợt."}]},
            {"word": "swimming", "meaning": "bơi lội", "emoji": "🏊", "class": "n", "examples": [{"en": "Swimming is good for health.", "vi": "Bơi lội rất tốt cho sức khỏe."}, {"en": "I go swimming on weekends.", "vi": "Tôi đi bơi vào cuối tuần."}]},
            {"word": "running", "meaning": "chạy bộ", "emoji": "🏃", "class": "n", "examples": [{"en": "Running is good for me.", "vi": "Chạy bộ rất tốt cho tôi."}, {"en": "I like running in the park.", "vi": "Tôi thích chạy bộ trong công viên."}]},
            {"word": "cycling", "meaning": "đạp xe", "emoji": "🚲", "class": "n", "examples": [{"en": "Cycling is fun.", "vi": "Đạp xe rất vui."}, {"en": "I go cycling on Sunday.", "vi": "Tôi đi đạp xe vào Chủ nhật."}]},
            {"word": "volleyball", "meaning": "bóng chuyền", "emoji": "🏐", "class": "n", "examples": [{"en": "We play volleyball on the beach.", "vi": "Chúng tôi chơi bóng chuyền trên bãi biển."}, {"en": "Volleyball is a team sport.", "vi": "Bóng chuyền là môn thể thao đồng đội."}]},
            {"word": "badminton", "meaning": "cầu lông", "emoji": "🏸", "class": "n", "examples": [{"en": "I play badminton with my dad.", "vi": "Tôi chơi cầu lông với bố."}, {"en": "Badminton is very popular.", "vi": "Cầu lông rất phổ biến."}]},
            {"word": "boxing", "meaning": "quyền anh", "emoji": "🥊", "class": "n", "examples": [{"en": "Boxing needs strong arms.", "vi": "Quyền anh cần cánh tay khỏe."}, {"en": "He practices boxing.", "vi": "Anh ấy tập quyền anh."}]},
            {"word": "golf", "meaning": "đánh gôn", "emoji": "⛳", "class": "n", "examples": [{"en": "My dad plays golf.", "vi": "Bố tôi chơi gôn."}, {"en": "Golf needs a big field.", "vi": "Chơi gôn cần một bãi cỏ rộng."}]},
            {"word": "ping-pong", "meaning": "bóng bàn", "emoji": "🏓", "class": "n", "examples": [{"en": "I play ping-pong.", "vi": "Tôi chơi bóng bàn."}, {"en": "Ping-pong is fast.", "vi": "Bóng bàn rất nhanh."}]},
            {"word": "hiking", "meaning": "leo núi/đi bộ", "emoji": "🥾", "class": "n", "examples": [{"en": "We go hiking in the mountains.", "vi": "Chúng tôi đi leo núi."}, {"en": "Hiking is good exercise.", "vi": "Đi bộ leo núi rất tốt."}]},
            {"word": "fishing", "meaning": "câu cá", "emoji": "🎣", "class": "n", "examples": [{"en": "I go fishing with my dad.", "vi": "Tôi đi câu cá với bố."}, {"en": "Fishing needs a fishing rod.", "vi": "Câu cá cần cần câu."}]},
            {"word": "skating", "meaning": "trượt patin", "emoji": "⛸️", "class": "n", "examples": [{"en": "I love skating.", "vi": "Tôi thích trượt patin."}, {"en": "Skating needs special shoes.", "vi": "Trượt patin cần giày đặc biệt."}]},
            {"word": "karate", "meaning": "karate", "emoji": "🥋", "class": "n", "examples": [{"en": "I learn karate.", "vi": "Tôi học karate."}, {"en": "Karate is a martial art.", "vi": "Karate là một môn võ thuật."}]},
        ]
    },
    {
        "id": "home-objects",
        "name": "Đồ Dùng Trong Bếp",
        "emoji": "🍳",
        "color": "orange",
        "words": [
            {"word": "spoon", "meaning": "thìa/muỗng", "emoji": "🥄", "class": "n", "examples": [{"en": "I eat soup with a spoon.", "vi": "Tôi ăn súp bằng thìa."}, {"en": "Give me a spoon please.", "vi": "Cho tôi một cái thìa."}]},
            {"word": "fork", "meaning": "nĩa", "emoji": "🍴", "class": "n", "examples": [{"en": "I eat salad with a fork.", "vi": "Tôi ăn salad bằng nĩa."}, {"en": "Pass me the fork.", "vi": "Đưa cho tôi cái nĩa."}]},
            {"word": "knife", "meaning": "dao", "emoji": "🔪", "class": "n", "examples": [{"en": "Mum cuts with a knife.", "vi": "Mẹ cắt bằng con dao."}, {"en": "Be careful with the knife.", "vi": "Cẩn thận với con dao nhé."}]},
            {"word": "plate", "meaning": "đĩa", "emoji": "🍽️", "class": "n", "examples": [{"en": "I put food on my plate.", "vi": "Tôi để thức ăn vào đĩa."}, {"en": "The plate is white.", "vi": "Cái đĩa màu trắng."}]},
            {"word": "bowl", "meaning": "bát/tô", "emoji": "🥣", "class": "n", "examples": [{"en": "I eat rice in a bowl.", "vi": "Tôi ăn cơm trong bát."}, {"en": "The bowl is full of soup.", "vi": "Bát đầy canh."}]},
            {"word": "glass", "meaning": "ly thủy tinh", "emoji": "🥛", "class": "n", "examples": [{"en": "I drink water from a glass.", "vi": "Tôi uống nước từ cái ly."}, {"en": "The glass is clear.", "vi": "Cái ly trong suốt."}]},
            {"word": "pot", "meaning": "nồi", "emoji": "🫕", "class": "n", "examples": [{"en": "Mum cooks in the pot.", "vi": "Mẹ nấu trong cái nồi."}, {"en": "The pot is hot.", "vi": "Cái nồi rất nóng."}]},
            {"word": "pan", "meaning": "chảo", "emoji": "🍳", "class": "n", "examples": [{"en": "Mum fries eggs in the pan.", "vi": "Mẹ rán trứng trong chảo."}, {"en": "The pan is on the stove.", "vi": "Cái chảo ở trên bếp."}]},
            {"word": "towel", "meaning": "khăn tắm", "emoji": "🧺", "class": "n", "examples": [{"en": "I dry with a towel.", "vi": "Tôi lau khô bằng khăn."}, {"en": "My towel is blue.", "vi": "Khăn tắm của tôi màu xanh."}]},
            {"word": "soap", "meaning": "xà phòng", "emoji": "🧼", "class": "n", "examples": [{"en": "I wash with soap.", "vi": "Tôi rửa bằng xà phòng."}, {"en": "The soap smells nice.", "vi": "Xà phòng thơm dễ chịu."}]},
            {"word": "pillow", "meaning": "gối", "emoji": "🛏️", "class": "n", "examples": [{"en": "I sleep on my pillow.", "vi": "Tôi ngủ trên gối."}, {"en": "My pillow is soft.", "vi": "Cái gối của tôi mềm."}]},
            {"word": "blanket", "meaning": "chăn", "emoji": "🛌", "class": "n", "examples": [{"en": "I sleep under my blanket.", "vi": "Tôi ngủ dưới cái chăn."}, {"en": "The blanket is warm.", "vi": "Cái chăn rất ấm."}]},
            {"word": "remote", "meaning": "điều khiển từ xa", "emoji": "📺", "class": "n", "examples": [{"en": "I use the remote for TV.", "vi": "Tôi dùng điều khiển để xem TV."}, {"en": "The remote is on the sofa.", "vi": "Điều khiển ở trên ghế sofa."}]},
            {"word": "trash", "meaning": "thùng rác", "emoji": "🗑️", "class": "n", "examples": [{"en": "I put paper in the trash.", "vi": "Tôi bỏ giấy vào thùng rác."}, {"en": "Empty the trash.", "vi": "Đổ rác đi."}]},
            {"word": "broom", "meaning": "cái chổi", "emoji": "🧹", "class": "n", "examples": [{"en": "I sweep with a broom.", "vi": "Tôi quét bằng cái chổi."}, {"en": "The broom is tall.", "vi": "Cái chổi cao."}]},
        ]
    },
    {
        "id": "common-tech",
        "name": "Công Nghệ",
        "emoji": "📱",
        "color": "blue",
        "words": [
            {"word": "phone", "meaning": "điện thoại", "emoji": "📱", "class": "n", "examples": [{"en": "Mum calls on the phone.", "vi": "Mẹ gọi điện thoại."}, {"en": "I see photos on the phone.", "vi": "Tôi xem ảnh trên điện thoại."}]},
            {"word": "computer", "meaning": "máy tính", "emoji": "💻", "class": "n", "examples": [{"en": "I learn on the computer.", "vi": "Tôi học trên máy tính."}, {"en": "The computer is on the table.", "vi": "Máy tính ở trên bàn."}]},
            {"word": "screen", "meaning": "màn hình", "emoji": "🖥️", "class": "n", "examples": [{"en": "I look at the screen.", "vi": "Tôi nhìn vào màn hình."}, {"en": "The screen is bright.", "vi": "Màn hình rất sáng."}]},
            {"word": "camera", "meaning": "máy ảnh", "emoji": "📷", "class": "n", "examples": [{"en": "Dad takes photos with the camera.", "vi": "Bố chụp ảnh bằng máy ảnh."}, {"en": "I smile for the camera.", "vi": "Tôi cười khi chụp ảnh."}]},
            {"word": "TV", "meaning": "ti vi", "emoji": "📺", "class": "n", "examples": [{"en": "I watch TV at home.", "vi": "Tôi xem ti vi ở nhà."}, {"en": "The TV is big.", "vi": "Cái ti vi rất to."}]},
            {"word": "tablet", "meaning": "máy tính bảng", "emoji": "📱", "class": "n", "examples": [{"en": "I draw on my tablet.", "vi": "Tôi vẽ trên máy tính bảng."}, {"en": "My tablet has games.", "vi": "Máy tính bảng của tôi có trò chơi."}]},
            {"word": "keyboard", "meaning": "bàn phím", "emoji": "⌨️", "class": "n", "examples": [{"en": "I type on the keyboard.", "vi": "Tôi gõ trên bàn phím."}, {"en": "The keyboard has letters.", "vi": "Bàn phím có các chữ cái."}]},
            {"word": "mouse", "meaning": "chuột máy tính", "emoji": "🖱️", "class": "n", "examples": [{"en": "I click the mouse.", "vi": "Tôi nhấp chuột."}, {"en": "Move the mouse to the left.", "vi": "Di chuột sang trái."}]},
            {"word": "battery", "meaning": "pin", "emoji": "🔋", "class": "n", "examples": [{"en": "The battery is low.", "vi": "Pin sắp hết rồi."}, {"en": "I change the battery.", "vi": "Tôi thay pin mới."}]},
            {"word": "charger", "meaning": "cục sạc", "emoji": "🔌", "class": "n", "examples": [{"en": "I charge my phone.", "vi": "Tôi sạc điện thoại."}, {"en": "The charger is on the table.", "vi": "Cục sạc ở trên bàn."}]},
            {"word": "wifi", "meaning": "wifi", "emoji": "📶", "class": "n", "examples": [{"en": "I need wifi for my tablet.", "vi": "Tôi cần wifi cho máy tính bảng."}, {"en": "The wifi is fast.", "vi": "Wifi nhanh lắm."}]},
            {"word": "game", "meaning": "trò chơi điện tử", "emoji": "🎮", "class": "n", "examples": [{"en": "I play a game.", "vi": "Tôi chơi trò chơi."}, {"en": "My game is on the tablet.", "vi": "Trò chơi của tôi ở trên máy tính bảng."}]},
            {"word": "photo", "meaning": "bức ảnh", "emoji": "📸", "class": "n", "examples": [{"en": "I take a photo.", "vi": "Tôi chụp một bức ảnh."}, {"en": "I look at photos.", "vi": "Tôi xem ảnh."}]},
            {"word": "video", "meaning": "video", "emoji": "🎬", "class": "n", "examples": [{"en": "I watch a video.", "vi": "Tôi xem video."}, {"en": "The video is funny.", "vi": "Video đó buồn cười lắm."}]},
            {"word": "internet", "meaning": "mạng internet", "emoji": "🌐", "class": "n", "examples": [{"en": "I use the internet.", "vi": "Tôi dùng mạng internet."}, {"en": "The internet has many things.", "vi": "Mạng internet có rất nhiều thứ."}]},
        ]
    },
    {
        "id": "celebrations",
        "name": "Lễ Hội & Tiệc",
        "emoji": "🎉",
        "color": "pink",
        "words": [
            {"word": "birthday", "meaning": "sinh nhật", "emoji": "🎂", "class": "n", "examples": [{"en": "Today is my birthday.", "vi": "Hôm nay là sinh nhật của tôi."}, {"en": "Happy birthday to you!", "vi": "Chúc mừng sinh nhật!"}]},
            {"word": "party", "meaning": "bữa tiệc", "emoji": "🎉", "class": "n", "examples": [{"en": "I go to a party.", "vi": "Tôi đi dự tiệc."}, {"en": "The party is fun.", "vi": "Bữa tiệc rất vui."}]},
            {"word": "gift", "meaning": "quà tặng", "emoji": "🎁", "class": "n", "examples": [{"en": "I get a gift.", "vi": "Tôi nhận được quà."}, {"en": "I give my friend a gift.", "vi": "Tôi tặng quà cho bạn."}]},
            {"word": "candle", "meaning": "nến", "emoji": "🕯️", "class": "n", "examples": [{"en": "I blow out the candles.", "vi": "Tôi thổi tắt nến."}, {"en": "There are five candles on the cake.", "vi": "Có năm cây nến trên bánh."}]},
            {"word": "firework", "meaning": "pháo hoa", "emoji": "🎆", "class": "n", "examples": [{"en": "I see fireworks in the sky.", "vi": "Tôi thấy pháo hoa trên bầu trời."}, {"en": "Fireworks are colorful.", "vi": "Pháo hoa rất nhiều màu."}]},
            {"word": "costume", "meaning": "trang phục hóa trang", "emoji": "🎭", "class": "n", "examples": [{"en": "I wear a costume.", "vi": "Tôi mặc trang phục hóa trang."}, {"en": "My costume is a dragon.", "vi": "Trang phục của tôi là con rồng."}]},
            {"word": "lantern", "meaning": "đèn lồng", "emoji": "🏮", "class": "n", "examples": [{"en": "I carry a lantern.", "vi": "Tôi mang đèn lồng."}, {"en": "The lantern is red.", "vi": "Đèn lồng màu đỏ."}]},
            {"word": "parade", "meaning": "diễu hành", "emoji": "🎊", "class": "n", "examples": [{"en": "I watch the parade.", "vi": "Tôi xem diễu hành."}, {"en": "The parade is colorful.", "vi": "Đoàn diễu hành rất nhiều màu sắc."}]},
            {"word": "cheer", "meaning": "hò reo", "emoji": "🙌", "class": "v", "examples": [{"en": "We cheer for our team.", "vi": "Chúng tôi hò reo cổ vũ đội mình."}, {"en": "Cheer loudly!", "vi": "Hò reo to lên nào!"}]},
            {"word": "clap", "meaning": "vỗ tay", "emoji": "👏", "class": "v", "examples": [{"en": "I clap my hands.", "vi": "Tôi vỗ tay."}, {"en": "Clap for the singer!", "vi": "Vỗ tay cho ca sĩ nào!"}]},
            {"word": "countdown", "meaning": "đếm ngược", "emoji": "⏱️", "class": "n", "examples": [{"en": "We do a countdown.", "vi": "Chúng tôi đếm ngược."}, {"en": "Three, two, one, go!", "vi": "Ba, hai, một, bắt đầu!"}]},
            {"word": "invite", "meaning": "mời", "emoji": "📨", "class": "v", "examples": [{"en": "I invite my friends.", "vi": "Tôi mời các bạn."}, {"en": "She invites me to her party.", "vi": "Cô ấy mời tôi đến tiệc."}]},
            {"word": "celebrate", "meaning": "ăn mừng", "emoji": "🎊", "class": "v", "examples": [{"en": "We celebrate my birthday.", "vi": "Chúng tôi ăn mừng sinh nhật của tôi."}, {"en": "Let's celebrate!", "vi": "Cùng ăn mừng nào!"}]},
            {"word": "wish", "meaning": "điều ước/chúc", "emoji": "🌠", "class": "n", "examples": [{"en": "I make a wish.", "vi": "Tôi ước một điều."}, {"en": "My wish comes true.", "vi": "Điều ước của tôi trở thành sự thật."}]},
            {"word": "balloon", "meaning": "bóng bay", "emoji": "🎈", "class": "n", "examples": [{"en": "I have a red balloon.", "vi": "Tôi có một quả bóng bay đỏ."}, {"en": "The balloon flies up.", "vi": "Quả bóng bay lên."}]},
        ]
    },
    {
        "id": "outdoor-play",
        "name": "Vui Chơi Ngoài Trời",
        "emoji": "🌳",
        "color": "green",
        "words": [
            {"word": "park", "meaning": "công viên", "emoji": "🌳", "class": "n", "examples": [{"en": "I play in the park.", "vi": "Tôi chơi trong công viên."}, {"en": "The park is green.", "vi": "Công viên xanh mướt."}]},
            {"word": "slide", "meaning": "cầu trượt", "emoji": "🛝", "class": "n", "examples": [{"en": "I go down the slide.", "vi": "Tôi trượt xuống cầu trượt."}, {"en": "The slide is tall.", "vi": "Cầu trượt rất cao."}]},
            {"word": "swing", "meaning": "xích đu", "emoji": "🎠", "class": "n", "examples": [{"en": "I sit on the swing.", "vi": "Tôi ngồi trên xích đu."}, {"en": "Push me on the swing!", "vi": "Đẩy xích đu cho tôi!"}]},
            {"word": "climb", "meaning": "leo trèo", "emoji": "🧗", "class": "v", "examples": [{"en": "I climb the tree.", "vi": "Tôi leo lên cây."}, {"en": "Climb up!", "vi": "Leo lên nào!"}]},
            {"word": "hide", "meaning": "trốn", "emoji": "🙈", "class": "v", "examples": [{"en": "I hide behind the tree.", "vi": "Tôi trốn sau gốc cây."}, {"en": "Hide and seek!", "vi": "Trốn tìm nào!"}]},
            {"word": "seek", "meaning": "tìm", "emoji": "🔍", "class": "v", "examples": [{"en": "I seek my friends.", "vi": "Tôi tìm các bạn."}, {"en": "I seek you!", "vi": "Tôi sẽ tìm bạn!"}]},
            {"word": "race", "meaning": "chạy đua", "emoji": "🏁", "class": "n", "examples": [{"en": "Let's have a race!", "vi": "Chạy đua nào!"}, {"en": "I win the race.", "vi": "Tôi thắng cuộc đua."}]},
            {"word": "catch", "meaning": "bắt", "emoji": "🤲", "class": "v", "examples": [{"en": "I catch the ball.", "vi": "Tôi bắt quả bóng."}, {"en": "Catch me!", "vi": "Bắt tôi đi!"}]},
            {"word": "dig", "meaning": "đào", "emoji": "⛏️", "class": "v", "examples": [{"en": "I dig in the sand.", "vi": "Tôi đào trong cát."}, {"en": "Dogs dig holes.", "vi": "Chó đào hố."}]},
            {"word": "splash", "meaning": "té nước", "emoji": "💦", "class": "v", "examples": [{"en": "I splash in the water.", "vi": "Tôi té nước."}, {"en": "Don't splash me!", "vi": "Đừng té nước vào tôi!"}]},
            {"word": "skip", "meaning": "nhảy dây", "emoji": "🐸", "class": "v", "examples": [{"en": "I skip rope.", "vi": "Tôi nhảy dây."}, {"en": "Skip to the tree.", "vi": "Nhảy đến gốc cây nào."}]},
            {"word": "explore", "meaning": "khám phá", "emoji": "🔭", "class": "v", "examples": [{"en": "I explore the park.", "vi": "Tôi khám phá công viên."}, {"en": "Let's explore!", "vi": "Cùng khám phá nào!"}]},
            {"word": "sandbox", "meaning": "hộp cát", "emoji": "🏖️", "class": "n", "examples": [{"en": "I play in the sandbox.", "vi": "Tôi chơi trong hộp cát."}, {"en": "Build a castle in the sandbox.", "vi": "Xây lâu đài trong hộp cát."}]},
            {"word": "fountain", "meaning": "đài phun nước", "emoji": "⛲", "class": "n", "examples": [{"en": "I see a big fountain.", "vi": "Tôi thấy một đài phun nước to."}, {"en": "The fountain is in the park.", "vi": "Đài phun nước ở trong công viên."}]},
            {"word": "chase", "meaning": "đuổi bắt", "emoji": "🏃", "class": "v", "examples": [{"en": "I chase my friend.", "vi": "Tôi đuổi theo bạn."}, {"en": "Chase the dog!", "vi": "Đuổi theo con chó!"}]},
        ]
    },
]

if __name__ == "__main__":
    print(f"Topics 16-30: {len(SEEKER_TOPICS_16_30)} topics")
    total = sum(len(t["words"]) for t in SEEKER_TOPICS_16_30)
    print(f"Total words: {total}")
