"""
Seeker (Pre-A1) level data — topics 1-15
Run after add_seeker_part2.py is ready, then run add_seeker_merge.py
"""

SEEKER_TOPICS_1_15 = [
    {
        "id": "colors-basic",
        "name": "Màu Sắc",
        "emoji": "🌈",
        "color": "red",
        "words": [
            {"word": "red", "meaning": "màu đỏ", "emoji": "🔴", "class": "adj", "examples": [{"en": "I see a red ball.", "vi": "Tôi thấy một quả bóng màu đỏ."}, {"en": "The apple is red.", "vi": "Quả táo màu đỏ."}]},
            {"word": "blue", "meaning": "màu xanh dương", "emoji": "🔵", "class": "adj", "examples": [{"en": "The sky is blue.", "vi": "Bầu trời màu xanh dương."}, {"en": "I like the blue shirt.", "vi": "Tôi thích cái áo màu xanh dương."}]},
            {"word": "green", "meaning": "màu xanh lá", "emoji": "🟢", "class": "adj", "examples": [{"en": "Grass is green.", "vi": "Cỏ màu xanh lá."}, {"en": "I see a green tree.", "vi": "Tôi thấy một cây màu xanh lá."}]},
            {"word": "yellow", "meaning": "màu vàng", "emoji": "🟡", "class": "adj", "examples": [{"en": "The sun is yellow.", "vi": "Mặt trời màu vàng."}, {"en": "I have a yellow pencil.", "vi": "Tôi có một cây bút màu vàng."}]},
            {"word": "pink", "meaning": "màu hồng", "emoji": "🩷", "class": "adj", "examples": [{"en": "The flower is pink.", "vi": "Bông hoa màu hồng."}, {"en": "I love pink.", "vi": "Tôi thích màu hồng."}]},
            {"word": "orange", "meaning": "màu cam", "emoji": "🟠", "class": "adj", "examples": [{"en": "The cat has orange fur.", "vi": "Con mèo có bộ lông màu cam."}, {"en": "I draw an orange sun.", "vi": "Tôi vẽ một mặt trời màu cam."}]},
            {"word": "black", "meaning": "màu đen", "emoji": "⚫", "class": "adj", "examples": [{"en": "My cat is black.", "vi": "Con mèo của tôi màu đen."}, {"en": "I write with a black pen.", "vi": "Tôi viết bằng bút màu đen."}]},
            {"word": "white", "meaning": "màu trắng", "emoji": "⚪", "class": "adj", "examples": [{"en": "Snow is white.", "vi": "Tuyết màu trắng."}, {"en": "I have a white rabbit.", "vi": "Tôi có một con thỏ màu trắng."}]},
            {"word": "brown", "meaning": "màu nâu", "emoji": "🟫", "class": "adj", "examples": [{"en": "The bear is brown.", "vi": "Con gấu màu nâu."}, {"en": "I see a brown dog.", "vi": "Tôi thấy một con chó màu nâu."}]},
            {"word": "grey", "meaning": "màu xám", "emoji": "🩶", "class": "adj", "examples": [{"en": "The elephant is grey.", "vi": "Con voi màu xám."}, {"en": "The sky is grey today.", "vi": "Bầu trời hôm nay màu xám."}]},
        ]
    },
    {
        "id": "numbers",
        "name": "Số Đếm",
        "emoji": "🔢",
        "color": "violet",
        "words": [
            {"word": "one", "meaning": "một", "emoji": "1️⃣", "class": "n", "examples": [{"en": "I have one cat.", "vi": "Tôi có một con mèo."}, {"en": "One apple is on the table.", "vi": "Một quả táo ở trên bàn."}]},
            {"word": "two", "meaning": "hai", "emoji": "2️⃣", "class": "n", "examples": [{"en": "I have two dogs.", "vi": "Tôi có hai con chó."}, {"en": "I see two birds.", "vi": "Tôi thấy hai con chim."}]},
            {"word": "three", "meaning": "ba", "emoji": "3️⃣", "class": "n", "examples": [{"en": "I have three books.", "vi": "Tôi có ba quyển sách."}, {"en": "Three fish are in the bowl.", "vi": "Ba con cá ở trong bình."}]},
            {"word": "four", "meaning": "bốn", "emoji": "4️⃣", "class": "n", "examples": [{"en": "I see four cats.", "vi": "Tôi thấy bốn con mèo."}, {"en": "A dog has four legs.", "vi": "Con chó có bốn chân."}]},
            {"word": "five", "meaning": "năm", "emoji": "5️⃣", "class": "n", "examples": [{"en": "I have five pencils.", "vi": "Tôi có năm cây bút chì."}, {"en": "Five birds are on the tree.", "vi": "Năm con chim đậu trên cây."}]},
            {"word": "six", "meaning": "sáu", "emoji": "6️⃣", "class": "n", "examples": [{"en": "I can count to six.", "vi": "Tôi có thể đếm đến sáu."}, {"en": "She has six crayons.", "vi": "Cô bé có sáu cây bút màu."}]},
            {"word": "seven", "meaning": "bảy", "emoji": "7️⃣", "class": "n", "examples": [{"en": "I see seven stars.", "vi": "Tôi thấy bảy ngôi sao."}, {"en": "There are seven days in a week.", "vi": "Một tuần có bảy ngày."}]},
            {"word": "eight", "meaning": "tám", "emoji": "8️⃣", "class": "n", "examples": [{"en": "I have eight crayons.", "vi": "Tôi có tám cây bút màu."}, {"en": "A spider has eight legs.", "vi": "Con nhện có tám chân."}]},
            {"word": "nine", "meaning": "chín", "emoji": "9️⃣", "class": "n", "examples": [{"en": "I count nine apples.", "vi": "Tôi đếm được chín quả táo."}, {"en": "She is nine years old.", "vi": "Cô bé chín tuổi."}]},
            {"word": "ten", "meaning": "mười", "emoji": "🔟", "class": "n", "examples": [{"en": "I have ten fingers.", "vi": "Tôi có mười ngón tay."}, {"en": "Ten birds fly in the sky.", "vi": "Mười con chim bay trên bầu trời."}]},
        ]
    },
    {
        "id": "family-basic",
        "name": "Gia Đình",
        "emoji": "👨‍👩‍👧‍👦",
        "color": "rose",
        "words": [
            {"word": "mum", "meaning": "mẹ", "emoji": "👩", "class": "n", "examples": [{"en": "I love my mum.", "vi": "Tôi yêu mẹ."}, {"en": "My mum cooks very well.", "vi": "Mẹ tôi nấu ăn rất giỏi."}]},
            {"word": "dad", "meaning": "bố", "emoji": "👨", "class": "n", "examples": [{"en": "My dad is tall.", "vi": "Bố tôi rất cao."}, {"en": "I play with my dad.", "vi": "Tôi chơi cùng bố."}]},
            {"word": "sister", "meaning": "chị/em gái", "emoji": "👧", "class": "n", "examples": [{"en": "My sister is funny.", "vi": "Chị/em gái tôi rất buồn cười."}, {"en": "I play with my sister.", "vi": "Tôi chơi cùng chị/em gái."}]},
            {"word": "brother", "meaning": "anh/em trai", "emoji": "👦", "class": "n", "examples": [{"en": "My brother is big.", "vi": "Anh/em trai tôi rất cao lớn."}, {"en": "I love my brother.", "vi": "Tôi yêu anh/em trai tôi."}]},
            {"word": "baby", "meaning": "em bé", "emoji": "👶", "class": "n", "examples": [{"en": "The baby is happy.", "vi": "Em bé rất vui."}, {"en": "I see a small baby.", "vi": "Tôi thấy một em bé nhỏ."}]},
            {"word": "grandma", "meaning": "bà", "emoji": "👵", "class": "n", "examples": [{"en": "My grandma is kind.", "vi": "Bà tôi rất hiền."}, {"en": "I visit my grandma.", "vi": "Tôi đến thăm bà."}]},
            {"word": "grandpa", "meaning": "ông", "emoji": "👴", "class": "n", "examples": [{"en": "My grandpa tells stories.", "vi": "Ông kể chuyện cho tôi nghe."}, {"en": "I love my grandpa.", "vi": "Tôi yêu ông ngoại."}]},
            {"word": "family", "meaning": "gia đình", "emoji": "👨‍👩‍👧‍👦", "class": "n", "examples": [{"en": "My family is big.", "vi": "Gia đình tôi rất đông."}, {"en": "I love my family.", "vi": "Tôi yêu gia đình tôi."}]},
            {"word": "home", "meaning": "nhà", "emoji": "🏠", "class": "n", "examples": [{"en": "I go home at five.", "vi": "Tôi về nhà lúc năm giờ."}, {"en": "My home is big.", "vi": "Nhà tôi rất to."}]},
            {"word": "love", "meaning": "yêu thương", "emoji": "❤️", "class": "n", "examples": [{"en": "I give love to my mum.", "vi": "Tôi yêu thương mẹ."}, {"en": "Love is in my heart.", "vi": "Tình yêu ở trong tim tôi."}]},
        ]
    },
    {
        "id": "simple-feelings",
        "name": "Cảm Xúc",
        "emoji": "😊",
        "color": "yellow",
        "words": [
            {"word": "happy", "meaning": "vui vẻ", "emoji": "😊", "class": "adj", "examples": [{"en": "I am happy today.", "vi": "Hôm nay tôi rất vui."}, {"en": "The baby is happy.", "vi": "Em bé rất vui vẻ."}]},
            {"word": "sad", "meaning": "buồn", "emoji": "😢", "class": "adj", "examples": [{"en": "I am sad today.", "vi": "Hôm nay tôi buồn."}, {"en": "She is sad and cries.", "vi": "Cô ấy buồn và khóc."}]},
            {"word": "angry", "meaning": "tức giận", "emoji": "😠", "class": "adj", "examples": [{"en": "He is very angry.", "vi": "Anh ấy rất tức giận."}, {"en": "I am angry at my brother.", "vi": "Tôi tức giận với em trai."}]},
            {"word": "scared", "meaning": "sợ hãi", "emoji": "😨", "class": "adj", "examples": [{"en": "I am scared of the dark.", "vi": "Tôi sợ bóng tối."}, {"en": "The cat is scared.", "vi": "Con mèo sợ hãi."}]},
            {"word": "tired", "meaning": "mệt mỏi", "emoji": "😴", "class": "adj", "examples": [{"en": "I am tired after school.", "vi": "Tôi mệt sau khi đi học."}, {"en": "She is very tired.", "vi": "Cô ấy rất mệt."}]},
            {"word": "hungry", "meaning": "đói bụng", "emoji": "🤤", "class": "adj", "examples": [{"en": "I am hungry now.", "vi": "Tôi đang đói."}, {"en": "The dog is hungry.", "vi": "Con chó đang đói."}]},
            {"word": "funny", "meaning": "buồn cười", "emoji": "😄", "class": "adj", "examples": [{"en": "The clown is funny.", "vi": "Chú hề rất buồn cười."}, {"en": "That story is funny.", "vi": "Câu chuyện đó buồn cười lắm."}]},
            {"word": "good", "meaning": "tốt", "emoji": "👍", "class": "adj", "examples": [{"en": "This food is good.", "vi": "Thức ăn này rất ngon."}, {"en": "I am a good student.", "vi": "Tôi là một học sinh tốt."}]},
            {"word": "bad", "meaning": "xấu/tệ", "emoji": "👎", "class": "adj", "examples": [{"en": "This is a bad day.", "vi": "Hôm nay là một ngày tệ."}, {"en": "That smell is bad.", "vi": "Mùi đó rất khó chịu."}]},
            {"word": "okay", "meaning": "ổn", "emoji": "👌", "class": "adj", "examples": [{"en": "I am okay now.", "vi": "Bây giờ tôi ổn rồi."}, {"en": "Is that okay with you?", "vi": "Điều đó có ổn với bạn không?"}]},
        ]
    },
    {
        "id": "body-parts",
        "name": "Cơ Thể",
        "emoji": "🧍",
        "color": "orange",
        "words": [
            {"word": "head", "meaning": "đầu", "emoji": "🙂", "class": "n", "examples": [{"en": "I touch my head.", "vi": "Tôi chạm vào đầu mình."}, {"en": "She shakes her head.", "vi": "Cô ấy lắc đầu."}]},
            {"word": "eye", "meaning": "mắt", "emoji": "👁️", "class": "n", "examples": [{"en": "I have two eyes.", "vi": "Tôi có hai mắt."}, {"en": "Her eyes are brown.", "vi": "Mắt cô ấy màu nâu."}]},
            {"word": "ear", "meaning": "tai", "emoji": "👂", "class": "n", "examples": [{"en": "I hear with my ears.", "vi": "Tôi nghe bằng tai."}, {"en": "The rabbit has big ears.", "vi": "Con thỏ có đôi tai to."}]},
            {"word": "nose", "meaning": "mũi", "emoji": "👃", "class": "n", "examples": [{"en": "I smell with my nose.", "vi": "Tôi ngửi bằng mũi."}, {"en": "The clown has a red nose.", "vi": "Chú hề có cái mũi đỏ."}]},
            {"word": "mouth", "meaning": "miệng", "emoji": "👄", "class": "n", "examples": [{"en": "I eat with my mouth.", "vi": "Tôi ăn bằng miệng."}, {"en": "Open your mouth wide.", "vi": "Mở miệng to ra nào."}]},
            {"word": "hand", "meaning": "bàn tay", "emoji": "✋", "class": "n", "examples": [{"en": "I wave my hand.", "vi": "Tôi vẫy tay."}, {"en": "Wash your hands, please.", "vi": "Hãy rửa tay đi nào."}]},
            {"word": "foot", "meaning": "bàn chân", "emoji": "🦶", "class": "n", "examples": [{"en": "I kick with my foot.", "vi": "Tôi đá bằng bàn chân."}, {"en": "My foot hurts today.", "vi": "Hôm nay bàn chân tôi đau."}]},
            {"word": "arm", "meaning": "cánh tay", "emoji": "💪", "class": "n", "examples": [{"en": "I hug with my arms.", "vi": "Tôi ôm bằng cánh tay."}, {"en": "My arm is strong.", "vi": "Cánh tay tôi rất khỏe."}]},
            {"word": "leg", "meaning": "chân", "emoji": "🦵", "class": "n", "examples": [{"en": "I run with my legs.", "vi": "Tôi chạy bằng đôi chân."}, {"en": "She has long legs.", "vi": "Cô ấy có đôi chân dài."}]},
            {"word": "hair", "meaning": "tóc", "emoji": "💇", "class": "n", "examples": [{"en": "My hair is black.", "vi": "Tóc tôi màu đen."}, {"en": "She has long hair.", "vi": "Cô ấy có mái tóc dài."}]},
        ]
    },
    {
        "id": "pets",
        "name": "Động Vật",
        "emoji": "🐾",
        "color": "green",
        "words": [
            {"word": "cat", "meaning": "mèo", "emoji": "🐱", "class": "n", "examples": [{"en": "My cat is soft.", "vi": "Con mèo của tôi rất mềm mại."}, {"en": "The cat drinks milk.", "vi": "Con mèo uống sữa."}]},
            {"word": "dog", "meaning": "chó", "emoji": "🐶", "class": "n", "examples": [{"en": "My dog is big.", "vi": "Con chó của tôi rất to."}, {"en": "The dog runs fast.", "vi": "Con chó chạy rất nhanh."}]},
            {"word": "fish", "meaning": "cá", "emoji": "🐟", "class": "n", "examples": [{"en": "I have a red fish.", "vi": "Tôi có một con cá đỏ."}, {"en": "The fish swims in water.", "vi": "Con cá bơi trong nước."}]},
            {"word": "bird", "meaning": "chim", "emoji": "🐦", "class": "n", "examples": [{"en": "The bird sings well.", "vi": "Con chim hót rất hay."}, {"en": "I see a blue bird.", "vi": "Tôi thấy một con chim xanh."}]},
            {"word": "horse", "meaning": "ngựa", "emoji": "🐴", "class": "n", "examples": [{"en": "The horse is big and fast.", "vi": "Con ngựa to và nhanh."}, {"en": "I ride a horse.", "vi": "Tôi cưỡi ngựa."}]},
            {"word": "rabbit", "meaning": "thỏ", "emoji": "🐰", "class": "n", "examples": [{"en": "The rabbit is white.", "vi": "Con thỏ màu trắng."}, {"en": "My rabbit eats carrots.", "vi": "Con thỏ của tôi ăn cà rốt."}]},
            {"word": "cow", "meaning": "bò", "emoji": "🐄", "class": "n", "examples": [{"en": "The cow gives us milk.", "vi": "Con bò cho chúng ta sữa."}, {"en": "I see a big cow.", "vi": "Tôi thấy một con bò to."}]},
            {"word": "pig", "meaning": "lợn/heo", "emoji": "🐷", "class": "n", "examples": [{"en": "The pig is pink.", "vi": "Con lợn màu hồng."}, {"en": "A pig says oink.", "vi": "Con lợn kêu ủn ỉn."}]},
            {"word": "duck", "meaning": "vịt", "emoji": "🦆", "class": "n", "examples": [{"en": "The duck swims in the pond.", "vi": "Con vịt bơi trong ao."}, {"en": "A duck says quack.", "vi": "Con vịt kêu quạc quạc."}]},
            {"word": "frog", "meaning": "ếch", "emoji": "🐸", "class": "n", "examples": [{"en": "The frog is green.", "vi": "Con ếch màu xanh."}, {"en": "The frog jumps high.", "vi": "Con ếch nhảy cao."}]},
        ]
    },
    {
        "id": "everyday-food",
        "name": "Đồ Ăn",
        "emoji": "🍽️",
        "color": "amber",
        "words": [
            {"word": "apple", "meaning": "táo", "emoji": "🍎", "class": "n", "examples": [{"en": "I eat a red apple.", "vi": "Tôi ăn một quả táo đỏ."}, {"en": "An apple is good for me.", "vi": "Táo rất tốt cho tôi."}]},
            {"word": "banana", "meaning": "chuối", "emoji": "🍌", "class": "n", "examples": [{"en": "I love bananas.", "vi": "Tôi rất thích chuối."}, {"en": "The banana is yellow.", "vi": "Quả chuối màu vàng."}]},
            {"word": "milk", "meaning": "sữa", "emoji": "🥛", "class": "n", "examples": [{"en": "I drink milk every day.", "vi": "Tôi uống sữa mỗi ngày."}, {"en": "Milk is white.", "vi": "Sữa có màu trắng."}]},
            {"word": "bread", "meaning": "bánh mì", "emoji": "🍞", "class": "n", "examples": [{"en": "I eat bread in the morning.", "vi": "Tôi ăn bánh mì vào buổi sáng."}, {"en": "This bread is soft.", "vi": "Cái bánh mì này mềm lắm."}]},
            {"word": "egg", "meaning": "trứng", "emoji": "🥚", "class": "n", "examples": [{"en": "I eat one egg for breakfast.", "vi": "Tôi ăn một quả trứng vào bữa sáng."}, {"en": "The egg is round.", "vi": "Quả trứng có hình tròn."}]},
            {"word": "rice", "meaning": "cơm/gạo", "emoji": "🍚", "class": "n", "examples": [{"en": "I eat rice every day.", "vi": "Tôi ăn cơm mỗi ngày."}, {"en": "Rice is white.", "vi": "Cơm có màu trắng."}]},
            {"word": "water", "meaning": "nước", "emoji": "💧", "class": "n", "examples": [{"en": "I drink water every day.", "vi": "Tôi uống nước mỗi ngày."}, {"en": "Water is clear.", "vi": "Nước trong suốt."}]},
            {"word": "cake", "meaning": "bánh kem", "emoji": "🎂", "class": "n", "examples": [{"en": "I love birthday cake.", "vi": "Tôi thích bánh sinh nhật."}, {"en": "The cake is sweet.", "vi": "Cái bánh rất ngọt."}]},
            {"word": "orange", "meaning": "quả cam", "emoji": "🍊", "class": "n", "examples": [{"en": "I eat an orange.", "vi": "Tôi ăn một quả cam."}, {"en": "The orange is sweet.", "vi": "Quả cam này ngọt lắm."}]},
            {"word": "juice", "meaning": "nước ép", "emoji": "🧃", "class": "n", "examples": [{"en": "I drink orange juice.", "vi": "Tôi uống nước cam."}, {"en": "The juice is cold.", "vi": "Nước ép lạnh lắm."}]},
        ]
    },
    {
        "id": "basic-clothes",
        "name": "Quần Áo",
        "emoji": "👕",
        "color": "sky",
        "words": [
            {"word": "shirt", "meaning": "áo sơ mi", "emoji": "👕", "class": "n", "examples": [{"en": "I wear a blue shirt.", "vi": "Tôi mặc áo sơ mi màu xanh."}, {"en": "This shirt is clean.", "vi": "Cái áo này sạch sẽ."}]},
            {"word": "dress", "meaning": "váy đầm", "emoji": "👗", "class": "n", "examples": [{"en": "She wears a pink dress.", "vi": "Cô ấy mặc váy màu hồng."}, {"en": "The dress is pretty.", "vi": "Chiếc váy rất đẹp."}]},
            {"word": "shoes", "meaning": "giày", "emoji": "👟", "class": "n", "examples": [{"en": "I put on my shoes.", "vi": "Tôi đi giày vào."}, {"en": "My shoes are white.", "vi": "Đôi giày của tôi màu trắng."}]},
            {"word": "hat", "meaning": "mũ", "emoji": "🧢", "class": "n", "examples": [{"en": "I wear a red hat.", "vi": "Tôi đội mũ màu đỏ."}, {"en": "The hat is on my head.", "vi": "Cái mũ đang ở trên đầu tôi."}]},
            {"word": "trousers", "meaning": "quần dài", "emoji": "👖", "class": "n", "examples": [{"en": "I wear blue trousers.", "vi": "Tôi mặc quần dài màu xanh."}, {"en": "My trousers are new.", "vi": "Chiếc quần dài của tôi mới tinh."}]},
            {"word": "shorts", "meaning": "quần ngắn", "emoji": "🩳", "class": "n", "examples": [{"en": "I wear shorts at the beach.", "vi": "Tôi mặc quần ngắn ở bãi biển."}, {"en": "My shorts are green.", "vi": "Cái quần ngắn của tôi màu xanh."}]},
            {"word": "socks", "meaning": "tất/vớ", "emoji": "🧦", "class": "n", "examples": [{"en": "I put on my socks.", "vi": "Tôi đi tất vào."}, {"en": "My socks are white.", "vi": "Đôi tất của tôi màu trắng."}]},
            {"word": "jacket", "meaning": "áo khoác", "emoji": "🧥", "class": "n", "examples": [{"en": "I wear a jacket when cold.", "vi": "Tôi mặc áo khoác khi trời lạnh."}, {"en": "Her jacket is yellow.", "vi": "Áo khoác của cô ấy màu vàng."}]},
            {"word": "coat", "meaning": "áo choàng dài", "emoji": "🥼", "class": "n", "examples": [{"en": "My coat is warm.", "vi": "Áo choàng của tôi rất ấm."}, {"en": "She wears a brown coat.", "vi": "Cô ấy mặc áo choàng màu nâu."}]},
            {"word": "bag", "meaning": "túi/ba lô", "emoji": "🎒", "class": "n", "examples": [{"en": "I carry my school bag.", "vi": "Tôi mang cặp đi học."}, {"en": "My bag is green.", "vi": "Cái cặp của tôi màu xanh."}]},
        ]
    },
    {
        "id": "basic-transport",
        "name": "Phương Tiện",
        "emoji": "🚗",
        "color": "blue",
        "words": [
            {"word": "car", "meaning": "ô tô", "emoji": "🚗", "class": "n", "examples": [{"en": "My dad drives a car.", "vi": "Bố tôi lái ô tô."}, {"en": "The car is red.", "vi": "Chiếc ô tô màu đỏ."}]},
            {"word": "bus", "meaning": "xe buýt", "emoji": "🚌", "class": "n", "examples": [{"en": "I go to school by bus.", "vi": "Tôi đi học bằng xe buýt."}, {"en": "The bus is big and yellow.", "vi": "Xe buýt to và màu vàng."}]},
            {"word": "train", "meaning": "tàu hỏa", "emoji": "🚂", "class": "n", "examples": [{"en": "The train is very fast.", "vi": "Tàu hỏa chạy rất nhanh."}, {"en": "I ride the train.", "vi": "Tôi đi tàu hỏa."}]},
            {"word": "plane", "meaning": "máy bay", "emoji": "✈️", "class": "n", "examples": [{"en": "The plane flies in the sky.", "vi": "Máy bay bay trên bầu trời."}, {"en": "I want to ride a plane.", "vi": "Tôi muốn đi máy bay."}]},
            {"word": "bike", "meaning": "xe đạp", "emoji": "🚲", "class": "n", "examples": [{"en": "I ride my bike to school.", "vi": "Tôi đạp xe đi học."}, {"en": "My bike is blue.", "vi": "Xe đạp của tôi màu xanh."}]},
            {"word": "boat", "meaning": "thuyền", "emoji": "⛵", "class": "n", "examples": [{"en": "The boat is on the river.", "vi": "Con thuyền ở trên sông."}, {"en": "I ride a small boat.", "vi": "Tôi đi thuyền nhỏ."}]},
            {"word": "taxi", "meaning": "xe taxi", "emoji": "🚕", "class": "n", "examples": [{"en": "We take a taxi home.", "vi": "Chúng tôi đi taxi về nhà."}, {"en": "The taxi is yellow.", "vi": "Xe taxi màu vàng."}]},
            {"word": "truck", "meaning": "xe tải", "emoji": "🚚", "class": "n", "examples": [{"en": "The truck carries boxes.", "vi": "Xe tải chở hàng hóa."}, {"en": "That truck is very big.", "vi": "Chiếc xe tải đó rất to."}]},
            {"word": "ship", "meaning": "tàu thủy", "emoji": "🚢", "class": "n", "examples": [{"en": "The ship sails on the sea.", "vi": "Tàu thủy chạy trên biển."}, {"en": "I see a big ship.", "vi": "Tôi thấy một con tàu to."}]},
            {"word": "helicopter", "meaning": "trực thăng", "emoji": "🚁", "class": "n", "examples": [{"en": "The helicopter flies up high.", "vi": "Trực thăng bay lên cao."}, {"en": "I see a red helicopter.", "vi": "Tôi thấy một chiếc trực thăng đỏ."}]},
        ]
    },
    {
        "id": "classroom",
        "name": "Lớp Học",
        "emoji": "📚",
        "color": "indigo",
        "words": [
            {"word": "book", "meaning": "sách", "emoji": "📖", "class": "n", "examples": [{"en": "I read a book.", "vi": "Tôi đọc sách."}, {"en": "This book is big.", "vi": "Quyển sách này rất dày."}]},
            {"word": "pen", "meaning": "bút bi", "emoji": "🖊️", "class": "n", "examples": [{"en": "I write with a pen.", "vi": "Tôi viết bằng bút bi."}, {"en": "My pen is blue.", "vi": "Cây bút của tôi màu xanh."}]},
            {"word": "pencil", "meaning": "bút chì", "emoji": "✏️", "class": "n", "examples": [{"en": "I draw with a pencil.", "vi": "Tôi vẽ bằng bút chì."}, {"en": "She has a yellow pencil.", "vi": "Cô ấy có một cây bút chì vàng."}]},
            {"word": "chair", "meaning": "ghế", "emoji": "🪑", "class": "n", "examples": [{"en": "I sit on a chair.", "vi": "Tôi ngồi trên ghế."}, {"en": "The chair is small.", "vi": "Cái ghế nhỏ xíu."}]},
            {"word": "table", "meaning": "bàn", "emoji": "📋", "class": "n", "examples": [{"en": "I put my book on the table.", "vi": "Tôi để sách trên bàn."}, {"en": "The table is big.", "vi": "Cái bàn rất to."}]},
            {"word": "teacher", "meaning": "giáo viên", "emoji": "👨‍🏫", "class": "n", "examples": [{"en": "My teacher is kind.", "vi": "Thầy/cô giáo của tôi rất tốt bụng."}, {"en": "I listen to my teacher.", "vi": "Tôi lắng nghe thầy/cô giáo."}]},
            {"word": "paper", "meaning": "giấy", "emoji": "📄", "class": "n", "examples": [{"en": "I draw on the paper.", "vi": "Tôi vẽ lên tờ giấy."}, {"en": "Give me a paper, please.", "vi": "Cho tôi một tờ giấy đi."}]},
            {"word": "crayon", "meaning": "bút màu sáp", "emoji": "🖍️", "class": "n", "examples": [{"en": "I color with crayons.", "vi": "Tôi tô màu bằng bút sáp."}, {"en": "I have red and blue crayons.", "vi": "Tôi có bút sáp đỏ và xanh."}]},
            {"word": "board", "meaning": "bảng", "emoji": "📝", "class": "n", "examples": [{"en": "The teacher writes on the board.", "vi": "Thầy/cô viết lên bảng."}, {"en": "I look at the board.", "vi": "Tôi nhìn lên bảng."}]},
            {"word": "friend", "meaning": "bạn bè", "emoji": "👫", "class": "n", "examples": [{"en": "She is my best friend.", "vi": "Cô ấy là bạn thân nhất của tôi."}, {"en": "I play with my friends.", "vi": "Tôi chơi cùng các bạn."}]},
        ]
    },
    {
        "id": "household-items",
        "name": "Trong Nhà",
        "emoji": "🏠",
        "color": "teal",
        "words": [
            {"word": "door", "meaning": "cửa ra vào", "emoji": "🚪", "class": "n", "examples": [{"en": "Please open the door.", "vi": "Làm ơn mở cửa ra."}, {"en": "The door is big and brown.", "vi": "Cánh cửa to và màu nâu."}]},
            {"word": "window", "meaning": "cửa sổ", "emoji": "🪟", "class": "n", "examples": [{"en": "I look out the window.", "vi": "Tôi nhìn ra ngoài cửa sổ."}, {"en": "Open the window please.", "vi": "Mở cửa sổ ra đi."}]},
            {"word": "bed", "meaning": "giường", "emoji": "🛏️", "class": "n", "examples": [{"en": "I sleep in my bed.", "vi": "Tôi ngủ trên giường."}, {"en": "My bed is soft.", "vi": "Chiếc giường của tôi rất mềm."}]},
            {"word": "sofa", "meaning": "ghế sofa", "emoji": "🛋️", "class": "n", "examples": [{"en": "I sit on the sofa.", "vi": "Tôi ngồi trên ghế sofa."}, {"en": "The sofa is very soft.", "vi": "Ghế sofa rất mềm."}]},
            {"word": "lamp", "meaning": "đèn", "emoji": "💡", "class": "n", "examples": [{"en": "Turn on the lamp please.", "vi": "Bật đèn lên đi."}, {"en": "The lamp gives light.", "vi": "Cái đèn chiếu sáng."}]},
            {"word": "floor", "meaning": "sàn nhà", "emoji": "🟫", "class": "n", "examples": [{"en": "I sit on the floor.", "vi": "Tôi ngồi trên sàn nhà."}, {"en": "The floor is clean.", "vi": "Sàn nhà rất sạch."}]},
            {"word": "wall", "meaning": "bức tường", "emoji": "🧱", "class": "n", "examples": [{"en": "I hang a picture on the wall.", "vi": "Tôi treo tranh lên tường."}, {"en": "The wall is white.", "vi": "Bức tường màu trắng."}]},
            {"word": "kitchen", "meaning": "nhà bếp", "emoji": "🍳", "class": "n", "examples": [{"en": "Mum cooks in the kitchen.", "vi": "Mẹ nấu ăn trong bếp."}, {"en": "The kitchen smells good.", "vi": "Nhà bếp thơm mùi đồ ăn."}]},
            {"word": "bathroom", "meaning": "phòng tắm", "emoji": "🚿", "class": "n", "examples": [{"en": "I wash in the bathroom.", "vi": "Tôi tắm trong phòng tắm."}, {"en": "The bathroom is small.", "vi": "Phòng tắm nhỏ."}]},
            {"word": "garden", "meaning": "vườn", "emoji": "🌿", "class": "n", "examples": [{"en": "I play in the garden.", "vi": "Tôi chơi trong vườn."}, {"en": "The garden has many flowers.", "vi": "Khu vườn có nhiều hoa."}]},
            {"word": "stairs", "meaning": "cầu thang", "emoji": "🪜", "class": "n", "examples": [{"en": "I walk up the stairs.", "vi": "Tôi đi lên cầu thang."}, {"en": "Be careful on the stairs.", "vi": "Cẩn thận khi đi cầu thang nhé."}]},
            {"word": "shelf", "meaning": "kệ sách", "emoji": "📚", "class": "n", "examples": [{"en": "I put my books on the shelf.", "vi": "Tôi để sách lên kệ."}, {"en": "The shelf is full of books.", "vi": "Kệ sách đầy sách."}]},
            {"word": "mirror", "meaning": "gương", "emoji": "🪞", "class": "n", "examples": [{"en": "I look in the mirror.", "vi": "Tôi nhìn vào gương."}, {"en": "The mirror is big.", "vi": "Cái gương rất to."}]},
            {"word": "clock", "meaning": "đồng hồ", "emoji": "🕐", "class": "n", "examples": [{"en": "The clock is on the wall.", "vi": "Đồng hồ treo trên tường."}, {"en": "The clock says eight.", "vi": "Đồng hồ chỉ tám giờ."}]},
            {"word": "cup", "meaning": "cốc/ly", "emoji": "☕", "class": "n", "examples": [{"en": "I drink from my cup.", "vi": "Tôi uống từ cái cốc."}, {"en": "The cup is full of water.", "vi": "Cái cốc đầy nước."}]},
        ]
    },
    {
        "id": "my-face",
        "name": "Khuôn Mặt & Cơ Thể",
        "emoji": "🙂",
        "color": "pink",
        "words": [
            {"word": "forehead", "meaning": "trán", "emoji": "😐", "class": "n", "examples": [{"en": "She has a big forehead.", "vi": "Cô ấy có cái trán rộng."}, {"en": "I touch my forehead.", "vi": "Tôi chạm vào trán mình."}]},
            {"word": "cheek", "meaning": "má", "emoji": "🥰", "class": "n", "examples": [{"en": "Grandma kisses my cheek.", "vi": "Bà hôn vào má tôi."}, {"en": "Her cheeks are pink.", "vi": "Má cô ấy hồng hào."}]},
            {"word": "chin", "meaning": "cằm", "emoji": "😑", "class": "n", "examples": [{"en": "He has a strong chin.", "vi": "Anh ấy có cái cằm vuông."}, {"en": "I touch my chin.", "vi": "Tôi chạm vào cằm mình."}]},
            {"word": "lip", "meaning": "môi", "emoji": "💋", "class": "n", "examples": [{"en": "Her lips are red.", "vi": "Môi cô ấy màu đỏ."}, {"en": "I smile with my lips.", "vi": "Tôi mỉm cười bằng đôi môi."}]},
            {"word": "tooth", "meaning": "răng", "emoji": "🦷", "class": "n", "examples": [{"en": "I brush my teeth.", "vi": "Tôi đánh răng."}, {"en": "The tooth fairy takes my tooth.", "vi": "Nàng tiên răng lấy chiếc răng của tôi."}]},
            {"word": "tongue", "meaning": "lưỡi", "emoji": "👅", "class": "n", "examples": [{"en": "I taste food with my tongue.", "vi": "Tôi nếm thức ăn bằng lưỡi."}, {"en": "The dog's tongue is pink.", "vi": "Lưỡi của con chó màu hồng."}]},
            {"word": "eyebrow", "meaning": "lông mày", "emoji": "🤨", "class": "n", "examples": [{"en": "She raises her eyebrow.", "vi": "Cô ấy nhướn lông mày."}, {"en": "He has thick eyebrows.", "vi": "Anh ấy có đôi lông mày rậm."}]},
            {"word": "eyelash", "meaning": "lông mi", "emoji": "👁️", "class": "n", "examples": [{"en": "She has long eyelashes.", "vi": "Cô ấy có hàng lông mi dài."}, {"en": "An eyelash fell on my cheek.", "vi": "Một sợi lông mi rơi xuống má tôi."}]},
            {"word": "finger", "meaning": "ngón tay", "emoji": "☝️", "class": "n", "examples": [{"en": "I point with my finger.", "vi": "Tôi chỉ bằng ngón tay."}, {"en": "I have ten fingers.", "vi": "Tôi có mười ngón tay."}]},
            {"word": "toe", "meaning": "ngón chân", "emoji": "🦶", "class": "n", "examples": [{"en": "I wiggle my toes.", "vi": "Tôi cử động các ngón chân."}, {"en": "I have ten toes.", "vi": "Tôi có mười ngón chân."}]},
            {"word": "knee", "meaning": "đầu gối", "emoji": "🦵", "class": "n", "examples": [{"en": "My knee hurts.", "vi": "Đầu gối tôi bị đau."}, {"en": "I bend my knee.", "vi": "Tôi cúi gập đầu gối."}]},
            {"word": "nail", "meaning": "móng tay", "emoji": "💅", "class": "n", "examples": [{"en": "I cut my nails.", "vi": "Tôi cắt móng tay."}, {"en": "Her nails are pink.", "vi": "Móng tay của cô ấy màu hồng."}]},
            {"word": "wrist", "meaning": "cổ tay", "emoji": "⌚", "class": "n", "examples": [{"en": "I wear a watch on my wrist.", "vi": "Tôi đeo đồng hồ ở cổ tay."}, {"en": "My wrist is small.", "vi": "Cổ tay tôi nhỏ."}]},
            {"word": "thumb", "meaning": "ngón cái", "emoji": "👍", "class": "n", "examples": [{"en": "I give a thumbs up.", "vi": "Tôi giơ ngón cái lên."}, {"en": "My thumb is the biggest finger.", "vi": "Ngón cái là ngón to nhất."}]},
            {"word": "neck", "meaning": "cổ", "emoji": "🧣", "class": "n", "examples": [{"en": "I wear a scarf on my neck.", "vi": "Tôi quàng khăn ở cổ."}, {"en": "A giraffe has a long neck.", "vi": "Hươu cao cổ có cái cổ rất dài."}]},
        ]
    },
    {
        "id": "weather-basic",
        "name": "Thời Tiết",
        "emoji": "⛅",
        "color": "sky",
        "words": [
            {"word": "sun", "meaning": "mặt trời", "emoji": "☀️", "class": "n", "examples": [{"en": "The sun is bright today.", "vi": "Mặt trời rất sáng hôm nay."}, {"en": "I play in the sun.", "vi": "Tôi chơi dưới nắng."}]},
            {"word": "rain", "meaning": "mưa", "emoji": "🌧️", "class": "n", "examples": [{"en": "I hear the rain.", "vi": "Tôi nghe thấy tiếng mưa."}, {"en": "It rains today.", "vi": "Hôm nay trời mưa."}]},
            {"word": "cloud", "meaning": "mây", "emoji": "☁️", "class": "n", "examples": [{"en": "I see a big white cloud.", "vi": "Tôi thấy một đám mây trắng to."}, {"en": "The cloud is in the sky.", "vi": "Đám mây ở trên bầu trời."}]},
            {"word": "wind", "meaning": "gió", "emoji": "💨", "class": "n", "examples": [{"en": "The wind is strong today.", "vi": "Hôm nay gió thổi rất mạnh."}, {"en": "The wind blows my hat away.", "vi": "Gió thổi bay mũ của tôi."}]},
            {"word": "snow", "meaning": "tuyết", "emoji": "❄️", "class": "n", "examples": [{"en": "I see snow outside.", "vi": "Tôi thấy tuyết bên ngoài."}, {"en": "Snow is cold and white.", "vi": "Tuyết thì lạnh và màu trắng."}]},
            {"word": "hot", "meaning": "nóng", "emoji": "🌡️", "class": "adj", "examples": [{"en": "It is hot today.", "vi": "Hôm nay trời nóng."}, {"en": "The soup is very hot.", "vi": "Bát súp rất nóng."}]},
            {"word": "cold", "meaning": "lạnh", "emoji": "🥶", "class": "adj", "examples": [{"en": "It is cold today.", "vi": "Hôm nay trời lạnh."}, {"en": "The water is very cold.", "vi": "Nước lạnh lắm."}]},
            {"word": "wet", "meaning": "ướt", "emoji": "💦", "class": "adj", "examples": [{"en": "My shoes are wet.", "vi": "Giày của tôi bị ướt."}, {"en": "The grass is wet.", "vi": "Cỏ bị ướt."}]},
            {"word": "dry", "meaning": "khô", "emoji": "🏜️", "class": "adj", "examples": [{"en": "My clothes are dry now.", "vi": "Quần áo của tôi đã khô rồi."}, {"en": "The ground is dry.", "vi": "Mặt đất khô ráo."}]},
            {"word": "storm", "meaning": "bão", "emoji": "⛈️", "class": "n", "examples": [{"en": "There is a big storm.", "vi": "Có một cơn bão lớn."}, {"en": "I stay home in a storm.", "vi": "Tôi ở nhà khi có bão."}]},
            {"word": "fog", "meaning": "sương mù", "emoji": "🌫️", "class": "n", "examples": [{"en": "There is fog this morning.", "vi": "Sáng nay có sương mù."}, {"en": "I can not see in the fog.", "vi": "Tôi không thấy gì trong sương mù."}]},
            {"word": "warm", "meaning": "ấm áp", "emoji": "🌤️", "class": "adj", "examples": [{"en": "It is warm today.", "vi": "Hôm nay trời ấm áp."}, {"en": "The sun makes me warm.", "vi": "Mặt trời làm tôi ấm áp."}]},
            {"word": "cool", "meaning": "mát mẻ", "emoji": "🌬️", "class": "adj", "examples": [{"en": "The breeze is cool.", "vi": "Làn gió mát mẻ quá."}, {"en": "It is cool in the morning.", "vi": "Buổi sáng trời mát mẻ."}]},
            {"word": "ice", "meaning": "băng đá", "emoji": "🧊", "class": "n", "examples": [{"en": "I put ice in my drink.", "vi": "Tôi bỏ đá vào nước uống."}, {"en": "Ice is very cold.", "vi": "Đá lạnh lắm."}]},
            {"word": "rainbow", "meaning": "cầu vồng", "emoji": "🌈", "class": "n", "examples": [{"en": "I see a rainbow after rain.", "vi": "Tôi thấy cầu vồng sau cơn mưa."}, {"en": "The rainbow has many colors.", "vi": "Cầu vồng có nhiều màu sắc."}]},
        ]
    },
    {
        "id": "common-fruits",
        "name": "Trái Cây",
        "emoji": "🍎",
        "color": "red",
        "words": [
            {"word": "mango", "meaning": "xoài", "emoji": "🥭", "class": "n", "examples": [{"en": "I eat a sweet mango.", "vi": "Tôi ăn một quả xoài ngọt."}, {"en": "The mango is yellow.", "vi": "Quả xoài màu vàng."}]},
            {"word": "grape", "meaning": "nho", "emoji": "🍇", "class": "n", "examples": [{"en": "I eat green grapes.", "vi": "Tôi ăn nho xanh."}, {"en": "Grapes grow on a vine.", "vi": "Nho mọc trên dây leo."}]},
            {"word": "strawberry", "meaning": "dâu tây", "emoji": "🍓", "class": "n", "examples": [{"en": "The strawberry is red and sweet.", "vi": "Quả dâu tây đỏ và ngọt."}, {"en": "I love strawberries.", "vi": "Tôi rất thích dâu tây."}]},
            {"word": "watermelon", "meaning": "dưa hấu", "emoji": "🍉", "class": "n", "examples": [{"en": "I eat cold watermelon.", "vi": "Tôi ăn dưa hấu lạnh."}, {"en": "Watermelon is red inside.", "vi": "Dưa hấu màu đỏ bên trong."}]},
            {"word": "pineapple", "meaning": "dứa/thơm", "emoji": "🍍", "class": "n", "examples": [{"en": "The pineapple is sweet.", "vi": "Quả dứa rất ngọt."}, {"en": "Pineapple has a green top.", "vi": "Quả dứa có chỏm xanh ở trên."}]},
            {"word": "peach", "meaning": "đào", "emoji": "🍑", "class": "n", "examples": [{"en": "The peach is soft.", "vi": "Quả đào mềm mại."}, {"en": "I eat a peach.", "vi": "Tôi ăn một quả đào."}]},
            {"word": "pear", "meaning": "lê", "emoji": "🍐", "class": "n", "examples": [{"en": "The pear is green.", "vi": "Quả lê màu xanh."}, {"en": "I eat a sweet pear.", "vi": "Tôi ăn một quả lê ngọt."}]},
            {"word": "lemon", "meaning": "chanh vàng", "emoji": "🍋", "class": "n", "examples": [{"en": "The lemon is sour.", "vi": "Quả chanh rất chua."}, {"en": "I put lemon in my drink.", "vi": "Tôi bỏ chanh vào nước uống."}]},
            {"word": "cherry", "meaning": "anh đào", "emoji": "🍒", "class": "n", "examples": [{"en": "I eat two cherries.", "vi": "Tôi ăn hai quả anh đào."}, {"en": "Cherries are red and small.", "vi": "Anh đào đỏ và nhỏ."}]},
            {"word": "coconut", "meaning": "dừa", "emoji": "🥥", "class": "n", "examples": [{"en": "I drink coconut water.", "vi": "Tôi uống nước dừa."}, {"en": "The coconut is brown.", "vi": "Quả dừa màu nâu."}]},
            {"word": "papaya", "meaning": "đu đủ", "emoji": "🍈", "class": "n", "examples": [{"en": "Papaya is orange inside.", "vi": "Đu đủ màu cam bên trong."}, {"en": "I eat fresh papaya.", "vi": "Tôi ăn đu đủ tươi."}]},
            {"word": "plum", "meaning": "mận", "emoji": "🟣", "class": "n", "examples": [{"en": "The plum is purple.", "vi": "Quả mận màu tím."}, {"en": "I eat a sweet plum.", "vi": "Tôi ăn một quả mận ngọt."}]},
            {"word": "melon", "meaning": "dưa lưới", "emoji": "🫐", "class": "n", "examples": [{"en": "The melon is sweet.", "vi": "Quả dưa lưới rất ngọt."}, {"en": "Melon is green outside.", "vi": "Dưa lưới màu xanh bên ngoài."}]},
            {"word": "kiwi", "meaning": "kiwi", "emoji": "🥝", "class": "n", "examples": [{"en": "The kiwi is green inside.", "vi": "Quả kiwi màu xanh bên trong."}, {"en": "Kiwi is sour and sweet.", "vi": "Kiwi vừa chua vừa ngọt."}]},
            {"word": "lychee", "meaning": "vải thiều", "emoji": "🔴", "class": "n", "examples": [{"en": "I eat lychee in summer.", "vi": "Tôi ăn vải thiều vào mùa hè."}, {"en": "Lychee is sweet.", "vi": "Vải thiều rất ngọt."}]},
        ]
    },
    {
        "id": "basic-vegetables",
        "name": "Rau Củ",
        "emoji": "🥦",
        "color": "green",
        "words": [
            {"word": "carrot", "meaning": "cà rốt", "emoji": "🥕", "class": "n", "examples": [{"en": "The carrot is orange.", "vi": "Củ cà rốt màu cam."}, {"en": "My rabbit eats carrots.", "vi": "Con thỏ của tôi ăn cà rốt."}]},
            {"word": "tomato", "meaning": "cà chua", "emoji": "🍅", "class": "n", "examples": [{"en": "The tomato is red.", "vi": "Quả cà chua màu đỏ."}, {"en": "I eat tomatoes in salad.", "vi": "Tôi ăn cà chua trong salad."}]},
            {"word": "potato", "meaning": "khoai tây", "emoji": "🥔", "class": "n", "examples": [{"en": "I eat potato chips.", "vi": "Tôi ăn khoai tây chiên."}, {"en": "The potato is brown.", "vi": "Củ khoai tây màu nâu."}]},
            {"word": "onion", "meaning": "hành tây", "emoji": "🧅", "class": "n", "examples": [{"en": "Onion makes me cry.", "vi": "Hành tây làm tôi chảy nước mắt."}, {"en": "Mum cooks with onion.", "vi": "Mẹ nấu ăn với hành tây."}]},
            {"word": "corn", "meaning": "ngô/bắp", "emoji": "🌽", "class": "n", "examples": [{"en": "I eat sweet corn.", "vi": "Tôi ăn ngô ngọt."}, {"en": "The corn is yellow.", "vi": "Bắp ngô màu vàng."}]},
            {"word": "bean", "meaning": "đậu", "emoji": "🫘", "class": "n", "examples": [{"en": "I eat green beans.", "vi": "Tôi ăn đậu xanh."}, {"en": "Beans are good for me.", "vi": "Đậu rất tốt cho sức khỏe."}]},
            {"word": "pea", "meaning": "đậu Hà Lan", "emoji": "🟢", "class": "n", "examples": [{"en": "Peas are small and green.", "vi": "Đậu Hà Lan nhỏ và màu xanh."}, {"en": "I eat peas with rice.", "vi": "Tôi ăn đậu Hà Lan với cơm."}]},
            {"word": "cabbage", "meaning": "bắp cải", "emoji": "🥬", "class": "n", "examples": [{"en": "The cabbage is green.", "vi": "Bắp cải màu xanh."}, {"en": "I eat cabbage soup.", "vi": "Tôi ăn canh bắp cải."}]},
            {"word": "cucumber", "meaning": "dưa chuột", "emoji": "🥒", "class": "n", "examples": [{"en": "The cucumber is long and green.", "vi": "Quả dưa chuột dài và màu xanh."}, {"en": "I eat cucumber in salad.", "vi": "Tôi ăn dưa chuột trong salad."}]},
            {"word": "mushroom", "meaning": "nấm", "emoji": "🍄", "class": "n", "examples": [{"en": "The mushroom is white.", "vi": "Cây nấm màu trắng."}, {"en": "I eat mushroom soup.", "vi": "Tôi ăn canh nấm."}]},
            {"word": "pumpkin", "meaning": "bí ngô", "emoji": "🎃", "class": "n", "examples": [{"en": "The pumpkin is orange.", "vi": "Quả bí ngô màu cam."}, {"en": "I eat pumpkin soup.", "vi": "Tôi ăn canh bí ngô."}]},
            {"word": "garlic", "meaning": "tỏi", "emoji": "🧄", "class": "n", "examples": [{"en": "Mum uses garlic to cook.", "vi": "Mẹ dùng tỏi để nấu ăn."}, {"en": "Garlic has a strong smell.", "vi": "Tỏi có mùi rất nồng."}]},
            {"word": "ginger", "meaning": "gừng", "emoji": "🫚", "class": "n", "examples": [{"en": "I drink ginger tea.", "vi": "Tôi uống trà gừng."}, {"en": "Ginger is spicy.", "vi": "Gừng có vị cay."}]},
            {"word": "spinach", "meaning": "rau bina", "emoji": "🥗", "class": "n", "examples": [{"en": "Spinach is green.", "vi": "Rau bina màu xanh."}, {"en": "I eat spinach to be strong.", "vi": "Tôi ăn rau bina để khỏe mạnh."}]},
            {"word": "chili", "meaning": "ớt", "emoji": "🌶️", "class": "n", "examples": [{"en": "The chili is very spicy.", "vi": "Quả ớt rất cay."}, {"en": "Chili is red.", "vi": "Ớt màu đỏ."}]},
        ]
    },
]

if __name__ == "__main__":
    import json
    print(f"Topics 1-15: {len(SEEKER_TOPICS_1_15)} topics")
    total = sum(len(t["words"]) for t in SEEKER_TOPICS_1_15)
    print(f"Total words: {total}")
