#!/usr/bin/env node
/**
 * Export phonics data to Markdown for QC.
 *
 * Usage:
 *   node scripts/export-phonics.js
 *
 * Output: exports/phonics-audit/phonics.md
 *
 * Format is parseable by import-phonics.js to round-trip back to JSON.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const levelsPath = path.join(ROOT, 'data', 'phonicsLevels.json');
const knowledgePath = path.join(ROOT, 'data', 'phonicsKnowledge.json');
const outDir = path.join(ROOT, 'exports', 'phonics-audit');
const outPath = path.join(outDir, 'phonics.md');

fs.mkdirSync(outDir, { recursive: true });

const levels = JSON.parse(fs.readFileSync(levelsPath, 'utf8'));
const knowledge = JSON.parse(fs.readFileSync(knowledgePath, 'utf8'));

const lines = [];

function line(s = '') { lines.push(s); }

// ── Knowledge section (pair/consonant/challenge type) ─────────────────────────
// Fields: how_to, vs_vietnamese, spelling, mistakes, mnemonic
function exportKnowledgePair(k) {
  line('### KNOWLEDGE');
  line();

  line('**how_to:**');
  for (const item of k.how_to) line(`- ${item}`);
  line();

  line(`**vs_vietnamese:** ${k.vs_vietnamese}`);
  line();

  if (k.spelling?.length) {
    line('**spelling:**');
    for (const s of k.spelling) {
      line(`- ${s.pattern} | ${s.examples.join(', ')}`);
    }
    line();
  }

  if (k.mistakes?.length) {
    line('**mistakes:**');
    for (const m of k.mistakes) line(`- ${m}`);
    line();
  }

  if (k.mnemonic) {
    line(`**mnemonic:** ${k.mnemonic}`);
    line();
  }
}

// ── Knowledge section (rule/intonation type) ──────────────────────────────────
// Fields: why, how_to, exceptions, vs_vietnamese
function exportKnowledgeRule(k) {
  line('### KNOWLEDGE');
  line();

  if (k.why) {
    line(`**why:** ${k.why}`);
    line();
  }

  line('**how_to:**');
  for (const item of k.how_to) line(`- ${item}`);
  line();

  if (k.exceptions?.length) {
    line('**exceptions:**');
    for (const e of k.exceptions) line(`- ${e}`);
    line();
  }

  line(`**vs_vietnamese:** ${k.vs_vietnamese}`);
  line();
}

// ── Practice section (pair type) ──────────────────────────────────────────────
function exportPractice(lesson) {
  line('### PRACTICE');
  line();

  if (lesson.tip) {
    line(`**tip:** ${lesson.tip}`);
    line();
  }

  if (lesson.practice_words?.length) {
    line(`**practice_words:** ${lesson.practice_words.join(', ')}`);
    line();
  }

  if (lesson.practice_sentences?.length) {
    line('**practice_sentences:**');
    lesson.practice_sentences.forEach((s, i) => {
      const highlights = s.highlight?.length ? ` [${s.highlight.join(', ')}]` : '';
      line(`${i + 1}. ${s.en}${highlights}`);
    });
    line();
  }
}

// ── Sentences section (rhythm type) ──────────────────────────────────────────
function exportRhythmSentences(lesson) {
  line('### PRACTICE');
  line();
  if (lesson.sentences?.length) {
    line('**sentences:**');
    lesson.sentences.forEach((s, i) => {
      const stressed = s.stressed?.length ? ` [stressed: ${s.stressed.join(', ')}]` : '';
      const vi = s.vi ? ` [vi: ${s.vi}]` : '';
      line(`${i + 1}. ${s.en}${stressed}${vi}`);
    });
    line();
  }
}

// ── Buckets section (rule type) ───────────────────────────────────────────────
function exportBuckets(lesson) {
  line('### BUCKETS');
  line();

  for (const bucket of (lesson.buckets || [])) {
    line(`#### BUCKET: ${bucket.label}`);
    line(`condition: ${bucket.condition}`);
    if (bucket.tip) line(`tip: ${bucket.tip}`);
    line(`words: ${bucket.words.join(' | ')}`);
    line();
  }
}

// ── Main export ───────────────────────────────────────────────────────────────
line('<!-- phonics-qc.md — generated by scripts/export-phonics.js -->');
line('<!-- Edit this file for QC, then run scripts/import-phonics.js to write back to JSON -->');
line();

let totalLessons = 0;
let missingKnowledge = [];

for (const level of levels.levels) {
  line(`# LEVEL: ${level.id} — ${level.title}`);
  line();

  for (const lesson of level.lessons) {
    totalLessons++;
    const k = knowledge[lesson.id];

    line('---');
    line(`## LESSON: ${lesson.id} | type: ${lesson.type} | ${lesson.title}`);
    line();

    if (!k) {
      missingKnowledge.push(lesson.id);
      line('> ⚠️ NO KNOWLEDGE ENTRY FOUND');
      line();
      continue;
    }

    // Knowledge section
    if (lesson.type === 'rule') {
      exportKnowledgeRule(k);
    } else {
      exportKnowledgePair(k);
    }

    // Practice/Buckets section
    if (lesson.type === 'rule') {
      exportBuckets(lesson);
    } else if (lesson.type === 'rhythm') {
      exportRhythmSentences(lesson);
    } else {
      exportPractice(lesson);
    }
  }

  line();
}

fs.writeFileSync(outPath, lines.join('\n'), 'utf8');

console.log(`✅ Exported ${totalLessons} lessons → exports/phonics-audit/phonics.md`);
if (missingKnowledge.length) {
  console.warn(`⚠️  Missing knowledge entries: ${missingKnowledge.join(', ')}`);
}
