import json, os

topics_21_30 = [
  {
    "id": "language-communication",
    "name": "Ngôn Ngữ & Giao Tiếp",
    "emoji": "🗣️",
    "color": "blue",
    "words": [
      {"word": "linguistics", "meaning": "ngôn ngữ học", "emoji": "🔤", "class": "n",
       "examples": [{"en": "Linguistics is the scientific study of language and its structure.", "vi": "Ngôn ngữ học là nghiên cứu khoa học về ngôn ngữ và cấu trúc của nó."},
                    {"en": "She majored in linguistics at university.", "vi": "Cô ấy học chuyên ngành ngôn ngữ học tại trường đại học."}]},
      {"word": "dialect", "meaning": "phương ngữ, tiếng địa phương", "emoji": "🗺️", "class": "n",
       "examples": [{"en": "Different regions of the country speak distinct dialects.", "vi": "Các vùng khác nhau của đất nước nói các phương ngữ khác nhau."},
                    {"en": "The dialect of this village has its own unique vocabulary.", "vi": "Phương ngữ của làng này có từ vựng đặc trưng riêng."}]},
      {"word": "fluency", "meaning": "sự thông thạo ngôn ngữ", "emoji": "💬", "class": "n",
       "examples": [{"en": "She achieved fluency in Mandarin after living in Beijing for two years.", "vi": "Cô đạt được sự thông thạo tiếng Quan Thoại sau khi sống ở Bắc Kinh hai năm."},
                    {"en": "Reading widely is one of the best ways to develop fluency.", "vi": "Đọc nhiều là một trong những cách tốt nhất để phát triển sự thông thạo."}]},
      {"word": "rhetoric", "meaning": "tu từ học, nghệ thuật hùng biện", "emoji": "🎙️", "class": "n",
       "examples": [{"en": "Politicians use rhetoric to persuade and motivate voters.", "vi": "Các chính trị gia sử dụng tu từ để thuyết phục và động viên cử tri."},
                    {"en": "She studied classical rhetoric to improve her public speaking.", "vi": "Cô nghiên cứu tu từ học cổ điển để cải thiện kỹ năng nói trước công chúng."}]},
      {"word": "eloquent", "meaning": "hùng hồn, diễn đạt lưu loát", "emoji": "✨", "class": "adj",
       "examples": [{"en": "His eloquent speech moved the audience to tears.", "vi": "Bài phát biểu hùng hồn của ông khiến khán giả rơi nước mắt."},
                    {"en": "An eloquent writer can express complex ideas with clarity and grace.", "vi": "Một nhà văn hùng hồn có thể diễn đạt các ý tưởng phức tạp một cách rõ ràng và duyên dáng."}]},
      {"word": "nuance", "meaning": "sắc thái tinh tế", "emoji": "🎨", "class": "n",
       "examples": [{"en": "The translator tried to capture every nuance of the original text.", "vi": "Dịch giả cố gắng nắm bắt mọi sắc thái của văn bản gốc."},
                    {"en": "Understanding cultural nuances is essential for effective communication.", "vi": "Hiểu các sắc thái văn hóa là điều cần thiết cho giao tiếp hiệu quả."}]},
      {"word": "bilingual", "meaning": "song ngữ", "emoji": "🌐", "class": "adj",
       "examples": [{"en": "Bilingual children often perform better in tasks requiring attention.", "vi": "Trẻ em song ngữ thường làm tốt hơn trong các nhiệm vụ đòi hỏi sự chú ý."},
                    {"en": "She grew up bilingual, speaking both English and French at home.", "vi": "Cô lớn lên nói song ngữ, nói cả tiếng Anh và tiếng Pháp ở nhà."}]},
      {"word": "discourse", "meaning": "diễn ngôn, hội thoại học thuật", "emoji": "💭", "class": "n",
       "examples": [{"en": "Public discourse on climate change has become increasingly polarized.", "vi": "Diễn ngôn công cộng về biến đổi khí hậu ngày càng phân cực."},
                    {"en": "Academic discourse requires formal language and logical argument.", "vi": "Diễn ngôn học thuật đòi hỏi ngôn ngữ trang trọng và lập luận logic."}]},
      {"word": "ambiguous", "meaning": "mơ hồ, có nhiều nghĩa", "emoji": "❓", "class": "adj",
       "examples": [{"en": "The instructions were ambiguous, so students interpreted them differently.", "vi": "Hướng dẫn mơ hồ nên học sinh hiểu chúng theo cách khác nhau."},
                    {"en": "Avoid ambiguous language when writing legal documents.", "vi": "Tránh ngôn ngữ mơ hồ khi viết tài liệu pháp lý."}]},
      {"word": "articulate", "meaning": "diễn đạt rõ ràng, mạch lạc", "emoji": "🎯", "class": "adj",
       "examples": [{"en": "She is very articulate and explains ideas clearly.", "vi": "Cô ấy rất mạch lạc và giải thích ý tưởng một cách rõ ràng."},
                    {"en": "Being articulate in job interviews greatly improves your chances.", "vi": "Diễn đạt rõ ràng trong phỏng vấn xin việc cải thiện đáng kể cơ hội của bạn."}]},
      {"word": "convey", "meaning": "truyền đạt, diễn đạt", "emoji": "📨", "class": "v",
       "examples": [{"en": "A good photograph can convey emotions without words.", "vi": "Một bức ảnh tốt có thể truyền đạt cảm xúc mà không cần lời nói."},
                    {"en": "It can be difficult to convey sarcasm in a written message.", "vi": "Khó có thể truyền đạt sự mỉa mai trong một tin nhắn viết."}]},
      {"word": "syntax", "meaning": "cú pháp", "emoji": "🔡", "class": "n",
       "examples": [{"en": "Understanding syntax helps you form grammatically correct sentences.", "vi": "Hiểu cú pháp giúp bạn tạo thành các câu đúng ngữ pháp."},
                    {"en": "The syntax of English differs greatly from that of Vietnamese.", "vi": "Cú pháp tiếng Anh khác nhiều so với tiếng Việt."}]},
      {"word": "etymology", "meaning": "từ nguyên học", "emoji": "🔍", "class": "n",
       "examples": [{"en": "The etymology of the word 'music' traces back to ancient Greek.", "vi": "Từ nguyên của từ 'music' có thể truy nguyên về tiếng Hy Lạp cổ đại."},
                    {"en": "Studying etymology helps you guess the meaning of unfamiliar words.", "vi": "Nghiên cứu từ nguyên giúp bạn đoán nghĩa của những từ chưa quen."}]},
    ]
  },
  {
    "id": "sports-performance",
    "name": "Thể Thao & Thành Tích",
    "emoji": "🏅",
    "color": "green",
    "words": [
      {"word": "endurance", "meaning": "sức bền", "emoji": "🏃", "class": "n",
       "examples": [{"en": "Marathon runners need exceptional endurance.", "vi": "Các vận động viên chạy marathon cần sức bền xuất sắc."},
                    {"en": "Building endurance requires consistent training over months.", "vi": "Xây dựng sức bền đòi hỏi huấn luyện đều đặn trong nhiều tháng."}]},
      {"word": "agility", "meaning": "sự nhanh nhẹn", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Agility training improves speed and coordination.", "vi": "Huấn luyện nhanh nhẹn cải thiện tốc độ và sự phối hợp."},
                    {"en": "Soccer players need both agility and stamina.", "vi": "Cầu thủ bóng đá cần cả sự nhanh nhẹn lẫn thể lực."}]},
      {"word": "tactics", "meaning": "chiến thuật", "emoji": "🧠", "class": "n",
       "examples": [{"en": "The team's tactics were to defend tightly and attack on the counter.", "vi": "Chiến thuật của đội là phòng thủ chặt chẽ và tấn công phản công."},
                    {"en": "Tactics can determine the outcome of a match as much as skill.", "vi": "Chiến thuật có thể quyết định kết quả của một trận đấu không kém gì kỹ năng."}]},
      {"word": "stamina", "meaning": "thể lực, sức chịu đựng", "emoji": "💪", "class": "n",
       "examples": [{"en": "He built up his stamina by running five kilometers every morning.", "vi": "Anh ấy tăng cường thể lực bằng cách chạy năm km mỗi sáng."},
                    {"en": "Stamina is as important as speed in competitive swimming.", "vi": "Thể lực quan trọng không kém tốc độ trong bơi lội cạnh tranh."}]},
      {"word": "tournament", "meaning": "giải đấu", "emoji": "🏆", "class": "n",
       "examples": [{"en": "Sixteen teams competed in the regional tournament.", "vi": "Mười sáu đội thi đấu trong giải đấu khu vực."},
                    {"en": "She won the national tennis tournament at just sixteen years old.", "vi": "Cô ấy giành chiến thắng giải quần vợt quốc gia khi mới mười sáu tuổi."}]},
      {"word": "championship", "meaning": "chức vô địch", "emoji": "🥇", "class": "n",
       "examples": [{"en": "They won the world championship for the third consecutive year.", "vi": "Họ giành chức vô địch thế giới năm thứ ba liên tiếp."},
                    {"en": "The championship game attracted millions of viewers worldwide.", "vi": "Trận chung kết thu hút hàng triệu khán giả trên toàn thế giới."}]},
      {"word": "qualify", "meaning": "đủ tiêu chuẩn (thi đấu)", "emoji": "✅", "class": "v",
       "examples": [{"en": "Only the top three teams will qualify for the finals.", "vi": "Chỉ ba đội đứng đầu sẽ đủ tiêu chuẩn vào vòng chung kết."},
                    {"en": "She trained hard to qualify for the Olympic Games.", "vi": "Cô ấy luyện tập chăm chỉ để đủ tiêu chuẩn tham dự Thế vận hội Olympic."}]},
      {"word": "athlete", "meaning": "vận động viên", "emoji": "🏋️", "class": "n",
       "examples": [{"en": "Elite athletes dedicate their lives to their sport.", "vi": "Các vận động viên đỉnh cao dành cả cuộc đời cho môn thể thao của mình."},
                    {"en": "The young athlete broke the national record in the 100-meter sprint.", "vi": "Vận động viên trẻ phá kỷ lục quốc gia trong nội dung chạy 100 mét."}]},
      {"word": "competitive", "meaning": "cạnh tranh, có tinh thần thi đấu", "emoji": "🔥", "class": "adj",
       "examples": [{"en": "She has always been highly competitive and hates losing.", "vi": "Cô ấy luôn rất cạnh tranh và ghét thua cuộc."},
                    {"en": "The competitive nature of professional sport can cause burnout.", "vi": "Tính chất cạnh tranh của thể thao chuyên nghiệp có thể gây ra kiệt sức."}]},
      {"word": "sportsmanship", "meaning": "tinh thần thể thao", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Good sportsmanship means respecting opponents, win or lose.", "vi": "Tinh thần thể thao tốt có nghĩa là tôn trọng đối thủ, dù thắng hay thua."},
                    {"en": "The coach taught his players the value of sportsmanship.", "vi": "Huấn luyện viên dạy các cầu thủ giá trị của tinh thần thể thao."}]},
      {"word": "record", "meaning": "kỷ lục", "emoji": "📊", "class": "n",
       "examples": [{"en": "Usain Bolt holds the world record for the 100-meter sprint.", "vi": "Usain Bolt giữ kỷ lục thế giới nội dung chạy 100 mét."},
                    {"en": "She set a new school record in the long jump competition.", "vi": "Cô ấy lập kỷ lục trường mới trong cuộc thi nhảy xa."}]},
      {"word": "performance", "meaning": "thành tích, hiệu suất", "emoji": "⭐", "class": "n",
       "examples": [{"en": "The athlete's performance improved significantly after changing coaches.", "vi": "Thành tích của vận động viên cải thiện đáng kể sau khi thay huấn luyện viên."},
                    {"en": "Peak performance requires both physical and mental preparation.", "vi": "Thành tích đỉnh cao đòi hỏi cả sự chuẩn bị thể chất và tinh thần."}]},
      {"word": "training", "meaning": "huấn luyện, luyện tập", "emoji": "🏋️", "class": "n",
       "examples": [{"en": "Intense training for months prepared her for the marathon.", "vi": "Luyện tập cường độ cao trong nhiều tháng chuẩn bị cho cô ấy chạy marathon."},
                    {"en": "Strength training builds muscle and improves overall fitness.", "vi": "Luyện tập sức mạnh giúp phát triển cơ bắp và cải thiện thể lực tổng thể."}]},
    ]
  },
  {
    "id": "history-civilization",
    "name": "Lịch Sử & Văn Minh",
    "emoji": "🏺",
    "color": "amber",
    "words": [
      {"word": "empire", "meaning": "đế chế", "emoji": "👑", "class": "n",
       "examples": [{"en": "The Roman Empire lasted for over five hundred years.", "vi": "Đế chế La Mã tồn tại hơn năm trăm năm."},
                    {"en": "At its peak, the British Empire covered a quarter of the globe.", "vi": "Vào thời đỉnh cao, Đế chế Anh bao phủ một phần tư toàn cầu."}]},
      {"word": "dynasty", "meaning": "triều đại", "emoji": "🏯", "class": "n",
       "examples": [{"en": "The Ming Dynasty is famous for its porcelain and the Great Wall.", "vi": "Triều đại Minh nổi tiếng với đồ sứ và Vạn Lý Trường Thành."},
                    {"en": "Each dynasty left its mark on the country's culture and architecture.", "vi": "Mỗi triều đại để lại dấu ấn trên văn hóa và kiến trúc của đất nước."}]},
      {"word": "colonialism", "meaning": "chủ nghĩa thực dân", "emoji": "⚓", "class": "n",
       "examples": [{"en": "Colonialism had lasting effects on the economies of developing nations.", "vi": "Chủ nghĩa thực dân để lại hậu quả lâu dài đối với nền kinh tế của các nước đang phát triển."},
                    {"en": "The legacy of colonialism is still felt in many parts of the world.", "vi": "Di sản của chủ nghĩa thực dân vẫn còn được cảm nhận ở nhiều nơi trên thế giới."}]},
      {"word": "revolution", "meaning": "cách mạng", "emoji": "✊", "class": "n",
       "examples": [{"en": "The Industrial Revolution transformed economies worldwide.", "vi": "Cuộc Cách mạng Công nghiệp đã biến đổi nền kinh tế trên toàn thế giới."},
                    {"en": "The French Revolution changed the political landscape of Europe.", "vi": "Cách mạng Pháp đã thay đổi bức tranh chính trị châu Âu."}]},
      {"word": "archaeology", "meaning": "khảo cổ học", "emoji": "⛏️", "class": "n",
       "examples": [{"en": "Archaeology helps us understand how ancient peoples lived.", "vi": "Khảo cổ học giúp chúng ta hiểu cách mà các dân tộc cổ đại sinh sống."},
                    {"en": "Archaeologists discovered an ancient city buried beneath the sand.", "vi": "Các nhà khảo cổ học phát hiện một thành phố cổ đại bị chôn vùi dưới cát."}]},
      {"word": "artifact", "meaning": "hiện vật lịch sử", "emoji": "🏺", "class": "n",
       "examples": [{"en": "The museum displays thousands of artifacts from ancient Egypt.", "vi": "Bảo tàng trưng bày hàng nghìn hiện vật từ Ai Cập cổ đại."},
                    {"en": "A bronze artifact discovered in the ruins was over 3,000 years old.", "vi": "Một hiện vật đồng phát hiện trong đống đổ nát đã hơn 3.000 năm tuổi."}]},
      {"word": "conquest", "meaning": "cuộc chinh phục", "emoji": "⚔️", "class": "n",
       "examples": [{"en": "Alexander the Great's conquest of Persia changed ancient history.", "vi": "Cuộc chinh phục Ba Tư của Alexander Đại đế đã thay đổi lịch sử cổ đại."},
                    {"en": "The conquest brought new languages and religions to the region.", "vi": "Cuộc chinh phục mang đến các ngôn ngữ và tôn giáo mới cho khu vực."}]},
      {"word": "feudal", "meaning": "phong kiến", "emoji": "🏰", "class": "adj",
       "examples": [{"en": "Under the feudal system, peasants worked the land for lords.", "vi": "Dưới chế độ phong kiến, nông dân canh tác đất đai cho các lãnh chúa."},
                    {"en": "Feudal societies were organized around a strict hierarchy.", "vi": "Các xã hội phong kiến được tổ chức xung quanh một hệ thống cấp bậc nghiêm ngặt."}]},
      {"word": "legacy", "meaning": "di sản (lịch sử)", "emoji": "🎗️", "class": "n",
       "examples": [{"en": "The legacy of the civil rights movement continues to shape society.", "vi": "Di sản của phong trào quyền dân sự tiếp tục định hình xã hội."},
                    {"en": "Leaders are often judged by the legacy they leave behind.", "vi": "Các nhà lãnh đạo thường được đánh giá bằng di sản họ để lại."}]},
      {"word": "civilization", "meaning": "nền văn minh", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Ancient Mesopotamia is often called the cradle of civilization.", "vi": "Lưỡng Hà cổ đại thường được gọi là cái nôi của văn minh."},
                    {"en": "Every civilization has developed its own language, art, and religion.", "vi": "Mỗi nền văn minh đã phát triển ngôn ngữ, nghệ thuật và tôn giáo riêng."}]},
      {"word": "monument", "meaning": "di tích lịch sử, đài tưởng niệm", "emoji": "🗽", "class": "n",
       "examples": [{"en": "The war monument was built to honor fallen soldiers.", "vi": "Đài tưởng niệm chiến tranh được xây dựng để vinh danh các chiến sĩ đã hy sinh."},
                    {"en": "Angkor Wat is both a religious site and an ancient monument.", "vi": "Angkor Wat vừa là địa điểm tôn giáo vừa là di tích cổ đại."}]},
      {"word": "uprising", "meaning": "cuộc nổi dậy", "emoji": "✊", "class": "n",
       "examples": [{"en": "The peasant uprising challenged the power of the ruling class.", "vi": "Cuộc nổi dậy của nông dân thách thức quyền lực của giai cấp thống trị."},
                    {"en": "The uprising was crushed by the army within three days.", "vi": "Cuộc nổi dậy bị quân đội dập tắt trong vòng ba ngày."}]},
      {"word": "chronology", "meaning": "niên biểu, trình tự thời gian", "emoji": "📅", "class": "n",
       "examples": [{"en": "Historians use chronology to organize events in the order they occurred.", "vi": "Các nhà sử học sử dụng niên biểu để sắp xếp các sự kiện theo thứ tự xảy ra."},
                    {"en": "The textbook provides a detailed chronology of the war.", "vi": "Sách giáo khoa cung cấp niên biểu chi tiết về cuộc chiến."}]},
    ]
  },
  {
    "id": "philosophy-ethics",
    "name": "Triết Học & Đạo Đức",
    "emoji": "🤔",
    "color": "violet",
    "words": [
      {"word": "morality", "meaning": "đạo đức, luân lý", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Morality guides our understanding of right and wrong.", "vi": "Đạo đức hướng dẫn sự hiểu biết của chúng ta về đúng và sai."},
                    {"en": "Different cultures have different standards of morality.", "vi": "Các nền văn hóa khác nhau có các tiêu chuẩn đạo đức khác nhau."}]},
      {"word": "virtue", "meaning": "đức hạnh", "emoji": "🌟", "class": "n",
       "examples": [{"en": "Honesty is considered a fundamental virtue in most cultures.", "vi": "Sự trung thực được coi là đức hạnh cơ bản ở hầu hết các nền văn hóa."},
                    {"en": "Aristotle believed that virtue was the key to a good life.", "vi": "Aristotle tin rằng đức hạnh là chìa khóa cho một cuộc sống tốt đẹp."}]},
      {"word": "dilemma", "meaning": "tình huống tiến thoái lưỡng nan", "emoji": "🔀", "class": "n",
       "examples": [{"en": "The doctor faced an ethical dilemma about how to treat the patient.", "vi": "Bác sĩ phải đối mặt với tình huống đạo đức nan giải về cách điều trị bệnh nhân."},
                    {"en": "The prisoner's dilemma is a classic problem in game theory.", "vi": "Tình huống nan giải của tù nhân là bài toán kinh điển trong lý thuyết trò chơi."}]},
      {"word": "consciousness", "meaning": "ý thức", "emoji": "🧠", "class": "n",
       "examples": [{"en": "Philosophers have debated the nature of consciousness for centuries.", "vi": "Các triết gia đã tranh luận về bản chất của ý thức trong nhiều thế kỷ."},
                    {"en": "Human consciousness allows us to reflect on our own thoughts.", "vi": "Ý thức con người cho phép chúng ta suy nghĩ về chính những suy nghĩ của mình."}]},
      {"word": "rational", "meaning": "hợp lý, có lý trí", "emoji": "💡", "class": "adj",
       "examples": [{"en": "A rational decision is based on evidence and logic rather than emotion.", "vi": "Một quyết định hợp lý dựa trên bằng chứng và logic chứ không phải cảm xúc."},
                    {"en": "Kant argued that rational beings have inherent moral worth.", "vi": "Kant lập luận rằng những sinh vật có lý trí có giá trị đạo đức vốn có."}]},
      {"word": "doctrine", "meaning": "học thuyết", "emoji": "📚", "class": "n",
       "examples": [{"en": "The doctrine of human rights underpins international law.", "vi": "Học thuyết về quyền con người là nền tảng của luật pháp quốc tế."},
                    {"en": "Religious doctrines provide moral guidance to their followers.", "vi": "Các học thuyết tôn giáo cung cấp hướng dẫn đạo đức cho tín đồ của họ."}]},
      {"word": "paradox", "meaning": "nghịch lý", "emoji": "🔄", "class": "n",
       "examples": [{"en": "The paradox of choice suggests that more options can make us less happy.", "vi": "Nghịch lý của sự lựa chọn cho thấy nhiều lựa chọn hơn có thể khiến chúng ta ít hạnh phúc hơn."},
                    {"en": "Zeno's paradox raised challenging questions about motion and infinity.", "vi": "Nghịch lý của Zeno đặt ra những câu hỏi thách thức về chuyển động và vô hạn."}]},
      {"word": "premise", "meaning": "tiền đề", "emoji": "📌", "class": "n",
       "examples": [{"en": "The argument rests on the false premise that all people are equal in ability.", "vi": "Lập luận dựa trên tiền đề sai rằng tất cả mọi người đều bình đẳng về năng lực."},
                    {"en": "A logical conclusion follows necessarily from its premises.", "vi": "Một kết luận logic tất yếu suy ra từ các tiền đề của nó."}]},
      {"word": "integrity", "meaning": "sự chính trực, liêm chính", "emoji": "🎖️", "class": "n",
       "examples": [{"en": "A leader with integrity earns the trust of the people.", "vi": "Một nhà lãnh đạo có liêm chính sẽ được lòng tin của người dân."},
                    {"en": "Academic integrity requires students to submit only their own work.", "vi": "Liêm chính học thuật đòi hỏi sinh viên chỉ nộp bài của chính mình."}]},
      {"word": "pragmatic", "meaning": "thực dụng", "emoji": "🔧", "class": "adj",
       "examples": [{"en": "A pragmatic approach focuses on what works rather than what is ideal.", "vi": "Cách tiếp cận thực dụng tập trung vào những gì hiệu quả chứ không phải những gì lý tưởng."},
                    {"en": "She took a pragmatic view, choosing the most practical solution.", "vi": "Cô ấy có cái nhìn thực dụng, chọn giải pháp thực tế nhất."}]},
      {"word": "skepticism", "meaning": "chủ nghĩa hoài nghi", "emoji": "🤨", "class": "n",
       "examples": [{"en": "Scientific skepticism encourages questioning claims without sufficient evidence.", "vi": "Chủ nghĩa hoài nghi khoa học khuyến khích đặt câu hỏi về các tuyên bố không có đủ bằng chứng."},
                    {"en": "A healthy level of skepticism protects us from misinformation.", "vi": "Mức độ hoài nghi lành mạnh bảo vệ chúng ta khỏi thông tin sai lệch."}]},
      {"word": "implication", "meaning": "hàm ý, hệ quả", "emoji": "💭", "class": "n",
       "examples": [{"en": "The implications of climate change extend far into the future.", "vi": "Hệ quả của biến đổi khí hậu kéo dài đến tận tương lai xa."},
                    {"en": "Consider all the implications before making an irreversible decision.", "vi": "Hãy cân nhắc tất cả hàm ý trước khi đưa ra quyết định không thể đảo ngược."}]},
      {"word": "utilitarianism", "meaning": "chủ nghĩa vị lợi", "emoji": "📊", "class": "n",
       "examples": [{"en": "Utilitarianism holds that actions are right if they maximize overall happiness.", "vi": "Chủ nghĩa vị lợi cho rằng hành động là đúng nếu chúng tối đa hóa hạnh phúc tổng thể."},
                    {"en": "A utilitarian would justify a painful decision if it benefits the majority.", "vi": "Một người theo chủ nghĩa vị lợi sẽ biện hộ cho một quyết định đau đớn nếu nó mang lại lợi ích cho đa số."}]},
    ]
  },
  {
    "id": "digital-society",
    "name": "Xã Hội Số",
    "emoji": "📱",
    "color": "slate",
    "words": [
      {"word": "surveillance", "meaning": "giám sát (kỹ thuật số)", "emoji": "👁️", "class": "n",
       "examples": [{"en": "Mass surveillance raises serious concerns about privacy.", "vi": "Giám sát hàng loạt gây ra lo ngại nghiêm trọng về quyền riêng tư."},
                    {"en": "Security cameras are a form of surveillance used to prevent crime.", "vi": "Camera an ninh là một hình thức giám sát được sử dụng để ngăn chặn tội phạm."}]},
      {"word": "misinformation", "meaning": "thông tin sai lệch", "emoji": "❌", "class": "n",
       "examples": [{"en": "Social media platforms struggle to stop the spread of misinformation.", "vi": "Các nền tảng mạng xã hội vật lộn để ngăn chặn sự lan truyền của thông tin sai lệch."},
                    {"en": "Health misinformation can have dangerous real-world consequences.", "vi": "Thông tin sai lệch về sức khỏe có thể gây ra hậu quả nguy hiểm trong thực tế."}]},
      {"word": "privacy", "meaning": "quyền riêng tư", "emoji": "🔒", "class": "n",
       "examples": [{"en": "Data privacy laws protect users from having their information sold.", "vi": "Luật bảo mật dữ liệu bảo vệ người dùng khỏi việc thông tin của họ bị bán."},
                    {"en": "Privacy settings allow you to control who sees your posts.", "vi": "Cài đặt quyền riêng tư cho phép bạn kiểm soát ai có thể thấy bài đăng của bạn."}]},
      {"word": "viral", "meaning": "lan truyền (trên mạng)", "emoji": "🔥", "class": "adj",
       "examples": [{"en": "The video went viral and was viewed ten million times in one day.", "vi": "Video trở nên viral và được xem mười triệu lần trong một ngày."},
                    {"en": "Creating viral content can boost a brand's visibility overnight.", "vi": "Tạo nội dung viral có thể tăng độ nhận biết thương hiệu chỉ sau một đêm."}]},
      {"word": "deepfake", "meaning": "video giả mạo bằng AI", "emoji": "🎭", "class": "n",
       "examples": [{"en": "Deepfake videos can make it appear that someone said something they never did.", "vi": "Video deepfake có thể làm cho ai đó trông như đã nói điều họ chưa bao giờ nói."},
                    {"en": "The spread of deepfakes poses a serious threat to trust in media.", "vi": "Sự lan truyền của deepfake gây ra mối đe dọa nghiêm trọng đối với niềm tin vào truyền thông."}]},
      {"word": "cyberbullying", "meaning": "bắt nạt trực tuyến", "emoji": "😢", "class": "n",
       "examples": [{"en": "Cyberbullying can cause serious psychological harm to victims.", "vi": "Bắt nạt trực tuyến có thể gây hại tâm lý nghiêm trọng cho nạn nhân."},
                    {"en": "Schools are teaching students how to recognize and report cyberbullying.", "vi": "Các trường học đang dạy học sinh cách nhận biết và báo cáo bắt nạt trực tuyến."}]},
      {"word": "influencer", "meaning": "người có tầm ảnh hưởng trên mạng", "emoji": "📸", "class": "n",
       "examples": [{"en": "Brands pay influencers to promote their products on social media.", "vi": "Các thương hiệu trả tiền cho người có tầm ảnh hưởng để quảng bá sản phẩm trên mạng xã hội."},
                    {"en": "Being a social media influencer has become a full-time career.", "vi": "Trở thành người có tầm ảnh hưởng trên mạng xã hội đã trở thành một nghề nghiệp toàn thời gian."}]},
      {"word": "streaming", "meaning": "phát trực tuyến", "emoji": "▶️", "class": "n",
       "examples": [{"en": "Streaming services have replaced traditional TV for many viewers.", "vi": "Các dịch vụ phát trực tuyến đã thay thế TV truyền thống đối với nhiều khán giả."},
                    {"en": "Live streaming allows content creators to interact with their audience in real time.", "vi": "Phát trực tiếp cho phép người tạo nội dung tương tác với khán giả theo thời gian thực."}]},
      {"word": "subscription", "meaning": "đăng ký (dịch vụ)", "emoji": "💳", "class": "n",
       "examples": [{"en": "The monthly subscription gives you access to thousands of movies.", "vi": "Đăng ký hàng tháng cho phép bạn truy cập hàng nghìn bộ phim."},
                    {"en": "Many apps have moved from one-time purchases to subscription models.", "vi": "Nhiều ứng dụng đã chuyển từ mua một lần sang mô hình đăng ký."}]},
      {"word": "anonymous", "meaning": "ẩn danh", "emoji": "🎭", "class": "adj",
       "examples": [{"en": "Anonymous online comments can be more hurtful than face-to-face criticism.", "vi": "Bình luận ẩn danh trực tuyến có thể gây tổn thương hơn sự chỉ trích trực tiếp."},
                    {"en": "The whistleblower remained anonymous to protect their identity.", "vi": "Người tố giác vẫn ẩn danh để bảo vệ danh tính của họ."}]},
      {"word": "digital divide", "meaning": "khoảng cách số", "emoji": "📵", "class": "n",
       "examples": [{"en": "The digital divide separates those with internet access from those without.", "vi": "Khoảng cách số phân chia những người có quyền truy cập internet với những người không có."},
                    {"en": "Bridging the digital divide requires investment in infrastructure.", "vi": "Thu hẹp khoảng cách số đòi hỏi đầu tư vào cơ sở hạ tầng."}]},
      {"word": "netizen", "meaning": "công dân mạng", "emoji": "🌐", "class": "n",
       "examples": [{"en": "Netizens around the world debated the controversial decision online.", "vi": "Các công dân mạng trên khắp thế giới tranh luận về quyết định gây tranh cãi trực tuyến."},
                    {"en": "Active netizens can shape public opinion through social media.", "vi": "Các công dân mạng tích cực có thể định hình dư luận qua mạng xã hội."}]},
      {"word": "moderate", "meaning": "kiểm duyệt nội dung", "emoji": "🛡️", "class": "v",
       "examples": [{"en": "Platforms are required to moderate harmful content.", "vi": "Các nền tảng được yêu cầu kiểm duyệt nội dung có hại."},
                    {"en": "It is difficult to moderate content at scale without automated tools.", "vi": "Khó có thể kiểm duyệt nội dung ở quy mô lớn mà không có công cụ tự động."}]},
    ]
  },
  {
    "id": "social-behavior",
    "name": "Hành Vi Xã Hội",
    "emoji": "👥",
    "color": "rose",
    "words": [
      {"word": "norm", "meaning": "chuẩn mực xã hội", "emoji": "📏", "class": "n",
       "examples": [{"en": "Social norms define what is considered acceptable behavior.", "vi": "Chuẩn mực xã hội xác định những gì được coi là hành vi có thể chấp nhận."},
                    {"en": "Norms vary across cultures and change over time.", "vi": "Chuẩn mực khác nhau giữa các nền văn hóa và thay đổi theo thời gian."}]},
      {"word": "conformity", "meaning": "sự tuân thủ, a dua theo số đông", "emoji": "🐑", "class": "n",
       "examples": [{"en": "Social conformity pressures people to behave like those around them.", "vi": "Áp lực tuân thủ xã hội ép mọi người hành xử như những người xung quanh."},
                    {"en": "Conformity can stifle creativity and independent thinking.", "vi": "Sự tuân thủ có thể kìm hãm sự sáng tạo và tư duy độc lập."}]},
      {"word": "peer pressure", "meaning": "áp lực đồng trang lứa", "emoji": "😰", "class": "n",
       "examples": [{"en": "Teenagers often face peer pressure to fit in with their friends.", "vi": "Thanh thiếu niên thường phải đối mặt với áp lực đồng trang lứa để hòa nhập với bạn bè."},
                    {"en": "Positive peer pressure can encourage students to work harder.", "vi": "Áp lực đồng trang lứa tích cực có thể khuyến khích học sinh học chăm hơn."}]},
      {"word": "hierarchy", "meaning": "hệ thống cấp bậc", "emoji": "📊", "class": "n",
       "examples": [{"en": "Many workplaces still have a rigid hierarchy.", "vi": "Nhiều nơi làm việc vẫn có hệ thống cấp bậc cứng nhắc."},
                    {"en": "Social hierarchy can limit opportunities for those at the bottom.", "vi": "Hệ thống cấp bậc xã hội có thể hạn chế cơ hội cho những người ở tầng thấp nhất."}]},
      {"word": "taboo", "meaning": "điều cấm kỵ", "emoji": "🚫", "class": "n",
       "examples": [{"en": "In some cultures, it is taboo to discuss money in public.", "vi": "Ở một số nền văn hóa, nói về tiền bạc ở nơi công cộng là điều cấm kỵ."},
                    {"en": "Social taboos shift over time as societies evolve.", "vi": "Các điều cấm kỵ xã hội thay đổi theo thời gian khi xã hội phát triển."}]},
      {"word": "ritual", "meaning": "nghi lễ, nghi thức", "emoji": "🕯️", "class": "n",
       "examples": [{"en": "Graduation ceremonies are a ritual that marks the transition to adulthood.", "vi": "Lễ tốt nghiệp là một nghi lễ đánh dấu sự chuyển tiếp sang tuổi trưởng thành."},
                    {"en": "Morning rituals help people start the day with focus.", "vi": "Nghi thức buổi sáng giúp mọi người bắt đầu ngày mới với sự tập trung."}]},
      {"word": "prejudice", "meaning": "thành kiến, định kiến", "emoji": "😤", "class": "n",
       "examples": [{"en": "Prejudice based on race or religion is a major social issue.", "vi": "Thành kiến dựa trên chủng tộc hoặc tôn giáo là một vấn đề xã hội lớn."},
                    {"en": "Education can help reduce prejudice by promoting understanding.", "vi": "Giáo dục có thể giúp giảm thành kiến bằng cách thúc đẩy sự hiểu biết."}]},
      {"word": "tolerance", "meaning": "sự khoan nhượng, chấp nhận", "emoji": "🤝", "class": "n",
       "examples": [{"en": "A tolerant society accepts people of different backgrounds.", "vi": "Một xã hội khoan nhượng chấp nhận những người có xuất thân khác nhau."},
                    {"en": "Tolerance does not mean agreeing with others but respecting their right to differ.", "vi": "Khoan nhượng không có nghĩa là đồng ý với người khác mà là tôn trọng quyền khác biệt của họ."}]},
      {"word": "status", "meaning": "địa vị xã hội", "emoji": "🎖️", "class": "n",
       "examples": [{"en": "Social status is often linked to wealth, education, and occupation.", "vi": "Địa vị xã hội thường gắn liền với tài sản, học vấn và nghề nghiệp."},
                    {"en": "Status symbols like expensive cars signal wealth to others.", "vi": "Các biểu tượng địa vị như xe hơi đắt tiền phát tín hiệu về sự giàu có với người khác."}]},
      {"word": "etiquette", "meaning": "phép lịch sự, quy tắc ứng xử", "emoji": "🎩", "class": "n",
       "examples": [{"en": "Business etiquette varies significantly from country to country.", "vi": "Quy tắc ứng xử kinh doanh khác nhau đáng kể từ nước này sang nước khác."},
                    {"en": "Table etiquette includes not speaking with your mouth full.", "vi": "Quy tắc bàn ăn bao gồm không nói chuyện khi miệng đầy thức ăn."}]},
      {"word": "assimilate", "meaning": "hòa nhập (vào xã hội)", "emoji": "🌐", "class": "v",
       "examples": [{"en": "Immigrants often feel pressure to assimilate into the local culture.", "vi": "Người nhập cư thường cảm thấy áp lực phải hòa nhập vào văn hóa địa phương."},
                    {"en": "Children assimilate new languages faster than adults.", "vi": "Trẻ em tiếp thu ngôn ngữ mới nhanh hơn người lớn."}]},
      {"word": "interaction", "meaning": "sự tương tác", "emoji": "🔄", "class": "n",
       "examples": [{"en": "Daily interactions between people build the fabric of community.", "vi": "Các tương tác hàng ngày giữa mọi người xây dựng nên cộng đồng."},
                    {"en": "Positive interactions with teachers improve student engagement.", "vi": "Tương tác tích cực với giáo viên cải thiện sự gắn kết của học sinh."}]},
      {"word": "community", "meaning": "cộng đồng", "emoji": "🏘️", "class": "n",
       "examples": [{"en": "A strong community provides support during difficult times.", "vi": "Một cộng đồng vững mạnh cung cấp sự hỗ trợ trong những lúc khó khăn."},
                    {"en": "Building a sense of community is important for social well-being.", "vi": "Xây dựng tinh thần cộng đồng rất quan trọng cho phúc lợi xã hội."}]},
    ]
  },
  {
    "id": "career-workplace",
    "name": "Sự Nghiệp & Nơi Làm Việc",
    "emoji": "💼",
    "color": "orange",
    "words": [
      {"word": "negotiate", "meaning": "đàm phán", "emoji": "🤝", "class": "v",
       "examples": [{"en": "She negotiated a higher salary before accepting the job offer.", "vi": "Cô ấy đàm phán mức lương cao hơn trước khi chấp nhận lời mời làm việc."},
                    {"en": "Good negotiation skills are valuable in any career.", "vi": "Kỹ năng đàm phán tốt có giá trị trong bất kỳ sự nghiệp nào."}]},
      {"word": "promotion", "meaning": "sự thăng chức", "emoji": "📈", "class": "n",
       "examples": [{"en": "Hard work and dedication led to his promotion to manager.", "vi": "Làm việc chăm chỉ và tận tâm dẫn đến việc anh ấy được thăng chức lên quản lý."},
                    {"en": "She applied for a promotion after five years in the same role.", "vi": "Cô ấy đăng ký thăng chức sau năm năm ở cùng một vị trí."}]},
      {"word": "mentor", "meaning": "người hướng dẫn, cố vấn", "emoji": "👨‍🏫", "class": "n",
       "examples": [{"en": "Having a good mentor can accelerate your career development.", "vi": "Có một người cố vấn tốt có thể đẩy nhanh sự phát triển sự nghiệp của bạn."},
                    {"en": "She acted as a mentor for younger employees in the company.", "vi": "Cô ấy đóng vai trò là người hướng dẫn cho các nhân viên trẻ hơn trong công ty."}]},
      {"word": "burnout", "meaning": "kiệt sức (công việc)", "emoji": "🔥", "class": "n",
       "examples": [{"en": "Burnout is becoming increasingly common in high-pressure professions.", "vi": "Kiệt sức ngày càng phổ biến trong các nghề nghiệp áp lực cao."},
                    {"en": "Taking regular breaks helps prevent burnout.", "vi": "Nghỉ ngơi thường xuyên giúp ngăn ngừa kiệt sức."}]},
      {"word": "productivity", "meaning": "năng suất làm việc", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Remote work has increased productivity for many employees.", "vi": "Làm việc từ xa đã tăng năng suất cho nhiều nhân viên."},
                    {"en": "Good time management is essential for maintaining productivity.", "vi": "Quản lý thời gian tốt là điều cần thiết để duy trì năng suất."}]},
      {"word": "appraisal", "meaning": "đánh giá năng lực nhân viên", "emoji": "📋", "class": "n",
       "examples": [{"en": "The annual appraisal helps employees understand their progress.", "vi": "Đánh giá hàng năm giúp nhân viên hiểu được sự tiến bộ của họ."},
                    {"en": "An honest appraisal identifies strengths and areas for improvement.", "vi": "Đánh giá trung thực xác định điểm mạnh và các lĩnh vực cần cải thiện."}]},
      {"word": "resign", "meaning": "từ chức, xin nghỉ việc", "emoji": "🚪", "class": "v",
       "examples": [{"en": "She resigned from her position to pursue a different career path.", "vi": "Cô ấy từ chức để theo đuổi con đường sự nghiệp khác."},
                    {"en": "The manager resigned after the scandal became public.", "vi": "Người quản lý từ chức sau khi vụ bê bối được công khai."}]},
      {"word": "probation", "meaning": "thời gian thử việc", "emoji": "⏳", "class": "n",
       "examples": [{"en": "New employees are usually on probation for the first three months.", "vi": "Nhân viên mới thường trong thời gian thử việc ba tháng đầu."},
                    {"en": "During probation, performance is closely monitored.", "vi": "Trong thời gian thử việc, hiệu suất được theo dõi chặt chẽ."}]},
      {"word": "incentive", "meaning": "phần thưởng khuyến khích", "emoji": "🎁", "class": "n",
       "examples": [{"en": "Performance bonuses are a common incentive to motivate employees.", "vi": "Thưởng hiệu suất là một phần thưởng khuyến khích phổ biến để tạo động lực cho nhân viên."},
                    {"en": "The government offers tax incentives to attract foreign investment.", "vi": "Chính phủ cung cấp ưu đãi thuế để thu hút đầu tư nước ngoài."}]},
      {"word": "feedback", "meaning": "phản hồi, nhận xét", "emoji": "💬", "class": "n",
       "examples": [{"en": "Constructive feedback helps employees improve their performance.", "vi": "Phản hồi mang tính xây dựng giúp nhân viên cải thiện hiệu suất của họ."},
                    {"en": "Regular feedback from customers helps the company improve its service.", "vi": "Phản hồi thường xuyên từ khách hàng giúp công ty cải thiện dịch vụ của mình."}]},
      {"word": "colleague", "meaning": "đồng nghiệp", "emoji": "👔", "class": "n",
       "examples": [{"en": "She got on well with all her colleagues at work.", "vi": "Cô ấy hòa thuận với tất cả đồng nghiệp ở nơi làm việc."},
                    {"en": "Building good relationships with colleagues improves teamwork.", "vi": "Xây dựng mối quan hệ tốt với đồng nghiệp cải thiện làm việc nhóm."}]},
      {"word": "deadline", "meaning": "hạn chót", "emoji": "⏰", "class": "n",
       "examples": [{"en": "Missing a deadline can damage your professional reputation.", "vi": "Bỏ lỡ hạn chót có thể làm hỏng danh tiếng chuyên nghiệp của bạn."},
                    {"en": "She always delivers her work ahead of the deadline.", "vi": "Cô ấy luôn nộp bài trước hạn chót."}]},
      {"word": "resume", "meaning": "hồ sơ xin việc", "emoji": "📄", "class": "n",
       "examples": [{"en": "A well-written resume is the first step to getting a job interview.", "vi": "Một hồ sơ xin việc được viết tốt là bước đầu tiên để có được buổi phỏng vấn."},
                    {"en": "Tailor your resume to match the requirements of each job posting.", "vi": "Điều chỉnh hồ sơ của bạn để phù hợp với yêu cầu của từng tin tuyển dụng."}]},
    ]
  },
  {
    "id": "conflict-resolution",
    "name": "Giải Quyết Xung Đột",
    "emoji": "🕊️",
    "color": "red",
    "words": [
      {"word": "mediation", "meaning": "hòa giải (bởi bên thứ ba)", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Mediation helped the two neighbors resolve their dispute peacefully.", "vi": "Hòa giải đã giúp hai người hàng xóm giải quyết tranh chấp một cách hòa bình."},
                    {"en": "International mediation was required to end the armed conflict.", "vi": "Hòa giải quốc tế là cần thiết để chấm dứt xung đột vũ trang."}]},
      {"word": "arbitration", "meaning": "trọng tài phán xử", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Arbitration is often faster and cheaper than going to court.", "vi": "Trọng tài phán xử thường nhanh hơn và rẻ hơn so với ra tòa."},
                    {"en": "The dispute was settled through binding arbitration.", "vi": "Tranh chấp được giải quyết thông qua trọng tài ràng buộc."}]},
      {"word": "compromise", "meaning": "thỏa hiệp", "emoji": "🔀", "class": "n",
       "examples": [{"en": "A compromise was reached after hours of negotiation.", "vi": "Sự thỏa hiệp đã đạt được sau nhiều giờ đàm phán."},
                    {"en": "Successful relationships require willingness to compromise.", "vi": "Các mối quan hệ thành công đòi hỏi sự sẵn sàng thỏa hiệp."}]},
      {"word": "reconcile", "meaning": "hòa giải, hòa thuận trở lại", "emoji": "💚", "class": "v",
       "examples": [{"en": "It took years for the two families to reconcile after the dispute.", "vi": "Hai gia đình mất nhiều năm để hòa giải sau tranh chấp."},
                    {"en": "The peace process aimed to reconcile the two sides.", "vi": "Tiến trình hòa bình nhằm mục tiêu hòa giải hai bên."}]},
      {"word": "dispute", "meaning": "tranh chấp", "emoji": "⚡", "class": "n",
       "examples": [{"en": "A territorial dispute between the two countries has lasted decades.", "vi": "Tranh chấp lãnh thổ giữa hai nước đã kéo dài hàng thập kỷ."},
                    {"en": "The labor dispute resulted in workers going on strike.", "vi": "Tranh chấp lao động dẫn đến việc công nhân đình công."}]},
      {"word": "escalate", "meaning": "leo thang (xung đột)", "emoji": "📈", "class": "v",
       "examples": [{"en": "The situation escalated quickly into a full-scale conflict.", "vi": "Tình hình leo thang nhanh chóng thành một cuộc xung đột toàn diện."},
                    {"en": "Avoid using aggressive language as it can escalate tensions.", "vi": "Tránh sử dụng ngôn ngữ hung hăng vì nó có thể làm leo thang căng thẳng."}]},
      {"word": "tension", "meaning": "căng thẳng (giữa các bên)", "emoji": "😤", "class": "n",
       "examples": [{"en": "Tensions between the two countries rose after the border incident.", "vi": "Căng thẳng giữa hai nước gia tăng sau vụ việc biên giới."},
                    {"en": "Workplace tensions can reduce productivity and morale.", "vi": "Căng thẳng tại nơi làm việc có thể làm giảm năng suất và tinh thần."}]},
      {"word": "ceasefire", "meaning": "ngừng bắn", "emoji": "🏳️", "class": "n",
       "examples": [{"en": "A temporary ceasefire was agreed to allow humanitarian aid to enter.", "vi": "Một lệnh ngừng bắn tạm thời được thỏa thuận để cho phép viện trợ nhân đạo vào."},
                    {"en": "The ceasefire broke down after only three days.", "vi": "Lệnh ngừng bắn đã sụp đổ chỉ sau ba ngày."}]},
      {"word": "diplomatic", "meaning": "ngoại giao, khéo léo", "emoji": "🏛️", "class": "adj",
       "examples": [{"en": "A diplomatic solution is always preferable to military action.", "vi": "Một giải pháp ngoại giao luôn được ưu tiên hơn hành động quân sự."},
                    {"en": "She handled the difficult situation in a diplomatic manner.", "vi": "Cô ấy xử lý tình huống khó khăn một cách khéo léo."}]},
      {"word": "consensus", "meaning": "đồng thuận", "emoji": "🤲", "class": "n",
       "examples": [{"en": "The committee reached a consensus after lengthy debate.", "vi": "Ủy ban đạt được đồng thuận sau cuộc tranh luận kéo dài."},
                    {"en": "Building consensus is essential for effective group decision-making.", "vi": "Xây dựng đồng thuận là điều cần thiết cho việc ra quyết định nhóm hiệu quả."}]},
      {"word": "alliance", "meaning": "liên minh", "emoji": "🤝", "class": "n",
       "examples": [{"en": "The two countries formed a military alliance for mutual defense.", "vi": "Hai nước thành lập liên minh quân sự để phòng thủ chung."},
                    {"en": "Political alliances can shift quickly in response to events.", "vi": "Các liên minh chính trị có thể thay đổi nhanh chóng để phản ứng với các sự kiện."}]},
      {"word": "resolution", "meaning": "nghị quyết, giải pháp", "emoji": "📜", "class": "n",
       "examples": [{"en": "The UN passed a resolution calling for an immediate ceasefire.", "vi": "Liên Hợp Quốc thông qua nghị quyết kêu gọi ngừng bắn ngay lập tức."},
                    {"en": "Finding a resolution that satisfies all parties is challenging.", "vi": "Tìm ra giải pháp thỏa mãn tất cả các bên là thách thức."}]},
      {"word": "negotiation", "meaning": "đàm phán (chính thức)", "emoji": "💬", "class": "n",
       "examples": [{"en": "Peace negotiations between the two sides lasted for two years.", "vi": "Đàm phán hòa bình giữa hai bên kéo dài hai năm."},
                    {"en": "Skilled negotiation can resolve conflicts without violence.", "vi": "Đàm phán khéo léo có thể giải quyết xung đột mà không cần bạo lực."}]},
    ]
  },
  {
    "id": "statistics-data",
    "name": "Thống Kê & Dữ Liệu",
    "emoji": "📊",
    "color": "cyan",
    "words": [
      {"word": "average", "meaning": "giá trị trung bình", "emoji": "➗", "class": "n",
       "examples": [{"en": "The average temperature in July is around 35 degrees Celsius.", "vi": "Nhiệt độ trung bình vào tháng Bảy là khoảng 35 độ Celsius."},
                    {"en": "On average, students spend two hours a day on homework.", "vi": "Trung bình, học sinh dành hai giờ mỗi ngày cho bài tập về nhà."}]},
      {"word": "median", "meaning": "trung vị", "emoji": "📍", "class": "n",
       "examples": [{"en": "The median income is a better measure than the average when there are extreme values.", "vi": "Thu nhập trung vị là thước đo tốt hơn so với trung bình khi có các giá trị cực đoan."},
                    {"en": "The median age of the population is rising in developed countries.", "vi": "Độ tuổi trung vị của dân số đang tăng ở các nước phát triển."}]},
      {"word": "proportion", "meaning": "tỷ lệ", "emoji": "🔢", "class": "n",
       "examples": [{"en": "A large proportion of the budget is spent on education.", "vi": "Một tỷ lệ lớn ngân sách được chi cho giáo dục."},
                    {"en": "The proportion of women in leadership roles has increased.", "vi": "Tỷ lệ phụ nữ trong các vai trò lãnh đạo đã tăng."}]},
      {"word": "trend", "meaning": "xu hướng", "emoji": "📈", "class": "n",
       "examples": [{"en": "There is a clear upward trend in global temperatures.", "vi": "Có một xu hướng tăng rõ ràng trong nhiệt độ toàn cầu."},
                    {"en": "The data shows a worrying trend in youth unemployment.", "vi": "Dữ liệu cho thấy một xu hướng đáng lo ngại về thất nghiệp thanh niên."}]},
      {"word": "survey", "meaning": "khảo sát", "emoji": "📝", "class": "n",
       "examples": [{"en": "A survey of 1,000 people found that most prefer remote work.", "vi": "Một cuộc khảo sát với 1.000 người cho thấy hầu hết thích làm việc từ xa."},
                    {"en": "Online surveys allow researchers to collect data quickly.", "vi": "Khảo sát trực tuyến cho phép các nhà nghiên cứu thu thập dữ liệu nhanh chóng."}]},
      {"word": "visualize", "meaning": "trực quan hóa (dữ liệu)", "emoji": "📊", "class": "v",
       "examples": [{"en": "Charts and graphs help us visualize complex data sets.", "vi": "Biểu đồ và đồ thị giúp chúng ta trực quan hóa các tập dữ liệu phức tạp."},
                    {"en": "The researcher used a heat map to visualize geographic patterns.", "vi": "Nhà nghiên cứu sử dụng bản đồ nhiệt để trực quan hóa các mẫu địa lý."}]},
      {"word": "outlier", "meaning": "giá trị ngoại lệ", "emoji": "⭐", "class": "n",
       "examples": [{"en": "The outlier in the data skewed the average significantly.", "vi": "Giá trị ngoại lệ trong dữ liệu đã làm lệch đáng kể giá trị trung bình."},
                    {"en": "Researchers investigate outliers to understand unusual cases.", "vi": "Các nhà nghiên cứu điều tra các giá trị ngoại lệ để hiểu các trường hợp bất thường."}]},
      {"word": "distribution", "meaning": "phân phối (thống kê)", "emoji": "🔔", "class": "n",
       "examples": [{"en": "Test scores followed a normal distribution with most students near the average.", "vi": "Điểm kiểm tra có phân phối chuẩn với hầu hết học sinh gần giá trị trung bình."},
                    {"en": "The distribution of wealth is unequal in most societies.", "vi": "Sự phân phối tài sản không bình đẳng ở hầu hết các xã hội."}]},
      {"word": "inference", "meaning": "suy luận (từ dữ liệu)", "emoji": "💭", "class": "n",
       "examples": [{"en": "Statistical inference allows conclusions to be drawn from sample data.", "vi": "Suy luận thống kê cho phép rút ra kết luận từ dữ liệu mẫu."},
                    {"en": "Drawing inferences from limited data can lead to incorrect conclusions.", "vi": "Suy luận từ dữ liệu hạn chế có thể dẫn đến kết luận không chính xác."}]},
      {"word": "dataset", "meaning": "tập dữ liệu", "emoji": "💾", "class": "n",
       "examples": [{"en": "The researchers analyzed a dataset of over a million medical records.", "vi": "Các nhà nghiên cứu phân tích tập dữ liệu gồm hơn một triệu hồ sơ y tế."},
                    {"en": "Machine learning models require large, clean datasets to perform well.", "vi": "Các mô hình học máy đòi hỏi tập dữ liệu lớn và sạch để hoạt động tốt."}]},
      {"word": "regression", "meaning": "hồi quy (thống kê)", "emoji": "📉", "class": "n",
       "examples": [{"en": "Linear regression predicts future values based on past data.", "vi": "Hồi quy tuyến tính dự đoán các giá trị tương lai dựa trên dữ liệu quá khứ."},
                    {"en": "A regression analysis showed a strong relationship between income and education.", "vi": "Phân tích hồi quy cho thấy mối quan hệ mạnh mẽ giữa thu nhập và giáo dục."}]},
      {"word": "interpret", "meaning": "diễn giải (dữ liệu)", "emoji": "🔍", "class": "v",
       "examples": [{"en": "It is important to interpret data correctly before drawing conclusions.", "vi": "Điều quan trọng là diễn giải dữ liệu chính xác trước khi rút ra kết luận."},
                    {"en": "Different analysts may interpret the same data in different ways.", "vi": "Các nhà phân tích khác nhau có thể diễn giải cùng một dữ liệu theo những cách khác nhau."}]},
      {"word": "margin", "meaning": "biên độ, sai số biên", "emoji": "📏", "class": "n",
       "examples": [{"en": "The poll has a margin of error of plus or minus 3 percent.", "vi": "Cuộc thăm dò có biên độ sai số cộng hoặc trừ 3 phần trăm."},
                    {"en": "Profit margin measures how much of revenue becomes profit.", "vi": "Biên lợi nhuận đo lường bao nhiêu doanh thu trở thành lợi nhuận."}]},
    ]
  },
  {
    "id": "creativity-innovation",
    "name": "Sáng Tạo & Đổi Mới",
    "emoji": "🎨",
    "color": "yellow",
    "words": [
      {"word": "brainstorm", "meaning": "động não, tạo ý tưởng", "emoji": "⚡", "class": "v",
       "examples": [{"en": "The team brainstormed ideas for the new marketing campaign.", "vi": "Nhóm động não ý tưởng cho chiến dịch marketing mới."},
                    {"en": "Brainstorming sessions work best when everyone feels free to contribute.", "vi": "Các buổi động não hoạt động tốt nhất khi mọi người cảm thấy tự do đóng góp."}]},
      {"word": "inspiration", "meaning": "cảm hứng", "emoji": "💡", "class": "n",
       "examples": [{"en": "She drew inspiration from her travels around the world.", "vi": "Cô lấy cảm hứng từ những chuyến du lịch vòng quanh thế giới."},
                    {"en": "Inspiration can come from unexpected sources.", "vi": "Cảm hứng có thể đến từ những nguồn bất ngờ."}]},
      {"word": "original", "meaning": "độc đáo, nguyên bản", "emoji": "🌟", "class": "adj",
       "examples": [{"en": "Her designs are original and unlike anything else on the market.", "vi": "Thiết kế của cô ấy rất độc đáo và không giống bất cứ thứ gì khác trên thị trường."},
                    {"en": "Original thinking is valued in creative fields.", "vi": "Tư duy độc đáo được đánh giá cao trong các lĩnh vực sáng tạo."}]},
      {"word": "breakthrough", "meaning": "đột phá", "emoji": "🚀", "class": "n",
       "examples": [{"en": "The discovery of penicillin was a major breakthrough in medicine.", "vi": "Sự phát hiện ra penicillin là một đột phá lớn trong y học."},
                    {"en": "They were on the verge of a breakthrough in battery technology.", "vi": "Họ đang trên bờ vực của một đột phá trong công nghệ pin."}]},
      {"word": "collaborate", "meaning": "hợp tác sáng tạo", "emoji": "🤝", "class": "v",
       "examples": [{"en": "The two artists collaborated on a joint exhibition.", "vi": "Hai nghệ sĩ hợp tác trong một triển lãm chung."},
                    {"en": "Collaborating with others brings diverse perspectives to a project.", "vi": "Hợp tác với người khác mang lại những quan điểm đa dạng cho dự án."}]},
      {"word": "concept", "meaning": "ý tưởng, khái niệm", "emoji": "💭", "class": "n",
       "examples": [{"en": "The concept for the project was sketched out on a napkin.", "vi": "Ý tưởng cho dự án được phác thảo trên một tờ khăn ăn."},
                    {"en": "Turning a concept into a product requires both creativity and skill.", "vi": "Biến ý tưởng thành sản phẩm đòi hỏi cả sự sáng tạo và kỹ năng."}]},
      {"word": "implement", "meaning": "thực thi, triển khai", "emoji": "🔧", "class": "v",
       "examples": [{"en": "Having a great idea is only half the battle — you must also implement it.", "vi": "Có một ý tưởng tuyệt vời chỉ là một nửa thách thức — bạn cũng phải thực thi nó."},
                    {"en": "The new system was implemented across all branches of the company.", "vi": "Hệ thống mới được triển khai trên tất cả các chi nhánh của công ty."}]},
      {"word": "refine", "meaning": "tinh chỉnh, hoàn thiện", "emoji": "💎", "class": "v",
       "examples": [{"en": "She spent months refining her technique before entering the competition.", "vi": "Cô dành nhiều tháng tinh chỉnh kỹ thuật trước khi tham gia cuộc thi."},
                    {"en": "Good writing requires you to continuously refine your ideas.", "vi": "Viết tốt đòi hỏi bạn liên tục tinh chỉnh ý tưởng của mình."}]},
      {"word": "unconventional", "meaning": "phi truyền thống, khác thường", "emoji": "🌀", "class": "adj",
       "examples": [{"en": "His unconventional approach to problem-solving surprised everyone.", "vi": "Cách tiếp cận giải quyết vấn đề phi truyền thống của anh ấy khiến mọi người ngạc nhiên."},
                    {"en": "Unconventional ideas are often dismissed before they prove their value.", "vi": "Các ý tưởng phi truyền thống thường bị bác bỏ trước khi chứng minh giá trị của chúng."}]},
      {"word": "improvise", "meaning": "ứng biến", "emoji": "🎭", "class": "v",
       "examples": [{"en": "When the equipment failed, she had to improvise a solution.", "vi": "Khi thiết bị hỏng, cô ấy phải ứng biến một giải pháp."},
                    {"en": "Jazz musicians are trained to improvise during performances.", "vi": "Các nhạc sĩ jazz được đào tạo để ứng biến trong khi biểu diễn."}]},
      {"word": "generate", "meaning": "tạo ra (ý tưởng, giải pháp)", "emoji": "⚙️", "class": "v",
       "examples": [{"en": "The workshop helped participants generate fresh ideas.", "vi": "Hội thảo giúp những người tham gia tạo ra những ý tưởng mới."},
                    {"en": "AI tools can now generate text, images, and music.", "vi": "Các công cụ AI hiện có thể tạo ra văn bản, hình ảnh và âm nhạc."}]},
      {"word": "design thinking", "meaning": "tư duy thiết kế", "emoji": "🧩", "class": "n",
       "examples": [{"en": "Design thinking puts the user at the center of the problem-solving process.", "vi": "Tư duy thiết kế đặt người dùng vào trung tâm của quá trình giải quyết vấn đề."},
                    {"en": "Companies use design thinking to develop innovative products.", "vi": "Các công ty sử dụng tư duy thiết kế để phát triển các sản phẩm sáng tạo."}]},
      {"word": "prototype", "meaning": "nguyên mẫu thử nghiệm", "emoji": "🔬", "class": "n",
       "examples": [{"en": "Build a quick prototype to test your idea before investing fully.", "vi": "Hãy xây dựng một nguyên mẫu nhanh để thử nghiệm ý tưởng trước khi đầu tư đầy đủ."},
                    {"en": "The prototype was rough but showed the concept clearly.", "vi": "Nguyên mẫu còn thô nhưng thể hiện rõ ràng ý tưởng."}]},
    ]
  },
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'words.json')
with open(data_path) as f:
    data = json.load(f)

data['scholar']['topics'].extend(topics_21_30)

with open(data_path, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done: {len(topics_21_30)} more topics added")
for t in topics_21_30:
    print(f"  {t['id']}: {len(t['words'])} words")
total = sum(len(t['words']) for t in data['scholar']['topics'])
print(f"\nScholar FINAL: {len(data['scholar']['topics'])} topics, {total} words")
print(f"\nAll levels:")
for level in data:
    topics = data[level]['topics']
    wcount = sum(len(t['words']) for t in topics)
    print(f"  {level}: {len(topics)} topics, {wcount} words")
