import json, os

topics_11_20 = [
  {
    "id": "art-culture",
    "name": "Nghệ Thuật & Văn Hóa",
    "emoji": "🎨",
    "color": "purple",
    "words": [
      {"word": "aesthetic", "meaning": "thẩm mỹ", "emoji": "✨", "class": "adj",
       "examples": [{"en": "The architect had a minimalist aesthetic style.", "vi": "Kiến trúc sư có phong cách thẩm mỹ tối giản."},
                    {"en": "Aesthetic choices in design reflect cultural values.", "vi": "Các lựa chọn thẩm mỹ trong thiết kế phản ánh các giá trị văn hóa."}]},
      {"word": "heritage", "meaning": "di sản văn hóa", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Angkor Wat is a symbol of Cambodia's rich cultural heritage.", "vi": "Angkor Wat là biểu tượng của di sản văn hóa phong phú của Campuchia."},
                    {"en": "Preserving our heritage helps connect future generations to the past.", "vi": "Bảo tồn di sản giúp kết nối các thế hệ tương lai với quá khứ."}]},
      {"word": "sculpture", "meaning": "điêu khắc", "emoji": "🗿", "class": "n",
       "examples": [{"en": "Michelangelo's sculpture of David is one of the world's great artworks.", "vi": "Tác phẩm điêu khắc David của Michelangelo là một trong những tác phẩm nghệ thuật vĩ đại nhất thế giới."},
                    {"en": "The sculpture was carved from a single block of marble.", "vi": "Tác phẩm điêu khắc được chạm khắc từ một khối đá cẩm thạch duy nhất."}]},
      {"word": "contemporary", "meaning": "đương đại", "emoji": "🕰️", "class": "adj",
       "examples": [{"en": "Contemporary art often challenges traditional ideas about beauty.", "vi": "Nghệ thuật đương đại thường thách thức các quan niệm truyền thống về vẻ đẹp."},
                    {"en": "She is one of the most celebrated contemporary artists.", "vi": "Cô ấy là một trong những nghệ sĩ đương đại được tôn vinh nhất."}]},
      {"word": "curator", "meaning": "người quản lý triển lãm", "emoji": "🖼️", "class": "n",
       "examples": [{"en": "The curator selected over fifty paintings for the exhibition.", "vi": "Người quản lý triển lãm đã chọn hơn năm mươi bức tranh cho cuộc triển lãm."},
                    {"en": "A museum curator is responsible for caring for the collection.", "vi": "Người quản lý bảo tàng chịu trách nhiệm chăm sóc bộ sưu tập."}]},
      {"word": "exhibition", "meaning": "cuộc triển lãm", "emoji": "🎭", "class": "n",
       "examples": [{"en": "The exhibition attracted over a hundred thousand visitors.", "vi": "Cuộc triển lãm thu hút hơn một trăm nghìn khách thăm quan."},
                    {"en": "Her first solo exhibition was a great success.", "vi": "Cuộc triển lãm solo đầu tiên của cô ấy là một thành công lớn."}]},
      {"word": "portrait", "meaning": "chân dung", "emoji": "🖼️", "class": "n",
       "examples": [{"en": "The portrait captured the subject's personality beautifully.", "vi": "Bức chân dung thể hiện tính cách của chủ thể một cách đẹp đẽ."},
                    {"en": "Rembrandt is famous for his masterful self-portraits.", "vi": "Rembrandt nổi tiếng với những bức chân dung tự họa bậc thầy."}]},
      {"word": "abstract", "meaning": "trừu tượng", "emoji": "🌀", "class": "adj",
       "examples": [{"en": "Abstract art uses shapes and colors to express ideas, not reality.", "vi": "Nghệ thuật trừu tượng sử dụng hình dạng và màu sắc để diễn đạt ý tưởng, không phải thực tế."},
                    {"en": "Some people find abstract paintings difficult to interpret.", "vi": "Một số người thấy tranh trừu tượng khó diễn giải."}]},
      {"word": "genre", "meaning": "thể loại (nghệ thuật)", "emoji": "🎭", "class": "n",
       "examples": [{"en": "Jazz is a genre of music that originated in New Orleans.", "vi": "Jazz là một thể loại âm nhạc có nguồn gốc từ New Orleans."},
                    {"en": "Her novels cross genre boundaries between romance and thriller.", "vi": "Các tiểu thuyết của cô vượt qua ranh giới thể loại giữa lãng mạn và kinh dị."}]},
      {"word": "masterpiece", "meaning": "kiệt tác", "emoji": "🏆", "class": "n",
       "examples": [{"en": "The Mona Lisa is considered Leonardo da Vinci's masterpiece.", "vi": "Mona Lisa được coi là kiệt tác của Leonardo da Vinci."},
                    {"en": "Critics called her latest film a masterpiece of modern cinema.", "vi": "Các nhà phê bình gọi bộ phim mới nhất của cô là kiệt tác của điện ảnh hiện đại."}]},
      {"word": "Renaissance", "meaning": "thời kỳ Phục Hưng", "emoji": "🌅", "class": "n",
       "examples": [{"en": "The Renaissance was a period of great artistic and intellectual rebirth.", "vi": "Thời kỳ Phục Hưng là giai đoạn tái sinh nghệ thuật và trí tuệ vĩ đại."},
                    {"en": "Renaissance artists were inspired by ancient Greek and Roman culture.", "vi": "Các nghệ sĩ Phục Hưng được truyền cảm hứng bởi văn hóa Hy Lạp và La Mã cổ đại."}]},
      {"word": "installation", "meaning": "tác phẩm sắp đặt", "emoji": "🎪", "class": "n",
       "examples": [{"en": "The artist created a massive installation using recycled materials.", "vi": "Nghệ sĩ tạo ra một tác phẩm sắp đặt khổng lồ bằng vật liệu tái chế."},
                    {"en": "The interactive installation invited visitors to participate.", "vi": "Tác phẩm sắp đặt tương tác mời khách thăm quan tham gia."}]},
      {"word": "canvas", "meaning": "khung vải (vẽ tranh)", "emoji": "🎨", "class": "n",
       "examples": [{"en": "She began sketching on the canvas before applying paint.", "vi": "Cô bắt đầu phác thảo trên khung vải trước khi tô màu."},
                    {"en": "The artist worked on multiple canvases simultaneously.", "vi": "Nghệ sĩ làm việc trên nhiều khung vải cùng một lúc."}]},
    ]
  },
  {
    "id": "education-system",
    "name": "Hệ Thống Giáo Dục",
    "emoji": "🎓",
    "color": "amber",
    "words": [
      {"word": "curriculum", "meaning": "chương trình giảng dạy", "emoji": "📚", "class": "n",
       "examples": [{"en": "The national curriculum sets out what students must learn at each level.", "vi": "Chương trình giảng dạy quốc gia quy định những gì học sinh phải học ở mỗi cấp độ."},
                    {"en": "Schools have the freedom to adapt the curriculum to local needs.", "vi": "Các trường có quyền điều chỉnh chương trình học cho phù hợp với nhu cầu địa phương."}]},
      {"word": "pedagogy", "meaning": "phương pháp sư phạm", "emoji": "👩‍🏫", "class": "n",
       "examples": [{"en": "Modern pedagogy emphasizes student-centred learning.", "vi": "Phương pháp sư phạm hiện đại nhấn mạnh việc học lấy học sinh làm trung tâm."},
                    {"en": "Teachers study pedagogy to improve their teaching methods.", "vi": "Giáo viên nghiên cứu phương pháp sư phạm để cải thiện phương pháp giảng dạy của họ."}]},
      {"word": "assessment", "meaning": "đánh giá học tập", "emoji": "📝", "class": "n",
       "examples": [{"en": "Continuous assessment gives a more complete picture of student progress.", "vi": "Đánh giá liên tục cho thấy bức tranh đầy đủ hơn về tiến độ học tập của học sinh."},
                    {"en": "Portfolio assessment allows students to demonstrate a range of skills.", "vi": "Đánh giá hồ sơ cho phép học sinh thể hiện nhiều kỹ năng."}]},
      {"word": "literacy", "meaning": "năng lực đọc viết", "emoji": "📖", "class": "n",
       "examples": [{"en": "Improving literacy rates is a key goal of education policy.", "vi": "Cải thiện tỷ lệ biết đọc biết viết là mục tiêu quan trọng của chính sách giáo dục."},
                    {"en": "Digital literacy is now considered as important as reading and writing.", "vi": "Năng lực kỹ thuật số ngày nay được coi là quan trọng như đọc và viết."}]},
      {"word": "scholarship", "meaning": "học bổng", "emoji": "🎓", "class": "n",
       "examples": [{"en": "She won a scholarship to study at Oxford University.", "vi": "Cô ấy giành được học bổng để học tại Đại học Oxford."},
                    {"en": "Many students rely on scholarships to afford higher education.", "vi": "Nhiều sinh viên dựa vào học bổng để chi trả cho giáo dục đại học."}]},
      {"word": "tuition", "meaning": "học phí", "emoji": "💸", "class": "n",
       "examples": [{"en": "Rising tuition fees make university less accessible for many families.", "vi": "Học phí tăng làm cho đại học khó tiếp cận hơn đối với nhiều gia đình."},
                    {"en": "The tuition for international students is often much higher.", "vi": "Học phí cho sinh viên quốc tế thường cao hơn nhiều."}]},
      {"word": "enrollment", "meaning": "sự ghi danh nhập học", "emoji": "📋", "class": "n",
       "examples": [{"en": "Enrollment in online courses has grown rapidly in recent years.", "vi": "Ghi danh vào các khóa học trực tuyến đã tăng trưởng nhanh chóng trong những năm gần đây."},
                    {"en": "The enrollment deadline is next Friday.", "vi": "Hạn ghi danh là thứ Sáu tuần tới."}]},
      {"word": "compulsory", "meaning": "bắt buộc", "emoji": "‼️", "class": "adj",
       "examples": [{"en": "Education is compulsory for children between the ages of six and fifteen.", "vi": "Giáo dục là bắt buộc cho trẻ em từ sáu đến mười lăm tuổi."},
                    {"en": "Wearing a helmet is compulsory when riding a motorcycle.", "vi": "Đội mũ bảo hiểm là bắt buộc khi đi xe máy."}]},
      {"word": "accreditation", "meaning": "công nhận chất lượng", "emoji": "✅", "class": "n",
       "examples": [{"en": "The university received accreditation from the national education board.", "vi": "Trường đại học nhận được công nhận chất lượng từ ban giáo dục quốc gia."},
                    {"en": "Accreditation ensures that schools meet required standards.", "vi": "Công nhận chất lượng đảm bảo rằng các trường đáp ứng các tiêu chuẩn yêu cầu."}]},
      {"word": "dropout", "meaning": "bỏ học giữa chừng", "emoji": "🚪", "class": "n",
       "examples": [{"en": "High dropout rates indicate problems with the education system.", "vi": "Tỷ lệ bỏ học cao cho thấy các vấn đề với hệ thống giáo dục."},
                    {"en": "Financial difficulties are a leading cause of student dropout.", "vi": "Khó khăn tài chính là nguyên nhân hàng đầu khiến sinh viên bỏ học."}]},
      {"word": "vocational", "meaning": "hướng nghề, dạy nghề", "emoji": "🔧", "class": "adj",
       "examples": [{"en": "Vocational training prepares students for specific careers.", "vi": "Đào tạo nghề chuẩn bị cho học sinh những nghề nghiệp cụ thể."},
                    {"en": "A vocational qualification is valued as much as a degree by many employers.", "vi": "Bằng dạy nghề được nhiều nhà tuyển dụng đánh giá cao như bằng đại học."}]},
      {"word": "extracurricular", "meaning": "ngoại khóa", "emoji": "⚽", "class": "adj",
       "examples": [{"en": "Extracurricular activities develop skills that are not taught in class.", "vi": "Các hoạt động ngoại khóa phát triển các kỹ năng không được dạy trong lớp."},
                    {"en": "Universities often look for students with extracurricular achievements.", "vi": "Các trường đại học thường tìm kiếm sinh viên có thành tích ngoại khóa."}]},
      {"word": "discipline", "meaning": "kỷ luật (học đường)", "emoji": "📏", "class": "n",
       "examples": [{"en": "Classroom discipline is important for effective teaching.", "vi": "Kỷ luật trong lớp học rất quan trọng cho việc giảng dạy hiệu quả."},
                    {"en": "Self-discipline helps students manage their time and studies.", "vi": "Tự kỷ luật giúp học sinh quản lý thời gian và việc học."}]},
    ]
  },
  {
    "id": "business-management",
    "name": "Kinh Doanh & Quản Lý",
    "emoji": "💼",
    "color": "orange",
    "words": [
      {"word": "strategy", "meaning": "chiến lược", "emoji": "♟️", "class": "n",
       "examples": [{"en": "The company's long-term strategy is to expand into Asian markets.", "vi": "Chiến lược dài hạn của công ty là mở rộng sang thị trường châu Á."},
                    {"en": "A clear business strategy helps teams work toward the same goals.", "vi": "Chiến lược kinh doanh rõ ràng giúp các nhóm làm việc hướng tới các mục tiêu chung."}]},
      {"word": "revenue", "meaning": "doanh thu", "emoji": "💰", "class": "n",
       "examples": [{"en": "The company's annual revenue grew by 20% last year.", "vi": "Doanh thu hàng năm của công ty tăng 20% năm ngoái."},
                    {"en": "Subscription services generate steady monthly revenue.", "vi": "Dịch vụ đăng ký tạo ra doanh thu hàng tháng ổn định."}]},
      {"word": "stakeholder", "meaning": "các bên liên quan", "emoji": "👥", "class": "n",
       "examples": [{"en": "The project must consider the needs of all stakeholders.", "vi": "Dự án phải xem xét nhu cầu của tất cả các bên liên quan."},
                    {"en": "Investors, employees, and customers are all key stakeholders.", "vi": "Nhà đầu tư, nhân viên và khách hàng đều là các bên liên quan chính."}]},
      {"word": "merger", "meaning": "sáp nhập", "emoji": "🔀", "class": "n",
       "examples": [{"en": "The merger of the two banks created the largest financial institution in the country.", "vi": "Việc sáp nhập hai ngân hàng tạo ra tổ chức tài chính lớn nhất đất nước."},
                    {"en": "The merger was approved after months of negotiation.", "vi": "Vụ sáp nhập được phê duyệt sau nhiều tháng đàm phán."}]},
      {"word": "acquisition", "meaning": "mua lại (doanh nghiệp)", "emoji": "🏢", "class": "n",
       "examples": [{"en": "The tech giant made a major acquisition of a smaller startup.", "vi": "Gã khổng lồ công nghệ đã mua lại một startup nhỏ hơn."},
                    {"en": "The acquisition helped the company enter a new market.", "vi": "Việc mua lại giúp công ty gia nhập thị trường mới."}]},
      {"word": "outsource", "meaning": "thuê ngoài", "emoji": "🌐", "class": "v",
       "examples": [{"en": "Many companies outsource customer service to reduce costs.", "vi": "Nhiều công ty thuê ngoài dịch vụ khách hàng để giảm chi phí."},
                    {"en": "Outsourcing production allowed the firm to focus on design.", "vi": "Thuê ngoài sản xuất cho phép công ty tập trung vào thiết kế."}]},
      {"word": "forecast", "meaning": "dự báo", "emoji": "📊", "class": "n",
       "examples": [{"en": "The sales forecast for next year is optimistic.", "vi": "Dự báo doanh số năm tới rất lạc quan."},
                    {"en": "Accurate financial forecasts help businesses plan ahead.", "vi": "Dự báo tài chính chính xác giúp doanh nghiệp lên kế hoạch trước."}]},
      {"word": "audit", "meaning": "kiểm toán", "emoji": "🔍", "class": "n",
       "examples": [{"en": "An annual audit ensures that financial records are accurate.", "vi": "Kiểm toán hàng năm đảm bảo rằng hồ sơ tài chính chính xác."},
                    {"en": "The company failed the audit due to missing documents.", "vi": "Công ty không qua được kiểm toán do thiếu tài liệu."}]},
      {"word": "entrepreneur", "meaning": "doanh nhân", "emoji": "🚀", "class": "n",
       "examples": [{"en": "She became a successful entrepreneur after launching her own app.", "vi": "Cô ấy trở thành doanh nhân thành công sau khi ra mắt ứng dụng của riêng mình."},
                    {"en": "Entrepreneurs take risks in the hope of creating something valuable.", "vi": "Các doanh nhân chấp nhận rủi ro với hy vọng tạo ra điều gì đó có giá trị."}]},
      {"word": "liability", "meaning": "trách nhiệm pháp lý tài chính", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "Limited liability means investors cannot lose more than their investment.", "vi": "Trách nhiệm hữu hạn có nghĩa là nhà đầu tư không thể mất nhiều hơn khoản đầu tư của họ."},
                    {"en": "Liabilities on the balance sheet represent what the company owes.", "vi": "Nợ phải trả trên bảng cân đối kế toán đại diện cho những gì công ty nợ."}]},
      {"word": "dividend", "meaning": "cổ tức", "emoji": "💵", "class": "n",
       "examples": [{"en": "The company paid a generous dividend to its shareholders.", "vi": "Công ty trả cổ tức hào phóng cho các cổ đông."},
                    {"en": "Dividends are paid from a company's profits.", "vi": "Cổ tức được trả từ lợi nhuận của công ty."}]},
      {"word": "budget", "meaning": "ngân sách", "emoji": "📒", "class": "n",
       "examples": [{"en": "The project went over budget by 15%.", "vi": "Dự án vượt ngân sách 15%."},
                    {"en": "A well-planned budget helps avoid financial problems.", "vi": "Ngân sách được lên kế hoạch tốt giúp tránh các vấn đề tài chính."}]},
      {"word": "partnership", "meaning": "hợp tác kinh doanh", "emoji": "🤝", "class": "n",
       "examples": [{"en": "The two companies entered a strategic partnership.", "vi": "Hai công ty bước vào quan hệ đối tác chiến lược."},
                    {"en": "A strong partnership requires trust and clear communication.", "vi": "Quan hệ đối tác mạnh mẽ đòi hỏi sự tin tưởng và giao tiếp rõ ràng."}]},
    ]
  },
  {
    "id": "urban-development",
    "name": "Phát Triển Đô Thị",
    "emoji": "🏙️",
    "color": "stone",
    "words": [
      {"word": "architecture", "meaning": "kiến trúc", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "The city's architecture blends ancient temples with modern towers.", "vi": "Kiến trúc của thành phố kết hợp các đền cổ với các tòa nhà hiện đại."},
                    {"en": "She studied architecture at university before becoming a designer.", "vi": "Cô học kiến trúc tại trường đại học trước khi trở thành nhà thiết kế."}]},
      {"word": "zoning", "meaning": "phân vùng quy hoạch", "emoji": "🗺️", "class": "n",
       "examples": [{"en": "Zoning laws restrict what can be built in different areas.", "vi": "Luật phân vùng hạn chế những gì có thể được xây dựng ở các khu vực khác nhau."},
                    {"en": "Mixed-use zoning allows residential and commercial buildings side by side.", "vi": "Phân vùng hỗn hợp cho phép các tòa nhà dân cư và thương mại cạnh nhau."}]},
      {"word": "density", "meaning": "mật độ dân số", "emoji": "👥", "class": "n",
       "examples": [{"en": "High population density creates challenges for city planners.", "vi": "Mật độ dân số cao tạo ra thách thức cho các nhà quy hoạch thành phố."},
                    {"en": "Greater housing density can reduce urban sprawl.", "vi": "Mật độ nhà ở lớn hơn có thể giảm sự mở rộng đô thị."}]},
      {"word": "gentrification", "meaning": "sự biến đổi khu dân cư cũ thành khu cao cấp", "emoji": "🏗️", "class": "n",
       "examples": [{"en": "Gentrification raised property prices and displaced long-term residents.", "vi": "Sự quý tộc hóa làm tăng giá bất động sản và dẫn đến người dân lâu năm bị dời đi."},
                    {"en": "Gentrification can revitalize neglected neighborhoods but cause inequality.", "vi": "Sự quý tộc hóa có thể làm sống lại các khu phố bị bỏ bê nhưng gây ra bất bình đẳng."}]},
      {"word": "renovation", "meaning": "cải tạo, tu sửa", "emoji": "🔨", "class": "n",
       "examples": [{"en": "The renovation of the old theater took two years to complete.", "vi": "Việc tu sửa nhà hát cũ mất hai năm để hoàn thành."},
                    {"en": "Renovating historic buildings preserves them for future generations.", "vi": "Cải tạo các công trình lịch sử giúp bảo tồn chúng cho các thế hệ tương lai."}]},
      {"word": "municipality", "meaning": "chính quyền đô thị", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "The municipality is responsible for waste collection and road maintenance.", "vi": "Chính quyền đô thị chịu trách nhiệm thu gom rác thải và bảo trì đường bộ."},
                    {"en": "Citizens voted for a new mayor to lead the municipality.", "vi": "Công dân bầu chọn thị trưởng mới để lãnh đạo chính quyền đô thị."}]},
      {"word": "transit", "meaning": "giao thông vận tải công cộng", "emoji": "🚇", "class": "n",
       "examples": [{"en": "Expanding the public transit network reduces traffic congestion.", "vi": "Mở rộng mạng lưới giao thông công cộng giảm ùn tắc giao thông."},
                    {"en": "Many commuters rely on transit to get to work.", "vi": "Nhiều người đi làm dựa vào giao thông công cộng để đến nơi làm việc."}]},
      {"word": "skyscraper", "meaning": "tòa nhà chọc trời", "emoji": "🏙️", "class": "n",
       "examples": [{"en": "The city's skyline is defined by its many skyscrapers.", "vi": "Đường chân trời của thành phố được xác định bởi nhiều tòa nhà chọc trời."},
                    {"en": "Building skyscrapers requires complex engineering techniques.", "vi": "Xây dựng các tòa nhà chọc trời đòi hỏi các kỹ thuật kỹ thuật phức tạp."}]},
      {"word": "congestion", "meaning": "tắc nghẽn giao thông", "emoji": "🚗", "class": "n",
       "examples": [{"en": "Traffic congestion in the city center is worst during rush hour.", "vi": "Tắc nghẽn giao thông ở trung tâm thành phố tồi tệ nhất trong giờ cao điểm."},
                    {"en": "Congestion charging reduces the number of cars in the city.", "vi": "Phí tắc nghẽn làm giảm số lượng xe hơi trong thành phố."}]},
      {"word": "landmark", "meaning": "địa danh, công trình nổi tiếng", "emoji": "🗼", "class": "n",
       "examples": [{"en": "The Eiffel Tower is one of the most recognizable landmarks in the world.", "vi": "Tháp Eiffel là một trong những địa danh dễ nhận biết nhất thế giới."},
                    {"en": "The old lighthouse is a beloved landmark in our town.", "vi": "Ngọn hải đăng cũ là địa danh được yêu quý ở thị trấn chúng tôi."}]},
      {"word": "pedestrian", "meaning": "người đi bộ", "emoji": "🚶", "class": "n",
       "examples": [{"en": "Pedestrian-friendly streets encourage people to walk instead of drive.", "vi": "Những con đường thân thiện với người đi bộ khuyến khích mọi người đi bộ thay vì lái xe."},
                    {"en": "A new pedestrian bridge was built over the busy highway.", "vi": "Một cây cầu dành cho người đi bộ mới được xây dựng qua đường cao tốc đông đúc."}]},
      {"word": "urban sprawl", "meaning": "mở rộng đô thị ra ngoại ô", "emoji": "🌆", "class": "n",
       "examples": [{"en": "Urban sprawl leads to longer commutes and more car dependency.", "vi": "Mở rộng đô thị dẫn đến hành trình đi làm dài hơn và phụ thuộc xe hơi nhiều hơn."},
                    {"en": "City planners are trying to limit urban sprawl by building upward.", "vi": "Các nhà quy hoạch thành phố đang cố gắng hạn chế mở rộng đô thị bằng cách xây dựng theo chiều cao."}]},
      {"word": "construction", "meaning": "xây dựng", "emoji": "🏗️", "class": "n",
       "examples": [{"en": "The construction of the new bridge will take three years.", "vi": "Việc xây dựng cầu mới sẽ mất ba năm."},
                    {"en": "Construction noise disrupted the residents of the nearby apartments.", "vi": "Tiếng ồn xây dựng làm phiền cư dân của các căn hộ gần đó."}]},
    ]
  },
  {
    "id": "global-issues",
    "name": "Vấn Đề Toàn Cầu",
    "emoji": "🌏",
    "color": "red",
    "words": [
      {"word": "poverty", "meaning": "nghèo đói", "emoji": "😔", "class": "n",
       "examples": [{"en": "Millions of people still live in extreme poverty.", "vi": "Hàng triệu người vẫn sống trong cảnh nghèo đói cực độ."},
                    {"en": "Education is one of the most effective tools against poverty.", "vi": "Giáo dục là một trong những công cụ hiệu quả nhất chống lại nghèo đói."}]},
      {"word": "inequality", "meaning": "bất bình đẳng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Income inequality has widened in many countries over the last decade.", "vi": "Bất bình đẳng thu nhập đã gia tăng ở nhiều quốc gia trong thập kỷ qua."},
                    {"en": "Gender inequality continues to limit women's opportunities worldwide.", "vi": "Bất bình đẳng giới tiếp tục hạn chế cơ hội của phụ nữ trên toàn thế giới."}]},
      {"word": "migration", "meaning": "di cư", "emoji": "✈️", "class": "n",
       "examples": [{"en": "Economic migration drives people to seek better opportunities abroad.", "vi": "Di cư kinh tế thúc đẩy mọi người tìm kiếm cơ hội tốt hơn ở nước ngoài."},
                    {"en": "Climate migration may increase as sea levels rise.", "vi": "Di cư khí hậu có thể gia tăng khi mực nước biển dâng."}]},
      {"word": "refugee", "meaning": "người tị nạn", "emoji": "🏕️", "class": "n",
       "examples": [{"en": "Millions of refugees fled the war to neighboring countries.", "vi": "Hàng triệu người tị nạn chạy trốn chiến tranh sang các nước láng giềng."},
                    {"en": "Refugee camps provide basic shelter and food.", "vi": "Các trại tị nạn cung cấp chỗ ở và thức ăn cơ bản."}]},
      {"word": "famine", "meaning": "nạn đói", "emoji": "🌾", "class": "n",
       "examples": [{"en": "Drought and conflict together caused a devastating famine.", "vi": "Hạn hán và xung đột cùng nhau gây ra nạn đói tàn phá."},
                    {"en": "International aid organizations responded to the famine with food supplies.", "vi": "Các tổ chức viện trợ quốc tế ứng phó với nạn đói bằng lương thực."}]},
      {"word": "terrorism", "meaning": "khủng bố", "emoji": "💣", "class": "n",
       "examples": [{"en": "Terrorism threatens peace and security around the world.", "vi": "Khủng bố đe dọa hòa bình và an ninh trên toàn thế giới."},
                    {"en": "International cooperation is essential to combat terrorism.", "vi": "Hợp tác quốc tế là điều cần thiết để chống khủng bố."}]},
      {"word": "humanitarian", "meaning": "nhân đạo", "emoji": "❤️", "class": "adj",
       "examples": [{"en": "The Red Cross provides humanitarian aid in conflict zones.", "vi": "Chữ thập đỏ cung cấp viện trợ nhân đạo ở các vùng xung đột."},
                    {"en": "The humanitarian crisis required an urgent international response.", "vi": "Cuộc khủng hoảng nhân đạo đòi hỏi phản ứng quốc tế khẩn cấp."}]},
      {"word": "displacement", "meaning": "di dời cưỡng bức", "emoji": "🏚️", "class": "n",
       "examples": [{"en": "Climate change has caused the displacement of many coastal communities.", "vi": "Biến đổi khí hậu đã gây ra việc di dời nhiều cộng đồng ven biển."},
                    {"en": "Conflict is the leading cause of displacement worldwide.", "vi": "Xung đột là nguyên nhân hàng đầu dẫn đến di dời trên toàn thế giới."}]},
      {"word": "sanitation", "meaning": "vệ sinh môi trường", "emoji": "🚰", "class": "n",
       "examples": [{"en": "Access to clean water and sanitation is a basic human right.", "vi": "Tiếp cận nước sạch và vệ sinh môi trường là quyền con người cơ bản."},
                    {"en": "Poor sanitation spreads disease in overcrowded settlements.", "vi": "Vệ sinh môi trường kém làm lây lan dịch bệnh ở các khu định cư đông đúc."}]},
      {"word": "nuclear", "meaning": "hạt nhân", "emoji": "☢️", "class": "adj",
       "examples": [{"en": "The threat of nuclear war remains a major global concern.", "vi": "Mối đe dọa chiến tranh hạt nhân vẫn là mối lo ngại lớn trên toàn cầu."},
                    {"en": "Some countries are developing nuclear energy as a clean power source.", "vi": "Một số quốc gia đang phát triển năng lượng hạt nhân như một nguồn điện sạch."}]},
      {"word": "epidemic", "meaning": "dịch bệnh (khu vực)", "emoji": "🦠", "class": "n",
       "examples": [{"en": "An epidemic of cholera swept through the region.", "vi": "Một dịch tả quét qua khu vực."},
                    {"en": "Early response is critical to containing an epidemic.", "vi": "Phản ứng sớm là rất quan trọng để ngăn chặn dịch bệnh."}]},
      {"word": "geopolitics", "meaning": "địa chính trị", "emoji": "🗺️", "class": "n",
       "examples": [{"en": "Geopolitics shapes the relationships between powerful nations.", "vi": "Địa chính trị định hình mối quan hệ giữa các quốc gia hùng mạnh."},
                    {"en": "The conflict had deep geopolitical roots.", "vi": "Cuộc xung đột có gốc rễ địa chính trị sâu xa."}]},
      {"word": "aid", "meaning": "viện trợ", "emoji": "🆘", "class": "n",
       "examples": [{"en": "Foreign aid helped the country rebuild after the earthquake.", "vi": "Viện trợ nước ngoài giúp đất nước tái thiết sau trận động đất."},
                    {"en": "Humanitarian aid was delivered to remote villages by helicopter.", "vi": "Viện trợ nhân đạo được đưa đến các làng xa xôi bằng trực thăng."}]},
    ]
  },
  {
    "id": "literature-analysis",
    "name": "Phân Tích Văn Học",
    "emoji": "📖",
    "color": "fuchsia",
    "words": [
      {"word": "narrative", "meaning": "thể loại tự sự, câu chuyện", "emoji": "📜", "class": "n",
       "examples": [{"en": "The narrative follows a young woman's journey of self-discovery.", "vi": "Câu chuyện theo bước chân một người phụ nữ trẻ trên hành trình tự khám phá."},
                    {"en": "A first-person narrative creates a sense of intimacy with the reader.", "vi": "Văn tự sự ngôi thứ nhất tạo cảm giác thân mật với người đọc."}]},
      {"word": "protagonist", "meaning": "nhân vật chính", "emoji": "⭐", "class": "n",
       "examples": [{"en": "The protagonist must overcome many obstacles before reaching his goal.", "vi": "Nhân vật chính phải vượt qua nhiều trở ngại trước khi đạt được mục tiêu."},
                    {"en": "Hamlet is one of literature's most complex protagonists.", "vi": "Hamlet là một trong những nhân vật chính phức tạp nhất của văn học."}]},
      {"word": "antagonist", "meaning": "nhân vật phản diện", "emoji": "😈", "class": "n",
       "examples": [{"en": "The antagonist creates conflict that drives the story forward.", "vi": "Nhân vật phản diện tạo ra xung đột thúc đẩy câu chuyện tiến lên."},
                    {"en": "In this novel, the antagonist is society itself, not a single person.", "vi": "Trong cuốn tiểu thuyết này, nhân vật phản diện chính là xã hội, không phải một người cụ thể."}]},
      {"word": "metaphor", "meaning": "ẩn dụ", "emoji": "🌊", "class": "n",
       "examples": [{"en": "The storm in the poem is a metaphor for the character's inner turmoil.", "vi": "Cơn bão trong bài thơ là ẩn dụ cho sự hỗn loạn nội tâm của nhân vật."},
                    {"en": "Using metaphors makes writing more vivid and engaging.", "vi": "Sử dụng ẩn dụ làm cho văn viết sinh động và hấp dẫn hơn."}]},
      {"word": "symbolism", "meaning": "chủ nghĩa biểu tượng", "emoji": "🕊️", "class": "n",
       "examples": [{"en": "The dove is used as symbolism for peace throughout the text.", "vi": "Con chim bồ câu được dùng như biểu tượng cho hòa bình xuyên suốt văn bản."},
                    {"en": "Symbolism allows authors to convey complex ideas through images.", "vi": "Chủ nghĩa biểu tượng cho phép tác giả truyền đạt các ý tưởng phức tạp qua hình ảnh."}]},
      {"word": "irony", "meaning": "sự mỉa mai, nghịch lý", "emoji": "😏", "class": "n",
       "examples": [{"en": "The irony of the story is that the thief was a police officer.", "vi": "Sự mỉa mai của câu chuyện là tên trộm lại là một cảnh sát."},
                    {"en": "Verbal irony occurs when a speaker means the opposite of what they say.", "vi": "Mỉa mai ngôn từ xảy ra khi người nói có ý nghĩa ngược lại với điều họ nói."}]},
      {"word": "theme", "meaning": "chủ đề (văn học)", "emoji": "💡", "class": "n",
       "examples": [{"en": "Love and betrayal are central themes in Shakespeare's plays.", "vi": "Tình yêu và sự phản bội là các chủ đề trung tâm trong các vở kịch của Shakespeare."},
                    {"en": "The theme of identity runs throughout the novel.", "vi": "Chủ đề bản sắc xuất hiện xuyên suốt tiểu thuyết."}]},
      {"word": "motif", "meaning": "mô-típ văn học", "emoji": "🔄", "class": "n",
       "examples": [{"en": "A recurring motif of water in the poem suggests purification.", "vi": "Mô-típ nước lặp đi lặp lại trong bài thơ gợi ý sự thanh tẩy."},
                    {"en": "The color red is a motif representing danger in this story.", "vi": "Màu đỏ là mô-típ đại diện cho nguy hiểm trong câu chuyện này."}]},
      {"word": "foreshadowing", "meaning": "điềm báo, dự báo trước", "emoji": "🌩️", "class": "n",
       "examples": [{"en": "The author uses foreshadowing to hint at the tragic ending.", "vi": "Tác giả sử dụng điềm báo để gợi ý kết thúc bi thảm."},
                    {"en": "Foreshadowing builds suspense and prepares readers for future events.", "vi": "Điềm báo xây dựng sự hồi hộp và chuẩn bị cho người đọc về các sự kiện tương lai."}]},
      {"word": "allegory", "meaning": "ngụ ngôn", "emoji": "🐾", "class": "n",
       "examples": [{"en": "Animal Farm is an allegory for the Russian Revolution.", "vi": "Trang trại súc vật là một tác phẩm ngụ ngôn về Cách mạng Nga."},
                    {"en": "Allegory allows writers to criticize society indirectly.", "vi": "Ngụ ngôn cho phép nhà văn phê phán xã hội một cách gián tiếp."}]},
      {"word": "prose", "meaning": "văn xuôi", "emoji": "✍️", "class": "n",
       "examples": [{"en": "His prose style is clear, direct, and deeply personal.", "vi": "Phong cách văn xuôi của ông rõ ràng, trực tiếp và rất cá nhân."},
                    {"en": "Prose is distinguished from poetry by its lack of strict meter.", "vi": "Văn xuôi được phân biệt với thơ bởi sự thiếu nhịp điệu cố định."}]},
      {"word": "perspective", "meaning": "góc nhìn, quan điểm", "emoji": "👁️", "class": "n",
       "examples": [{"en": "The story is told from the perspective of a child.", "vi": "Câu chuyện được kể từ góc nhìn của một đứa trẻ."},
                    {"en": "Reading different perspectives helps us understand complex issues.", "vi": "Đọc các góc nhìn khác nhau giúp chúng ta hiểu các vấn đề phức tạp."}]},
      {"word": "verse", "meaning": "thơ, câu thơ", "emoji": "🎵", "class": "n",
       "examples": [{"en": "Shakespeare wrote in verse, using iambic pentameter.", "vi": "Shakespeare viết bằng thơ, sử dụng thể thơ iamb ngũ nhịp."},
                    {"en": "The poet's most famous verse is still memorized by children today.", "vi": "Câu thơ nổi tiếng nhất của nhà thơ vẫn được trẻ em thuộc lòng ngày nay."}]},
    ]
  },
  {
    "id": "space-universe",
    "name": "Vũ Trụ & Không Gian",
    "emoji": "🚀",
    "color": "indigo",
    "words": [
      {"word": "galaxy", "meaning": "thiên hà", "emoji": "🌌", "class": "n",
       "examples": [{"en": "Our solar system is located in the Milky Way galaxy.", "vi": "Hệ mặt trời của chúng ta nằm trong thiên hà Ngân Hà."},
                    {"en": "Astronomers have discovered billions of galaxies in the universe.", "vi": "Các nhà thiên văn học đã khám phá ra hàng tỷ thiên hà trong vũ trụ."}]},
      {"word": "orbit", "meaning": "quỹ đạo", "emoji": "🔄", "class": "n",
       "examples": [{"en": "The Earth takes 365 days to complete one orbit around the Sun.", "vi": "Trái đất mất 365 ngày để hoàn thành một quỹ đạo quanh Mặt trời."},
                    {"en": "Satellites are placed in orbit to observe the Earth's surface.", "vi": "Vệ tinh được đặt vào quỹ đạo để quan sát bề mặt Trái đất."}]},
      {"word": "asteroid", "meaning": "tiểu hành tinh", "emoji": "🪨", "class": "n",
       "examples": [{"en": "Scientists believe an asteroid strike caused the extinction of dinosaurs.", "vi": "Các nhà khoa học tin rằng một tiểu hành tinh va chạm đã gây ra sự tuyệt chủng của khủng long."},
                    {"en": "NASA monitors asteroids that could potentially hit Earth.", "vi": "NASA theo dõi các tiểu hành tinh có thể va vào Trái đất."}]},
      {"word": "telescope", "meaning": "kính thiên văn", "emoji": "🔭", "class": "n",
       "examples": [{"en": "The Hubble telescope has captured stunning images of distant galaxies.", "vi": "Kính thiên văn Hubble đã chụp được những hình ảnh tuyệt đẹp của các thiên hà xa xôi."},
                    {"en": "Amateur astronomers use telescopes to observe stars and planets.", "vi": "Các nhà thiên văn học nghiệp dư sử dụng kính thiên văn để quan sát các ngôi sao và hành tinh."}]},
      {"word": "gravity", "meaning": "trọng lực", "emoji": "🍎", "class": "n",
       "examples": [{"en": "Gravity holds the planets in their orbits around the Sun.", "vi": "Trọng lực giữ các hành tinh trong quỹ đạo quanh Mặt trời."},
                    {"en": "The Moon's gravity causes ocean tides on Earth.", "vi": "Trọng lực của Mặt trăng gây ra thủy triều đại dương trên Trái đất."}]},
      {"word": "atmosphere", "meaning": "bầu khí quyển", "emoji": "🌫️", "class": "n",
       "examples": [{"en": "Earth's atmosphere protects life from harmful solar radiation.", "vi": "Bầu khí quyển của Trái đất bảo vệ sự sống khỏi bức xạ mặt trời có hại."},
                    {"en": "Mars has a very thin atmosphere that cannot support human life.", "vi": "Sao Hỏa có bầu khí quyển rất mỏng không thể hỗ trợ sự sống của con người."}]},
      {"word": "comet", "meaning": "sao chổi", "emoji": "☄️", "class": "n",
       "examples": [{"en": "Halley's Comet is visible from Earth every 75-76 years.", "vi": "Sao chổi Halley có thể nhìn thấy từ Trái đất mỗi 75-76 năm."},
                    {"en": "A comet develops a bright tail as it approaches the Sun.", "vi": "Sao chổi phát triển đuôi sáng khi tiếp cận Mặt trời."}]},
      {"word": "black hole", "meaning": "hố đen", "emoji": "⚫", "class": "n",
       "examples": [{"en": "A black hole has such strong gravity that even light cannot escape.", "vi": "Hố đen có lực hút mạnh đến nỗi ngay cả ánh sáng cũng không thể thoát ra."},
                    {"en": "Scientists captured the first image of a black hole in 2019.", "vi": "Các nhà khoa học chụp được hình ảnh đầu tiên về hố đen vào năm 2019."}]},
      {"word": "constellation", "meaning": "chòm sao", "emoji": "⭐", "class": "n",
       "examples": [{"en": "Orion is one of the most recognizable constellations in the night sky.", "vi": "Orion là một trong những chòm sao dễ nhận biết nhất trên bầu trời đêm."},
                    {"en": "Ancient sailors used constellations to navigate at sea.", "vi": "Các thủy thủ cổ đại sử dụng các chòm sao để định hướng trên biển."}]},
      {"word": "nebula", "meaning": "tinh vân", "emoji": "🌈", "class": "n",
       "examples": [{"en": "A nebula is a cloud of gas and dust in outer space.", "vi": "Tinh vân là một đám mây khí và bụi trong không gian ngoài vũ trụ."},
                    {"en": "Stars are born inside dense regions of a nebula.", "vi": "Các ngôi sao được sinh ra bên trong các vùng dày đặc của tinh vân."}]},
      {"word": "satellite", "meaning": "vệ tinh nhân tạo", "emoji": "🛰️", "class": "n",
       "examples": [{"en": "GPS systems rely on a network of satellites orbiting Earth.", "vi": "Hệ thống GPS phụ thuộc vào mạng lưới vệ tinh quay quanh Trái đất."},
                    {"en": "The first artificial satellite, Sputnik, was launched in 1957.", "vi": "Vệ tinh nhân tạo đầu tiên, Sputnik, được phóng vào năm 1957."}]},
      {"word": "astronaut", "meaning": "phi hành gia", "emoji": "👨‍🚀", "class": "n",
       "examples": [{"en": "Astronauts train for years before going on a space mission.", "vi": "Các phi hành gia huấn luyện nhiều năm trước khi thực hiện nhiệm vụ không gian."},
                    {"en": "The astronaut spent six months aboard the International Space Station.", "vi": "Phi hành gia đã trải qua sáu tháng trên Trạm Vũ trụ Quốc tế."}]},
      {"word": "solar system", "meaning": "hệ mặt trời", "emoji": "🪐", "class": "n",
       "examples": [{"en": "Our solar system contains eight planets orbiting the Sun.", "vi": "Hệ mặt trời của chúng ta có tám hành tinh quay quanh Mặt trời."},
                    {"en": "Pluto was reclassified from a planet to a dwarf planet in our solar system.", "vi": "Sao Diêm vương được phân loại lại từ hành tinh thành hành tinh lùn trong hệ mặt trời."}]},
    ]
  },
  {
    "id": "food-agriculture",
    "name": "Thực Phẩm & Nông Nghiệp",
    "emoji": "🌾",
    "color": "lime",
    "words": [
      {"word": "irrigation", "meaning": "tưới tiêu", "emoji": "💧", "class": "n",
       "examples": [{"en": "Irrigation allows farmers to grow crops in dry regions.", "vi": "Tưới tiêu cho phép nông dân trồng cây ở các vùng khô hạn."},
                    {"en": "Drip irrigation is an efficient method that saves water.", "vi": "Tưới nhỏ giọt là phương pháp hiệu quả tiết kiệm nước."}]},
      {"word": "pesticide", "meaning": "thuốc trừ sâu", "emoji": "🐛", "class": "n",
       "examples": [{"en": "Overuse of pesticides can harm insects that are beneficial to farming.", "vi": "Lạm dụng thuốc trừ sâu có thể gây hại cho các côn trùng có lợi cho nông nghiệp."},
                    {"en": "Organic farmers avoid synthetic pesticides.", "vi": "Nông dân hữu cơ tránh sử dụng thuốc trừ sâu tổng hợp."}]},
      {"word": "harvest", "meaning": "thu hoạch mùa màng", "emoji": "🌽", "class": "n",
       "examples": [{"en": "The harvest was poor this year due to the dry summer.", "vi": "Mùa thu hoạch kém năm nay do mùa hè khô hạn."},
                    {"en": "Farmers work long hours during the harvest season.", "vi": "Nông dân làm việc nhiều giờ trong mùa thu hoạch."}]},
      {"word": "organic", "meaning": "hữu cơ", "emoji": "🥦", "class": "adj",
       "examples": [{"en": "Organic produce is grown without artificial chemicals.", "vi": "Sản phẩm hữu cơ được trồng mà không có hóa chất nhân tạo."},
                    {"en": "Demand for organic food has grown significantly over the past decade.", "vi": "Nhu cầu về thực phẩm hữu cơ đã tăng đáng kể trong thập kỷ qua."}]},
      {"word": "fertilizer", "meaning": "phân bón", "emoji": "🌱", "class": "n",
       "examples": [{"en": "Chemical fertilizers increase crop yields but can pollute waterways.", "vi": "Phân bón hóa học tăng năng suất cây trồng nhưng có thể ô nhiễm nguồn nước."},
                    {"en": "Compost is a natural fertilizer made from decomposed organic material.", "vi": "Phân compost là phân bón tự nhiên làm từ vật liệu hữu cơ phân hủy."}]},
      {"word": "livestock", "meaning": "gia súc", "emoji": "🐄", "class": "n",
       "examples": [{"en": "Livestock farming provides meat, dairy, and leather.", "vi": "Chăn nuôi gia súc cung cấp thịt, sữa và da."},
                    {"en": "Intensive livestock farming raises concerns about animal welfare.", "vi": "Chăn nuôi gia súc thâm canh làm dấy lên lo ngại về phúc lợi động vật."}]},
      {"word": "drought", "meaning": "hạn hán", "emoji": "☀️", "class": "n",
       "examples": [{"en": "A prolonged drought destroyed crops across the entire region.", "vi": "Một đợt hạn hán kéo dài đã phá hủy mùa màng trên toàn khu vực."},
                    {"en": "Farmers are adopting drought-resistant crops to survive dry spells.", "vi": "Nông dân đang áp dụng các giống cây chịu hạn để sống sót qua các đợt khô hạn."}]},
      {"word": "yield", "meaning": "năng suất", "emoji": "📈", "class": "n",
       "examples": [{"en": "New seed varieties have greatly increased crop yields.", "vi": "Các giống hạt mới đã tăng đáng kể năng suất cây trồng."},
                    {"en": "Good soil management maintains high yields year after year.", "vi": "Quản lý đất tốt duy trì năng suất cao qua nhiều năm."}]},
      {"word": "arable", "meaning": "có thể canh tác được", "emoji": "🌍", "class": "adj",
       "examples": [{"en": "Only a small percentage of the Earth's land is arable.", "vi": "Chỉ một tỷ lệ nhỏ đất trên Trái đất có thể canh tác được."},
                    {"en": "Converting forests to arable land destroys habitats.", "vi": "Chuyển đổi rừng thành đất canh tác phá hủy môi trường sống."}]},
      {"word": "genetically modified", "meaning": "biến đổi gen", "emoji": "🧬", "class": "adj",
       "examples": [{"en": "Genetically modified crops are designed to resist pests and disease.", "vi": "Cây trồng biến đổi gen được thiết kế để kháng sâu bệnh."},
                    {"en": "The safety of genetically modified food is still debated.", "vi": "Sự an toàn của thực phẩm biến đổi gen vẫn còn được tranh luận."}]},
      {"word": "crop", "meaning": "vụ mùa, cây trồng", "emoji": "🌿", "class": "n",
       "examples": [{"en": "Rice is the most important food crop in Southeast Asia.", "vi": "Gạo là cây lương thực quan trọng nhất ở Đông Nam Á."},
                    {"en": "Rotating crops prevents soil from losing its nutrients.", "vi": "Luân canh cây trồng ngăn đất mất chất dinh dưỡng."}]},
      {"word": "agribusiness", "meaning": "nông nghiệp thương mại quy mô lớn", "emoji": "🏭", "class": "n",
       "examples": [{"en": "Agribusiness has transformed traditional small-scale farming.", "vi": "Nông nghiệp thương mại đã biến đổi nông nghiệp quy mô nhỏ truyền thống."},
                    {"en": "Large agribusiness firms control much of the global food supply.", "vi": "Các công ty nông nghiệp thương mại lớn kiểm soát phần lớn nguồn cung thực phẩm toàn cầu."}]},
      {"word": "subsistence", "meaning": "tự cung tự cấp", "emoji": "🏡", "class": "adj",
       "examples": [{"en": "Many rural families practice subsistence farming to feed themselves.", "vi": "Nhiều gia đình nông thôn thực hành nông nghiệp tự cung tự cấp để tự nuôi sống bản thân."},
                    {"en": "Subsistence farmers grow only what they need for their own consumption.", "vi": "Nông dân tự cung tự cấp chỉ trồng những gì họ cần cho tiêu dùng của riêng mình."}]},
    ]
  },
  {
    "id": "human-rights",
    "name": "Quyền Con Người",
    "emoji": "✊",
    "color": "pink",
    "words": [
      {"word": "discrimination", "meaning": "phân biệt đối xử", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Racial discrimination in hiring is illegal in most countries.", "vi": "Phân biệt đối xử về chủng tộc trong tuyển dụng là bất hợp pháp ở hầu hết các quốc gia."},
                    {"en": "She filed a complaint about discrimination at her workplace.", "vi": "Cô ấy nộp đơn khiếu nại về phân biệt đối xử tại nơi làm việc."}]},
      {"word": "oppression", "meaning": "sự áp bức", "emoji": "⛓️", "class": "n",
       "examples": [{"en": "The movement was founded to fight against the oppression of minorities.", "vi": "Phong trào được thành lập để đấu tranh chống lại sự áp bức của các dân tộc thiểu số."},
                    {"en": "Oppression can take many forms, including economic and political control.", "vi": "Áp bức có thể có nhiều hình thức, bao gồm kiểm soát kinh tế và chính trị."}]},
      {"word": "advocacy", "meaning": "vận động (quyền lợi)", "emoji": "📣", "class": "n",
       "examples": [{"en": "She devoted her career to advocacy for children's rights.", "vi": "Cô dành sự nghiệp của mình để vận động cho quyền trẻ em."},
                    {"en": "Advocacy groups lobby governments to change unfair policies.", "vi": "Các nhóm vận động thúc đẩy chính phủ thay đổi các chính sách không công bằng."}]},
      {"word": "ratify", "meaning": "phê chuẩn (điều ước)", "emoji": "✍️", "class": "v",
       "examples": [{"en": "The country ratified the human rights convention last year.", "vi": "Quốc gia phê chuẩn công ước nhân quyền năm ngoái."},
                    {"en": "Until the treaty is ratified, it has no legal force.", "vi": "Cho đến khi điều ước được phê chuẩn, nó không có hiệu lực pháp lý."}]},
      {"word": "convention", "meaning": "công ước quốc tế", "emoji": "🌐", "class": "n",
       "examples": [{"en": "The UN Convention on the Rights of the Child protects children globally.", "vi": "Công ước Liên Hợp Quốc về Quyền Trẻ em bảo vệ trẻ em trên toàn cầu."},
                    {"en": "Countries that sign the convention are expected to respect its principles.", "vi": "Các quốc gia ký công ước được kỳ vọng tôn trọng các nguyên tắc của nó."}]},
      {"word": "asylum", "meaning": "nơi tị nạn chính trị", "emoji": "🏠", "class": "n",
       "examples": [{"en": "She applied for asylum after fleeing political persecution.", "vi": "Cô ấy xin tị nạn sau khi chạy trốn khỏi sự đàn áp chính trị."},
                    {"en": "Under international law, people have the right to seek asylum.", "vi": "Theo luật quốc tế, mọi người có quyền tìm kiếm nơi tị nạn."}]},
      {"word": "persecution", "meaning": "sự đàn áp", "emoji": "😨", "class": "n",
       "examples": [{"en": "Many fled the country due to religious persecution.", "vi": "Nhiều người chạy trốn khỏi đất nước do bị đàn áp tôn giáo."},
                    {"en": "The persecution of journalists silences important voices.", "vi": "Việc đàn áp các nhà báo bịt miệng những tiếng nói quan trọng."}]},
      {"word": "dignity", "meaning": "phẩm giá con người", "emoji": "🌟", "class": "n",
       "examples": [{"en": "Every person deserves to be treated with dignity.", "vi": "Mọi người đều xứng đáng được đối xử với phẩm giá."},
                    {"en": "Poverty can undermine people's dignity and sense of worth.", "vi": "Nghèo đói có thể làm suy yếu phẩm giá và ý thức về giá trị của con người."}]},
      {"word": "violation", "meaning": "vi phạm (nhân quyền)", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "The report documented serious human rights violations.", "vi": "Báo cáo ghi chép các vi phạm nhân quyền nghiêm trọng."},
                    {"en": "Torture is a clear violation of international law.", "vi": "Tra tấn là vi phạm rõ ràng luật pháp quốc tế."}]},
      {"word": "equality", "meaning": "sự bình đẳng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Gender equality means giving men and women the same opportunities.", "vi": "Bình đẳng giới có nghĩa là trao cho nam và nữ những cơ hội như nhau."},
                    {"en": "The constitution guarantees equality before the law for all citizens.", "vi": "Hiến pháp bảo đảm bình đẳng trước pháp luật cho tất cả công dân."}]},
      {"word": "charter", "meaning": "hiến chương", "emoji": "📜", "class": "n",
       "examples": [{"en": "The UN Charter commits member states to peaceful resolution of disputes.", "vi": "Hiến chương Liên Hợp Quốc cam kết các quốc gia thành viên giải quyết tranh chấp một cách hòa bình."},
                    {"en": "The organization's charter outlines its founding principles.", "vi": "Hiến chương của tổ chức nêu rõ các nguyên tắc sáng lập."}]},
      {"word": "justice", "meaning": "công lý", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Victims of war crimes deserve justice.", "vi": "Nạn nhân của tội ác chiến tranh xứng đáng được công lý."},
                    {"en": "Access to justice is a fundamental human right.", "vi": "Tiếp cận công lý là một quyền con người cơ bản."}]},
      {"word": "freedom", "meaning": "tự do", "emoji": "🕊️", "class": "n",
       "examples": [{"en": "Freedom of speech is protected in democratic societies.", "vi": "Tự do ngôn luận được bảo vệ trong các xã hội dân chủ."},
                    {"en": "The struggle for freedom has defined many historical movements.", "vi": "Cuộc đấu tranh vì tự do đã xác định nhiều phong trào lịch sử."}]},
    ]
  },
  {
    "id": "innovation-startup",
    "name": "Khởi Nghiệp & Đổi Mới",
    "emoji": "💡",
    "color": "teal",
    "words": [
      {"word": "venture capital", "meaning": "vốn đầu tư mạo hiểm", "emoji": "💸", "class": "n",
       "examples": [{"en": "The startup raised five million dollars in venture capital funding.", "vi": "Công ty khởi nghiệp huy động được năm triệu đô la vốn đầu tư mạo hiểm."},
                    {"en": "Venture capital firms look for high-growth potential companies.", "vi": "Các công ty đầu tư mạo hiểm tìm kiếm các công ty có tiềm năng tăng trưởng cao."}]},
      {"word": "pitch", "meaning": "thuyết trình kêu gọi đầu tư", "emoji": "🎤", "class": "n",
       "examples": [{"en": "Her pitch to the investors was confident and well-researched.", "vi": "Bài thuyết trình kêu gọi đầu tư của cô ấy tự tin và được nghiên cứu kỹ."},
                    {"en": "A strong pitch deck can convince investors to fund your idea.", "vi": "Một bộ slide thuyết trình tốt có thể thuyết phục nhà đầu tư tài trợ cho ý tưởng của bạn."}]},
      {"word": "scalable", "meaning": "có thể mở rộng quy mô", "emoji": "📈", "class": "adj",
       "examples": [{"en": "Investors want to fund scalable business models.", "vi": "Nhà đầu tư muốn tài trợ cho các mô hình kinh doanh có thể mở rộng quy mô."},
                    {"en": "A scalable product can grow without a proportional increase in costs.", "vi": "Một sản phẩm có thể mở rộng quy mô có thể tăng trưởng mà không tăng chi phí tương ứng."}]},
      {"word": "disrupt", "meaning": "phá vỡ (thị trường truyền thống)", "emoji": "💥", "class": "v",
       "examples": [{"en": "Airbnb disrupted the hotel industry with a new business model.", "vi": "Airbnb đã phá vỡ ngành khách sạn bằng một mô hình kinh doanh mới."},
                    {"en": "Technology continues to disrupt traditional industries.", "vi": "Công nghệ tiếp tục phá vỡ các ngành công nghiệp truyền thống."}]},
      {"word": "pivot", "meaning": "thay đổi hướng kinh doanh", "emoji": "🔄", "class": "v",
       "examples": [{"en": "The company pivoted from software to hardware after market feedback.", "vi": "Công ty đã thay đổi hướng từ phần mềm sang phần cứng sau phản hồi từ thị trường."},
                    {"en": "Knowing when to pivot is a critical skill for entrepreneurs.", "vi": "Biết khi nào nên thay đổi hướng là kỹ năng quan trọng của doanh nhân."}]},
      {"word": "incubator", "meaning": "vườn ươm doanh nghiệp", "emoji": "🌱", "class": "n",
       "examples": [{"en": "The university's startup incubator provides mentorship and resources.", "vi": "Vườn ươm doanh nghiệp của trường đại học cung cấp cố vấn và nguồn lực."},
                    {"en": "Many successful companies began in business incubators.", "vi": "Nhiều công ty thành công đã bắt đầu từ các vườn ươm doanh nghiệp."}]},
      {"word": "valuation", "meaning": "định giá doanh nghiệp", "emoji": "💰", "class": "n",
       "examples": [{"en": "The startup's valuation reached one billion dollars after the funding round.", "vi": "Định giá của công ty khởi nghiệp đạt một tỷ đô la sau vòng gọi vốn."},
                    {"en": "Valuation depends on a company's revenue, growth, and market potential.", "vi": "Định giá phụ thuộc vào doanh thu, tăng trưởng và tiềm năng thị trường của công ty."}]},
      {"word": "iteration", "meaning": "chu kỳ phát triển, cải tiến liên tục", "emoji": "🔁", "class": "n",
       "examples": [{"en": "After several iterations, the product was ready for launch.", "vi": "Sau nhiều chu kỳ phát triển, sản phẩm đã sẵn sàng ra mắt."},
                    {"en": "Each iteration of the app added new features based on user feedback.", "vi": "Mỗi lần cải tiến ứng dụng đều thêm các tính năng mới dựa trên phản hồi của người dùng."}]},
      {"word": "funding", "meaning": "vốn tài trợ", "emoji": "💵", "class": "n",
       "examples": [{"en": "Securing funding is one of the biggest challenges for new startups.", "vi": "Đảm bảo vốn tài trợ là một trong những thách thức lớn nhất đối với các startup mới."},
                    {"en": "The team used crowdfunding to raise initial funding for the project.", "vi": "Nhóm sử dụng huy động vốn cộng đồng để tăng vốn ban đầu cho dự án."}]},
      {"word": "accelerator", "meaning": "chương trình tăng tốc khởi nghiệp", "emoji": "🚀", "class": "n",
       "examples": [{"en": "Y Combinator is one of the world's most famous startup accelerators.", "vi": "Y Combinator là một trong những chương trình tăng tốc khởi nghiệp nổi tiếng nhất thế giới."},
                    {"en": "An accelerator gives startups mentorship, funding, and networking opportunities.", "vi": "Một chương trình tăng tốc cung cấp cho startup cố vấn, vốn và cơ hội kết nối."}]},
      {"word": "lean", "meaning": "tinh gọn (phương pháp quản lý)", "emoji": "⚡", "class": "adj",
       "examples": [{"en": "The lean startup method encourages testing ideas quickly and cheaply.", "vi": "Phương pháp startup tinh gọn khuyến khích kiểm tra ý tưởng nhanh chóng và tiết kiệm."},
                    {"en": "A lean operation minimizes waste and maximizes efficiency.", "vi": "Hoạt động tinh gọn giảm thiểu lãng phí và tối đa hóa hiệu quả."}]},
      {"word": "seed round", "meaning": "vòng gọi vốn hạt giống", "emoji": "🌰", "class": "n",
       "examples": [{"en": "The company raised 500,000 dollars in its seed round.", "vi": "Công ty huy động được 500.000 đô la trong vòng gọi vốn hạt giống."},
                    {"en": "A seed round usually comes from angel investors or friends and family.", "vi": "Vòng gọi vốn hạt giống thường đến từ các nhà đầu tư thiên thần hoặc bạn bè và gia đình."}]},
      {"word": "disruption", "meaning": "sự gián đoạn, phá vỡ trật tự cũ", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Digital disruption has transformed the music and film industries.", "vi": "Sự phá vỡ kỹ thuật số đã biến đổi ngành âm nhạc và điện ảnh."},
                    {"en": "Embracing disruption is key to staying competitive in modern business.", "vi": "Chấp nhận sự phá vỡ trật tự cũ là chìa khóa để duy trì cạnh tranh trong kinh doanh hiện đại."}]},
    ]
  },
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'words.json')
with open(data_path) as f:
    data = json.load(f)

data['scholar']['topics'].extend(topics_11_20)

with open(data_path, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done: {len(topics_11_20)} more topics added")
for t in topics_11_20:
    print(f"  {t['id']}: {len(t['words'])} words")
total = sum(len(t['words']) for t in data['scholar']['topics'])
print(f"Scholar total so far: {len(data['scholar']['topics'])} topics, {total} words")
