import json, os

topics_1_10 = [
  {
    "id": "academic-skills",
    "name": "Kỹ Năng Học Thuật",
    "emoji": "📝",
    "color": "indigo",
    "words": [
      {"word": "analyze", "meaning": "phân tích", "emoji": "🔍", "class": "v",
       "examples": [{"en": "You need to analyze the data before drawing any conclusions.", "vi": "Bạn cần phân tích dữ liệu trước khi đưa ra kết luận."},
                    {"en": "The student analyzed the poem for its hidden meaning.", "vi": "Học sinh phân tích bài thơ để tìm ý nghĩa ẩn."}]},
      {"word": "synthesize", "meaning": "tổng hợp", "emoji": "🔗", "class": "v",
       "examples": [{"en": "Good writers synthesize ideas from multiple sources.", "vi": "Những nhà văn giỏi tổng hợp ý tưởng từ nhiều nguồn."},
                    {"en": "The report synthesizes the findings of ten studies.", "vi": "Báo cáo tổng hợp kết quả của mười nghiên cứu."}]},
      {"word": "evaluate", "meaning": "đánh giá", "emoji": "⚖️", "class": "v",
       "examples": [{"en": "We must evaluate the strengths and weaknesses of each argument.", "vi": "Chúng ta phải đánh giá điểm mạnh và điểm yếu của từng lập luận."},
                    {"en": "The committee evaluated all applications carefully.", "vi": "Ủy ban đánh giá tất cả các đơn xin cẩn thận."}]},
      {"word": "thesis", "meaning": "luận văn / luận điểm", "emoji": "📄", "class": "n",
       "examples": [{"en": "Her thesis argued that climate change affects migration patterns.", "vi": "Luận văn của cô lập luận rằng biến đổi khí hậu ảnh hưởng đến các kiểu di cư."},
                    {"en": "A strong thesis statement is the foundation of any essay.", "vi": "Một luận điểm mạnh là nền tảng của bất kỳ bài luận nào."}]},
      {"word": "methodology", "meaning": "phương pháp luận", "emoji": "🗂️", "class": "n",
       "examples": [{"en": "The research methodology was clearly explained in chapter two.", "vi": "Phương pháp luận nghiên cứu được giải thích rõ ràng trong chương hai."},
                    {"en": "We need a consistent methodology to compare results.", "vi": "Chúng ta cần một phương pháp luận nhất quán để so sánh kết quả."}]},
      {"word": "citation", "meaning": "trích dẫn", "emoji": "📌", "class": "n",
       "examples": [{"en": "Always include a citation when you use someone else's idea.", "vi": "Luôn ghi trích dẫn khi bạn sử dụng ý tưởng của người khác."},
                    {"en": "The essay had over twenty citations from academic journals.", "vi": "Bài luận có hơn hai mươi trích dẫn từ các tạp chí học thuật."}]},
      {"word": "abstract", "meaning": "tóm tắt (bài nghiên cứu)", "emoji": "📋", "class": "n",
       "examples": [{"en": "Read the abstract before deciding whether to read the full paper.", "vi": "Đọc tóm tắt trước khi quyết định đọc toàn bộ bài báo."},
                    {"en": "The abstract summarized the key findings in 200 words.", "vi": "Phần tóm tắt tóm gọn các phát hiện chính trong 200 từ."}]},
      {"word": "paraphrase", "meaning": "diễn giải lại", "emoji": "✏️", "class": "v",
       "examples": [{"en": "Paraphrase the author's idea in your own words.", "vi": "Hãy diễn giải lại ý tưởng của tác giả bằng lời của bạn."},
                    {"en": "He paraphrased the paragraph to avoid plagiarism.", "vi": "Anh ấy diễn giải lại đoạn văn để tránh đạo văn."}]},
      {"word": "coherent", "meaning": "mạch lạc, nhất quán", "emoji": "🧵", "class": "adj",
       "examples": [{"en": "A coherent argument is easy to follow and understand.", "vi": "Một lập luận mạch lạc dễ theo dõi và hiểu."},
                    {"en": "Make sure your essay is coherent from introduction to conclusion.", "vi": "Hãy đảm bảo bài luận của bạn mạch lạc từ mở đầu đến kết luận."}]},
      {"word": "argument", "meaning": "lập luận", "emoji": "💬", "class": "n",
       "examples": [{"en": "Her argument was supported by strong evidence.", "vi": "Lập luận của cô ấy được hỗ trợ bởi bằng chứng mạnh mẽ."},
                    {"en": "Construct your argument logically and clearly.", "vi": "Hãy xây dựng lập luận của bạn một cách logic và rõ ràng."}]},
      {"word": "critique", "meaning": "phê bình, phân tích phê phán", "emoji": "🎯", "class": "n",
       "examples": [{"en": "The professor gave a detailed critique of the student's work.", "vi": "Giáo sư đưa ra bài phê bình chi tiết về công trình của học sinh."},
                    {"en": "Write a critique that identifies both strengths and weaknesses.", "vi": "Hãy viết một bài phê bình xác định cả điểm mạnh lẫn điểm yếu."}]},
      {"word": "bibliography", "meaning": "danh mục tài liệu tham khảo", "emoji": "📚", "class": "n",
       "examples": [{"en": "Include a full bibliography at the end of your paper.", "vi": "Hãy ghi đầy đủ danh mục tài liệu tham khảo ở cuối bài."},
                    {"en": "The bibliography listed over thirty books and articles.", "vi": "Danh mục tài liệu liệt kê hơn ba mươi sách và bài báo."}]},
      {"word": "peer review", "meaning": "phản biện đồng nghiệp", "emoji": "👥", "class": "n",
       "examples": [{"en": "The study passed peer review before being published.", "vi": "Nghiên cứu đã vượt qua phản biện đồng nghiệp trước khi được xuất bản."},
                    {"en": "Peer review helps catch errors in scientific papers.", "vi": "Phản biện đồng nghiệp giúp phát hiện lỗi trong các bài báo khoa học."}]},
    ]
  },
  {
    "id": "media-journalism",
    "name": "Truyền Thông & Báo Chí",
    "emoji": "📰",
    "color": "slate",
    "words": [
      {"word": "headline", "meaning": "tiêu đề (báo)", "emoji": "🗞️", "class": "n",
       "examples": [{"en": "The headline grabbed everyone's attention.", "vi": "Tiêu đề thu hút sự chú ý của mọi người."},
                    {"en": "Misleading headlines spread misinformation quickly.", "vi": "Tiêu đề gây hiểu nhầm lan truyền thông tin sai nhanh chóng."}]},
      {"word": "broadcast", "meaning": "phát sóng", "emoji": "📡", "class": "v",
       "examples": [{"en": "The news was broadcast live on national television.", "vi": "Tin tức được phát sóng trực tiếp trên đài truyền hình quốc gia."},
                    {"en": "They broadcast the event to millions of viewers.", "vi": "Họ phát sóng sự kiện đến hàng triệu khán giả."}]},
      {"word": "journalist", "meaning": "nhà báo", "emoji": "🎤", "class": "n",
       "examples": [{"en": "The journalist investigated the corruption scandal for months.", "vi": "Nhà báo điều tra vụ bê bối tham nhũng trong nhiều tháng."},
                    {"en": "Journalists have a duty to report the truth accurately.", "vi": "Nhà báo có trách nhiệm đưa tin chính xác."}]},
      {"word": "editorial", "meaning": "bài xã luận", "emoji": "✍️", "class": "n",
       "examples": [{"en": "The newspaper published an editorial criticizing the new law.", "vi": "Tờ báo đăng bài xã luận chỉ trích luật mới."},
                    {"en": "An editorial reflects the opinions of the newspaper's editors.", "vi": "Bài xã luận phản ánh quan điểm của ban biên tập tờ báo."}]},
      {"word": "bias", "meaning": "thiên kiến, thành kiến", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Every media outlet has some degree of bias.", "vi": "Mọi cơ quan truyền thông đều có một mức độ thiên kiến nhất định."},
                    {"en": "Readers should be aware of bias when consuming news.", "vi": "Độc giả nên nhận thức về thiên kiến khi tiêu thụ tin tức."}]},
      {"word": "censorship", "meaning": "kiểm duyệt", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Censorship of the press limits freedom of information.", "vi": "Kiểm duyệt báo chí hạn chế quyền tự do thông tin."},
                    {"en": "The government faced criticism for its censorship policies.", "vi": "Chính phủ đối mặt với chỉ trích về các chính sách kiểm duyệt."}]},
      {"word": "correspondent", "meaning": "phóng viên thường trú", "emoji": "🌍", "class": "n",
       "examples": [{"en": "Our foreign correspondent reported from the conflict zone.", "vi": "Phóng viên nước ngoài của chúng tôi đưa tin từ vùng xung đột."},
                    {"en": "She became the BBC's chief correspondent in Asia.", "vi": "Cô trở thành phóng viên thường trú chính của BBC tại châu Á."}]},
      {"word": "coverage", "meaning": "sự đưa tin, phạm vi đưa tin", "emoji": "📸", "class": "n",
       "examples": [{"en": "The election received extensive coverage in the media.", "vi": "Cuộc bầu cử được đưa tin rộng rãi trên các phương tiện truyền thông."},
                    {"en": "Media coverage of the disaster helped raise donations.", "vi": "Đưa tin về thảm họa giúp thu hút quyên góp."}]},
      {"word": "propaganda", "meaning": "tuyên truyền", "emoji": "📢", "class": "n",
       "examples": [{"en": "Propaganda is used to influence public opinion.", "vi": "Tuyên truyền được dùng để tác động đến dư luận."},
                    {"en": "They spread propaganda through social media.", "vi": "Họ lan truyền tuyên truyền qua mạng xã hội."}]},
      {"word": "verify", "meaning": "xác minh", "emoji": "✅", "class": "v",
       "examples": [{"en": "Always verify the facts before publishing a story.", "vi": "Luôn xác minh sự thật trước khi đăng bài."},
                    {"en": "The editor asked the reporter to verify all the sources.", "vi": "Biên tập viên yêu cầu phóng viên xác minh tất cả các nguồn."}]},
      {"word": "circulation", "meaning": "lượng phát hành", "emoji": "📊", "class": "n",
       "examples": [{"en": "The newspaper's circulation has dropped with the rise of online news.", "vi": "Lượng phát hành của tờ báo giảm cùng với sự phát triển của tin tức trực tuyến."},
                    {"en": "This magazine has a weekly circulation of 500,000 copies.", "vi": "Tạp chí này có lượng phát hành hàng tuần là 500.000 bản."}]},
      {"word": "source", "meaning": "nguồn tin", "emoji": "🔎", "class": "n",
       "examples": [{"en": "A reliable source confirmed the story.", "vi": "Một nguồn tin đáng tin cậy đã xác nhận câu chuyện."},
                    {"en": "Good journalism always cites its sources.", "vi": "Báo chí tốt luôn trích dẫn nguồn tin."}]},
      {"word": "feature", "meaning": "bài phóng sự đặc biệt", "emoji": "🌟", "class": "n",
       "examples": [{"en": "She wrote a feature on the lives of street children.", "vi": "Cô viết bài phóng sự về cuộc sống của trẻ em đường phố."},
                    {"en": "The magazine's feature explored the future of work.", "vi": "Bài phóng sự của tạp chí khám phá tương lai của công việc."}]},
    ]
  },
  {
    "id": "law-justice",
    "name": "Pháp Luật & Công Lý",
    "emoji": "⚖️",
    "color": "gray",
    "words": [
      {"word": "defendant", "meaning": "bị cáo", "emoji": "🧑‍⚖️", "class": "n",
       "examples": [{"en": "The defendant pleaded not guilty at the trial.", "vi": "Bị cáo khai không có tội tại phiên tòa."},
                    {"en": "The defense lawyer protected the rights of the defendant.", "vi": "Luật sư bào chữa bảo vệ quyền lợi của bị cáo."}]},
      {"word": "verdict", "meaning": "phán quyết", "emoji": "🔨", "class": "n",
       "examples": [{"en": "The jury reached a verdict of not guilty.", "vi": "Bồi thẩm đoàn đưa ra phán quyết không có tội."},
                    {"en": "Everyone awaited the verdict nervously.", "vi": "Mọi người lo lắng chờ đợi phán quyết."}]},
      {"word": "testimony", "meaning": "lời khai", "emoji": "🗣️", "class": "n",
       "examples": [{"en": "The witness gave her testimony in court.", "vi": "Nhân chứng đưa ra lời khai tại tòa."},
                    {"en": "His testimony proved critical to the outcome of the trial.", "vi": "Lời khai của anh ấy rất quan trọng đối với kết quả phiên tòa."}]},
      {"word": "prosecution", "meaning": "bên công tố", "emoji": "⚔️", "class": "n",
       "examples": [{"en": "The prosecution presented strong evidence against the accused.", "vi": "Bên công tố đưa ra bằng chứng mạnh mẽ chống lại bị cáo."},
                    {"en": "The prosecution called five witnesses to the stand.", "vi": "Bên công tố gọi năm nhân chứng lên tòa."}]},
      {"word": "legislation", "meaning": "luật pháp, lập pháp", "emoji": "📜", "class": "n",
       "examples": [{"en": "New legislation was passed to protect consumers.", "vi": "Luật mới được thông qua để bảo vệ người tiêu dùng."},
                    {"en": "The government proposed legislation to reduce air pollution.", "vi": "Chính phủ đề xuất luật để giảm ô nhiễm không khí."}]},
      {"word": "amendment", "meaning": "điều khoản sửa đổi", "emoji": "✏️", "class": "n",
       "examples": [{"en": "An amendment to the constitution was proposed.", "vi": "Một điều khoản sửa đổi hiến pháp đã được đề xuất."},
                    {"en": "The amendment guarantees freedom of speech.", "vi": "Điều khoản sửa đổi đảm bảo tự do ngôn luận."}]},
      {"word": "liable", "meaning": "chịu trách nhiệm pháp lý", "emoji": "📋", "class": "adj",
       "examples": [{"en": "The company was held liable for the accident.", "vi": "Công ty bị quy trách nhiệm pháp lý về vụ tai nạn."},
                    {"en": "You may be liable for damages if you break the contract.", "vi": "Bạn có thể chịu trách nhiệm bồi thường nếu vi phạm hợp đồng."}]},
      {"word": "attorney", "meaning": "luật sư", "emoji": "👔", "class": "n",
       "examples": [{"en": "She hired an attorney to represent her in court.", "vi": "Cô thuê một luật sư để đại diện cho mình tại tòa."},
                    {"en": "The attorney advised his client to remain silent.", "vi": "Luật sư khuyên thân chủ của mình giữ im lặng."}]},
      {"word": "appeal", "meaning": "kháng cáo", "emoji": "📩", "class": "n",
       "examples": [{"en": "The convicted man filed an appeal against his sentence.", "vi": "Người bị kết án đã nộp đơn kháng cáo bản án."},
                    {"en": "The appeal was rejected by the higher court.", "vi": "Kháng cáo bị tòa án cấp trên bác bỏ."}]},
      {"word": "jurisdiction", "meaning": "thẩm quyền tài phán", "emoji": "🗺️", "class": "n",
       "examples": [{"en": "This crime falls under the jurisdiction of the federal court.", "vi": "Tội phạm này thuộc thẩm quyền tài phán của tòa liên bang."},
                    {"en": "Different countries have different jurisdictions over international cases.", "vi": "Các quốc gia khác nhau có thẩm quyền khác nhau đối với các vụ án quốc tế."}]},
      {"word": "penalty", "meaning": "hình phạt", "emoji": "🔒", "class": "n",
       "examples": [{"en": "The penalty for tax evasion can include imprisonment.", "vi": "Hình phạt cho tội trốn thuế có thể bao gồm tù giam."},
                    {"en": "Stricter penalties were introduced to deter crime.", "vi": "Hình phạt nghiêm khắc hơn được đưa ra để ngăn chặn tội phạm."}]},
      {"word": "statute", "meaning": "quy chế, đạo luật", "emoji": "📖", "class": "n",
       "examples": [{"en": "The statute of limitations means some crimes cannot be prosecuted.", "vi": "Thời hiệu truy tố có nghĩa là một số tội phạm không thể bị truy tố."},
                    {"en": "This statute was enacted to protect children's rights.", "vi": "Đạo luật này được ban hành để bảo vệ quyền trẻ em."}]},
      {"word": "constitute", "meaning": "cấu thành (tội danh)", "emoji": "⚠️", "class": "v",
       "examples": [{"en": "Taking someone else's work without credit constitutes plagiarism.", "vi": "Lấy tác phẩm của người khác mà không ghi nhận là cấu thành hành vi đạo văn."},
                    {"en": "This behavior may constitute a breach of contract.", "vi": "Hành vi này có thể cấu thành vi phạm hợp đồng."}]},
    ]
  },
  {
    "id": "economics-trade",
    "name": "Kinh Tế & Thương Mại",
    "emoji": "📈",
    "color": "emerald",
    "words": [
      {"word": "inflation", "meaning": "lạm phát", "emoji": "💹", "class": "n",
       "examples": [{"en": "High inflation reduces people's purchasing power.", "vi": "Lạm phát cao làm giảm sức mua của người dân."},
                    {"en": "The government raised interest rates to control inflation.", "vi": "Chính phủ tăng lãi suất để kiểm soát lạm phát."}]},
      {"word": "recession", "meaning": "suy thoái kinh tế", "emoji": "📉", "class": "n",
       "examples": [{"en": "The country entered a recession after the financial crisis.", "vi": "Đất nước rơi vào suy thoái kinh tế sau cuộc khủng hoảng tài chính."},
                    {"en": "During a recession, unemployment typically rises.", "vi": "Trong thời kỳ suy thoái, tỷ lệ thất nghiệp thường tăng."}]},
      {"word": "tariff", "meaning": "thuế quan", "emoji": "🏷️", "class": "n",
       "examples": [{"en": "The government imposed tariffs on imported steel.", "vi": "Chính phủ áp đặt thuế quan lên thép nhập khẩu."},
                    {"en": "High tariffs can protect domestic industries but raise prices.", "vi": "Thuế quan cao có thể bảo vệ ngành công nghiệp trong nước nhưng làm tăng giá."}]},
      {"word": "subsidy", "meaning": "trợ cấp nhà nước", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Farmers received government subsidies to help them survive the drought.", "vi": "Nông dân nhận được trợ cấp của chính phủ để giúp họ vượt qua hạn hán."},
                    {"en": "Subsidies for renewable energy encourage green investment.", "vi": "Trợ cấp cho năng lượng tái tạo khuyến khích đầu tư xanh."}]},
      {"word": "monopoly", "meaning": "độc quyền", "emoji": "🏆", "class": "n",
       "examples": [{"en": "The company had a monopoly on the supply of clean water.", "vi": "Công ty có độc quyền cung cấp nước sạch."},
                    {"en": "Monopolies often lead to higher prices and less innovation.", "vi": "Độc quyền thường dẫn đến giá cao hơn và ít đổi mới hơn."}]},
      {"word": "deficit", "meaning": "thâm hụt ngân sách", "emoji": "🔻", "class": "n",
       "examples": [{"en": "The country ran a large budget deficit last year.", "vi": "Quốc gia có thâm hụt ngân sách lớn năm ngoái."},
                    {"en": "A trade deficit occurs when a country imports more than it exports.", "vi": "Thâm hụt thương mại xảy ra khi một nước nhập khẩu nhiều hơn xuất khẩu."}]},
      {"word": "commodity", "meaning": "hàng hóa cơ bản", "emoji": "🛢️", "class": "n",
       "examples": [{"en": "Oil is one of the world's most traded commodities.", "vi": "Dầu là một trong những hàng hóa được giao dịch nhiều nhất thế giới."},
                    {"en": "Commodity prices fluctuate with global supply and demand.", "vi": "Giá hàng hóa biến động theo cung cầu toàn cầu."}]},
      {"word": "fiscal", "meaning": "thuộc tài khóa", "emoji": "💰", "class": "adj",
       "examples": [{"en": "The government adopted a strict fiscal policy to reduce spending.", "vi": "Chính phủ áp dụng chính sách tài khóa nghiêm ngặt để giảm chi tiêu."},
                    {"en": "The fiscal year ends on March 31st.", "vi": "Năm tài khóa kết thúc vào ngày 31 tháng 3."}]},
      {"word": "currency", "meaning": "tiền tệ", "emoji": "💵", "class": "n",
       "examples": [{"en": "The local currency lost half its value in one year.", "vi": "Đồng tiền địa phương mất một nửa giá trị trong một năm."},
                    {"en": "The euro is the shared currency of many European countries.", "vi": "Euro là đồng tiền chung của nhiều nước châu Âu."}]},
      {"word": "transaction", "meaning": "giao dịch", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Every financial transaction is recorded in the system.", "vi": "Mọi giao dịch tài chính được ghi lại trong hệ thống."},
                    {"en": "Online transactions have become the norm for shopping.", "vi": "Giao dịch trực tuyến đã trở thành tiêu chuẩn cho mua sắm."}]},
      {"word": "export", "meaning": "xuất khẩu", "emoji": "🚢", "class": "v",
       "examples": [{"en": "Vietnam exports a large amount of coffee every year.", "vi": "Việt Nam xuất khẩu một lượng lớn cà phê mỗi năm."},
                    {"en": "Exporting manufactured goods helps grow the economy.", "vi": "Xuất khẩu hàng hóa chế tạo giúp phát triển kinh tế."}]},
      {"word": "import", "meaning": "nhập khẩu", "emoji": "📦", "class": "v",
       "examples": [{"en": "The country imports most of its energy from abroad.", "vi": "Đất nước nhập khẩu hầu hết năng lượng từ nước ngoài."},
                    {"en": "Importing cheaper goods can hurt local producers.", "vi": "Nhập khẩu hàng hóa rẻ hơn có thể gây hại cho các nhà sản xuất trong nước."}]},
      {"word": "GDP", "meaning": "tổng sản phẩm quốc nội", "emoji": "🌐", "class": "n",
       "examples": [{"en": "GDP measures the total value of goods and services produced in a country.", "vi": "GDP đo tổng giá trị hàng hóa và dịch vụ được sản xuất trong một quốc gia."},
                    {"en": "The country's GDP grew by 6% last year.", "vi": "GDP của đất nước tăng trưởng 6% năm ngoái."}]},
    ]
  },
  {
    "id": "psychology-mind",
    "name": "Tâm Lý & Tư Duy",
    "emoji": "🧠",
    "color": "violet",
    "words": [
      {"word": "perception", "meaning": "nhận thức, sự cảm nhận", "emoji": "👁️", "class": "n",
       "examples": [{"en": "Our perception of reality is shaped by our experiences.", "vi": "Nhận thức của chúng ta về thực tế được định hình bởi kinh nghiệm."},
                    {"en": "Perception can differ greatly from person to person.", "vi": "Nhận thức có thể khác nhau rất nhiều giữa người này và người khác."}]},
      {"word": "cognitive", "meaning": "thuộc nhận thức", "emoji": "🔬", "class": "adj",
       "examples": [{"en": "Playing chess improves cognitive skills.", "vi": "Chơi cờ vua cải thiện các kỹ năng nhận thức."},
                    {"en": "Cognitive development in children happens rapidly in early years.", "vi": "Sự phát triển nhận thức ở trẻ em diễn ra nhanh chóng trong những năm đầu đời."}]},
      {"word": "trauma", "meaning": "chấn thương tâm lý", "emoji": "💔", "class": "n",
       "examples": [{"en": "Childhood trauma can affect mental health in adult life.", "vi": "Chấn thương tâm lý thời thơ ấu có thể ảnh hưởng đến sức khỏe tâm thần ở tuổi trưởng thành."},
                    {"en": "Therapy helps people process trauma and move forward.", "vi": "Liệu pháp tâm lý giúp mọi người xử lý chấn thương và tiến về phía trước."}]},
      {"word": "resilience", "meaning": "khả năng phục hồi tâm lý", "emoji": "🌱", "class": "n",
       "examples": [{"en": "Resilience allows people to recover from setbacks.", "vi": "Khả năng phục hồi giúp con người vượt qua thất bại."},
                    {"en": "Building resilience in children prepares them for life's challenges.", "vi": "Xây dựng khả năng phục hồi cho trẻ em chuẩn bị cho chúng đối mặt với thử thách cuộc sống."}]},
      {"word": "motivation", "meaning": "động lực", "emoji": "🔥", "class": "n",
       "examples": [{"en": "Intrinsic motivation leads to deeper learning than rewards.", "vi": "Động lực nội tại dẫn đến học tập sâu hơn so với phần thưởng."},
                    {"en": "Lack of motivation can result in poor performance.", "vi": "Thiếu động lực có thể dẫn đến kết quả kém."}]},
      {"word": "subconscious", "meaning": "tiềm thức", "emoji": "🌙", "class": "n",
       "examples": [{"en": "Our subconscious influences many of our decisions.", "vi": "Tiềm thức của chúng ta ảnh hưởng đến nhiều quyết định của chúng ta."},
                    {"en": "Freud believed that subconscious desires drive human behavior.", "vi": "Freud tin rằng những ham muốn tiềm thức thúc đẩy hành vi con người."}]},
      {"word": "identity", "meaning": "bản sắc, danh tính", "emoji": "🪞", "class": "n",
       "examples": [{"en": "Teenagers often struggle with questions of identity.", "vi": "Thanh thiếu niên thường vật lộn với các câu hỏi về bản sắc."},
                    {"en": "Cultural identity is shaped by language, traditions, and shared history.", "vi": "Bản sắc văn hóa được định hình bởi ngôn ngữ, truyền thống và lịch sử chung."}]},
      {"word": "stereotype", "meaning": "định kiến, khuôn mẫu", "emoji": "🏷️", "class": "n",
       "examples": [{"en": "Stereotypes can lead to unfair judgments about people.", "vi": "Định kiến có thể dẫn đến những phán xét không công bằng về con người."},
                    {"en": "We should challenge stereotypes rather than accept them.", "vi": "Chúng ta nên thách thức định kiến thay vì chấp nhận chúng."}]},
      {"word": "empathy", "meaning": "sự đồng cảm", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Empathy allows us to understand other people's feelings.", "vi": "Sự đồng cảm cho phép chúng ta hiểu cảm xúc của người khác."},
                    {"en": "Teachers with empathy build stronger connections with students.", "vi": "Giáo viên có sự đồng cảm xây dựng mối kết nối sâu sắc hơn với học sinh."}]},
      {"word": "anxiety", "meaning": "lo âu", "emoji": "😰", "class": "n",
       "examples": [{"en": "Exam anxiety affects many students' performance.", "vi": "Lo âu thi cử ảnh hưởng đến hiệu suất của nhiều học sinh."},
                    {"en": "Regular exercise is known to reduce anxiety.", "vi": "Tập thể dục thường xuyên được biết đến là giúp giảm lo âu."}]},
      {"word": "disorder", "meaning": "rối loạn tâm lý", "emoji": "🌀", "class": "n",
       "examples": [{"en": "Anxiety disorders are among the most common mental health conditions.", "vi": "Rối loạn lo âu là một trong những vấn đề sức khỏe tâm thần phổ biến nhất."},
                    {"en": "Early treatment can help manage most psychological disorders.", "vi": "Điều trị sớm có thể giúp kiểm soát hầu hết các rối loạn tâm lý."}]},
      {"word": "therapy", "meaning": "liệu pháp tâm lý", "emoji": "🛋️", "class": "n",
       "examples": [{"en": "Cognitive behavioral therapy is effective for treating depression.", "vi": "Liệu pháp nhận thức hành vi có hiệu quả trong điều trị trầm cảm."},
                    {"en": "Many people find therapy helpful during difficult times.", "vi": "Nhiều người thấy liệu pháp tâm lý hữu ích trong những giai đoạn khó khăn."}]},
      {"word": "behavior", "meaning": "hành vi", "emoji": "🎭", "class": "n",
       "examples": [{"en": "Human behavior is influenced by both genetics and environment.", "vi": "Hành vi con người bị ảnh hưởng bởi cả di truyền và môi trường."},
                    {"en": "The psychologist studied the behavior of children in groups.", "vi": "Nhà tâm lý học nghiên cứu hành vi của trẻ em trong các nhóm."}]},
    ]
  },
  {
    "id": "politics-society",
    "name": "Chính Trị & Xã Hội",
    "emoji": "🏛️",
    "color": "blue",
    "words": [
      {"word": "democracy", "meaning": "dân chủ", "emoji": "🗳️", "class": "n",
       "examples": [{"en": "Democracy gives citizens the right to vote for their leaders.", "vi": "Dân chủ cho công dân quyền bầu chọn lãnh đạo của họ."},
                    {"en": "A functioning democracy requires a free press.", "vi": "Một nền dân chủ hoạt động tốt đòi hỏi có báo chí tự do."}]},
      {"word": "constitution", "meaning": "hiến pháp", "emoji": "📜", "class": "n",
       "examples": [{"en": "The constitution protects the fundamental rights of citizens.", "vi": "Hiến pháp bảo vệ các quyền cơ bản của công dân."},
                    {"en": "Any new law must be consistent with the constitution.", "vi": "Bất kỳ luật mới nào cũng phải phù hợp với hiến pháp."}]},
      {"word": "parliament", "meaning": "nghị viện", "emoji": "🏟️", "class": "n",
       "examples": [{"en": "Parliament voted to approve the new budget.", "vi": "Nghị viện đã bỏ phiếu thông qua ngân sách mới."},
                    {"en": "Members of parliament debate laws before they are passed.", "vi": "Các nghị sĩ tranh luận về luật trước khi được thông qua."}]},
      {"word": "ideology", "meaning": "hệ tư tưởng", "emoji": "💡", "class": "n",
       "examples": [{"en": "Political parties are often defined by their ideology.", "vi": "Các đảng chính trị thường được xác định bởi hệ tư tưởng của họ."},
                    {"en": "The two candidates had very different ideologies.", "vi": "Hai ứng cử viên có hệ tư tưởng rất khác nhau."}]},
      {"word": "referendum", "meaning": "trưng cầu dân ý", "emoji": "🗳️", "class": "n",
       "examples": [{"en": "The government held a referendum on EU membership.", "vi": "Chính phủ tổ chức trưng cầu dân ý về tư cách thành viên EU."},
                    {"en": "A majority voted yes in the referendum.", "vi": "Đa số bỏ phiếu đồng ý trong cuộc trưng cầu dân ý."}]},
      {"word": "coalition", "meaning": "liên minh chính trị", "emoji": "🤝", "class": "n",
       "examples": [{"en": "No party won a majority, so they formed a coalition government.", "vi": "Không đảng nào giành đa số nên họ thành lập chính phủ liên minh."},
                    {"en": "The coalition of smaller parties was able to block the legislation.", "vi": "Liên minh các đảng nhỏ hơn có thể chặn dự luật."}]},
      {"word": "sovereignty", "meaning": "chủ quyền", "emoji": "🌐", "class": "n",
       "examples": [{"en": "National sovereignty means a country controls its own affairs.", "vi": "Chủ quyền quốc gia có nghĩa là một quốc gia kiểm soát công việc của chính mình."},
                    {"en": "The treaty was seen as a threat to the country's sovereignty.", "vi": "Hiệp ước bị coi là mối đe dọa đối với chủ quyền quốc gia."}]},
      {"word": "campaign", "meaning": "chiến dịch chính trị", "emoji": "📣", "class": "n",
       "examples": [{"en": "She ran a successful election campaign on education reform.", "vi": "Cô ấy thực hiện một chiến dịch bầu cử thành công về cải cách giáo dục."},
                    {"en": "The campaign raised millions of dollars in donations.", "vi": "Chiến dịch quyên được hàng triệu đô la."}]},
      {"word": "sanction", "meaning": "lệnh trừng phạt", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Economic sanctions were imposed on the country after the conflict.", "vi": "Lệnh trừng phạt kinh tế được áp đặt lên quốc gia sau xung đột."},
                    {"en": "The UN voted to apply sanctions to pressure the regime.", "vi": "Liên Hợp Quốc bỏ phiếu áp dụng lệnh trừng phạt để gây sức ép lên chế độ."}]},
      {"word": "treaty", "meaning": "hiệp ước", "emoji": "🖊️", "class": "n",
       "examples": [{"en": "The two countries signed a peace treaty after the war.", "vi": "Hai nước đã ký kết một hiệp ước hòa bình sau cuộc chiến."},
                    {"en": "The climate treaty obligated countries to cut emissions.", "vi": "Hiệp ước khí hậu buộc các quốc gia cắt giảm khí thải."}]},
      {"word": "policy", "meaning": "chính sách", "emoji": "📄", "class": "n",
       "examples": [{"en": "The new policy requires all students to wear uniforms.", "vi": "Chính sách mới yêu cầu tất cả học sinh mặc đồng phục."},
                    {"en": "Foreign policy decisions affect international relations.", "vi": "Các quyết định chính sách đối ngoại ảnh hưởng đến quan hệ quốc tế."}]},
      {"word": "reform", "meaning": "cải cách", "emoji": "🔄", "class": "n",
       "examples": [{"en": "Economic reform was needed to modernize the country.", "vi": "Cải cách kinh tế là cần thiết để hiện đại hóa đất nước."},
                    {"en": "The education reform aimed to improve learning outcomes.", "vi": "Cải cách giáo dục nhằm mục tiêu cải thiện kết quả học tập."}]},
      {"word": "authority", "meaning": "chính quyền, thẩm quyền", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "The local authority is responsible for maintaining roads.", "vi": "Chính quyền địa phương chịu trách nhiệm bảo trì đường bộ."},
                    {"en": "Authorities arrested the suspects the following morning.", "vi": "Nhà chức trách đã bắt giữ các nghi phạm vào sáng hôm sau."}]},
    ]
  },
  {
    "id": "science-research",
    "name": "Khoa Học & Nghiên Cứu",
    "emoji": "🔬",
    "color": "cyan",
    "words": [
      {"word": "variable", "meaning": "biến số", "emoji": "📊", "class": "n",
       "examples": [{"en": "In this experiment, temperature is the independent variable.", "vi": "Trong thí nghiệm này, nhiệt độ là biến số độc lập."},
                    {"en": "Researchers control variables to ensure accurate results.", "vi": "Các nhà nghiên cứu kiểm soát các biến số để đảm bảo kết quả chính xác."}]},
      {"word": "correlation", "meaning": "mối tương quan", "emoji": "📈", "class": "n",
       "examples": [{"en": "There is a strong correlation between exercise and mental health.", "vi": "Có mối tương quan mạnh mẽ giữa tập thể dục và sức khỏe tâm thần."},
                    {"en": "Correlation does not always mean causation.", "vi": "Tương quan không phải lúc nào cũng có nghĩa là nhân quả."}]},
      {"word": "replicate", "meaning": "lặp lại (thí nghiệm)", "emoji": "🔁", "class": "v",
       "examples": [{"en": "Scientists tried to replicate the experiment in different conditions.", "vi": "Các nhà khoa học cố gắng lặp lại thí nghiệm trong các điều kiện khác nhau."},
                    {"en": "A finding is stronger when it can be replicated by others.", "vi": "Một phát hiện mạnh hơn khi nó có thể được lặp lại bởi người khác."}]},
      {"word": "finding", "meaning": "phát hiện nghiên cứu", "emoji": "💡", "class": "n",
       "examples": [{"en": "The findings of the study were published in a leading journal.", "vi": "Các phát hiện của nghiên cứu được công bố trên một tạp chí hàng đầu."},
                    {"en": "The findings suggest a link between diet and cancer risk.", "vi": "Các phát hiện gợi ý mối liên hệ giữa chế độ ăn và nguy cơ ung thư."}]},
      {"word": "sample", "meaning": "mẫu nghiên cứu", "emoji": "🧪", "class": "n",
       "examples": [{"en": "The study used a sample of 500 university students.", "vi": "Nghiên cứu sử dụng mẫu gồm 500 sinh viên đại học."},
                    {"en": "A larger sample size leads to more reliable results.", "vi": "Kích thước mẫu lớn hơn dẫn đến kết quả đáng tin cậy hơn."}]},
      {"word": "molecule", "meaning": "phân tử", "emoji": "⚛️", "class": "n",
       "examples": [{"en": "Water is made up of two hydrogen atoms and one oxygen molecule.", "vi": "Nước được tạo thành từ hai nguyên tử hydro và một phân tử oxy."},
                    {"en": "Scientists studied the molecule's structure under a microscope.", "vi": "Các nhà khoa học nghiên cứu cấu trúc phân tử dưới kính hiển vi."}]},
      {"word": "genome", "meaning": "bộ gen", "emoji": "🧬", "class": "n",
       "examples": [{"en": "The human genome contains over 20,000 genes.", "vi": "Bộ gen người chứa hơn 20.000 gen."},
                    {"en": "Mapping the genome has revolutionized medicine.", "vi": "Lập bản đồ bộ gen đã tạo ra cuộc cách mạng trong y học."}]},
      {"word": "clinical", "meaning": "lâm sàng", "emoji": "🏥", "class": "adj",
       "examples": [{"en": "The drug was tested in clinical trials before approval.", "vi": "Thuốc được thử nghiệm trong các thử nghiệm lâm sàng trước khi được phê duyệt."},
                    {"en": "Clinical research involves studying patients directly.", "vi": "Nghiên cứu lâm sàng liên quan đến việc nghiên cứu bệnh nhân trực tiếp."}]},
      {"word": "theory", "meaning": "lý thuyết (khoa học)", "emoji": "💭", "class": "n",
       "examples": [{"en": "Darwin's theory of evolution changed how we understand life.", "vi": "Lý thuyết tiến hóa của Darwin đã thay đổi cách chúng ta hiểu về sự sống."},
                    {"en": "A scientific theory must be testable and supported by evidence.", "vi": "Một lý thuyết khoa học phải có thể kiểm chứng và được hỗ trợ bởi bằng chứng."}]},
      {"word": "significant", "meaning": "có ý nghĩa thống kê", "emoji": "⭐", "class": "adj",
       "examples": [{"en": "The difference between the two groups was statistically significant.", "vi": "Sự khác biệt giữa hai nhóm có ý nghĩa thống kê."},
                    {"en": "The researchers found a significant improvement in the treatment group.", "vi": "Các nhà nghiên cứu tìm thấy sự cải thiện đáng kể trong nhóm được điều trị."}]},
      {"word": "conclusion", "meaning": "kết luận", "emoji": "✅", "class": "n",
       "examples": [{"en": "The conclusion of the study supported the original hypothesis.", "vi": "Kết luận của nghiên cứu ủng hộ giả thuyết ban đầu."},
                    {"en": "You must not jump to conclusions without enough evidence.", "vi": "Bạn không được vội vàng kết luận khi chưa có đủ bằng chứng."}]},
      {"word": "ethics", "meaning": "đạo đức nghiên cứu", "emoji": "🌿", "class": "n",
       "examples": [{"en": "All research involving humans must follow strict ethics guidelines.", "vi": "Tất cả các nghiên cứu liên quan đến con người phải tuân theo hướng dẫn đạo đức nghiêm ngặt."},
                    {"en": "The ethics committee approved the study design.", "vi": "Ủy ban đạo đức đã phê duyệt thiết kế nghiên cứu."}]},
      {"word": "data", "meaning": "dữ liệu", "emoji": "💾", "class": "n",
       "examples": [{"en": "The data collected over five years showed a clear pattern.", "vi": "Dữ liệu thu thập trong năm năm cho thấy một mô hình rõ ràng."},
                    {"en": "Raw data must be analyzed before any conclusions can be drawn.", "vi": "Dữ liệu thô phải được phân tích trước khi có thể rút ra kết luận."}]},
    ]
  },
  {
    "id": "environment-policy",
    "name": "Chính Sách Môi Trường",
    "emoji": "🌍",
    "color": "green",
    "words": [
      {"word": "emission", "meaning": "khí thải", "emoji": "🏭", "class": "n",
       "examples": [{"en": "Carbon emissions from cars contribute to global warming.", "vi": "Khí thải carbon từ xe hơi góp phần vào sự nóng lên toàn cầu."},
                    {"en": "Countries pledged to reduce their emissions by 2030.", "vi": "Các quốc gia cam kết giảm khí thải vào năm 2030."}]},
      {"word": "renewable", "meaning": "tái tạo được", "emoji": "♻️", "class": "adj",
       "examples": [{"en": "Solar and wind are renewable sources of energy.", "vi": "Năng lượng mặt trời và gió là các nguồn năng lượng tái tạo."},
                    {"en": "Investing in renewable energy reduces dependence on fossil fuels.", "vi": "Đầu tư vào năng lượng tái tạo giảm sự phụ thuộc vào nhiên liệu hóa thạch."}]},
      {"word": "sustainable", "meaning": "bền vững", "emoji": "🌿", "class": "adj",
       "examples": [{"en": "Sustainable farming protects the land for future generations.", "vi": "Nông nghiệp bền vững bảo vệ đất cho các thế hệ tương lai."},
                    {"en": "We need sustainable solutions to the plastic waste problem.", "vi": "Chúng ta cần các giải pháp bền vững cho vấn đề rác thải nhựa."}]},
      {"word": "biodiversity", "meaning": "đa dạng sinh học", "emoji": "🦋", "class": "n",
       "examples": [{"en": "Deforestation threatens biodiversity in tropical rainforests.", "vi": "Nạn phá rừng đe dọa đa dạng sinh học trong rừng nhiệt đới."},
                    {"en": "Protecting biodiversity is essential for healthy ecosystems.", "vi": "Bảo vệ đa dạng sinh học là điều cần thiết cho các hệ sinh thái lành mạnh."}]},
      {"word": "conservation", "meaning": "bảo tồn", "emoji": "🐾", "class": "n",
       "examples": [{"en": "Wildlife conservation efforts have saved many species from extinction.", "vi": "Các nỗ lực bảo tồn động vật hoang dã đã cứu nhiều loài khỏi tuyệt chủng."},
                    {"en": "Conservation of water resources is vital in dry regions.", "vi": "Bảo tồn tài nguyên nước rất quan trọng ở các vùng khô hạn."}]},
      {"word": "regulation", "meaning": "quy định, điều tiết", "emoji": "📋", "class": "n",
       "examples": [{"en": "Stricter environmental regulations could reduce industrial pollution.", "vi": "Các quy định môi trường nghiêm ngặt hơn có thể giảm ô nhiễm công nghiệp."},
                    {"en": "Businesses must comply with government regulations.", "vi": "Doanh nghiệp phải tuân thủ các quy định của chính phủ."}]},
      {"word": "contamination", "meaning": "ô nhiễm, nhiễm độc", "emoji": "☣️", "class": "n",
       "examples": [{"en": "Contamination of the river made the water unsafe to drink.", "vi": "Ô nhiễm sông khiến nước không an toàn để uống."},
                    {"en": "Soil contamination from chemicals is difficult to clean up.", "vi": "Nhiễm độc đất từ hóa chất rất khó để làm sạch."}]},
      {"word": "carbon footprint", "meaning": "dấu chân carbon", "emoji": "👣", "class": "n",
       "examples": [{"en": "Flying frequently increases your carbon footprint significantly.", "vi": "Bay thường xuyên làm tăng dấu chân carbon của bạn đáng kể."},
                    {"en": "Many companies are trying to reduce their carbon footprint.", "vi": "Nhiều công ty đang cố gắng giảm dấu chân carbon của họ."}]},
      {"word": "landfill", "meaning": "bãi chôn lấp rác", "emoji": "🗑️", "class": "n",
       "examples": [{"en": "Millions of tonnes of waste end up in landfills each year.", "vi": "Hàng triệu tấn rác kết thúc ở các bãi chôn lấp mỗi năm."},
                    {"en": "Recycling reduces the amount of waste sent to landfills.", "vi": "Tái chế giảm lượng rác được gửi đến bãi chôn lấp."}]},
      {"word": "initiative", "meaning": "sáng kiến", "emoji": "🚀", "class": "n",
       "examples": [{"en": "The government launched a new initiative to plant one million trees.", "vi": "Chính phủ khởi động sáng kiến mới để trồng một triệu cây."},
                    {"en": "A community initiative cleaned up the local beach.", "vi": "Một sáng kiến cộng đồng đã dọn sạch bãi biển địa phương."}]},
      {"word": "protocol", "meaning": "nghị định thư", "emoji": "📑", "class": "n",
       "examples": [{"en": "The Kyoto Protocol set binding targets for greenhouse gas emissions.", "vi": "Nghị định thư Kyoto đặt ra các mục tiêu ràng buộc về khí thải nhà kính."},
                    {"en": "Countries that signed the protocol must follow its rules.", "vi": "Các quốc gia đã ký nghị định thư phải tuân theo các quy tắc của nó."}]},
      {"word": "pledge", "meaning": "cam kết", "emoji": "🤝", "class": "n",
       "examples": [{"en": "World leaders made a pledge to reach net-zero emissions by 2050.", "vi": "Các nhà lãnh đạo thế giới cam kết đạt phát thải ròng bằng không vào năm 2050."},
                    {"en": "The company fulfilled its pledge to become carbon neutral.", "vi": "Công ty đã thực hiện cam kết trở thành trung hòa carbon."}]},
      {"word": "offshore", "meaning": "ngoài khơi", "emoji": "🌊", "class": "adj",
       "examples": [{"en": "Offshore wind farms generate clean electricity far from shore.", "vi": "Các trang trại gió ngoài khơi tạo ra điện sạch xa bờ biển."},
                    {"en": "Offshore drilling for oil can risk marine pollution.", "vi": "Khoan dầu ngoài khơi có thể gây rủi ro ô nhiễm biển."}]},
    ]
  },
  {
    "id": "health-medicine",
    "name": "Y Tế & Sức Khỏe",
    "emoji": "🏥",
    "color": "rose",
    "words": [
      {"word": "diagnosis", "meaning": "chẩn đoán", "emoji": "🩺", "class": "n",
       "examples": [{"en": "An early diagnosis gives patients a better chance of recovery.", "vi": "Chẩn đoán sớm cho bệnh nhân cơ hội hồi phục tốt hơn."},
                    {"en": "The diagnosis confirmed that she had type 2 diabetes.", "vi": "Chẩn đoán xác nhận cô ấy mắc bệnh tiểu đường loại 2."}]},
      {"word": "symptom", "meaning": "triệu chứng", "emoji": "🤒", "class": "n",
       "examples": [{"en": "Fever and fatigue are common symptoms of the flu.", "vi": "Sốt và mệt mỏi là các triệu chứng phổ biến của cúm."},
                    {"en": "Report any unusual symptoms to your doctor immediately.", "vi": "Báo cáo bất kỳ triệu chứng bất thường nào cho bác sĩ ngay lập tức."}]},
      {"word": "vaccination", "meaning": "tiêm chủng", "emoji": "💉", "class": "n",
       "examples": [{"en": "Childhood vaccination has almost eliminated many deadly diseases.", "vi": "Tiêm chủng trẻ em đã gần như loại bỏ nhiều bệnh nguy hiểm."},
                    {"en": "The vaccination program protected millions of people.", "vi": "Chương trình tiêm chủng đã bảo vệ hàng triệu người."}]},
      {"word": "chronic", "meaning": "mãn tính", "emoji": "🔄", "class": "adj",
       "examples": [{"en": "Chronic back pain affects millions of people worldwide.", "vi": "Đau lưng mãn tính ảnh hưởng đến hàng triệu người trên toàn thế giới."},
                    {"en": "A chronic illness requires long-term management.", "vi": "Bệnh mãn tính đòi hỏi quản lý lâu dài."}]},
      {"word": "surgery", "meaning": "phẫu thuật", "emoji": "🔪", "class": "n",
       "examples": [{"en": "The patient underwent surgery to remove the tumor.", "vi": "Bệnh nhân đã trải qua phẫu thuật để loại bỏ khối u."},
                    {"en": "Surgery was the only option to repair the damaged joint.", "vi": "Phẫu thuật là lựa chọn duy nhất để phục hồi khớp bị tổn thương."}]},
      {"word": "immune", "meaning": "miễn dịch", "emoji": "🛡️", "class": "adj",
       "examples": [{"en": "After recovery, some people become immune to the disease.", "vi": "Sau khi hồi phục, một số người trở nên miễn dịch với bệnh."},
                    {"en": "A healthy diet helps keep the immune system strong.", "vi": "Chế độ ăn uống lành mạnh giúp giữ cho hệ miễn dịch khỏe mạnh."}]},
      {"word": "pandemic", "meaning": "đại dịch", "emoji": "🦠", "class": "n",
       "examples": [{"en": "The COVID-19 pandemic affected people in every country.", "vi": "Đại dịch COVID-19 ảnh hưởng đến người dân ở mọi quốc gia."},
                    {"en": "Pandemic preparedness requires global cooperation.", "vi": "Sự chuẩn bị ứng phó đại dịch đòi hỏi hợp tác toàn cầu."}]},
      {"word": "prescription", "meaning": "đơn thuốc", "emoji": "💊", "class": "n",
       "examples": [{"en": "The doctor wrote a prescription for antibiotics.", "vi": "Bác sĩ viết đơn thuốc kháng sinh."},
                    {"en": "Some medications require a prescription from a licensed doctor.", "vi": "Một số loại thuốc cần có đơn của bác sĩ có giấy phép."}]},
      {"word": "treatment", "meaning": "điều trị", "emoji": "🩹", "class": "n",
       "examples": [{"en": "The new treatment proved effective for most patients.", "vi": "Phương pháp điều trị mới đã chứng minh hiệu quả đối với hầu hết bệnh nhân."},
                    {"en": "Early treatment significantly improves cancer survival rates.", "vi": "Điều trị sớm cải thiện đáng kể tỷ lệ sống sót của bệnh ung thư."}]},
      {"word": "prevention", "meaning": "phòng ngừa", "emoji": "🚧", "class": "n",
       "examples": [{"en": "Prevention is better than cure when it comes to disease.", "vi": "Phòng ngừa tốt hơn chữa bệnh khi nói đến dịch bệnh."},
                    {"en": "Public health campaigns focus on disease prevention.", "vi": "Các chiến dịch y tế công cộng tập trung vào phòng ngừa bệnh."}]},
      {"word": "mortality", "meaning": "tỷ lệ tử vong", "emoji": "📉", "class": "n",
       "examples": [{"en": "Child mortality rates have dropped dramatically over the past century.", "vi": "Tỷ lệ tử vong ở trẻ em đã giảm mạnh trong thế kỷ qua."},
                    {"en": "The mortality rate from this disease is very low with proper treatment.", "vi": "Tỷ lệ tử vong từ căn bệnh này rất thấp với điều trị đúng cách."}]},
      {"word": "specialist", "meaning": "bác sĩ chuyên khoa", "emoji": "👨‍⚕️", "class": "n",
       "examples": [{"en": "The patient was referred to a specialist for further tests.", "vi": "Bệnh nhân được chuyển đến bác sĩ chuyên khoa để làm thêm xét nghiệm."},
                    {"en": "A heart specialist recommended surgery as the best option.", "vi": "Bác sĩ chuyên khoa tim khuyến nghị phẫu thuật là lựa chọn tốt nhất."}]},
      {"word": "pharmaceutical", "meaning": "dược phẩm", "emoji": "🏭", "class": "adj",
       "examples": [{"en": "The pharmaceutical industry invests heavily in drug research.", "vi": "Ngành dược phẩm đầu tư nhiều vào nghiên cứu thuốc."},
                    {"en": "New pharmaceutical treatments are tested for years before approval.", "vi": "Các phương pháp điều trị dược phẩm mới được kiểm tra trong nhiều năm trước khi được phê duyệt."}]},
    ]
  },
  {
    "id": "technology-future",
    "name": "Công Nghệ Tương Lai",
    "emoji": "🤖",
    "color": "sky",
    "words": [
      {"word": "artificial intelligence", "meaning": "trí tuệ nhân tạo", "emoji": "🤖", "class": "n",
       "examples": [{"en": "Artificial intelligence is transforming industries from healthcare to finance.", "vi": "Trí tuệ nhân tạo đang biến đổi các ngành từ y tế đến tài chính."},
                    {"en": "AI systems can now beat humans at complex games like chess.", "vi": "Các hệ thống AI hiện có thể đánh bại con người trong các trò chơi phức tạp như cờ vua."}]},
      {"word": "algorithm", "meaning": "thuật toán", "emoji": "🔢", "class": "n",
       "examples": [{"en": "The algorithm recommends videos based on your watch history.", "vi": "Thuật toán đề xuất video dựa trên lịch sử xem của bạn."},
                    {"en": "Programmers write algorithms to solve specific problems.", "vi": "Lập trình viên viết các thuật toán để giải quyết các vấn đề cụ thể."}]},
      {"word": "automation", "meaning": "tự động hóa", "emoji": "⚙️", "class": "n",
       "examples": [{"en": "Automation in factories has replaced many manual jobs.", "vi": "Tự động hóa trong nhà máy đã thay thế nhiều công việc thủ công."},
                    {"en": "Business automation saves time and reduces human error.", "vi": "Tự động hóa kinh doanh tiết kiệm thời gian và giảm lỗi của con người."}]},
      {"word": "cybersecurity", "meaning": "an ninh mạng", "emoji": "🔐", "class": "n",
       "examples": [{"en": "Cybersecurity threats are growing as more systems go online.", "vi": "Các mối đe dọa an ninh mạng ngày càng tăng khi nhiều hệ thống kết nối trực tuyến."},
                    {"en": "Companies invest heavily in cybersecurity to protect their data.", "vi": "Các công ty đầu tư nhiều vào an ninh mạng để bảo vệ dữ liệu của họ."}]},
      {"word": "virtual reality", "meaning": "thực tế ảo", "emoji": "🥽", "class": "n",
       "examples": [{"en": "Virtual reality is used in training surgeons and pilots.", "vi": "Thực tế ảo được sử dụng trong đào tạo bác sĩ phẫu thuật và phi công."},
                    {"en": "VR headsets allow users to explore immersive digital environments.", "vi": "Kính thực tế ảo cho phép người dùng khám phá các môi trường kỹ thuật số đắm chìm."}]},
      {"word": "blockchain", "meaning": "chuỗi khối", "emoji": "🔗", "class": "n",
       "examples": [{"en": "Blockchain technology makes transactions secure and transparent.", "vi": "Công nghệ chuỗi khối làm cho các giao dịch an toàn và minh bạch."},
                    {"en": "Cryptocurrencies like Bitcoin are built on blockchain.", "vi": "Các loại tiền điện tử như Bitcoin được xây dựng trên chuỗi khối."}]},
      {"word": "encrypt", "meaning": "mã hóa", "emoji": "🔒", "class": "v",
       "examples": [{"en": "Messages are encrypted to prevent unauthorized access.", "vi": "Tin nhắn được mã hóa để ngăn chặn truy cập trái phép."},
                    {"en": "The app encrypts all user data stored on the server.", "vi": "Ứng dụng mã hóa tất cả dữ liệu người dùng được lưu trữ trên máy chủ."}]},
      {"word": "interface", "meaning": "giao diện", "emoji": "🖥️", "class": "n",
       "examples": [{"en": "A user-friendly interface makes the app easy to navigate.", "vi": "Giao diện thân thiện với người dùng giúp ứng dụng dễ điều hướng."},
                    {"en": "The new interface was designed with accessibility in mind.", "vi": "Giao diện mới được thiết kế với khả năng tiếp cận trong tâm trí."}]},
      {"word": "obsolete", "meaning": "lỗi thời", "emoji": "📟", "class": "adj",
       "examples": [{"en": "Fax machines have become largely obsolete in the digital age.", "vi": "Máy fax đã trở nên lỗi thời trong thời đại kỹ thuật số."},
                    {"en": "Technology that seemed cutting-edge ten years ago is now obsolete.", "vi": "Công nghệ có vẻ tiên tiến mười năm trước giờ đã lỗi thời."}]},
      {"word": "prototype", "meaning": "nguyên mẫu", "emoji": "🔧", "class": "n",
       "examples": [{"en": "Engineers built a prototype of the new electric vehicle.", "vi": "Các kỹ sư đã chế tạo nguyên mẫu của xe điện mới."},
                    {"en": "The prototype was tested extensively before mass production.", "vi": "Nguyên mẫu được kiểm tra kỹ lưỡng trước khi sản xuất hàng loạt."}]},
      {"word": "integrate", "meaning": "tích hợp", "emoji": "🔌", "class": "v",
       "examples": [{"en": "The new software integrates with all existing systems.", "vi": "Phần mềm mới tích hợp với tất cả các hệ thống hiện có."},
                    {"en": "Schools are trying to integrate technology into daily learning.", "vi": "Các trường học đang cố gắng tích hợp công nghệ vào việc học hàng ngày."}]},
      {"word": "innovation", "meaning": "đổi mới sáng tạo", "emoji": "💡", "class": "n",
       "examples": [{"en": "Innovation drives economic growth and creates new industries.", "vi": "Đổi mới sáng tạo thúc đẩy tăng trưởng kinh tế và tạo ra các ngành công nghiệp mới."},
                    {"en": "Silicon Valley is known as a global hub for innovation.", "vi": "Silicon Valley được biết đến là trung tâm đổi mới sáng tạo toàn cầu."}]},
      {"word": "bandwidth", "meaning": "băng thông mạng", "emoji": "📶", "class": "n",
       "examples": [{"en": "Streaming high-definition videos requires a lot of bandwidth.", "vi": "Phát video độ phân giải cao đòi hỏi nhiều băng thông."},
                    {"en": "Slow internet speeds are often caused by limited bandwidth.", "vi": "Tốc độ internet chậm thường do băng thông hạn chế."}]},
    ]
  },
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'words.json')
with open(data_path) as f:
    data = json.load(f)

data['scholar'] = {'topics': topics_1_10}

with open(data_path, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done: {len(topics_1_10)} topics inserted")
for t in topics_1_10:
    print(f"  {t['id']}: {len(t['words'])} words")
