# -*- coding: utf-8 -*-
"""Adds 22 stories for the 22 new Master C1 topics."""
import json, os

NEW_MASTER_STORIES = {
  "master.constitutional-law": {
    "emojis": ["🏛️", "📜", "⚖️"],
    "en": "A **constitution** defines the fundamental structure of a state and the **fundamental rights** of its citizens. The **separation of powers** between the executive, **legislature**, and judiciary prevents any single branch from abusing authority. Courts use **judicial review** to strike down laws that violate the **rule of law** or exceed **jurisdiction**. When rights are threatened, citizens can invoke **due process** and the guarantee of **civil liberties**. Constitutional **amendments** allow societies to update their foundational documents while maintaining **democratic** values.",
    "vi": "**Hiến pháp** xác định cấu trúc cơ bản của nhà nước và các **quyền cơ bản** của công dân. **Phân chia quyền lực** giữa hành pháp, **cơ quan lập pháp** và tư pháp ngăn bất kỳ nhánh nào lạm dụng quyền lực. Tòa án sử dụng **kiểm tra tư pháp** để bác bỏ các luật vi phạm **nguyên tắc pháp quyền** hoặc vượt quá **thẩm quyền xét xử**. Khi quyền bị đe dọa, công dân có thể viện dẫn **thủ tục pháp lý đúng đắn** và sự đảm bảo **quyền tự do dân sự**. Các **tu chính án** hiến pháp cho phép xã hội cập nhật tài liệu nền tảng trong khi duy trì các giá trị **dân chủ**."
  },
  "master.environmental-governance": {
    "emojis": ["🌍", "♻️", "📜"],
    "en": "**Environmental governance** requires nations to **ratify** agreements and follow through with genuine **compliance**. A **carbon tax** creates economic incentives for businesses to reduce emissions and move toward **net-zero** targets. **Legislation** and **enforcement** mechanisms ensure that **mitigation** commitments translate into real action. The global **transition** to clean energy must protect **biodiversity** and communities dependent on fossil fuels. **Sustainability** goals demand both domestic **adaptation** and international **protocol** adherence, with **offsets** only as a last resort.",
    "vi": "**Quản trị môi trường** đòi hỏi các quốc gia **phê chuẩn** các thỏa thuận và thực hiện chúng với sự **tuân thủ** thực sự. **Thuế carbon** tạo ra các khuyến khích kinh tế cho doanh nghiệp giảm phát thải và hướng tới mục tiêu **phát thải ròng bằng không**. Các cơ chế **luật pháp** và **thực thi** đảm bảo rằng các cam kết **giảm nhẹ** được chuyển thành hành động thực tế. Sự **chuyển đổi** toàn cầu sang năng lượng sạch phải bảo vệ **đa dạng sinh học** và các cộng đồng phụ thuộc vào nhiên liệu hóa thạch. Các mục tiêu **bền vững** đòi hỏi cả **thích ứng** trong nước và tuân thủ **nghị định thư** quốc tế, với **bù đắp khí thải** chỉ là biện pháp cuối cùng."
  },
  "master.political-philosophy": {
    "emojis": ["⚖️", "🗳️", "💡"],
    "en": "**Political philosophy** asks fundamental questions about **power**, **legitimacy**, and the best form of **governance**. While **democracy** distributes power through elections and protects individual **rights**, **authoritarianism** concentrates control and suppresses **civil society**. The rise of **populism** often reflects frustration when citizens feel that **equality** and fair **reform** are being denied. Political **ideology** shapes how parties and governments frame social problems and propose solutions. **Pluralism** remains essential because no single viewpoint can fully account for the complexity of human **freedom**.",
    "vi": "**Triết học chính trị** đặt ra những câu hỏi cơ bản về **quyền lực**, **tính hợp pháp** và hình thức **quản trị** tốt nhất. Trong khi **dân chủ** phân phối quyền lực qua bầu cử và bảo vệ **quyền** cá nhân, **chủ nghĩa độc đoán** tập trung quyền kiểm soát và đàn áp **xã hội dân sự**. Sự trỗi dậy của **chủ nghĩa dân túy** thường phản ánh sự thất vọng khi công dân cảm thấy **bình đẳng** và **cải cách** công bằng đang bị từ chối. **Hệ tư tưởng** chính trị định hình cách các đảng và chính phủ đặt vấn đề xã hội và đề xuất giải pháp. **Chủ nghĩa đa nguyên** vẫn cần thiết vì không quan điểm nào có thể giải thích đầy đủ sự phức tạp của **tự do** con người."
  },
  "master.public-policy": {
    "emojis": ["📋", "🏛️", "🔬"],
    "en": "Effective **public policy** depends on **evidence-based** analysis and meaningful **stakeholder** engagement. **Governance** structures determine how decisions are made, from initial **legislation** through to **implementation**. Policies targeting **welfare** and **public service** delivery must be carefully designed to maximise positive **outcomes** for the most vulnerable. **Transparency** and **accountability** build public trust, while **regulation** prevents powerful interests from distorting the process. **Social policy** must also consider long-term consequences, not just immediate results, and ensure equitable **access** for all citizens.",
    "vi": "**Chính sách công** hiệu quả phụ thuộc vào phân tích **dựa trên bằng chứng** và sự tham gia có ý nghĩa của **các bên liên quan**. Cấu trúc **quản trị** xác định cách ra quyết định, từ **luật pháp** ban đầu đến **thực thi**. Các chính sách nhắm vào **phúc lợi** và cung cấp **dịch vụ công** phải được thiết kế cẩn thận để tối đa hóa **kết quả** tích cực cho những người dễ bị tổn thương nhất. **Minh bạch** và **trách nhiệm giải trình** xây dựng niềm tin của công chúng, trong khi **quy định** ngăn các lợi ích quyền lực làm méo mó quy trình. **Chính sách xã hội** cũng phải xem xét hậu quả lâu dài, không chỉ kết quả tức thời, và đảm bảo **tiếp cận** bình đẳng cho tất cả công dân."
  },
  "master.academic-discourse": {
    "emojis": ["📚", "🔬", "🎓"],
    "en": "Academic **discourse** is built on rigorous **analysis**, precise **citation**, and honest **peer review**. Every **thesis** must be grounded in a sound **methodology** and supported by verifiable **evidence**. Researchers are expected to apply **critical thinking** to challenge assumptions, even those central to their own discipline. **Academic integrity** means never committing **plagiarism** or misrepresenting data in a **publication**. Regular **seminars** and **collaboration** across institutions push the boundaries of knowledge and help scholars **evaluate** each other's contributions with greater depth.",
    "vi": "**Diễn ngôn** học thuật được xây dựng trên **phân tích** nghiêm ngặt, **trích dẫn** chính xác và **phản biện học thuật** trung thực. Mỗi **luận văn** phải được đặt nền tảng trên **phương pháp luận** vững chắc và được hỗ trợ bởi **bằng chứng** có thể kiểm chứng. Các nhà nghiên cứu được kỳ vọng áp dụng **tư duy phản biện** để thách thức các giả định, kể cả những giả định trung tâm của lĩnh vực của họ. **Trung thực học thuật** có nghĩa là không bao giờ thực hiện **đạo văn** hay xuyên tạc dữ liệu trong **ấn phẩm**. Các **hội thảo** thường xuyên và **hợp tác** giữa các cơ sở đẩy mạnh ranh giới kiến thức và giúp các học giả **đánh giá** đóng góp của nhau với chiều sâu hơn."
  },
  "master.geopolitics": {
    "emojis": ["🌐", "🤝", "⚡"],
    "en": "**Geopolitics** shapes the world order through the constant interplay of **sovereignty**, **diplomacy**, and competing national interests. When **negotiations** fail, countries may resort to imposing **sanctions** or forming a new **alliance** to shift the balance of **power**. **Multilateral** institutions provide forums for managing **tension** before it escalates into open **conflict**. **Nationalism** complicates cooperation because states often prioritise self-interest over collective **stability**. The challenge for global leaders is to build **cooperation** frameworks that respect sovereignty while addressing threats that no single nation can face alone.",
    "vi": "**Địa chính trị** định hình trật tự thế giới qua sự tương tác liên tục giữa **chủ quyền**, **ngoại giao** và các lợi ích quốc gia cạnh tranh. Khi **đàm phán** thất bại, các quốc gia có thể sử dụng việc áp đặt **lệnh trừng phạt** hoặc hình thành **liên minh** mới để thay đổi cán cân **quyền lực**. Các thể chế **đa phương** cung cấp diễn đàn để quản lý **căng thẳng** trước khi leo thang thành **xung đột** công khai. **Chủ nghĩa dân tộc** làm phức tạp hợp tác vì các quốc gia thường ưu tiên lợi ích riêng hơn **ổn định** tập thể. Thách thức cho các nhà lãnh đạo toàn cầu là xây dựng các khuôn khổ **hợp tác** tôn trọng chủ quyền trong khi giải quyết các mối đe dọa mà không quốc gia nào có thể đối phó một mình."
  },
  "master.macroeconomics": {
    "emojis": ["📈", "🏦", "💸"],
    "en": "During a **recession**, governments face difficult choices between **austerity** and stimulus spending. High **inflation** erodes purchasing power, prompting central banks to tighten **monetary policy** and raise interest rates. A rising **deficit** and growing **public debt** limit future **fiscal policy** options for managing the economy. **Market failure** in areas like healthcare and education justifies government intervention through **regulation** and **privatization** reform. Ultimately, addressing **unemployment** and **inequality** requires coordinated policies that promote sustainable **economic growth** rather than short-term gains.",
    "vi": "Trong thời kỳ **suy thoái kinh tế**, chính phủ đối mặt với những lựa chọn khó khăn giữa **thắt lưng buộc bụng** và chi tiêu kích thích. **Lạm phát** cao làm xói mòn sức mua, khiến các ngân hàng trung ương thắt chặt **chính sách tiền tệ** và tăng lãi suất. **Thâm hụt** tăng và **nợ công** ngày càng tăng hạn chế các lựa chọn **chính sách tài khóa** tương lai để quản lý nền kinh tế. **Thất bại thị trường** trong các lĩnh vực như y tế và giáo dục biện minh cho sự can thiệp của chính phủ qua **quy định** và cải cách **tư nhân hóa**. Cuối cùng, giải quyết **thất nghiệp** và **bất bình đẳng** đòi hỏi các chính sách phối hợp thúc đẩy **tăng trưởng kinh tế** bền vững hơn là lợi ích ngắn hạn."
  },
  "master.medical-ethics": {
    "emojis": ["🩺", "⚖️", "🧪"],
    "en": "**Medical ethics** rests on four core principles: **autonomy**, beneficence, non-maleficence, and justice. Patients must give **informed consent** before any procedure, and their **patient rights** must be upheld even in difficult circumstances. **Clinical trials** must pass scrutiny from an **ethics committee** and comply with strict **research ethics** guidelines to protect participants. Debates around **euthanasia** and **end-of-life** care reveal the tension between respecting individual wishes and broader moral obligations. **Organ donation**, **palliative care**, and **experimental** treatments all raise questions about **transparency** and fair **access** to scarce medical resources.",
    "vi": "**Đạo đức y khoa** dựa trên bốn nguyên tắc cốt lõi: **quyền tự quyết**, làm lợi, không gây hại và công bằng. Bệnh nhân phải có **đồng ý đầy đủ thông tin** trước bất kỳ thủ thuật nào, và **quyền của bệnh nhân** phải được bảo vệ ngay cả trong hoàn cảnh khó khăn. Các **thử nghiệm lâm sàng** phải được kiểm tra bởi **hội đồng đạo đức** và tuân thủ các hướng dẫn **đạo đức nghiên cứu** nghiêm ngặt để bảo vệ người tham gia. Các cuộc tranh luận xung quanh **an tử** và chăm sóc **cuối đời** cho thấy sự căng thẳng giữa tôn trọng ý nguyện cá nhân và các nghĩa vụ đạo đức rộng hơn. **Hiến tạng**, **chăm sóc giảm nhẹ** và các phương pháp điều trị **thử nghiệm** đều đặt ra câu hỏi về **minh bạch** và **tiếp cận** công bằng với nguồn lực y tế khan hiếm."
  },
  "master.sociology": {
    "emojis": ["👥", "📊", "🌈"],
    "en": "**Sociology** examines how **social class**, **inequality**, and **discrimination** shape people's life chances. **Social mobility** allows individuals to rise beyond their origins, but structural barriers often limit this in practice. Processes of **marginalization** and **exclusion** push vulnerable groups to the edges of economic and civic life, reinforcing **privilege** among the dominant. Dismantling harmful **stereotypes** requires changing both individual attitudes and the **institutions** that perpetuate them. Building **social capital** through trust, **diversity**, and **integration** is the foundation of a more equitable and cohesive society where **power** is more fairly distributed.",
    "vi": "**Xã hội học** xem xét cách **tầng lớp xã hội**, **bất bình đẳng** và **phân biệt đối xử** định hình cơ hội cuộc sống của mọi người. **Tính cơ động xã hội** cho phép cá nhân vươn lên trên nguồn gốc của họ, nhưng các rào cản cơ cấu thường hạn chế điều này trong thực tế. Các quá trình **ngoại lề hóa** và **loại trừ** đẩy các nhóm dễ bị tổn thương ra rìa của đời sống kinh tế và dân sự, củng cố **đặc quyền** trong số nhóm thống trị. Phá bỏ các **khuôn mẫu** có hại đòi hỏi thay đổi cả thái độ cá nhân và **thể chế** duy trì chúng. Xây dựng **vốn xã hội** qua sự tin tưởng, **đa dạng** và **hội nhập** là nền tảng của một xã hội công bằng và gắn kết hơn nơi **quyền lực** được phân phối công bằng hơn."
  },
  "master.business-ethics": {
    "emojis": ["💼", "🔍", "🌱"],
    "en": "Sustainable businesses are built on a culture of **integrity**, **transparency**, and genuine **compliance** with the law. **Corruption** and **bribery** distort competition and undermine public trust in markets and **governance**. An effective **audit** process and legal protections for **whistleblowers** help expose wrongdoing before it becomes systemic. Executives must manage **conflicts of interest** carefully to protect **stakeholder** confidence and uphold their **corporate responsibility** commitments. Ultimately, **accountability** for ethical failures must be real and enforceable, not merely symbolic.",
    "vi": "Các doanh nghiệp bền vững được xây dựng trên văn hóa **liêm chính**, **minh bạch** và **tuân thủ** pháp luật thực sự. **Tham nhũng** và **hối lộ** làm méo mó cạnh tranh và phá hoại niềm tin của công chúng vào thị trường và **quản trị**. Quy trình **kiểm toán** hiệu quả và bảo vệ pháp lý cho **người tố giác** giúp phơi bày hành vi sai trái trước khi nó trở thành hệ thống. Lãnh đạo phải quản lý **xung đột lợi ích** cẩn thận để bảo vệ niềm tin của **các bên liên quan** và duy trì các cam kết **trách nhiệm doanh nghiệp**. Cuối cùng, **trách nhiệm giải trình** đối với các thất bại đạo đức phải có thực và có thể thực thi, không chỉ mang tính biểu tượng."
  },
  "master.technology-ethics": {
    "emojis": ["💻", "🔒", "🤖"],
    "en": "As **AI** and **automation** reshape the economy, society must grapple with profound ethical questions about **rights** and **accountability**. **Algorithmic** bias embeds existing inequalities into systems that make consequential decisions about people's lives. Mass **surveillance** by states and corporations poses serious threats to **privacy** and civil liberties. **Digital equity** demands that the benefits of technological **disruption** and **innovation** are shared broadly rather than concentrated among the few. Governments must **regulate** powerful **platforms** to protect **data** and ensure that **technology** serves human values rather than undermining them.",
    "vi": "Khi **trí tuệ nhân tạo** và **tự động hóa** định hình lại nền kinh tế, xã hội phải đối mặt với những câu hỏi đạo đức sâu sắc về **quyền** và **trách nhiệm giải trình**. Thiên kiến **thuật toán** nhúng các bất bình đẳng hiện có vào các hệ thống đưa ra các quyết định quan trọng về cuộc sống con người. **Giám sát** hàng loạt bởi nhà nước và tập đoàn đặt ra các mối đe dọa nghiêm trọng với **quyền riêng tư** và tự do dân sự. **Bình đẳng kỹ thuật số** đòi hỏi lợi ích của sự **đổ vỡ** công nghệ và **đổi mới** được chia sẻ rộng rãi hơn là tập trung vào số ít. Chính phủ phải **quản lý** các **nền tảng** quyền lực để bảo vệ **dữ liệu** và đảm bảo **công nghệ** phục vụ các giá trị con người hơn là làm suy yếu chúng."
  },
  "master.media-literacy": {
    "emojis": ["📰", "🔍", "📢"],
    "en": "In the digital age, **media literacy** has become an essential civic skill for navigating **misinformation** and propaganda. Recognising **bias** and understanding **framing** helps readers assess whether coverage achieves genuine **objectivity**. The spread of **sensationalism** and **propaganda** through social media **echo chambers** deepens political polarisation. Independent organisations that **fact-check** claims and scrutinise **narrative** construction play a vital democratic role. Media **credibility** depends on transparent sourcing, fair **representation**, and a willingness to correct errors, but **censorship** is never an acceptable solution and threatens freedom of **influence** and expression.",
    "vi": "Trong thời đại kỹ thuật số, **năng lực truyền thông** đã trở thành kỹ năng công dân thiết yếu để điều hướng **thông tin sai lệch** và tuyên truyền. Nhận ra **thành kiến** và hiểu **đóng khung thông tin** giúp người đọc đánh giá liệu tin tức có đạt được **tính khách quan** thực sự hay không. Sự lan truyền của **chủ nghĩa giật gân** và **tuyên truyền** qua **buồng vang** mạng xã hội làm sâu sắc hơn sự phân cực chính trị. Các tổ chức độc lập **kiểm tra thực tế** các tuyên bố và xem xét việc xây dựng **tường thuật** đóng vai trò dân chủ quan trọng. **Độ tin cậy** truyền thông phụ thuộc vào nguồn minh bạch, **đại diện** công bằng và sẵn sàng sửa lỗi, nhưng **kiểm duyệt** không bao giờ là giải pháp chấp nhận được và đe dọa tự do **ảnh hưởng** và ngôn luận."
  },
  "master.rhetoric-debate": {
    "emojis": ["🗣️", "💬", "⚖️"],
    "en": "Mastery of **rhetoric** and structured **debate** is central to democratic **discourse** and academic argument. A well-built **argument** begins with a solid **premise**, progresses through valid **inference**, and ends in a well-supported **claim**. Skilled debaters make strategic **concessions** while deploying powerful **rebuttals** against opposing **counterarguments**. Spotting a logical **fallacy** can dismantle an opponent's position, but only if your own reasoning maintains internal **coherence**. Effective **persuasion** rests not just on **logic** but also on the speaker's **credibility** and the **tone** adopted throughout the exchange.",
    "vi": "Sự thành thạo về **hùng biện** và **tranh luận** có cấu trúc là trọng tâm của **diễn ngôn** dân chủ và lập luận học thuật. Một **lập luận** được xây dựng tốt bắt đầu bằng một **tiền đề** vững chắc, tiến triển qua **suy luận** hợp lệ và kết thúc bằng một **tuyên bố** được hỗ trợ tốt. Những người tranh luận có kỹ năng đưa ra các **nhượng bộ** chiến lược trong khi triển khai các **phản bác** mạnh mẽ chống lại các **phản luận** đối lập. Phát hiện **ngụy biện** logic có thể tháo dỡ lập trường của đối thủ, nhưng chỉ khi lý luận của chính bạn duy trì **tính mạch lạc** nội bộ. **Thuyết phục** hiệu quả không chỉ dựa vào **logic** mà còn vào **độ tin cậy** của người nói và **giọng điệu** được áp dụng trong suốt cuộc trao đổi."
  },
  "master.global-governance": {
    "emojis": ["🌐", "🕊️", "🤝"],
    "en": "**Global governance** depends on nations accepting shared rules through **international law** and **multilateral** institutions. **Humanitarian** crises demand rapid **peacekeeping** responses guided by clear **treaty** obligations and **diplomacy**. The tension between national **sovereignty** and global **compliance** is one of the central challenges of the current world order. **NGOs** and civil society actors complement the work of formal **institutions** by holding governments to account. When **sanctions** are imposed, they must be targeted carefully to avoid harming civilians and to preserve conditions for **cooperation** and eventual **reform**.",
    "vi": "**Quản trị toàn cầu** phụ thuộc vào việc các quốc gia chấp nhận các quy tắc chung qua **luật quốc tế** và các thể chế **đa phương**. Các cuộc khủng hoảng **nhân đạo** đòi hỏi phản ứng **gìn giữ hòa bình** nhanh chóng được hướng dẫn bởi các nghĩa vụ **hiệp ước** và **ngoại giao** rõ ràng. Căng thẳng giữa **chủ quyền** quốc gia và **tuân thủ** toàn cầu là một trong những thách thức trung tâm của trật tự thế giới hiện tại. Các **tổ chức phi chính phủ** và các tác nhân xã hội dân sự bổ sung cho công việc của các **thể chế** chính thức bằng cách buộc chính phủ chịu trách nhiệm. Khi **lệnh trừng phạt** được áp đặt, chúng phải được nhắm mục tiêu cẩn thận để tránh gây hại cho người dân và bảo tồn các điều kiện cho **hợp tác** và **cải cách** cuối cùng."
  },
  "master.bioethics": {
    "emojis": ["🧬", "⚖️", "🔬"],
    "en": "**Bioethics** confronts the profound moral questions raised by advances in **genetic engineering** and **gene editing**. **Stem cell** research holds enormous therapeutic promise, but it raises contentious debates about **human dignity** and the **moral** status of embryos. All **experimental** procedures require free **consent** and approval from an **ethics committee** to ensure they meet **research ethics** standards. Human **enhancement** technologies — from cognitive drugs to genetic modifications — challenge our understanding of **autonomy** and what it means to be human. The **impact** of these technologies on society demands careful **regulation** to protect the vulnerable and prevent irreversible harm.",
    "vi": "**Đạo đức sinh học** đối mặt với những câu hỏi đạo đức sâu sắc được đặt ra bởi những tiến bộ trong **kỹ thuật di truyền** và **chỉnh sửa gen**. Nghiên cứu **tế bào gốc** có tiềm năng điều trị to lớn, nhưng nó gây ra các cuộc tranh luận gây tranh cãi về **nhân phẩm** và địa vị **đạo đức** của phôi. Tất cả các thủ thuật **thử nghiệm** đòi hỏi **đồng ý** tự do và phê duyệt từ **hội đồng đạo đức** để đảm bảo chúng đáp ứng các tiêu chuẩn **đạo đức nghiên cứu**. Các công nghệ **tăng cường** con người — từ thuốc nhận thức đến sửa đổi di truyền — thách thức sự hiểu biết của chúng ta về **quyền tự quyết** và ý nghĩa của việc là con người. **Tác động** của các công nghệ này lên xã hội đòi hỏi **quy định** cẩn thận để bảo vệ người dễ bị tổn thương và ngăn chặn thiệt hại không thể đảo ngược."
  },
  "master.argumentation": {
    "emojis": ["💬", "🔍", "⚖️"],
    "en": "Rigorous **argumentation** is the foundation of academic writing, legal reasoning, and civic debate. Every **claim** must rest on a clearly stated **premise** and be supported by credible **evidence** that the writer can **substantiate**. Identifying the **assumption** behind an opposing view is often the key to constructing a powerful **counterargument**. A logical **inference** builds on what has been proven, while a **fallacy** introduces flawed reasoning that undermines the entire position. Critical readers will **evaluate** arguments for **coherence**, checking each step from **assertion** through to conclusion, and a fair **critique** acknowledges complexity from multiple **perspectives**.",
    "vi": "**Lập luận** nghiêm ngặt là nền tảng của viết học thuật, lý luận pháp lý và tranh luận dân sự. Mỗi **tuyên bố** phải dựa trên một **tiền đề** được nêu rõ ràng và được hỗ trợ bởi **bằng chứng** đáng tin cậy mà người viết có thể **chứng minh**. Xác định **giả định** đằng sau quan điểm đối lập thường là chìa khóa để xây dựng một **phản luận** mạnh mẽ. Một **suy luận** logic xây dựng trên những gì đã được chứng minh, trong khi một **ngụy biện** đưa ra lý luận sai lầm làm suy yếu toàn bộ lập trường. Độc giả phê phán sẽ **đánh giá** các lập luận về **tính mạch lạc**, kiểm tra từng bước từ **khẳng định** đến kết luận, và một **phê bình** công bằng thừa nhận sự phức tạp từ nhiều **quan điểm**."
  },
  "master.globalisation": {
    "emojis": ["🌎", "📦", "🔗"],
    "en": "**Globalisation** has transformed **trade**, finance, and culture through deepening economic **integration** and **interdependence**. Multinational **corporations** exploit competitive advantages across borders, fuelling growth but also raising concerns about labour rights and environmental standards. The **dominance** of a few powerful economies creates significant **inequality** both within and between nations. While **localization** efforts preserve cultural identity, the pressure to remain competitive in global **competition** often overwhelms them. **Migration**, technology, and the **influence** of shared media are reshaping what it means to belong to a particular society in a **globalized** world full of both **opportunity** and risk.",
    "vi": "**Toàn cầu hóa** đã biến đổi **thương mại**, tài chính và văn hóa thông qua **hội nhập** kinh tế sâu sắc hơn và **sự phụ thuộc lẫn nhau**. Các **tập đoàn** đa quốc gia khai thác lợi thế cạnh tranh qua các biên giới, thúc đẩy tăng trưởng nhưng cũng gây lo ngại về quyền lao động và tiêu chuẩn môi trường. **Sự thống trị** của một số nền kinh tế mạnh tạo ra **bất bình đẳng** đáng kể cả trong và giữa các quốc gia. Trong khi các nỗ lực **địa phương hóa** bảo tồn bản sắc văn hóa, áp lực duy trì cạnh tranh trong **cạnh tranh** toàn cầu thường áp đảo chúng. **Di cư**, công nghệ và **ảnh hưởng** của phương tiện truyền thông chung đang định hình lại ý nghĩa của việc thuộc về một xã hội cụ thể trong thế giới **toàn cầu hóa** đầy **cơ hội** và rủi ro."
  },
  "master.social-change": {
    "emojis": ["✊", "📢", "🦋"],
    "en": "**Social change** rarely happens without sustained effort from organised **movements** and determined **activism**. Public **demonstrations** and **protest** signal widespread discontent and pressure institutions to act, while strategic **advocacy** operates through legal and political channels. **Solidarity** among diverse groups amplifies their collective voice and strengthens **resistance** to entrenched power. **Mobilizing** communities around shared values of **justice** and **equality** is the first step toward meaningful **reform** and lasting societal **transformation**. Effective change requires not just passion but also clear goals, inclusive leadership, and the ability to sustain a long-term **campaign**.",
    "vi": "**Biến đổi xã hội** hiếm khi xảy ra mà không có nỗ lực bền vững từ các **phong trào** có tổ chức và **chủ nghĩa hoạt động** quyết tâm. Các cuộc **biểu tình** công khai và **cuộc biểu tình** báo hiệu sự bất mãn rộng rãi và gây áp lực lên các thể chế hành động, trong khi **vận động** chiến lược hoạt động qua các kênh pháp lý và chính trị. **Đoàn kết** giữa các nhóm đa dạng khuếch đại giọng nói tập thể của họ và củng cố **kháng cự** chống lại quyền lực đã bám rễ sâu. **Huy động** cộng đồng xung quanh các giá trị chung về **công lý** và bình đẳng là bước đầu tiên hướng tới **cải cách** có ý nghĩa và **biến đổi** xã hội lâu dài. Thay đổi hiệu quả đòi hỏi không chỉ đam mê mà còn mục tiêu rõ ràng, lãnh đạo bao trùm và khả năng duy trì **chiến dịch** lâu dài."
  },
  "master.immigration-identity": {
    "emojis": ["🏘️", "🌍", "🪞"],
    "en": "Immigration raises profound questions about **identity**, **belonging**, and the obligations of the **host country**. Members of the **diaspora** often navigate a complex **transnational** existence, balancing **assimilation** into the new society with the desire to preserve their cultural **heritage**. True **integration** goes beyond language learning to include genuine social acceptance and **equality** of opportunity for **minority** communities. **Multiculturalism** celebrates diversity but requires active policies to prevent **exclusion** and ensure meaningful **cultural exchange**. When **second-generation** immigrants feel torn between two worlds, their search for **acceptance** and a coherent sense of **identity** reflects the broader challenge of building inclusive societies.",
    "vi": "Di cư đặt ra những câu hỏi sâu sắc về **bản sắc**, **cảm giác thuộc về** và nghĩa vụ của **quốc gia tiếp nhận**. Các thành viên của **cộng đồng người di cư** thường điều hướng cuộc sống **xuyên quốc gia** phức tạp, cân bằng **đồng hóa** vào xã hội mới với mong muốn bảo tồn **di sản** văn hóa của họ. **Hội nhập** thực sự vượt ra ngoài học ngôn ngữ để bao gồm sự chấp nhận xã hội thực sự và bình đẳng cơ hội cho các cộng đồng **thiểu số**. **Chủ nghĩa đa văn hóa** tôn vinh sự đa dạng nhưng đòi hỏi các chính sách tích cực để ngăn chặn **loại trừ** và đảm bảo **trao đổi văn hóa** có ý nghĩa. Khi những người nhập cư **thế hệ thứ hai** cảm thấy bị kéo giữa hai thế giới, việc tìm kiếm **sự chấp nhận** và ý thức **bản sắc** mạch lạc của họ phản ánh thách thức rộng hơn của việc xây dựng xã hội bao trùm."
  },
  "master.psychology-society": {
    "emojis": ["🧠", "👥", "🔍"],
    "en": "**Social psychology** reveals how deeply **social pressure**, **conformity**, and **groupthink** shape individual **behaviour** and decision-making. **Bias** and **prejudice** operate at both conscious and unconscious levels, distorting **perception** and producing **discrimination** even among well-intentioned people. Advertisers and politicians exploit knowledge of human **motivation** and **attitude** formation to craft messages that **manipulate** rather than inform. Understanding **cognitive** processes helps us recognise when our own **rationality** is compromised by emotional or social influences. Overcoming **stereotypes** and **social pressure** demands active critical awareness and the courage to challenge prevailing group **conformity**.",
    "vi": "**Tâm lý xã hội** tiết lộ cách **áp lực xã hội**, **tuân thủ theo đám đông** và **tư duy nhóm** định hình sâu sắc **hành vi** cá nhân và việc ra quyết định. **Thành kiến** và **định kiến** hoạt động ở cả mức độ có ý thức và vô thức, làm méo mó **nhận thức** và tạo ra **phân biệt đối xử** ngay cả ở những người có ý định tốt. Các nhà quảng cáo và chính trị gia khai thác kiến thức về sự hình thành **động lực** và **thái độ** của con người để tạo ra các thông điệp **thao túng** hơn là thông tin. Hiểu các quá trình **nhận thức** giúp chúng ta nhận ra khi nào **tính hợp lý** của chúng ta bị ảnh hưởng bởi các ảnh hưởng cảm xúc hoặc xã hội. Vượt qua **khuôn mẫu** và **áp lực xã hội** đòi hỏi nhận thức phê phán tích cực và can đảm để thách thức **sự tuân thủ theo đám đông** phổ biến."
  },
  "master.consumer-society": {
    "emojis": ["🛒", "💎", "♻️"],
    "en": "Modern **consumer society** is driven by the relentless pursuit of **status**, **aspiration**, and **brand** recognition. Advertisers fuel **materialism** by linking product **consumption** to personal **identity** and social worth. The environmental cost of excessive **waste** and disposable **lifestyle** choices is increasingly difficult to ignore. Easy access to credit enables **impulse** buying that leaves many households drowning in **debt**. A growing movement toward **sustainability** and conscious consumption challenges the dominant narrative that more is always better, arguing instead that true **wellbeing** requires addressing the deep **inequality** built into consumer culture.",
    "vi": "**Xã hội tiêu dùng** hiện đại được thúc đẩy bởi sự theo đuổi không ngừng của **địa vị**, **khát vọng** và nhận diện **thương hiệu**. Các nhà quảng cáo thúc đẩy **chủ nghĩa vật chất** bằng cách liên kết **tiêu thụ** sản phẩm với **bản sắc** cá nhân và giá trị xã hội. Chi phí môi trường của **lãng phí** quá mức và các lựa chọn **lối sống** dùng một lần ngày càng khó bỏ qua. Tiếp cận tín dụng dễ dàng cho phép mua hàng **bốc đồng** khiến nhiều hộ gia đình chìm trong **nợ**. Một phong trào ngày càng tăng hướng tới **bền vững** và tiêu thụ có ý thức thách thức câu chuyện chủ đạo rằng nhiều hơn luôn tốt hơn, thay vào đó cho rằng **sức khỏe toàn diện** thực sự đòi hỏi giải quyết **bất bình đẳng** sâu sắc được tích hợp vào văn hóa tiêu dùng."
  },
  "master.language-power": {
    "emojis": ["🗣️", "📢", "🌐"],
    "en": "Language is never neutral: **discourse**, **framing**, and **narrative** all reflect and reinforce existing **power** relations in society. **Propaganda** exploits linguistic tools to manufacture consent and silence dissent, while **censorship** suppresses voices that challenge **dominant** ideologies. The marginalisation of **minority language** communities strips people of their cultural **heritage** and sense of **identity**. **Representation** in public language — who speaks, who is spoken about, and how — determines whose experiences are treated as legitimate. Building truly **multilingual** societies requires more than tolerance; it demands active policies that give equal **expression** to all voices and challenge structures of linguistic **power**.",
    "vi": "Ngôn ngữ không bao giờ trung lập: **diễn ngôn**, **đóng khung ngôn ngữ** và **tường thuật** đều phản ánh và củng cố các quan hệ **quyền lực** hiện có trong xã hội. **Tuyên truyền** khai thác các công cụ ngôn ngữ để tạo ra sự đồng thuận và bịt miệng sự bất đồng, trong khi **kiểm duyệt** đàn áp những giọng nói thách thức các hệ tư tưởng **thống trị**. Sự ngoại lề hóa các cộng đồng **ngôn ngữ thiểu số** tước bỏ của mọi người **di sản** văn hóa và ý thức **bản sắc** của họ. **Đại diện** trong ngôn ngữ công cộng — ai nói, ai được nói đến và như thế nào — xác định trải nghiệm của ai được coi là hợp pháp. Xây dựng các xã hội **đa ngôn ngữ** thực sự đòi hỏi nhiều hơn là sự khoan dung; nó đòi hỏi các chính sách tích cực trao **biểu đạt** bình đẳng cho tất cả mọi người và thách thức các cấu trúc **quyền lực** ngôn ngữ."
  }
}

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'stories.json')
with open(data_path, encoding='utf-8') as f:
    stories = json.load(f)

added = 0
for key, story in NEW_MASTER_STORIES.items():
    if key not in stories:
        stories[key] = story
        added += 1

with open(data_path, 'w', encoding='utf-8') as f:
    json.dump(stories, f, ensure_ascii=False, indent=2)

print(f"Added {added} new Master stories")
levels = {}
for key in stories.keys():
    lvl = key.split('.')[0]
    levels[lvl] = levels.get(lvl, 0) + 1
for lvl, count in sorted(levels.items()):
    print(f"  {lvl}: {count} stories")
print(f"Total: {len(stories)} stories")
