# -*- coding: utf-8 -*-
import json, os

stories = {
  "scholar.academic-skills": {
    "emojis": ["📚", "✍️", "🎓"],
    "en": "Writing a strong university essay requires more than just knowing the facts. You must **analyze** your sources carefully, **synthesize** information from multiple authors, and build a **coherent** **argument** around a clear **thesis**. Every claim should be supported with a proper **citation** from a credible source, and your **bibliography** must follow the correct format. Ask a peer to **evaluate** your **methodology** and give a **critique** to make sure your reasoning is always **logical**.",
    "vi": "Viết một bài luận đại học mạnh không chỉ đơn giản là biết các sự kiện. Bạn phải **phân tích** các nguồn cẩn thận, **tổng hợp** thông tin từ nhiều tác giả và xây dựng một **lập luận** **mạch lạc** xung quanh một **luận điểm** rõ ràng. Mỗi tuyên bố nên được hỗ trợ bằng **trích dẫn** thích hợp từ nguồn đáng tin cậy, và **danh mục tài liệu** phải theo đúng định dạng. Hãy nhờ bạn **đánh giá** **phương pháp luận** của bạn và đưa ra **phê bình** để đảm bảo lập luận luôn **logic**."
  },
  "scholar.media-journalism": {
    "emojis": ["📰", "🎙️", "📡"],
    "en": "In today's fast-moving media landscape, a responsible **journalist** must always **verify** every piece of information before publishing. A sensational **headline** may attract clicks, but it can damage credibility if the **source** turns out to be unreliable. Some governments use **censorship** and **propaganda** to control media **coverage** and prevent **impartial** reporting. Strong **editorial** standards and wide **circulation** of accurate news are essential defenses against misinformation in a democratic society.",
    "vi": "Trong bối cảnh truyền thông thay đổi nhanh ngày nay, một **nhà báo** có trách nhiệm luôn phải **xác minh** mọi thông tin trước khi xuất bản. Một **tiêu đề** giật gân có thể thu hút lượt nhấp, nhưng có thể gây tổn hại đến uy tín nếu **nguồn** hóa ra không đáng tin cậy. Một số chính phủ dùng **kiểm duyệt** và **tuyên truyền** để kiểm soát **đưa tin** và ngăn chặn báo cáo **khách quan**. Tiêu chuẩn **biên tập** mạnh mẽ và **lưu hành** rộng rãi tin tức chính xác là sự bảo vệ thiết yếu chống lại thông tin sai lệch trong xã hội dân chủ."
  },
  "scholar.law-justice": {
    "emojis": ["⚖️", "🏛️", "📜"],
    "en": "The **prosecution** presented compelling **evidence** that the **defendant** had violated a key environmental **statute**. However, the defense **attorney** argued that the existing **legislation** did not clearly define the act as a crime under current **jurisdiction**. The court heard hours of **testimony** from expert witnesses before the judge delivered a **verdict** that the defendant was **liable** for damages. The case prompted lawmakers to pass a new **amendment** to strengthen the **penalty** for future violations.",
    "vi": "**Bên công tố** trình bày **bằng chứng** thuyết phục rằng **bị cáo** đã vi phạm một **quy chế** môi trường quan trọng. Tuy nhiên, **luật sư** bào chữa lập luận rằng **luật pháp** hiện hành không xác định rõ ràng hành vi đó là tội phạm theo **thẩm quyền** hiện tại. Tòa án nghe nhiều giờ **lời khai** từ các nhân chứng chuyên gia trước khi thẩm phán đưa ra **phán quyết** rằng bị cáo phải chịu **trách nhiệm pháp lý**. Vụ án thúc đẩy các nhà lập pháp thông qua một **tu chính án** mới để tăng cường **hình phạt** cho các vi phạm trong tương lai."
  },
  "scholar.economics-trade": {
    "emojis": ["💰", "📊", "🌍"],
    "en": "During the global **recession**, governments faced difficult choices about how to stabilize their economies. Some raised the **interest rate** to slow **inflation**, while others cut **tariffs** on essential **imports** to keep prices manageable for consumers. A large budget **deficit** forced several countries to reduce the **subsidy** they provided to local farmers, threatening key **commodity** exports. Economists debated which **fiscal** policy would best protect **GDP** while restoring confidence in the national **currency**.",
    "vi": "Trong cuộc **suy thoái** toàn cầu, các chính phủ phải đối mặt với những lựa chọn khó khăn về cách ổn định nền kinh tế. Một số nước tăng **lãi suất** để làm chậm **lạm phát**, trong khi một số khác cắt giảm **thuế quan** đối với các **hàng nhập khẩu** thiết yếu để giữ giá cả ở mức có thể quản lý. Thâm hụt ngân sách lớn buộc một số quốc gia giảm **trợ cấp** cho nông dân địa phương, đe dọa xuất khẩu **hàng hóa** chủ chốt. Các nhà kinh tế tranh luận về chính sách **tài khóa** nào sẽ bảo vệ tốt nhất **GDP** trong khi khôi phục niềm tin vào **tiền tệ** quốc gia."
  },
  "scholar.psychology-mind": {
    "emojis": ["🧠", "💭", "🔬"],
    "en": "A growing body of research shows that early **trauma** can reshape the **cognitive** patterns that govern a person's **behavior** for years afterward. The **subconscious** mind holds memories and fears that influence our **perception** of the world, sometimes without our awareness. Fortunately, people who develop strong **resilience** and receive appropriate **therapy** can rebuild their sense of **identity** and find new **motivation**. Building **empathy** within communities also helps reduce the **anxiety** and harmful **stereotypes** that often surround those living with a mental health **disorder**.",
    "vi": "Ngày càng nhiều nghiên cứu cho thấy **chấn thương** tâm lý thời thơ ấu có thể định hình lại các mô hình **nhận thức** chi phối **hành vi** của một người trong nhiều năm sau đó. Tâm trí **vô thức** lưu giữ những ký ức và nỗi sợ hãi ảnh hưởng đến **nhận thức** của chúng ta về thế giới, đôi khi mà không có sự nhận biết của chúng ta. May mắn thay, những người phát triển **khả năng phục hồi** mạnh mẽ và nhận được **liệu pháp** thích hợp có thể tái xây dựng ý thức về **bản sắc** và tìm thấy **động lực** mới. Xây dựng **sự đồng cảm** trong cộng đồng cũng giúp giảm thiểu **lo lắng** và những **định kiến** có hại thường bao quanh những người sống với **rối loạn** sức khỏe tâm thần."
  },
  "scholar.politics-society": {
    "emojis": ["🏛️", "🗳️", "🌐"],
    "en": "The small nation's fragile **democracy** was tested when two major parties failed to form a stable **coalition** after the election. The prime minister launched a **campaign** to **reform** the **constitution** and clarify the balance of **authority** between branches of government. Opposition leaders called for a **referendum**, arguing that changes to national **sovereignty** required a public vote. International **diplomats** urged both sides to resolve the crisis through dialogue, warning that **sanctions** could follow if **treaty** obligations were ignored.",
    "vi": "Nền **dân chủ** mong manh của quốc gia nhỏ bị thử thách khi hai đảng lớn không thể thành lập **liên minh** ổn định sau bầu cử. Thủ tướng phát động **chiến dịch** để **cải cách** **hiến pháp** và làm rõ sự cân bằng **quyền lực** giữa các nhánh chính phủ. Các lãnh đạo đối lập kêu gọi **trưng cầu dân ý**, lập luận rằng những thay đổi về **chủ quyền** quốc gia đòi hỏi bỏ phiếu công khai. Các **nhà ngoại giao** quốc tế kêu gọi cả hai bên giải quyết khủng hoảng thông qua đối thoại, cảnh báo rằng **trừng phạt** có thể theo sau nếu nghĩa vụ **hiệp ước** bị bỏ qua."
  },
  "scholar.science-research": {
    "emojis": ["🔬", "📊", "🧪"],
    "en": "A team of biologists published a groundbreaking paper in a leading **peer-reviewed** journal describing their **finding** that a specific **molecule** in the human **genome** was linked to a rare neurological condition. Their **clinical** trial involved a large **sample** of patients and carefully controlled every **variable** to isolate the cause. The **data** showed a statistically **significant** **correlation**, though the team was careful not to draw a final **conclusion** until other labs could **replicate** the study. The **ethics** committee reviewed the research to ensure no participants were harmed.",
    "vi": "Một nhóm sinh vật học công bố bài báo đột phá trên tạp chí hàng đầu **được phản biện học thuật** mô tả **phát hiện** rằng một **phân tử** cụ thể trong **bộ gen** người liên quan đến một tình trạng thần kinh hiếm gặp. Thử nghiệm **lâm sàng** của họ liên quan đến một **mẫu** lớn bệnh nhân và kiểm soát cẩn thận mỗi **biến số** để tách biệt nguyên nhân. **Dữ liệu** cho thấy một **mối tương quan** có ý nghĩa thống kê **đáng kể**, mặc dù nhóm cẩn thận không rút ra **kết luận** cuối cùng cho đến khi các phòng thí nghiệm khác có thể **tái lặp** nghiên cứu. Ủy ban **đạo đức** xem xét nghiên cứu để đảm bảo không có người tham gia nào bị tổn hại."
  },
  "scholar.environment-policy": {
    "emojis": ["🌿", "⚡", "📜"],
    "en": "The government unveiled a sweeping environmental **initiative** aimed at making the country **carbon neutral** by 2050. The plan included stricter **regulation** on industrial **emissions**, expanded **offshore** wind farms, and a ban on sending organic waste to **landfill**. Companies were required to measure and reduce their **carbon footprint** as part of the international **protocol** they had signed. Critics argued that voluntary **pledges** were not enough and that stronger enforcement was needed to genuinely protect **biodiversity** and ensure truly **sustainable** **conservation** practices.",
    "vi": "Chính phủ công bố một **sáng kiến** môi trường toàn diện nhằm đưa đất nước trở thành **trung hòa carbon** vào năm 2050. Kế hoạch bao gồm các **quy định** chặt chẽ hơn về **khí thải** công nghiệp, mở rộng các trang trại điện gió **ngoài khơi** và cấm đưa chất thải hữu cơ đến **bãi rác**. Các công ty được yêu cầu đo lường và giảm **dấu chân carbon** như một phần của **nghị định thư** quốc tế. Các nhà phê bình lập luận rằng những **cam kết** tự nguyện là không đủ và cần thực thi mạnh mẽ hơn để thực sự bảo vệ **đa dạng sinh học** và đảm bảo các thực hành **bảo tồn** **bền vững** thực sự."
  },
  "scholar.health-medicine": {
    "emojis": ["💊", "🏥", "🔬"],
    "en": "The doctor referred the patient to a **specialist** after a series of unusual **symptoms** pointed to a rare **chronic** condition that standard tests had failed to detect. A precise **diagnosis** allowed them to begin a targeted **treatment** plan, combining **pharmaceutical** medication with changes in **nutrition** and lifestyle. The patient's weakened **immune** system meant that even minor infections posed a serious risk, so **vaccination** was strongly recommended. Improved early **prevention** protocols had significantly reduced **mortality** rates for this condition over the past decade.",
    "vi": "Bác sĩ giới thiệu bệnh nhân đến một **chuyên gia** sau khi một loạt **triệu chứng** bất thường chỉ ra tình trạng **mãn tính** hiếm gặp mà các xét nghiệm tiêu chuẩn không phát hiện được. Một **chẩn đoán** chính xác cho phép bắt đầu kế hoạch **điều trị** có mục tiêu, kết hợp thuốc **dược phẩm** với thay đổi trong **dinh dưỡng** và lối sống. Hệ thống **miễn dịch** suy yếu của bệnh nhân có nghĩa là ngay cả nhiễm trùng nhỏ cũng gây nguy cơ nghiêm trọng, nên **tiêm vắc xin** được khuyến nghị mạnh mẽ. Các giao thức **phòng ngừa** sớm được cải thiện đã giảm đáng kể tỷ lệ **tử vong** cho tình trạng này trong thập kỷ qua."
  },
  "scholar.technology-future": {
    "emojis": ["🤖", "💻", "🔮"],
    "en": "The company invested heavily in **artificial intelligence** and **machine learning** to stay ahead of rapid technological change. Their latest **prototype** used a sophisticated **algorithm** to predict user needs and could **integrate** seamlessly with existing systems through an intuitive **interface**. However, engineers warned that older software risked becoming **obsolete** if proper **cybersecurity** measures were not in place to **encrypt** sensitive data. The rise of **automation** and **virtual reality** also demanded higher **bandwidth** and continuous **innovation** to keep pace with user expectations.",
    "vi": "Công ty đầu tư mạnh vào **trí tuệ nhân tạo** và **học máy** để đón đầu sự thay đổi công nghệ nhanh chóng. **Nguyên mẫu** mới nhất sử dụng một **thuật toán** tinh vi để dự đoán nhu cầu người dùng và có thể **tích hợp** liền mạch với các hệ thống hiện có qua **giao diện** trực quan. Tuy nhiên, các kỹ sư cảnh báo rằng phần mềm cũ có nguy cơ trở nên **lỗi thời** nếu các biện pháp **an ninh mạng** thích hợp không được áp dụng để **mã hóa** dữ liệu nhạy cảm. Sự nổi lên của **tự động hóa** và **thực tế ảo** cũng đòi hỏi **băng thông** cao hơn và **đổi mới** liên tục để theo kịp kỳ vọng của người dùng."
  },
  "scholar.art-culture": {
    "emojis": ["🎨", "🏛️", "👁️"],
    "en": "The museum's new **exhibition** brought together rare **Renaissance** paintings and bold **contemporary** **installations** that challenged visitors to reconsider what art could be. A striking **sculpture** stood at the entrance — its **abstract** form drew attention to the **aesthetic** contrast between old and new. The **curator** explained that every work had been chosen to shift the viewer's **perception** of **heritage** and identity. One stunning **portrait** on a large **canvas** was widely regarded as the show's **masterpiece**, drawing crowds who rarely visited art spaces.",
    "vi": "**Triển lãm** mới của bảo tàng tập hợp những bức tranh **Phục hưng** hiếm có và những **tác phẩm sắp đặt** **đương đại** táo bạo thách thức du khách xem lại ý nghĩa của nghệ thuật. Một **tác phẩm điêu khắc** ấn tượng đứng ở lối vào — hình dạng **trừu tượng** của nó thu hút sự chú ý đến sự tương phản **thẩm mỹ** giữa cũ và mới. **Giám tuyển** giải thích rằng mọi tác phẩm đều được chọn để thay đổi **nhận thức** của người xem về **di sản** và bản sắc. Một **chân dung** tuyệt đẹp trên một **bức tranh** lớn được đánh giá rộng rãi là **kiệt tác** của triển lãm, thu hút đám đông ít khi ghé thăm không gian nghệ thuật."
  },
  "scholar.education-system": {
    "emojis": ["🎓", "📚", "🏫"],
    "en": "Reformers argued that the national **curriculum** needed a complete overhaul to reflect the skills students would need in modern life. Critics of traditional **pedagogy** called for more project-based learning and less reliance on high-stakes **assessment** that measured only memory. Rising **tuition** fees had contributed to higher **dropout** rates, particularly among students who lacked access to **scholarship** support. The government pledged to strengthen **vocational** pathways, invest in **extracurricular** programs, and make digital **literacy** a **compulsory** part of every school's **accreditation** standards.",
    "vi": "Các nhà cải cách lập luận rằng **chương trình giảng dạy** quốc gia cần được đại tu hoàn toàn để phản ánh những kỹ năng học sinh sẽ cần trong cuộc sống hiện đại. Các nhà phê bình **phương pháp sư phạm** truyền thống kêu gọi học tập dựa trên dự án nhiều hơn và ít phụ thuộc vào **đánh giá** có cược cao. Học phí **học phí** tăng đã góp phần vào tỷ lệ **bỏ học** cao hơn, đặc biệt là với những học sinh thiếu quyền tiếp cận hỗ trợ **học bổng**. Chính phủ cam kết củng cố các lộ trình **đào tạo nghề**, đầu tư vào các chương trình **ngoại khóa** và đưa **đọc viết** kỹ thuật số thành phần **bắt buộc** trong tiêu chuẩn **kiểm định** của mỗi trường."
  },
  "scholar.business-management": {
    "emojis": ["💼", "📊", "🤝"],
    "en": "The board of directors met to review the company's long-term **strategy** after a period of declining **revenue** and rising **liability** concerns. A proposed **merger** with a regional competitor had the potential to double their market share, but the financial **audit** revealed unexpected debt that complicated the deal. **Stakeholders** were divided — investors wanted a higher **dividend**, while managers argued for reinvesting in a new **partnership** with a tech firm. The CEO, a seasoned **entrepreneur**, insisted on a detailed **forecast** before approving any further **acquisition** or decision to **outsource** core operations.",
    "vi": "Hội đồng quản trị họp để xem xét **chiến lược** dài hạn của công ty sau một giai đoạn **doanh thu** giảm và lo ngại về **trách nhiệm pháp lý** gia tăng. Một đề xuất **sáp nhập** với đối thủ khu vực có tiềm năng tăng gấp đôi thị phần, nhưng cuộc **kiểm toán** tài chính tiết lộ khoản nợ bất ngờ làm phức tạp thỏa thuận. Các **bên liên quan** bị chia rẽ — nhà đầu tư muốn **cổ tức** cao hơn, trong khi các nhà quản lý lập luận cho việc tái đầu tư vào **quan hệ đối tác** mới với công ty công nghệ. Giám đốc điều hành, một **doanh nhân** dày dạn kinh nghiệm, nhấn mạnh cần có **dự báo** chi tiết trước khi phê duyệt bất kỳ quyết định **mua lại** hoặc **thuê ngoài** hoạt động cốt lõi nào."
  },
  "scholar.urban-development": {
    "emojis": ["🏙️", "🏗️", "🗺️"],
    "en": "City planners debated whether to allow a cluster of new **skyscrapers** in the historic quarter, which many residents felt would accelerate **gentrification**. The **municipality** commissioned a study on **zoning** laws and found that high-**density** **construction** was increasing **congestion** and reducing space for **pedestrian** walkways. Architects proposed a mixed-use **renovation** plan that would preserve key **landmarks** while improving **transit** links to outer suburbs. Critics of **urban sprawl** argued that the city needed to grow upward, not outward, to protect green land on its boundaries.",
    "vi": "Các nhà quy hoạch thành phố tranh luận về việc có nên cho phép một cụm **tòa nhà chọc trời** mới trong khu phố cổ, điều mà nhiều cư dân cảm thấy sẽ đẩy nhanh **quá trình đô thị hóa quý tộc**. **Chính quyền thành phố** đặt hàng một nghiên cứu về luật **phân vùng** và phát hiện ra rằng **xây dựng** mật độ cao đang làm tăng **tắc nghẽn** và giảm không gian cho các lối đi bộ **người đi bộ**. Các kiến trúc sư đề xuất một kế hoạch **cải tạo** đa chức năng có thể bảo tồn những **địa danh** quan trọng trong khi cải thiện các kết nối **giao thông công cộng** đến các vùng ngoại ô. Các nhà phê bình **đô thị hóa lan rộng** lập luận rằng thành phố cần phát triển theo chiều dọc để bảo vệ đất xanh ở vùng ngoại vi."
  },
  "scholar.global-issues": {
    "emojis": ["🌍", "✊", "🕊️"],
    "en": "The United Nations report painted a sobering picture of a world where **poverty** and **inequality** continued to drive mass **migration** and **displacement** across continents. In several regions, **famine** and **epidemic** outbreaks had overwhelmed **humanitarian** organizations struggling to deliver **aid** in conflict zones. **Geopolitics** complicated every response — some nations imposed **sanctions** rather than offering support, and fears over **nuclear** proliferation froze diplomatic channels. The report concluded that no country could solve these crises alone and that genuine global cooperation was the only path forward.",
    "vi": "Báo cáo của Liên Hợp Quốc vẽ ra một bức tranh đáng lo ngại về thế giới nơi **nghèo đói** và **bất bình đẳng** tiếp tục thúc đẩy **di cư** hàng loạt và **di dời** khắp các lục địa. Ở một số vùng, **nạn đói** và bùng phát **dịch bệnh** đã áp đảo các tổ chức **nhân đạo** đang nỗ lực cung cấp **viện trợ** ở các khu vực xung đột. **Địa chính trị** làm phức tạp mọi phản ứng — một số quốc gia áp đặt **trừng phạt** thay vì cung cấp hỗ trợ, và lo ngại về phổ biến **hạt nhân** làm đóng băng các kênh ngoại giao. Báo cáo kết luận rằng không quốc gia nào có thể giải quyết những khủng hoảng này một mình và sự hợp tác toàn cầu thực sự là con đường duy nhất tiến về phía trước."
  },
  "scholar.literature-analysis": {
    "emojis": ["📖", "✍️", "🔍"],
    "en": "In the novel, the **protagonist's** slow physical journey mirrors a deeper emotional transformation — a pattern of **symbolism** the author reinforces through recurring **motifs** of water and fire. The **antagonist** is not a villain in the traditional sense but a reflection of the hero's own fears, a structural **irony** that deepens the central **theme** of self-deception. The **foreshadowing** in the early chapters is subtle — woven into the **prose** almost invisibly — yet retrospectively feels inevitable. This **narrative** technique, combined with shifting **perspective** and echoes of medieval **allegory**, places the novel firmly in the tradition of literary complexity.",
    "vi": "Trong cuốn tiểu thuyết, hành trình thể chất chậm chạp của **nhân vật chính** phản chiếu một sự chuyển hóa cảm xúc sâu sắc hơn — một mô hình **biểu tượng** mà tác giả củng cố qua những **mô típ** lặp đi lặp lại của nước và lửa. **Nhân vật phản diện** không phải là kẻ ác theo nghĩa truyền thống mà là sự phản chiếu nỗi sợ hãi của chính người anh hùng, một **trớ trêu** cấu trúc làm sâu sắc thêm **chủ đề** trung tâm về sự tự lừa dối. **Báo trước** trong các chương đầu rất tinh tế — được dệt vào **văn xuôi** gần như vô hình — nhưng nhìn lại cảm thấy không thể tránh khỏi. Kỹ thuật **tường thuật** này, kết hợp với **quan điểm** thay đổi và dấu vang vọng của **ngụ ngôn** thời trung cổ, đặt cuốn tiểu thuyết vào truyền thống của sự phức tạp văn học."
  },
  "scholar.space-universe": {
    "emojis": ["🌌", "🔭", "🚀"],
    "en": "Deep in the southern **constellation** of Centaurus lies a **nebula** so vast that our entire **solar system** could fit within a fraction of it. Scientists used the most powerful **telescope** ever built to observe how a massive **black hole** was bending light and distorting the **orbit** of nearby stars through extreme **gravity**. A passing **comet**, its tail blazing white against the darkness, had been tracked for weeks by an **astronaut** aboard the orbiting **satellite**. What made this discovery remarkable was how it changed our understanding of how **galaxies** form and how **asteroids** behave in dense gravitational fields.",
    "vi": "Sâu trong **chòm sao** Centaurus phía nam có một **tinh vân** rộng lớn đến mức toàn bộ **hệ mặt trời** của chúng ta chỉ chiếm một phần nhỏ trong đó. Các nhà khoa học sử dụng **kính thiên văn** mạnh nhất từng được xây dựng để quan sát cách một **lỗ đen** khổng lồ đang bẻ cong ánh sáng và bóp méo **quỹ đạo** của các ngôi sao lân cận qua **trọng lực** cực đoan. Một **sao chổi** đang di chuyển ngang qua, đuôi cháy trắng trong bóng tối, đã được theo dõi nhiều tuần bởi một **phi hành gia** trên **vệ tinh** đang quay quanh quỹ đạo. Điều làm cho phát hiện này đáng chú ý là cách nó thay đổi sự hiểu biết của chúng ta về cách **thiên hà** hình thành và cách **tiểu hành tinh** hoạt động trong các trường hấp dẫn dày đặc."
  },
  "scholar.food-agriculture": {
    "emojis": ["🌾", "🚜", "💧"],
    "en": "As **drought** conditions worsened across the region, farmers struggled to maintain sufficient water flow through their **irrigation** networks to keep their **crops** alive. Large **agribusiness** companies promoted **genetically modified** seeds that promised higher **yields** even in poor soil, but many small-scale **subsistence** farmers lacked the capital to adopt them. The debate over **pesticides** and synthetic **fertilizers** intensified as consumers demanded more **organic** produce and regulators pushed for safer standards. Without urgent action to protect **arable** land and support **livestock** farmers, the next **harvest** could fall dangerously short.",
    "vi": "Khi điều kiện **hạn hán** trở nên tồi tệ hơn, nông dân phải vật lộn để duy trì lưu lượng nước đủ qua các mạng lưới **tưới tiêu** để giữ cho **cây trồng** sống sót. Các công ty **nông nghiệp lớn** quảng bá hạt giống **biến đổi gen** hứa hẹn **năng suất** cao hơn ngay cả trong đất nghèo, nhưng nhiều nông dân **tự cung tự cấp** nhỏ lẻ thiếu vốn để áp dụng chúng. Cuộc tranh luận về **thuốc trừ sâu** và **phân bón** tổng hợp trở nên gay gắt hơn khi người tiêu dùng đòi hỏi nhiều sản phẩm **hữu cơ** hơn. Nếu không có hành động khẩn cấp để bảo vệ đất **canh tác** và hỗ trợ nông dân chăn nuôi **gia súc**, vụ **thu hoạch** tiếp theo có thể bị thiếu hụt nguy hiểm."
  },
  "scholar.human-rights": {
    "emojis": ["✊", "⚖️", "🌍"],
    "en": "The international **convention** was drafted to establish a universal framework for protecting human **dignity** and ensuring basic **equality** for every person regardless of origin or belief. Dozens of nations gathered to **ratify** the **charter**, pledging to uphold **justice** and end systematic **oppression** within their borders. **Advocacy** groups presented documented cases of **persecution** to pressure governments that had failed to protect individuals seeking **asylum**. Despite the ceremony, activists warned that signing a document was meaningless without enforcement, and that true **freedom** could only exist where **violations** were met with real consequences.",
    "vi": "**Công ước** quốc tế được soạn thảo để thiết lập một khuôn khổ phổ quát bảo vệ **phẩm giá** con người và đảm bảo **bình đẳng** cơ bản cho mỗi người bất kể xuất xứ hay tín ngưỡng. Hàng chục quốc gia tập hợp để **phê chuẩn** **hiến chương**, cam kết duy trì **công lý** và chấm dứt **áp bức** có hệ thống. Các nhóm **vận động** trình bày các trường hợp được ghi nhận về **bức hại** để gây áp lực lên các chính phủ đã không bảo vệ những người tìm kiếm **quyền tị nạn**. Bất chấp buổi lễ, các nhà hoạt động cảnh báo rằng ký tên vào một tài liệu là vô nghĩa nếu không có thực thi, và rằng **tự do** thực sự chỉ tồn tại khi các **vi phạm** bị xử lý với hậu quả thực sự."
  },
  "scholar.innovation-startup": {
    "emojis": ["💡", "🚀", "💰"],
    "en": "The founders entered the **accelerator** program with a bold idea to **disrupt** the logistics industry using real-time data. After weeks of feedback and rapid **iteration**, they refined their product from a clunky prototype into something genuinely **scalable**. Their strong **pitch** attracted a lead investor who agreed to participate in a **seed round**, giving the company its first major **funding** boost. The **lean** approach they used — testing early, **pivoting** fast, and building only what users needed — helped them reach a **valuation** that caught the attention of a major **venture capital** firm.",
    "vi": "Những người sáng lập tham gia chương trình **tăng tốc** với ý tưởng táo bạo để **phá vỡ** ngành logistics bằng dữ liệu thời gian thực. Sau nhiều tuần nhận phản hồi và **lặp** lại nhanh chóng, họ tinh chỉnh sản phẩm từ một nguyên mẫu cồng kềnh thành thứ thực sự có thể **mở rộng**. **Bài thuyết trình** mạnh mẽ của họ thu hút một nhà đầu tư chủ chốt đồng ý tham gia một vòng **hạt giống**, mang lại khoản **tài trợ** lớn đầu tiên. Cách tiếp cận **tinh gọn** — kiểm tra sớm, **xoay trục** nhanh và chỉ xây dựng những gì người dùng cần — giúp họ đạt được **định giá** thu hút sự chú ý của một công ty **vốn đầu tư mạo hiểm** lớn."
  },
  "scholar.language-communication": {
    "emojis": ["🗣️", "📝", "🌐"],
    "en": "The professor opened her lecture on **linguistics** by asking whether language shapes thought or merely reflects it — a question whose **ambiguous** answer has occupied scholars for centuries. She explained how **syntax** and **etymology** reveal the historical migrations of people across continents, with each **dialect** carrying traces of past **discourse** and cultural exchange. A truly **eloquent** speaker, she argued, does not just achieve **fluency** but masters **nuance** — knowing precisely what tone to use to **convey** a complex idea without losing the audience. Being **bilingual** sharpens these instincts, as it trains the mind to **articulate** meaning across different systems of **rhetoric**.",
    "vi": "Giáo sư mở đầu bài giảng về **ngôn ngữ học** bằng cách hỏi liệu ngôn ngữ có định hình tư duy hay chỉ phản ánh nó — một câu hỏi có câu trả lời **mơ hồ** đã chiếm giữ các học giả trong nhiều thế kỷ. Cô giải thích cách **cú pháp** và **từ nguyên học** tiết lộ những cuộc di cư lịch sử của con người qua các lục địa, với mỗi **phương ngữ** mang dấu vết của **diễn ngôn** quá khứ và trao đổi văn hóa. Một diễn giả thực sự **hùng hồn**, cô lập luận, không chỉ đạt được **lưu loát** mà còn nắm vững **sắc thái** — biết chính xác âm điệu nào cần dùng để **truyền đạt** một ý tưởng phức tạp mà không mất khán giả. Là người **song ngữ** làm sắc nét những bản năng này vì nó luyện trí não để **diễn đạt** ý nghĩa qua các hệ thống **tu từ** khác nhau."
  },
  "scholar.sports-performance": {
    "emojis": ["🏅", "🏋️", "🎯"],
    "en": "The national **athlete** had spent four years rebuilding after injury, following a strict **training** regimen designed to restore both **stamina** and **agility**. His coach focused not just on physical **performance** but also on the mental **tactics** needed to compete at the highest level of the **championship**. In the regional **tournament**, he broke his own personal **record** in the final round, confirming he would **qualify** for the international games. What impressed the selectors most was not just his raw talent but his exceptional **sportsmanship** and the **competitive** calm he showed under pressure.",
    "vi": "**Vận động viên** quốc gia đã dành bốn năm tái xây dựng sau chấn thương, tuân theo một chế độ **tập luyện** nghiêm ngặt được thiết kế để phục hồi cả **sức bền** và **sự nhanh nhẹn**. Huấn luyện viên tập trung không chỉ vào **thành tích** thể chất mà còn vào **chiến thuật** tinh thần cần thiết để cạnh tranh ở đỉnh cao của **giải vô địch**. Trong **giải đấu** khu vực, anh phá vỡ **kỷ lục** cá nhân của chính mình ở vòng chung kết, xác nhận anh sẽ **giành quyền** tham dự các trò chơi quốc tế. Điều gây ấn tượng nhất với các giám khảo không chỉ là tài năng thuần túy mà còn là **tinh thần thể thao** xuất sắc và sự bình tĩnh **cạnh tranh** mà anh thể hiện dưới áp lực."
  },
  "scholar.history-civilization": {
    "emojis": ["🏛️", "⚔️", "📜"],
    "en": "The museum's new wing traced the rise and fall of three overlapping **civilizations** through a careful **chronology** of **artifacts** recovered from two decades of **archaeology**. The objects told a story of **conquest** and resistance — of one **empire** replacing a **feudal** **dynasty**, only to face its own internal **uprising** a century later. A towering **monument** at the center of the exhibition represented the enduring **legacy** of these societies, which shaped trade routes and legal systems still recognizable today. Scholars continue to debate whether **colonialism** accelerated the collapse of these cultures or preserved their intellectual traditions in distorted form.",
    "vi": "Cánh mới của bảo tàng truy tìm sự nổi lên và sụp đổ của ba **nền văn minh** chồng chéo nhau qua một **niên đại** cẩn thận của **hiện vật** được phục hồi từ hai thập kỷ **khảo cổ học**. Những đồ vật đó kể câu chuyện về **chinh phục** và kháng cự — về một **đế quốc** thay thế một **triều đại** **phong kiến**, chỉ để đối mặt với **cuộc nổi dậy** nội bộ của chính nó một thế kỷ sau. Một **công trình** sừng sững ở trung tâm triển lãm đại diện cho **di sản** lâu dài của những xã hội này, đã định hình các tuyến thương mại và hệ thống pháp luật vẫn có thể nhận ra ngày nay. Các học giả tiếp tục tranh luận liệu **chủ nghĩa thực dân** có đẩy nhanh sự sụp đổ của những nền văn hóa này hay bảo tồn truyền thống tri thức của họ dưới hình thức bị bóp méo."
  },
  "scholar.philosophy-ethics": {
    "emojis": ["🤔", "💭", "⚖️"],
    "en": "The seminar opened with a classic philosophical **dilemma**: is it morally justifiable to harm one person if doing so saves five others? Supporters of **utilitarianism** argued that **morality** must be measured by outcome, not intention, and that a **rational** calculation of harm and benefit is the most **pragmatic** path. Others challenged this **premise**, arguing that **doctrine** built on numbers alone risks destroying the very **integrity** and **virtue** it claims to protect. The deepest **paradox**, one philosopher noted, is that our **consciousness** allows us to understand the **implications** of our choices — yet we still struggle to agree on what is right.",
    "vi": "Hội thảo mở đầu với một **tiến thoái lưỡng nan** triết học kinh điển: có thể biện minh về mặt đạo đức khi làm hại một người nếu làm như vậy cứu được năm người khác không? Những người ủng hộ **chủ nghĩa công lợi** lập luận rằng **đạo đức** phải được đo lường bằng kết quả, không phải ý định, và rằng một phép tính **hợp lý** về tổn hại và lợi ích là con đường **thực dụng** nhất. Những người khác thách thức **tiền đề** này, lập luận rằng **học thuyết** được xây dựng trên con số thuần túy có nguy cơ phá hủy chính **tính liêm chính** và **đức hạnh** mà nó tuyên bố bảo vệ. **Nghịch lý** sâu sắc nhất, một nhà triết học lưu ý, là **ý thức** của chúng ta cho phép chúng ta hiểu **hàm ý** của những lựa chọn của mình — nhưng chúng ta vẫn phải vật lộn để đồng ý về điều gì là đúng."
  },
  "scholar.digital-society": {
    "emojis": ["📱", "🔒", "🌐"],
    "en": "A high-profile case involving a **deepfake** video of a politician went **viral** before platforms could **moderate** the content, reigniting debate over digital **privacy** and platform responsibility. Critics argued that constant **surveillance** by governments and corporations had already eroded trust, and that ordinary **netizens** had little real protection against **misinformation** campaigns. The rise of the **influencer** economy meant that **anonymous** users could spread harmful content disguised as personal endorsement. Researchers warned that the **digital divide** left millions unable to navigate a world shaped by **streaming**, **subscription** media, and algorithmically curated truth.",
    "vi": "Một vụ việc nổi tiếng liên quan đến video **deepfake** của một chính trị gia đã lan truyền **viral** trước khi các nền tảng có thể **kiểm duyệt** nội dung, châm ngòi lại cuộc tranh luận về **quyền riêng tư** kỹ thuật số và trách nhiệm của nền tảng. Các nhà phê bình lập luận rằng sự **giám sát** liên tục của các chính phủ và tập đoàn đã làm xói mòn niềm tin, và rằng **công dân mạng** bình thường có ít sự bảo vệ thực sự chống lại các chiến dịch **thông tin sai lệch**. Sự nổi lên của nền kinh tế **người có ảnh hưởng** có nghĩa là người dùng **ẩn danh** có thể lan truyền nội dung có hại được ngụy trang thành sự xác nhận cá nhân. Các nhà nghiên cứu cảnh báo rằng **khoảng cách số** khiến hàng triệu người không thể điều hướng trong thế giới được định hình bởi phương tiện **phát trực tuyến**, **đăng ký** và sự thật được thuật toán tuyển chọn."
  },
  "scholar.social-behavior": {
    "emojis": ["👥", "🔍", "📊"],
    "en": "Sociologists study how individuals navigate the unwritten rules — the **norms** and **etiquette** — that govern behavior within a **community**. **Conformity** often emerges not from genuine agreement but from **peer pressure** and the desire to maintain **status** within a social **hierarchy**. Certain topics remain **taboo**, and breaking this silence, even to challenge **prejudice**, can be socially costly in communities that have not yet built a culture of **tolerance**. **Rituals** and shared **interactions** play a powerful role in helping newcomers **assimilate** and feel belonging, but they can also reinforce the very boundaries they appear to dissolve.",
    "vi": "Các nhà xã hội học nghiên cứu cách cá nhân điều hướng những quy tắc bất thành văn — **chuẩn mực** và **lễ nghi** — chi phối hành vi trong một **cộng đồng**. **Tuân thủ** thường không xuất hiện từ sự đồng ý thực sự mà từ **áp lực đồng đẳng** và mong muốn duy trì **địa vị** trong một **hệ thống phân cấp** xã hội. Một số chủ đề vẫn còn **cấm kỵ**, và phá vỡ sự im lặng này, ngay cả để thách thức **định kiến**, có thể gây tốn kém về mặt xã hội trong các cộng đồng chưa xây dựng được văn hóa **khoan dung**. Các **nghi lễ** và **tương tác** chung đóng vai trò mạnh mẽ giúp những người mới đến **hòa nhập** và cảm thấy thuộc về, nhưng cũng có thể củng cố chính những ranh giới mà chúng có vẻ như đang xóa bỏ."
  },
  "scholar.career-workplace": {
    "emojis": ["💼", "🤝", "📈"],
    "en": "The annual **appraisal** meeting gave the young analyst a chance to **negotiate** a salary increase and make the case for a long-overdue **promotion**. Her **mentor** had coached her to present concrete evidence of her **productivity** and contributions rather than relying on goodwill alone. However, months of missed **deadlines** and rising **burnout** had affected her record, and she worried this would be raised by her manager. In the end, she received constructive **feedback**, avoided the threat of **probation**, and was offered a new **incentive** scheme that gave her reasons to stay and rebuild trust with her **colleagues**.",
    "vi": "Cuộc họp **đánh giá** hàng năm mang lại cho nhà phân tích trẻ cơ hội **đàm phán** tăng lương và trình bày lý do cho một **thăng tiến** đã chậm trễ. **Người hướng dẫn** của cô đã huấn luyện cô trình bày bằng chứng cụ thể về **năng suất** và đóng góp của mình thay vì chỉ dựa vào thiện chí. Tuy nhiên, nhiều tháng bỏ lỡ **thời hạn** và **kiệt sức** gia tăng đã ảnh hưởng đến hồ sơ của cô, và cô lo lắng điều này sẽ được người quản lý đề cập. Cuối cùng, cô nhận được **phản hồi** mang tính xây dựng, tránh được mối đe dọa về **thử việc**, và được cung cấp một kế hoạch **khuyến khích** mới mang lại cho cô lý do để ở lại và xây dựng lại niềm tin với **đồng nghiệp**."
  },
  "scholar.conflict-resolution": {
    "emojis": ["🕊️", "🤝", "⚖️"],
    "en": "What began as a minor trade **dispute** between two neighboring nations quickly began to **escalate** into something more serious as both governments refused to back down. International observers urged both sides to pursue **diplomatic** channels and enter a formal **negotiation** process before **tension** turned to open conflict. A neutral third party was brought in to facilitate **mediation**, and after weeks of difficult dialogue, the two delegations reached a fragile **consensus**. The signed **ceasefire** and framework for ongoing **arbitration** gave hope that the **alliance** between the two countries could eventually be **reconciled** into a lasting **resolution**.",
    "vi": "Những gì bắt đầu như một **tranh chấp** thương mại nhỏ giữa hai quốc gia láng giềng nhanh chóng bắt đầu **leo thang** thành điều gì đó nghiêm trọng hơn khi cả hai chính phủ từ chối nhượng bộ. Các quan sát viên quốc tế kêu gọi cả hai bên theo đuổi các kênh **ngoại giao** và tham gia vào quá trình **đàm phán** chính thức trước khi **căng thẳng** biến thành xung đột công khai. Một bên thứ ba trung lập được đưa vào để tạo điều kiện **hòa giải**, và sau nhiều tuần đối thoại khó khăn, hai phái đoàn đạt được một **sự đồng thuận** mong manh. **Ngừng bắn** được ký kết và khuôn khổ cho **trọng tài** liên tục mang lại hy vọng rằng **liên minh** giữa hai nước cuối cùng có thể được **hòa giải** thành một **giải pháp** lâu dài."
  },
  "scholar.statistics-data": {
    "emojis": ["📊", "📈", "🔬"],
    "en": "The research team collected a large **dataset** from a national **survey** on household income and began to **visualize** the results using interactive charts. The **distribution** showed a wide spread, with a significant **outlier** group earning far more than the majority — a pattern that made the **average** a misleading measure, so the team reported the **median** instead. A **regression** analysis was run to identify which variables best predicted the **trend** in spending, and the team worked carefully to **interpret** the results within a reasonable **margin** of error. The final report drew **inferences** about regional inequality that supported the call for a new government policy.",
    "vi": "Nhóm nghiên cứu thu thập một **tập dữ liệu** lớn từ một **cuộc khảo sát** quốc gia về thu nhập hộ gia đình và bắt đầu **trực quan hóa** kết quả bằng các biểu đồ tương tác. **Phân phối** cho thấy một sự phân tán rộng, với một nhóm **ngoại lệ** đáng kể kiếm được nhiều hơn đáng kể so với đa số — một mô hình khiến **trung bình** là thước đo gây hiểu nhầm, vì vậy nhóm báo cáo **trung vị** thay thế. Phân tích **hồi quy** được chạy để xác định biến nào dự đoán tốt nhất **xu hướng** trong chi tiêu, và nhóm làm việc cẩn thận để **giải thích** kết quả trong **biên độ** sai số hợp lý. Báo cáo cuối cùng rút ra **suy luận** về bất bình đẳng khu vực hỗ trợ lời kêu gọi cho một chính sách chính phủ mới."
  },
  "scholar.creativity-innovation": {
    "emojis": ["💡", "🎨", "🚀"],
    "en": "The design team used **design thinking** to tackle a problem that more traditional approaches had failed to solve. They began with a wide **brainstorm**, encouraging every team member to **generate** ideas freely — no matter how **unconventional** — before evaluating anything. Several promising **concepts** emerged, and the group chose to **collaborate** on two of them, building rough **prototypes** to test quickly with real users. The feedback allowed them to **refine** each idea rapidly, and after a bold decision to **improvise** around a major technical constraint, the team achieved a genuine **breakthrough** — an **original** solution that no one had expected.",
    "vi": "Đội thiết kế sử dụng **tư duy thiết kế** để giải quyết một vấn đề mà các cách tiếp cận truyền thống đã không thể giải quyết. Họ bắt đầu với một buổi **động não** rộng, khuyến khích mỗi thành viên **tạo ra** ý tưởng tự do — dù **không theo thông lệ** đến đâu — trước khi đánh giá bất cứ điều gì. Một số **khái niệm** đầy hứa hẹn xuất hiện, và nhóm chọn **cộng tác** trên hai trong số chúng, xây dựng **nguyên mẫu** thô để kiểm tra nhanh chóng với người dùng thực. Phản hồi cho phép họ **tinh chỉnh** mỗi ý tưởng nhanh chóng, và sau một quyết định táo bạo để **ứng biến** xung quanh một ràng buộc kỹ thuật lớn, nhóm đạt được một **đột phá** thực sự — một giải pháp **nguyên bản** mà không ai mong đợi."
  }
}

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'stories.json')
with open(data_path) as f:
    data = json.load(f)

data.update(stories)

with open(data_path, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {len(stories)} Scholar stories. Total: {len(data)} entries")
