# -*- coding: utf-8 -*-
import json, os, subprocess

TRANSFER_IDS = {
    "academic-skills", "law-justice", "science-research", "innovation-startup",
    "language-communication", "philosophy-ethics", "education-system", "food-agriculture"
}

NEW_MASTER_TOPICS_PART1 = [
  {
    "id": "constitutional-law",
    "name": "Luật Hiến Pháp",
    "emoji": "🏛️",
    "color": "indigo",
    "words": [
      {"word": "constitution", "meaning": "hiến pháp", "emoji": "📜", "class": "n",
       "examples": [{"en": "The constitution sets out the fundamental rights and duties of citizens.", "vi": "Hiến pháp quy định các quyền và nghĩa vụ cơ bản của công dân."},
                    {"en": "Any law that contradicts the constitution can be struck down by the courts.", "vi": "Bất kỳ luật nào mâu thuẫn với hiến pháp đều có thể bị tòa án bác bỏ."}]},
      {"word": "amendment", "meaning": "tu chính án, điều bổ sung", "emoji": "✏️", "class": "n",
       "examples": [{"en": "The First Amendment protects freedom of speech in the United States.", "vi": "Tu chính án thứ nhất bảo vệ quyền tự do ngôn luận ở Hoa Kỳ."},
                    {"en": "Constitutional amendments require a high level of political consensus.", "vi": "Các tu chính án hiến pháp đòi hỏi mức đồng thuận chính trị cao."}]},
      {"word": "jurisdiction", "meaning": "thẩm quyền xét xử", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "This crime falls under federal jurisdiction, not state jurisdiction.", "vi": "Tội phạm này thuộc thẩm quyền liên bang, không phải tiểu bang."},
                    {"en": "The court lacked jurisdiction to hear the international dispute.", "vi": "Tòa án không có thẩm quyền xét xử tranh chấp quốc tế đó."}]},
      {"word": "precedent", "meaning": "án lệ, tiền lệ pháp lý", "emoji": "📚", "class": "n",
       "examples": [{"en": "The judge cited a landmark precedent from 1954 to support the ruling.", "vi": "Thẩm phán dẫn một án lệ quan trọng từ năm 1954 để hỗ trợ phán quyết."},
                    {"en": "Setting a legal precedent means future courts must follow the same reasoning.", "vi": "Thiết lập án lệ có nghĩa là các tòa án trong tương lai phải tuân theo lý luận tương tự."}]},
      {"word": "civil liberties", "meaning": "quyền tự do dân sự", "emoji": "🕊️", "class": "phrase",
       "examples": [{"en": "Civil liberties such as free speech and the right to a fair trial are protected by law.", "vi": "Các quyền tự do dân sự như tự do ngôn luận và quyền được xét xử công bằng được luật pháp bảo vệ."},
                    {"en": "Surveillance technology has raised concerns about civil liberties.", "vi": "Công nghệ giám sát đã làm dấy lên lo ngại về quyền tự do dân sự."}]},
      {"word": "due process", "meaning": "thủ tục pháp lý đúng đắn", "emoji": "🔨", "class": "phrase",
       "examples": [{"en": "Every accused person is entitled to due process under the law.", "vi": "Mỗi bị cáo đều có quyền được hưởng thủ tục pháp lý đúng đắn theo luật."},
                    {"en": "Denying due process is a serious violation of constitutional rights.", "vi": "Từ chối thủ tục pháp lý đúng đắn là vi phạm nghiêm trọng quyền hiến định."}]},
      {"word": "separation of powers", "meaning": "phân chia quyền lực", "emoji": "🏛️", "class": "phrase",
       "examples": [{"en": "The separation of powers prevents any single branch from dominating the government.", "vi": "Phân chia quyền lực ngăn bất kỳ nhánh nào thống trị chính phủ."},
                    {"en": "Democratic systems rely on the separation of powers to avoid tyranny.", "vi": "Các hệ thống dân chủ dựa vào phân chia quyền lực để tránh chuyên chế."}]},
      {"word": "judicial review", "meaning": "kiểm tra tư pháp", "emoji": "🔍", "class": "phrase",
       "examples": [{"en": "Judicial review allows courts to determine whether laws comply with the constitution.", "vi": "Kiểm tra tư pháp cho phép tòa án xác định liệu luật có tuân thủ hiến pháp hay không."},
                    {"en": "The Supreme Court used judicial review to overturn the disputed legislation.", "vi": "Tòa án Tối cao sử dụng kiểm tra tư pháp để lật ngược luật bị tranh cãi."}]},
      {"word": "rule of law", "meaning": "nguyên tắc pháp quyền", "emoji": "⚖️", "class": "phrase",
       "examples": [{"en": "The rule of law ensures that no individual or institution is above the law.", "vi": "Nguyên tắc pháp quyền đảm bảo không cá nhân hay thể chế nào đứng trên pháp luật."},
                    {"en": "Weak rule of law undermines economic development and investor confidence.", "vi": "Pháp quyền yếu kém làm suy yếu phát triển kinh tế và niềm tin của nhà đầu tư."}]},
      {"word": "fundamental rights", "meaning": "quyền cơ bản", "emoji": "🌟", "class": "phrase",
       "examples": [{"en": "Access to education and healthcare are recognised as fundamental rights.", "vi": "Tiếp cận giáo dục và y tế được công nhận là các quyền cơ bản."},
                    {"en": "Governments have an obligation to protect the fundamental rights of all citizens.", "vi": "Chính phủ có nghĩa vụ bảo vệ các quyền cơ bản của tất cả công dân."}]},
      {"word": "accountability", "meaning": "trách nhiệm giải trình", "emoji": "📋", "class": "n",
       "examples": [{"en": "Democratic accountability requires elected officials to answer to the public.", "vi": "Trách nhiệm giải trình dân chủ đòi hỏi các quan chức dân cử phải trả lời trước công chúng."},
                    {"en": "Lack of accountability enables corruption to thrive unchecked.", "vi": "Thiếu trách nhiệm giải trình cho phép tham nhũng phát triển không bị kiểm soát."}]},
      {"word": "democratic", "meaning": "dân chủ", "emoji": "🗳️", "class": "adj",
       "examples": [{"en": "A democratic system depends on free and fair elections.", "vi": "Một hệ thống dân chủ phụ thuộc vào các cuộc bầu cử tự do và công bằng."},
                    {"en": "Democratic values include equality, freedom, and respect for minority rights.", "vi": "Các giá trị dân chủ bao gồm bình đẳng, tự do và tôn trọng quyền của thiểu số."}]},
      {"word": "legislature", "meaning": "cơ quan lập pháp", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "The legislature passed the new environmental bill after months of debate.", "vi": "Cơ quan lập pháp thông qua dự luật môi trường mới sau nhiều tháng tranh luận."},
                    {"en": "In a democracy, the legislature represents the will of the people.", "vi": "Trong một nền dân chủ, cơ quan lập pháp đại diện cho ý chí của người dân."}]}
    ]
  },
  {
    "id": "environmental-governance",
    "name": "Quản Trị Môi Trường",
    "emoji": "🌍",
    "color": "emerald",
    "words": [
      {"word": "ratify", "meaning": "phê chuẩn", "emoji": "✅", "class": "v",
       "examples": [{"en": "Most nations ratified the Paris Agreement to commit to reducing carbon emissions.", "vi": "Hầu hết các quốc gia đã phê chuẩn Hiệp định Paris để cam kết giảm phát thải carbon."},
                    {"en": "A treaty only becomes legally binding after enough countries ratify it.", "vi": "Một hiệp ước chỉ có hiệu lực ràng buộc pháp lý sau khi đủ số quốc gia phê chuẩn."}]},
      {"word": "carbon tax", "meaning": "thuế carbon", "emoji": "💨", "class": "n",
       "examples": [{"en": "A carbon tax makes polluting industries pay for the environmental damage they cause.", "vi": "Thuế carbon buộc các ngành gây ô nhiễm phải trả tiền cho thiệt hại môi trường họ gây ra."},
                    {"en": "Economists debate whether a carbon tax is the most effective climate policy.", "vi": "Các nhà kinh tế tranh luận liệu thuế carbon có phải là chính sách khí hậu hiệu quả nhất không."}]},
      {"word": "mitigation", "meaning": "giảm nhẹ", "emoji": "📉", "class": "n",
       "examples": [{"en": "Climate mitigation strategies include switching to renewable energy sources.", "vi": "Các chiến lược giảm nhẹ biến đổi khí hậu bao gồm chuyển sang nguồn năng lượng tái tạo."},
                    {"en": "Mitigation efforts must be matched by significant political will.", "vi": "Các nỗ lực giảm nhẹ phải đi kèm với ý chí chính trị mạnh mẽ."}]},
      {"word": "adaptation", "meaning": "thích ứng", "emoji": "🔄", "class": "n",
       "examples": [{"en": "Coastal communities require adaptation strategies to cope with rising sea levels.", "vi": "Các cộng đồng ven biển cần các chiến lược thích ứng để đối phó với nước biển dâng."},
                    {"en": "Both mitigation and adaptation are necessary to address climate change.", "vi": "Cả giảm nhẹ và thích ứng đều cần thiết để giải quyết biến đổi khí hậu."}]},
      {"word": "compliance", "meaning": "tuân thủ", "emoji": "📏", "class": "n",
       "examples": [{"en": "Companies face heavy fines for non-compliance with environmental regulations.", "vi": "Các công ty đối mặt với khoản phạt nặng vì không tuân thủ quy định môi trường."},
                    {"en": "Compliance monitoring ensures that agreed targets are actually being met.", "vi": "Giám sát tuân thủ đảm bảo rằng các mục tiêu đã thống nhất đang thực sự được đáp ứng."}]},
      {"word": "enforcement", "meaning": "thực thi", "emoji": "🛡️", "class": "n",
       "examples": [{"en": "Effective enforcement of environmental laws requires dedicated inspectors and penalties.", "vi": "Thực thi hiệu quả luật môi trường đòi hỏi thanh tra chuyên trách và các hình phạt."},
                    {"en": "Without enforcement mechanisms, international agreements remain largely symbolic.", "vi": "Không có cơ chế thực thi, các thỏa thuận quốc tế phần lớn vẫn mang tính biểu tượng."}]},
      {"word": "net-zero", "meaning": "phát thải ròng bằng không", "emoji": "🌿", "class": "adj",
       "examples": [{"en": "The government pledged to achieve net-zero emissions by 2050.", "vi": "Chính phủ cam kết đạt phát thải ròng bằng không vào năm 2050."},
                    {"en": "Reaching net-zero requires both reducing emissions and offsetting those that remain.", "vi": "Đạt phát thải ròng bằng không đòi hỏi cả giảm phát thải lẫn bù đắp những gì còn lại."}]},
      {"word": "biodiversity", "meaning": "đa dạng sinh học", "emoji": "🦋", "class": "n",
       "examples": [{"en": "Loss of biodiversity threatens the stability of ecosystems we depend on.", "vi": "Mất đa dạng sinh học đe dọa sự ổn định của các hệ sinh thái mà chúng ta phụ thuộc vào."},
                    {"en": "Protected areas are essential for conserving biodiversity.", "vi": "Các khu vực được bảo vệ là điều cần thiết để bảo tồn đa dạng sinh học."}]},
      {"word": "transition", "meaning": "chuyển đổi (năng lượng)", "emoji": "⚡", "class": "n",
       "examples": [{"en": "The transition from fossil fuels to renewables will reshape the global economy.", "vi": "Sự chuyển đổi từ nhiên liệu hóa thạch sang năng lượng tái tạo sẽ định hình lại nền kinh tế toàn cầu."},
                    {"en": "A just energy transition must protect workers in fossil fuel industries.", "vi": "Một sự chuyển đổi năng lượng công bằng phải bảo vệ người lao động trong các ngành nhiên liệu hóa thạch."}]},
      {"word": "legislation", "meaning": "luật pháp, lập pháp", "emoji": "📄", "class": "n",
       "examples": [{"en": "New legislation was introduced to reduce single-use plastic packaging.", "vi": "Luật mới được đưa ra để giảm bao bì nhựa dùng một lần."},
                    {"en": "Stronger legislation is needed to hold corporations accountable for pollution.", "vi": "Cần có luật pháp mạnh mẽ hơn để buộc các tập đoàn chịu trách nhiệm về ô nhiễm."}]},
      {"word": "protocol", "meaning": "nghị định thư", "emoji": "📜", "class": "n",
       "examples": [{"en": "The Kyoto Protocol was the first major international agreement to limit greenhouse gases.", "vi": "Nghị định thư Kyoto là thỏa thuận quốc tế lớn đầu tiên hạn chế khí nhà kính."},
                    {"en": "Nations that fail to implement the protocol face diplomatic pressure.", "vi": "Các quốc gia không thực hiện nghị định thư sẽ đối mặt với áp lực ngoại giao."}]},
      {"word": "sustainability", "meaning": "tính bền vững", "emoji": "♻️", "class": "n",
       "examples": [{"en": "Long-term sustainability requires balancing economic growth with environmental protection.", "vi": "Tính bền vững lâu dài đòi hỏi cân bằng tăng trưởng kinh tế với bảo vệ môi trường."},
                    {"en": "Sustainability has become central to corporate strategy worldwide.", "vi": "Tính bền vững đã trở thành trọng tâm của chiến lược doanh nghiệp trên toàn thế giới."}]},
      {"word": "offset", "meaning": "bù đắp khí thải", "emoji": "🌲", "class": "v",
       "examples": [{"en": "Airlines allow passengers to offset their carbon emissions by funding tree planting.", "vi": "Các hãng hàng không cho phép hành khách bù đắp khí thải carbon bằng cách tài trợ trồng cây."},
                    {"en": "Carbon offsetting is controversial because it does not reduce emissions at the source.", "vi": "Bù đắp carbon gây tranh cãi vì nó không giảm phát thải tại nguồn."}]}
    ]
  },
  {
    "id": "political-philosophy",
    "name": "Triết Học Chính Trị",
    "emoji": "⚖️",
    "color": "violet",
    "words": [
      {"word": "democracy", "meaning": "dân chủ", "emoji": "🗳️", "class": "n",
       "examples": [{"en": "Liberal democracy combines free elections with guaranteed individual rights.", "vi": "Dân chủ tự do kết hợp bầu cử tự do với các quyền cá nhân được đảm bảo."},
                    {"en": "Democracy requires an informed and engaged citizenry to function well.", "vi": "Dân chủ cần một công dân hiểu biết và tích cực tham gia để hoạt động tốt."}]},
      {"word": "authoritarianism", "meaning": "chủ nghĩa độc đoán", "emoji": "👊", "class": "n",
       "examples": [{"en": "Authoritarianism suppresses political opposition and limits civil freedoms.", "vi": "Chủ nghĩa độc đoán đàn áp phe đối lập chính trị và hạn chế tự do dân sự."},
                    {"en": "Many scholars debate whether authoritarianism can deliver long-term stability.", "vi": "Nhiều học giả tranh luận liệu chủ nghĩa độc đoán có thể mang lại ổn định lâu dài hay không."}]},
      {"word": "legitimacy", "meaning": "tính hợp pháp (chính trị)", "emoji": "✅", "class": "n",
       "examples": [{"en": "A government derives its legitimacy from the consent of the governed.", "vi": "Chính phủ có được tính hợp pháp từ sự đồng ý của người bị cai trị."},
                    {"en": "Corruption erodes public trust and undermines the legitimacy of institutions.", "vi": "Tham nhũng làm xói mòn niềm tin của công chúng và phá hoại tính hợp pháp của các thể chế."}]},
      {"word": "civil society", "meaning": "xã hội dân sự", "emoji": "🤝", "class": "n",
       "examples": [{"en": "A strong civil society acts as a check on government power.", "vi": "Xã hội dân sự mạnh đóng vai trò kiểm soát quyền lực chính phủ."},
                    {"en": "NGOs and community organisations are essential components of civil society.", "vi": "Các tổ chức phi chính phủ và cộng đồng là thành phần cốt lõi của xã hội dân sự."}]},
      {"word": "ideology", "meaning": "hệ tư tưởng", "emoji": "💡", "class": "n",
       "examples": [{"en": "Political parties often differ in ideology regarding the role of the state.", "vi": "Các đảng phái chính trị thường khác nhau về hệ tư tưởng liên quan đến vai trò của nhà nước."},
                    {"en": "Ideology shapes how individuals interpret social and political events.", "vi": "Hệ tư tưởng định hình cách cá nhân diễn giải các sự kiện xã hội và chính trị."}]},
      {"word": "populism", "meaning": "chủ nghĩa dân túy", "emoji": "📣", "class": "n",
       "examples": [{"en": "Populism thrives when citizens feel excluded from the political mainstream.", "vi": "Chủ nghĩa dân túy phát triển khi công dân cảm thấy bị loại khỏi dòng chính trị chính."},
                    {"en": "Critics argue that populism simplifies complex issues to gain electoral support.", "vi": "Các nhà phê bình cho rằng chủ nghĩa dân túy đơn giản hóa các vấn đề phức tạp để giành hỗ trợ bầu cử."}]},
      {"word": "governance", "meaning": "quản trị", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Good governance requires transparency, accountability, and public participation.", "vi": "Quản trị tốt đòi hỏi minh bạch, trách nhiệm giải trình và sự tham gia của công chúng."},
                    {"en": "Poor governance is a major obstacle to economic development in many regions.", "vi": "Quản trị kém là trở ngại lớn cho phát triển kinh tế ở nhiều khu vực."}]},
      {"word": "pluralism", "meaning": "chủ nghĩa đa nguyên", "emoji": "🌈", "class": "n",
       "examples": [{"en": "Political pluralism allows competing ideas and parties to coexist peacefully.", "vi": "Chủ nghĩa đa nguyên chính trị cho phép các ý tưởng và đảng phái cạnh tranh cùng tồn tại hòa bình."},
                    {"en": "Pluralism is considered a cornerstone of liberal democratic theory.", "vi": "Chủ nghĩa đa nguyên được coi là nền tảng của lý thuyết dân chủ tự do."}]},
      {"word": "reform", "meaning": "cải cách", "emoji": "🔧", "class": "n",
       "examples": [{"en": "Electoral reform is needed to make the voting system more representative.", "vi": "Cải cách bầu cử là cần thiết để làm cho hệ thống bỏ phiếu có tính đại diện hơn."},
                    {"en": "Structural reforms often face resistance from those who benefit from the status quo.", "vi": "Các cải cách cơ cấu thường gặp sự kháng cự từ những người hưởng lợi từ hiện trạng."}]},
      {"word": "power", "meaning": "quyền lực", "emoji": "💪", "class": "n",
       "examples": [{"en": "Political power must be distributed across institutions to prevent abuse.", "vi": "Quyền lực chính trị phải được phân phối giữa các thể chế để ngăn chặn lạm dụng."},
                    {"en": "The transfer of power through elections is a sign of democratic maturity.", "vi": "Chuyển giao quyền lực qua bầu cử là dấu hiệu của sự trưởng thành dân chủ."}]},
      {"word": "equality", "meaning": "bình đẳng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Political equality means every citizen has the same right to vote.", "vi": "Bình đẳng chính trị có nghĩa là mỗi công dân có quyền bỏ phiếu như nhau."},
                    {"en": "True equality goes beyond legal rights to include access and opportunity.", "vi": "Bình đẳng thực sự vượt ra ngoài quyền pháp lý để bao gồm tiếp cận và cơ hội."}]}
    ]
  },
  {
    "id": "public-policy",
    "name": "Chính Sách Công",
    "emoji": "📋",
    "color": "blue",
    "words": [
      {"word": "policy", "meaning": "chính sách", "emoji": "📄", "class": "n",
       "examples": [{"en": "Government policy on housing needs to address both supply and affordability.", "vi": "Chính sách nhà ở của chính phủ cần giải quyết cả vấn đề nguồn cung và khả năng chi trả."},
                    {"en": "Foreign policy reflects a country's values and strategic interests.", "vi": "Chính sách đối ngoại phản ánh các giá trị và lợi ích chiến lược của một quốc gia."}]},
      {"word": "evidence-based", "meaning": "dựa trên bằng chứng", "emoji": "🔬", "class": "adj",
       "examples": [{"en": "Evidence-based policy uses research and data rather than ideology or intuition.", "vi": "Chính sách dựa trên bằng chứng sử dụng nghiên cứu và dữ liệu thay vì hệ tư tưởng hay trực giác."},
                    {"en": "Health authorities advocate for evidence-based approaches to public health decisions.", "vi": "Cơ quan y tế vận động cho các cách tiếp cận dựa trên bằng chứng trong các quyết định y tế công cộng."}]},
      {"word": "implementation", "meaning": "thực thi chính sách", "emoji": "⚙️", "class": "n",
       "examples": [{"en": "A well-designed policy can fail at the implementation stage without sufficient resources.", "vi": "Một chính sách được thiết kế tốt có thể thất bại ở giai đoạn thực thi nếu thiếu nguồn lực."},
                    {"en": "Effective implementation requires coordination across multiple government agencies.", "vi": "Thực thi hiệu quả đòi hỏi phối hợp giữa nhiều cơ quan chính phủ."}]},
      {"word": "welfare", "meaning": "phúc lợi (xã hội)", "emoji": "🏥", "class": "n",
       "examples": [{"en": "The welfare state provides citizens with healthcare, education, and unemployment benefits.", "vi": "Nhà nước phúc lợi cung cấp cho công dân y tế, giáo dục và trợ cấp thất nghiệp."},
                    {"en": "Debates about welfare often centre on the balance between support and incentives to work.", "vi": "Các cuộc tranh luận về phúc lợi thường tập trung vào sự cân bằng giữa hỗ trợ và động lực làm việc."}]},
      {"word": "public service", "meaning": "dịch vụ công", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Reliable public services like transport and healthcare are essential for quality of life.", "vi": "Các dịch vụ công đáng tin cậy như giao thông và y tế là thiết yếu cho chất lượng cuộc sống."},
                    {"en": "Public service reforms aim to improve efficiency without sacrificing quality.", "vi": "Các cải cách dịch vụ công nhằm cải thiện hiệu quả mà không hy sinh chất lượng."}]},
      {"word": "transparency", "meaning": "minh bạch", "emoji": "🔍", "class": "n",
       "examples": [{"en": "Transparency in government spending helps prevent corruption.", "vi": "Minh bạch trong chi tiêu chính phủ giúp ngăn chặn tham nhũng."},
                    {"en": "Citizens demand greater transparency from elected officials.", "vi": "Công dân đòi hỏi sự minh bạch cao hơn từ các quan chức dân cử."}]},
      {"word": "stakeholder", "meaning": "các bên liên quan", "emoji": "👥", "class": "n",
       "examples": [{"en": "Effective policy requires consulting all relevant stakeholders before decisions are made.", "vi": "Chính sách hiệu quả đòi hỏi tham khảo ý kiến tất cả các bên liên quan trước khi ra quyết định."},
                    {"en": "Stakeholder engagement ensures that policy reflects diverse community needs.", "vi": "Sự tham gia của các bên liên quan đảm bảo chính sách phản ánh các nhu cầu cộng đồng đa dạng."}]},
      {"word": "outcome", "meaning": "kết quả", "emoji": "🎯", "class": "n",
       "examples": [{"en": "Policy outcomes must be measured regularly to assess whether goals are being achieved.", "vi": "Kết quả chính sách phải được đo lường thường xuyên để đánh giá liệu mục tiêu có đạt được không."},
                    {"en": "Better educational outcomes are linked to increased public investment in schools.", "vi": "Kết quả giáo dục tốt hơn liên quan đến đầu tư công tăng vào trường học."}]},
      {"word": "regulation", "meaning": "quy định", "emoji": "📏", "class": "n",
       "examples": [{"en": "Financial regulation is designed to prevent the kinds of crises seen in 2008.", "vi": "Quy định tài chính được thiết kế để ngăn chặn các loại khủng hoảng như năm 2008."},
                    {"en": "Excessive regulation can stifle innovation and economic growth.", "vi": "Quy định quá mức có thể bóp nghẹt đổi mới và tăng trưởng kinh tế."}]},
      {"word": "access", "meaning": "tiếp cận", "emoji": "🚪", "class": "n",
       "examples": [{"en": "Equal access to quality education is a key goal of social policy.", "vi": "Tiếp cận bình đẳng với giáo dục chất lượng là mục tiêu chính của chính sách xã hội."},
                    {"en": "Barriers to healthcare access disproportionately affect low-income communities.", "vi": "Rào cản tiếp cận y tế ảnh hưởng không cân xứng đến cộng đồng thu nhập thấp."}]},
      {"word": "social policy", "meaning": "chính sách xã hội", "emoji": "🤝", "class": "phrase",
       "examples": [{"en": "Social policy addresses issues like poverty, housing, and family support.", "vi": "Chính sách xã hội giải quyết các vấn đề như nghèo đói, nhà ở và hỗ trợ gia đình."},
                    {"en": "Effective social policy can reduce inequality and improve social mobility.", "vi": "Chính sách xã hội hiệu quả có thể giảm bất bình đẳng và cải thiện tính cơ động xã hội."}]}
    ]
  },
  {
    "id": "academic-discourse",
    "name": "Diễn Ngôn Học Thuật",
    "emoji": "📚",
    "color": "slate",
    "words": [
      {"word": "thesis", "meaning": "luận văn, luận điểm", "emoji": "📝", "class": "n",
       "examples": [{"en": "Her doctoral thesis examined the relationship between poverty and educational attainment.", "vi": "Luận án tiến sĩ của cô nghiên cứu mối quan hệ giữa nghèo đói và thành tích học tập."},
                    {"en": "A strong thesis statement clearly outlines the main argument of an essay.", "vi": "Một luận điểm mạnh mẽ phác thảo rõ ràng lập luận chính của bài luận."}]},
      {"word": "peer review", "meaning": "phản biện học thuật", "emoji": "🔍", "class": "n",
       "examples": [{"en": "Peer review ensures that published research meets rigorous academic standards.", "vi": "Phản biện học thuật đảm bảo nghiên cứu được công bố đáp ứng các tiêu chuẩn học thuật nghiêm ngặt."},
                    {"en": "The peer review process can take months before an article is accepted.", "vi": "Quá trình phản biện học thuật có thể mất nhiều tháng trước khi bài báo được chấp nhận."}]},
      {"word": "citation", "meaning": "trích dẫn", "emoji": "📌", "class": "n",
       "examples": [{"en": "Every claim in academic writing must be supported by accurate citations.", "vi": "Mọi tuyên bố trong văn bản học thuật phải được hỗ trợ bởi các trích dẫn chính xác."},
                    {"en": "Improper citation of sources is a form of academic dishonesty.", "vi": "Trích dẫn nguồn không đúng cách là một hình thức vi phạm học thuật."}]},
      {"word": "methodology", "meaning": "phương pháp luận", "emoji": "🔬", "class": "n",
       "examples": [{"en": "The research methodology section explains how data was collected and analysed.", "vi": "Phần phương pháp luận nghiên cứu giải thích cách thu thập và phân tích dữ liệu."},
                    {"en": "Choosing an appropriate methodology is critical to the validity of your findings.", "vi": "Chọn phương pháp luận phù hợp là quan trọng để đảm bảo tính hợp lệ của kết quả."}]},
      {"word": "plagiarism", "meaning": "đạo văn", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "Plagiarism involves presenting another person's work as your own without credit.", "vi": "Đạo văn là trình bày tác phẩm của người khác như của mình mà không ghi công."},
                    {"en": "Universities use software to detect plagiarism in submitted essays.", "vi": "Các trường đại học sử dụng phần mềm để phát hiện đạo văn trong các bài luận nộp."}]},
      {"word": "academic integrity", "meaning": "trung thực học thuật", "emoji": "🎓", "class": "phrase",
       "examples": [{"en": "Academic integrity means being honest in all aspects of scholarly work.", "vi": "Trung thực học thuật có nghĩa là trung thực trong mọi khía cạnh của công việc học thuật."},
                    {"en": "Violations of academic integrity can result in expulsion from university.", "vi": "Vi phạm trung thực học thuật có thể dẫn đến bị đuổi học."}]},
      {"word": "critical thinking", "meaning": "tư duy phản biện", "emoji": "🧠", "class": "phrase",
       "examples": [{"en": "Critical thinking requires evaluating evidence before accepting a conclusion.", "vi": "Tư duy phản biện đòi hỏi đánh giá bằng chứng trước khi chấp nhận kết luận."},
                    {"en": "Universities aim to develop critical thinking as a core academic skill.", "vi": "Các trường đại học nhằm phát triển tư duy phản biện như một kỹ năng học thuật cốt lõi."}]},
      {"word": "publication", "meaning": "ấn phẩm, công bố nghiên cứu", "emoji": "📰", "class": "n",
       "examples": [{"en": "Publication in a high-impact journal advances a researcher's career significantly.", "vi": "Công bố trên tạp chí có ảnh hưởng lớn thúc đẩy đáng kể sự nghiệp của nhà nghiên cứu."},
                    {"en": "Open-access publications allow anyone to read research without a subscription.", "vi": "Các ấn phẩm mở cho phép bất kỳ ai đọc nghiên cứu mà không cần đăng ký."}]},
      {"word": "seminar", "meaning": "hội thảo học thuật", "emoji": "🎤", "class": "n",
       "examples": [{"en": "The weekly seminar gives students a chance to discuss their research with peers.", "vi": "Hội thảo hàng tuần cho sinh viên cơ hội thảo luận nghiên cứu với bạn đồng nghiệp."},
                    {"en": "Attending seminars is one of the best ways to stay current in your field.", "vi": "Tham dự hội thảo là một trong những cách tốt nhất để cập nhật trong lĩnh vực của bạn."}]},
      {"word": "collaboration", "meaning": "hợp tác (học thuật)", "emoji": "🤝", "class": "n",
       "examples": [{"en": "International collaboration in research leads to more impactful discoveries.", "vi": "Hợp tác quốc tế trong nghiên cứu dẫn đến các khám phá có tác động lớn hơn."},
                    {"en": "The paper was the result of a collaboration between three universities.", "vi": "Bài báo là kết quả của sự hợp tác giữa ba trường đại học."}]},
      {"word": "evaluate", "meaning": "đánh giá", "emoji": "📊", "class": "v",
       "examples": [{"en": "Researchers must evaluate sources critically before using them in academic work.", "vi": "Nhà nghiên cứu phải đánh giá các nguồn một cách phê bình trước khi sử dụng trong công việc học thuật."},
                    {"en": "The committee will evaluate all submissions and select the most rigorous studies.", "vi": "Ủy ban sẽ đánh giá tất cả các bài nộp và chọn những nghiên cứu nghiêm ngặt nhất."}]}
    ]
  },
  {
    "id": "geopolitics",
    "name": "Địa Chính Trị",
    "emoji": "🌐",
    "color": "red",
    "words": [
      {"word": "sovereignty", "meaning": "chủ quyền", "emoji": "🏳️", "class": "n",
       "examples": [{"en": "Territorial sovereignty is a cornerstone of international law.", "vi": "Chủ quyền lãnh thổ là nền tảng của luật quốc tế."},
                    {"en": "The debate over sovereignty complicates efforts at regional integration.", "vi": "Tranh cãi về chủ quyền làm phức tạp các nỗ lực hội nhập khu vực."}]},
      {"word": "sanction", "meaning": "lệnh trừng phạt", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Economic sanctions were imposed to pressure the government to change its policies.", "vi": "Các lệnh trừng phạt kinh tế được áp đặt để gây áp lực buộc chính phủ thay đổi chính sách."},
                    {"en": "Sanctions can harm ordinary citizens as much as political leaders.", "vi": "Các lệnh trừng phạt có thể gây hại cho người dân thường nhiều như các nhà lãnh đạo chính trị."}]},
      {"word": "alliance", "meaning": "liên minh", "emoji": "🤝", "class": "n",
       "examples": [{"en": "NATO is a military alliance formed to provide collective security.", "vi": "NATO là liên minh quân sự được thành lập để cung cấp an ninh tập thể."},
                    {"en": "Geopolitical alliances shift as national interests evolve over time.", "vi": "Các liên minh địa chính trị thay đổi khi lợi ích quốc gia phát triển theo thời gian."}]},
      {"word": "intervention", "meaning": "can thiệp", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Military intervention in another country's affairs is highly controversial.", "vi": "Can thiệp quân sự vào công việc nội bộ của quốc gia khác gây tranh cãi rất lớn."},
                    {"en": "Humanitarian intervention is sometimes justified when governments commit atrocities.", "vi": "Can thiệp nhân đạo đôi khi được biện minh khi chính phủ thực hiện tội ác."}]},
      {"word": "nationalism", "meaning": "chủ nghĩa dân tộc", "emoji": "🏴", "class": "n",
       "examples": [{"en": "Nationalism can unite a country but also fuel conflicts with neighbouring states.", "vi": "Chủ nghĩa dân tộc có thể đoàn kết một quốc gia nhưng cũng có thể gây ra xung đột với các nước láng giềng."},
                    {"en": "The rise of economic nationalism has challenged the global free trade order.", "vi": "Sự trỗi dậy của chủ nghĩa dân tộc kinh tế đã thách thức trật tự thương mại tự do toàn cầu."}]},
      {"word": "multilateral", "meaning": "đa phương", "emoji": "🌐", "class": "adj",
       "examples": [{"en": "Multilateral agreements require consensus among many nations, making them difficult to reach.", "vi": "Các thỏa thuận đa phương đòi hỏi sự đồng thuận giữa nhiều quốc gia, khiến chúng khó đạt được."},
                    {"en": "The UN is the primary multilateral institution for addressing global challenges.", "vi": "Liên Hợp Quốc là thể chế đa phương chính để giải quyết các thách thức toàn cầu."}]},
      {"word": "treaty", "meaning": "hiệp ước", "emoji": "📜", "class": "n",
       "examples": [{"en": "The treaty ended decades of conflict between the two neighbouring countries.", "vi": "Hiệp ước kết thúc nhiều thập kỷ xung đột giữa hai quốc gia láng giềng."},
                    {"en": "Withdrawing from an international treaty damages a nation's diplomatic credibility.", "vi": "Rút khỏi hiệp ước quốc tế làm tổn hại uy tín ngoại giao của một quốc gia."}]},
      {"word": "negotiation", "meaning": "đàm phán", "emoji": "💬", "class": "n",
       "examples": [{"en": "Diplomatic negotiations are often the only way to avoid military conflict.", "vi": "Đàm phán ngoại giao thường là cách duy nhất để tránh xung đột quân sự."},
                    {"en": "Trade negotiations between major powers can take years to conclude.", "vi": "Đàm phán thương mại giữa các cường quốc lớn có thể mất nhiều năm để kết thúc."}]},
      {"word": "tension", "meaning": "căng thẳng", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Tensions between the two powers escalated after the border incident.", "vi": "Căng thẳng giữa hai cường quốc leo thang sau vụ việc biên giới."},
                    {"en": "Diplomatic channels are used to manage and de-escalate geopolitical tension.", "vi": "Các kênh ngoại giao được sử dụng để quản lý và hạ leo thang căng thẳng địa chính trị."}]},
      {"word": "stability", "meaning": "ổn định", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Regional stability depends on cooperation between neighbouring governments.", "vi": "Sự ổn định khu vực phụ thuộc vào sự hợp tác giữa các chính phủ láng giềng."},
                    {"en": "Economic stability is a prerequisite for sustained social development.", "vi": "Ổn định kinh tế là điều kiện tiên quyết cho phát triển xã hội bền vững."}]},
      {"word": "diplomacy", "meaning": "ngoại giao", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Skilled diplomacy can prevent minor disputes from escalating into crises.", "vi": "Ngoại giao khéo léo có thể ngăn chặn các tranh chấp nhỏ leo thang thành khủng hoảng."},
                    {"en": "Public diplomacy uses cultural exchange to improve a nation's image abroad.", "vi": "Ngoại giao công chúng sử dụng trao đổi văn hóa để cải thiện hình ảnh của quốc gia ở nước ngoài."}]}
    ]
  },
  {
    "id": "macroeconomics",
    "name": "Kinh Tế Vĩ Mô",
    "emoji": "📈",
    "color": "amber",
    "words": [
      {"word": "recession", "meaning": "suy thoái kinh tế", "emoji": "📉", "class": "n",
       "examples": [{"en": "The global recession of 2008 was triggered by the collapse of the housing market.", "vi": "Suy thoái kinh tế toàn cầu năm 2008 được kích hoạt bởi sự sụp đổ của thị trường nhà ở."},
                    {"en": "During a recession, unemployment rises and consumer spending falls sharply.", "vi": "Trong thời kỳ suy thoái, thất nghiệp tăng và chi tiêu người tiêu dùng giảm mạnh."}]},
      {"word": "deficit", "meaning": "thâm hụt", "emoji": "🔻", "class": "n",
       "examples": [{"en": "Running a large budget deficit can lead to higher government debt over time.", "vi": "Duy trì thâm hụt ngân sách lớn có thể dẫn đến nợ chính phủ cao hơn theo thời gian."},
                    {"en": "The trade deficit widened as imports grew faster than exports.", "vi": "Thâm hụt thương mại tăng khi nhập khẩu tăng nhanh hơn xuất khẩu."}]},
      {"word": "austerity", "meaning": "chính sách thắt lưng buộc bụng", "emoji": "✂️", "class": "n",
       "examples": [{"en": "Austerity measures introduced after the crisis led to deep cuts in public services.", "vi": "Các biện pháp thắt lưng buộc bụng được đưa ra sau khủng hoảng dẫn đến cắt giảm sâu dịch vụ công."},
                    {"en": "Critics argue that austerity slows recovery by reducing demand in the economy.", "vi": "Các nhà phê bình cho rằng thắt lưng buộc bụng làm chậm phục hồi bằng cách giảm cầu trong nền kinh tế."}]},
      {"word": "inflation", "meaning": "lạm phát", "emoji": "💸", "class": "n",
       "examples": [{"en": "High inflation reduces the purchasing power of wages and savings.", "vi": "Lạm phát cao làm giảm sức mua của tiền lương và tiết kiệm."},
                    {"en": "Central banks raise interest rates to bring inflation under control.", "vi": "Các ngân hàng trung ương tăng lãi suất để kiểm soát lạm phát."}]},
      {"word": "fiscal policy", "meaning": "chính sách tài khóa", "emoji": "💼", "class": "phrase",
       "examples": [{"en": "Expansionary fiscal policy involves increasing government spending to stimulate growth.", "vi": "Chính sách tài khóa mở rộng bao gồm tăng chi tiêu chính phủ để kích thích tăng trưởng."},
                    {"en": "Fiscal policy and monetary policy must work together to manage the economy.", "vi": "Chính sách tài khóa và chính sách tiền tệ phải phối hợp để quản lý nền kinh tế."}]},
      {"word": "monetary policy", "meaning": "chính sách tiền tệ", "emoji": "🏦", "class": "phrase",
       "examples": [{"en": "The central bank uses monetary policy tools like interest rates to manage inflation.", "vi": "Ngân hàng trung ương sử dụng các công cụ chính sách tiền tệ như lãi suất để quản lý lạm phát."},
                    {"en": "Quantitative easing is an unconventional monetary policy used during crises.", "vi": "Nới lỏng định lượng là chính sách tiền tệ phi thông thường được dùng trong khủng hoảng."}]},
      {"word": "public debt", "meaning": "nợ công", "emoji": "📊", "class": "n",
       "examples": [{"en": "High levels of public debt can limit a government's ability to respond to future crises.", "vi": "Mức nợ công cao có thể hạn chế khả năng của chính phủ đối phó với các cuộc khủng hoảng tương lai."},
                    {"en": "Public debt is not always harmful if the borrowed money is invested productively.", "vi": "Nợ công không phải lúc nào cũng có hại nếu tiền vay được đầu tư hiệu quả."}]},
      {"word": "market failure", "meaning": "thất bại thị trường", "emoji": "❌", "class": "phrase",
       "examples": [{"en": "Pollution is a classic example of market failure because costs are not borne by polluters.", "vi": "Ô nhiễm là ví dụ điển hình về thất bại thị trường vì chi phí không do người gây ô nhiễm chịu."},
                    {"en": "Government intervention is justified when markets fail to allocate resources efficiently.", "vi": "Can thiệp của chính phủ được biện minh khi thị trường không phân bổ nguồn lực hiệu quả."}]},
      {"word": "privatization", "meaning": "tư nhân hóa", "emoji": "🏭", "class": "n",
       "examples": [{"en": "Privatization of state-owned enterprises can improve efficiency but reduce public access.", "vi": "Tư nhân hóa các doanh nghiệp nhà nước có thể cải thiện hiệu quả nhưng giảm tiếp cận công cộng."},
                    {"en": "The privatization of utilities such as water and energy remains deeply controversial.", "vi": "Tư nhân hóa các tiện ích như nước và năng lượng vẫn gây tranh cãi sâu sắc."}]},
      {"word": "inequality", "meaning": "bất bình đẳng", "emoji": "📊", "class": "n",
       "examples": [{"en": "Growing income inequality is considered one of the defining challenges of our era.", "vi": "Bất bình đẳng thu nhập ngày càng tăng được coi là một trong những thách thức quan trọng của thời đại chúng ta."},
                    {"en": "Policies such as progressive taxation are designed to reduce economic inequality.", "vi": "Các chính sách như thuế lũy tiến được thiết kế để giảm bất bình đẳng kinh tế."}]},
      {"word": "unemployment", "meaning": "thất nghiệp", "emoji": "😔", "class": "n",
       "examples": [{"en": "Youth unemployment is particularly high in many southern European countries.", "vi": "Thất nghiệp trong giới trẻ đặc biệt cao ở nhiều quốc gia Nam Âu."},
                    {"en": "Structural unemployment occurs when workers' skills no longer match available jobs.", "vi": "Thất nghiệp cơ cấu xảy ra khi kỹ năng của người lao động không còn phù hợp với công việc hiện có."}]}
    ]
  },
  {
    "id": "medical-ethics",
    "name": "Đạo Đức Y Khoa",
    "emoji": "🩺",
    "color": "teal",
    "words": [
      {"word": "informed consent", "meaning": "đồng ý có đầy đủ thông tin", "emoji": "📋", "class": "phrase",
       "examples": [{"en": "Doctors must obtain informed consent from patients before any procedure.", "vi": "Bác sĩ phải có sự đồng ý đầy đủ thông tin từ bệnh nhân trước bất kỳ thủ thuật nào."},
                    {"en": "Informed consent requires that patients fully understand the risks involved.", "vi": "Đồng ý đầy đủ thông tin đòi hỏi bệnh nhân hiểu đầy đủ các rủi ro liên quan."}]},
      {"word": "clinical trial", "meaning": "thử nghiệm lâm sàng", "emoji": "🔬", "class": "phrase",
       "examples": [{"en": "New drugs must pass rigorous clinical trials before they can be approved for use.", "vi": "Các loại thuốc mới phải vượt qua các thử nghiệm lâm sàng nghiêm ngặt trước khi được phê duyệt sử dụng."},
                    {"en": "Participants in clinical trials must give their consent freely and voluntarily.", "vi": "Những người tham gia thử nghiệm lâm sàng phải cho phép tự do và tự nguyện."}]},
      {"word": "euthanasia", "meaning": "an tử", "emoji": "🕊️", "class": "n",
       "examples": [{"en": "Euthanasia is legal in a small number of countries where strict conditions apply.", "vi": "An tử hợp pháp ở một số ít quốc gia nơi các điều kiện nghiêm ngặt được áp dụng."},
                    {"en": "The ethical debate around euthanasia centres on autonomy versus the sanctity of life.", "vi": "Cuộc tranh luận đạo đức xung quanh an tử tập trung vào quyền tự quyết so với tính thiêng liêng của cuộc sống."}]},
      {"word": "autonomy", "meaning": "quyền tự quyết", "emoji": "🗽", "class": "n",
       "examples": [{"en": "Patient autonomy means individuals have the right to refuse medical treatment.", "vi": "Quyền tự quyết của bệnh nhân có nghĩa là cá nhân có quyền từ chối điều trị y tế."},
                    {"en": "Respecting patient autonomy is a fundamental principle of medical ethics.", "vi": "Tôn trọng quyền tự quyết của bệnh nhân là nguyên tắc cơ bản của đạo đức y khoa."}]},
      {"word": "palliative care", "meaning": "chăm sóc giảm nhẹ", "emoji": "🤲", "class": "phrase",
       "examples": [{"en": "Palliative care focuses on relieving pain and improving quality of life for terminally ill patients.", "vi": "Chăm sóc giảm nhẹ tập trung vào giảm đau và cải thiện chất lượng cuộc sống cho bệnh nhân giai đoạn cuối."},
                    {"en": "Access to palliative care is considered a human right by many health organisations.", "vi": "Tiếp cận chăm sóc giảm nhẹ được nhiều tổ chức y tế coi là quyền con người."}]},
      {"word": "research ethics", "meaning": "đạo đức nghiên cứu", "emoji": "🎓", "class": "phrase",
       "examples": [{"en": "Research ethics guidelines protect participants from harm or exploitation.", "vi": "Các hướng dẫn đạo đức nghiên cứu bảo vệ người tham gia khỏi bị tổn hại hoặc khai thác."},
                    {"en": "All medical research must be approved by a research ethics committee.", "vi": "Tất cả nghiên cứu y tế phải được phê duyệt bởi ủy ban đạo đức nghiên cứu."}]},
      {"word": "patient rights", "meaning": "quyền của bệnh nhân", "emoji": "🛡️", "class": "phrase",
       "examples": [{"en": "Patient rights include access to information, privacy, and dignity in care.", "vi": "Quyền của bệnh nhân bao gồm quyền tiếp cận thông tin, quyền riêng tư và nhân phẩm trong chăm sóc."},
                    {"en": "Healthcare systems must uphold patient rights even under resource constraints.", "vi": "Các hệ thống y tế phải bảo vệ quyền của bệnh nhân ngay cả khi bị hạn chế nguồn lực."}]},
      {"word": "experimental", "meaning": "mang tính thử nghiệm", "emoji": "🧪", "class": "adj",
       "examples": [{"en": "Experimental treatments are only offered when all standard therapies have failed.", "vi": "Các phương pháp điều trị thử nghiệm chỉ được cung cấp khi tất cả các liệu pháp tiêu chuẩn đã thất bại."},
                    {"en": "Patients must understand the uncertain outcomes of experimental procedures.", "vi": "Bệnh nhân phải hiểu các kết quả không chắc chắn của các thủ thuật thử nghiệm."}]},
      {"word": "organ donation", "meaning": "hiến tạng", "emoji": "❤️", "class": "phrase",
       "examples": [{"en": "Organ donation saves lives by providing transplantable organs to those on waiting lists.", "vi": "Hiến tạng cứu sống người bằng cách cung cấp các cơ quan có thể ghép cho những người trong danh sách chờ."},
                    {"en": "Some countries have opt-out systems where citizens are presumed to consent to organ donation.", "vi": "Một số quốc gia có hệ thống từ chối, trong đó công dân được coi là đồng ý hiến tạng."}]},
      {"word": "transparency", "meaning": "minh bạch", "emoji": "🔍", "class": "n",
       "examples": [{"en": "Transparency in clinical research ensures that findings are not selectively reported.", "vi": "Minh bạch trong nghiên cứu lâm sàng đảm bảo rằng các phát hiện không được báo cáo chọn lọc."},
                    {"en": "Drug companies face criticism when they lack transparency about trial results.", "vi": "Các công ty dược phẩm đối mặt với chỉ trích khi thiếu minh bạch về kết quả thử nghiệm."}]},
      {"word": "ethics committee", "meaning": "hội đồng đạo đức", "emoji": "🏛️", "class": "phrase",
       "examples": [{"en": "The hospital's ethics committee reviewed the controversial case before a decision was made.", "vi": "Hội đồng đạo đức của bệnh viện đã xem xét vụ việc gây tranh cãi trước khi đưa ra quyết định."},
                    {"en": "Ethics committees play a vital role in protecting vulnerable research participants.", "vi": "Hội đồng đạo đức đóng vai trò quan trọng trong việc bảo vệ những người tham gia nghiên cứu dễ bị tổn thương."}]}
    ]
  },
  {
    "id": "sociology",
    "name": "Xã Hội Học",
    "emoji": "👥",
    "color": "purple",
    "words": [
      {"word": "inequality", "meaning": "bất bình đẳng", "emoji": "📊", "class": "n",
       "examples": [{"en": "Social inequality affects access to education, healthcare, and economic opportunities.", "vi": "Bất bình đẳng xã hội ảnh hưởng đến tiếp cận giáo dục, y tế và cơ hội kinh tế."},
                    {"en": "Researchers measure inequality using indicators like income distribution and social mobility.", "vi": "Các nhà nghiên cứu đo lường bất bình đẳng bằng các chỉ số như phân phối thu nhập và tính cơ động xã hội."}]},
      {"word": "discrimination", "meaning": "phân biệt đối xử", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Discrimination based on race, gender, or religion is illegal in most countries.", "vi": "Phân biệt đối xử dựa trên chủng tộc, giới tính hay tôn giáo là bất hợp pháp ở hầu hết các quốc gia."},
                    {"en": "Unconscious discrimination can persist even when individuals believe they are unbiased.", "vi": "Phân biệt đối xử vô thức có thể tồn tại ngay cả khi cá nhân tin rằng họ không có thành kiến."}]},
      {"word": "social class", "meaning": "tầng lớp xã hội", "emoji": "🏘️", "class": "phrase",
       "examples": [{"en": "Social class continues to influence educational achievement and career prospects.", "vi": "Tầng lớp xã hội tiếp tục ảnh hưởng đến thành tích học tập và triển vọng nghề nghiệp."},
                    {"en": "Sociologists debate whether social class is determined by income, education, or occupation.", "vi": "Các nhà xã hội học tranh luận liệu tầng lớp xã hội được xác định bởi thu nhập, học vấn hay nghề nghiệp."}]},
      {"word": "social mobility", "meaning": "tính cơ động xã hội", "emoji": "📈", "class": "phrase",
       "examples": [{"en": "High social mobility means individuals can rise above the class they were born into.", "vi": "Tính cơ động xã hội cao có nghĩa là cá nhân có thể vươn lên trên tầng lớp họ sinh ra."},
                    {"en": "Countries with strong public education systems tend to have higher social mobility.", "vi": "Các quốc gia có hệ thống giáo dục công mạnh có xu hướng có tính cơ động xã hội cao hơn."}]},
      {"word": "marginalization", "meaning": "sự ngoại lề hóa", "emoji": "🚧", "class": "n",
       "examples": [{"en": "Economic marginalization leaves communities cut off from mainstream opportunities.", "vi": "Sự ngoại lề hóa kinh tế khiến cộng đồng bị cắt đứt khỏi các cơ hội chính."},
                    {"en": "Addressing marginalization requires targeted policies and inclusive institutions.", "vi": "Giải quyết sự ngoại lề hóa đòi hỏi các chính sách có mục tiêu và thể chế bao trùm."}]},
      {"word": "privilege", "meaning": "đặc quyền", "emoji": "⭐", "class": "n",
       "examples": [{"en": "Acknowledging privilege means recognising advantages you have that others may lack.", "vi": "Thừa nhận đặc quyền có nghĩa là nhận ra những lợi thế bạn có mà người khác có thể không có."},
                    {"en": "Structural privilege is embedded in institutions and not always visible to those who benefit.", "vi": "Đặc quyền cơ cấu được nhúng trong các thể chế và không phải lúc nào cũng hiện rõ với những người hưởng lợi."}]},
      {"word": "diversity", "meaning": "đa dạng", "emoji": "🌈", "class": "n",
       "examples": [{"en": "Embracing diversity strengthens organisations and communities.", "vi": "Đón nhận sự đa dạng củng cố các tổ chức và cộng đồng."},
                    {"en": "Cultural diversity enriches society but also requires tolerance and dialogue.", "vi": "Đa dạng văn hóa làm phong phú xã hội nhưng cũng đòi hỏi sự khoan dung và đối thoại."}]},
      {"word": "exclusion", "meaning": "sự loại trừ", "emoji": "⛔", "class": "n",
       "examples": [{"en": "Social exclusion makes it difficult for marginalised groups to participate fully in society.", "vi": "Sự loại trừ xã hội khiến các nhóm bị ngoại lề hóa khó tham gia đầy đủ vào xã hội."},
                    {"en": "Digital exclusion affects those without access to the internet and modern technology.", "vi": "Loại trừ kỹ thuật số ảnh hưởng đến những người không có tiếp cận internet và công nghệ hiện đại."}]},
      {"word": "stereotype", "meaning": "khuôn mẫu định kiến", "emoji": "🏷️", "class": "n",
       "examples": [{"en": "Racial stereotypes are harmful because they reduce individuals to oversimplified categories.", "vi": "Khuôn mẫu chủng tộc có hại vì chúng thu hẹp cá nhân thành các danh mục đơn giản hóa quá mức."},
                    {"en": "Media representations often reinforce gender stereotypes that limit expectations.", "vi": "Các hình ảnh truyền thông thường củng cố các khuôn mẫu giới tính hạn chế kỳ vọng."}]},
      {"word": "social capital", "meaning": "vốn xã hội", "emoji": "🌐", "class": "phrase",
       "examples": [{"en": "Communities with high social capital have stronger support networks and civic engagement.", "vi": "Các cộng đồng có vốn xã hội cao có mạng lưới hỗ trợ và sự tham gia dân sự mạnh hơn."},
                    {"en": "Building social capital requires trust, shared norms, and active participation.", "vi": "Xây dựng vốn xã hội đòi hỏi sự tin tưởng, các chuẩn mực chung và sự tham gia tích cực."}]},
      {"word": "institution", "meaning": "thể chế", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Social institutions like family, religion, and education shape individual behaviour.", "vi": "Các thể chế xã hội như gia đình, tôn giáo và giáo dục định hình hành vi cá nhân."},
                    {"en": "Reforming institutions is necessary to address deep-rooted structural inequalities.", "vi": "Cải cách thể chế là cần thiết để giải quyết các bất bình đẳng cơ cấu sâu rễ."}]}
    ]
  },
  {
    "id": "business-ethics",
    "name": "Đạo Đức Kinh Doanh",
    "emoji": "💼",
    "color": "cyan",
    "words": [
      {"word": "accountability", "meaning": "trách nhiệm giải trình", "emoji": "📋", "class": "n",
       "examples": [{"en": "Corporate accountability requires companies to answer for their environmental impact.", "vi": "Trách nhiệm giải trình doanh nghiệp yêu cầu các công ty phải trả lời về tác động môi trường của họ."},
                    {"en": "Shareholders demand accountability from executives regarding financial performance.", "vi": "Cổ đông đòi hỏi trách nhiệm giải trình từ lãnh đạo về hiệu quả tài chính."}]},
      {"word": "transparency", "meaning": "minh bạch", "emoji": "🔍", "class": "n",
       "examples": [{"en": "Financial transparency means publishing accurate and complete accounts for public scrutiny.", "vi": "Minh bạch tài chính có nghĩa là công bố báo cáo chính xác và đầy đủ để công chúng giám sát."},
                    {"en": "Supply chain transparency helps consumers make ethically informed purchasing decisions.", "vi": "Minh bạch chuỗi cung ứng giúp người tiêu dùng đưa ra quyết định mua hàng có đạo đức."}]},
      {"word": "corruption", "meaning": "tham nhũng", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "Corruption undermines fair competition and discourages honest businesses.", "vi": "Tham nhũng làm suy yếu cạnh tranh công bằng và nản lòng các doanh nghiệp trung thực."},
                    {"en": "Anti-corruption policies are essential for sustainable economic development.", "vi": "Các chính sách chống tham nhũng là thiết yếu cho phát triển kinh tế bền vững."}]},
      {"word": "integrity", "meaning": "liêm chính", "emoji": "💎", "class": "n",
       "examples": [{"en": "Business integrity means acting honestly even when no one is watching.", "vi": "Liêm chính trong kinh doanh có nghĩa là hành động trung thực ngay cả khi không có ai theo dõi."},
                    {"en": "A company's long-term reputation depends entirely on its integrity.", "vi": "Danh tiếng lâu dài của công ty hoàn toàn phụ thuộc vào liêm chính của công ty."}]},
      {"word": "compliance", "meaning": "tuân thủ", "emoji": "✅", "class": "n",
       "examples": [{"en": "All employees must complete compliance training on data protection laws.", "vi": "Tất cả nhân viên phải hoàn thành đào tạo tuân thủ về luật bảo vệ dữ liệu."},
                    {"en": "A strong compliance culture reduces the risk of legal and regulatory violations.", "vi": "Văn hóa tuân thủ mạnh mẽ giảm nguy cơ vi phạm pháp lý và quy định."}]},
      {"word": "whistleblower", "meaning": "người tố giác", "emoji": "📢", "class": "n",
       "examples": [{"en": "The whistleblower revealed that the company had been falsifying its financial records.", "vi": "Người tố giác tiết lộ rằng công ty đã làm giả hồ sơ tài chính."},
                    {"en": "Legal protections for whistleblowers encourage employees to report wrongdoing.", "vi": "Bảo vệ pháp lý cho người tố giác khuyến khích nhân viên báo cáo hành vi sai trái."}]},
      {"word": "conflict of interest", "meaning": "xung đột lợi ích", "emoji": "⚡", "class": "phrase",
       "examples": [{"en": "Board members must declare any conflict of interest before voting on decisions.", "vi": "Thành viên hội đồng quản trị phải khai báo bất kỳ xung đột lợi ích nào trước khi bỏ phiếu quyết định."},
                    {"en": "A conflict of interest arises when personal interests interfere with professional duties.", "vi": "Xung đột lợi ích xảy ra khi lợi ích cá nhân can thiệp vào nhiệm vụ chuyên nghiệp."}]},
      {"word": "corporate responsibility", "meaning": "trách nhiệm doanh nghiệp", "emoji": "🌱", "class": "phrase",
       "examples": [{"en": "Corporate responsibility extends beyond profit to include social and environmental obligations.", "vi": "Trách nhiệm doanh nghiệp mở rộng ra ngoài lợi nhuận để bao gồm các nghĩa vụ xã hội và môi trường."},
                    {"en": "Companies with strong corporate responsibility records often attract better talent.", "vi": "Các công ty có hồ sơ trách nhiệm doanh nghiệp tốt thường thu hút nhân tài tốt hơn."}]},
      {"word": "audit", "meaning": "kiểm toán", "emoji": "🔍", "class": "n",
       "examples": [{"en": "An independent audit verifies that a company's financial statements are accurate.", "vi": "Kiểm toán độc lập xác minh rằng báo cáo tài chính của công ty là chính xác."},
                    {"en": "Regular audits help identify inefficiencies and prevent financial misconduct.", "vi": "Kiểm toán thường xuyên giúp xác định sự kém hiệu quả và ngăn chặn hành vi tài chính sai trái."}]},
      {"word": "bribery", "meaning": "hối lộ", "emoji": "💵", "class": "n",
       "examples": [{"en": "Bribery distorts markets and gives unfair advantages to those willing to pay.", "vi": "Hối lộ làm méo mó thị trường và tạo lợi thế không công bằng cho những người sẵn sàng trả tiền."},
                    {"en": "Anti-bribery laws apply to companies operating in foreign markets.", "vi": "Luật chống hối lộ áp dụng cho các công ty hoạt động ở thị trường nước ngoài."}]},
      {"word": "stakeholder", "meaning": "các bên liên quan", "emoji": "👥", "class": "n",
       "examples": [{"en": "Businesses must balance the interests of all stakeholders, not just shareholders.", "vi": "Doanh nghiệp phải cân bằng lợi ích của tất cả các bên liên quan, không chỉ cổ đông."},
                    {"en": "Stakeholder engagement is essential when a company plans major changes.", "vi": "Sự tham gia của các bên liên quan là thiết yếu khi công ty lên kế hoạch thay đổi lớn."}]}
    ]
  },
  {
    "id": "technology-ethics",
    "name": "Đạo Đức Công Nghệ",
    "emoji": "💻",
    "color": "sky",
    "words": [
      {"word": "algorithm", "meaning": "thuật toán", "emoji": "🔢", "class": "n",
       "examples": [{"en": "The recommendation algorithm determines what content users see on social media.", "vi": "Thuật toán đề xuất xác định nội dung người dùng thấy trên mạng xã hội."},
                    {"en": "Algorithmic bias can discriminate against certain groups if training data is flawed.", "vi": "Thiên kiến thuật toán có thể phân biệt đối xử với một số nhóm nếu dữ liệu huấn luyện có sai sót."}]},
      {"word": "automation", "meaning": "tự động hóa", "emoji": "🤖", "class": "n",
       "examples": [{"en": "Automation in manufacturing has replaced millions of routine jobs worldwide.", "vi": "Tự động hóa trong sản xuất đã thay thế hàng triệu công việc thường ngày trên toàn thế giới."},
                    {"en": "While automation increases productivity, it also raises concerns about job security.", "vi": "Mặc dù tự động hóa tăng năng suất, nó cũng gây lo ngại về an toàn việc làm."}]},
      {"word": "surveillance", "meaning": "giám sát", "emoji": "👁️", "class": "n",
       "examples": [{"en": "Mass surveillance by governments raises serious civil liberties concerns.", "vi": "Giám sát hàng loạt của chính phủ gây ra lo ngại nghiêm trọng về quyền tự do dân sự."},
                    {"en": "Workplace surveillance technology monitors employee productivity but invades privacy.", "vi": "Công nghệ giám sát nơi làm việc theo dõi năng suất nhân viên nhưng xâm phạm quyền riêng tư."}]},
      {"word": "disruption", "meaning": "sự đổ vỡ/thay đổi đột phá", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Digital disruption has fundamentally changed industries like retail, media, and banking.", "vi": "Sự đổ vỡ kỹ thuật số đã thay đổi căn bản các ngành như bán lẻ, truyền thông và ngân hàng."},
                    {"en": "Disruptive technologies can create enormous opportunity but also significant social dislocation.", "vi": "Các công nghệ đột phá có thể tạo ra cơ hội lớn nhưng cũng gây ra sự dịch chuyển xã hội đáng kể."}]},
      {"word": "digital equity", "meaning": "bình đẳng kỹ thuật số", "emoji": "🌐", "class": "phrase",
       "examples": [{"en": "Digital equity requires that everyone has access to affordable internet and devices.", "vi": "Bình đẳng kỹ thuật số đòi hỏi mọi người được tiếp cận internet và thiết bị với giá cả phải chăng."},
                    {"en": "The digital divide undermines digital equity and deepens existing inequalities.", "vi": "Khoảng cách kỹ thuật số làm suy yếu bình đẳng kỹ thuật số và đào sâu bất bình đẳng hiện có."}]},
      {"word": "platform", "meaning": "nền tảng", "emoji": "📱", "class": "n",
       "examples": [{"en": "Major platforms like social media companies wield enormous influence over public discourse.", "vi": "Các nền tảng lớn như công ty mạng xã hội nắm giữ ảnh hưởng to lớn đối với diễn ngôn công cộng."},
                    {"en": "Regulating platforms while preserving free expression is a complex policy challenge.", "vi": "Điều chỉnh các nền tảng trong khi bảo vệ tự do ngôn luận là thách thức chính sách phức tạp."}]},
      {"word": "AI", "meaning": "trí tuệ nhân tạo", "emoji": "🤖", "class": "n",
       "examples": [{"en": "AI is being used in healthcare to assist with diagnosis and treatment recommendations.", "vi": "Trí tuệ nhân tạo đang được sử dụng trong y tế để hỗ trợ chẩn đoán và đề xuất điều trị."},
                    {"en": "The ethical implications of AI in decision-making are still not fully understood.", "vi": "Các hệ quả đạo đức của trí tuệ nhân tạo trong việc ra quyết định vẫn chưa được hiểu đầy đủ."}]},
      {"word": "data", "meaning": "dữ liệu", "emoji": "💾", "class": "n",
       "examples": [{"en": "Companies collect vast amounts of data on users without always explaining how it is used.", "vi": "Các công ty thu thập lượng lớn dữ liệu về người dùng mà không phải lúc nào cũng giải thích cách sử dụng."},
                    {"en": "Data protection laws give citizens control over how their personal data is stored.", "vi": "Luật bảo vệ dữ liệu cho phép công dân kiểm soát cách dữ liệu cá nhân được lưu trữ."}]},
      {"word": "privacy", "meaning": "quyền riêng tư", "emoji": "🔒", "class": "n",
       "examples": [{"en": "New technologies constantly challenge traditional concepts of privacy.", "vi": "Các công nghệ mới liên tục thách thức các khái niệm truyền thống về quyền riêng tư."},
                    {"en": "Privacy settings allow users to control who can see their personal information online.", "vi": "Cài đặt quyền riêng tư cho phép người dùng kiểm soát ai có thể xem thông tin cá nhân của họ trực tuyến."}]},
      {"word": "rights", "meaning": "quyền", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Digital rights include the right to privacy, free expression, and access to information.", "vi": "Quyền kỹ thuật số bao gồm quyền riêng tư, tự do ngôn luận và tiếp cận thông tin."},
                    {"en": "Protecting human rights in the digital age is a major challenge for governments.", "vi": "Bảo vệ quyền con người trong thời đại kỹ thuật số là thách thức lớn đối với chính phủ."}]},
      {"word": "regulation", "meaning": "quy định", "emoji": "📏", "class": "n",
       "examples": [{"en": "Regulation of AI is urgently needed to prevent misuse and protect human dignity.", "vi": "Quy định về AI cần thiết gấp để ngăn chặn lạm dụng và bảo vệ nhân phẩm."},
                    {"en": "Tech regulation lags behind innovation, leaving many gaps in consumer protection.", "vi": "Quy định công nghệ tụt hậu so với đổi mới, để lại nhiều khoảng trống trong bảo vệ người tiêu dùng."}]}
    ]
  }
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'words.json')

# Get transferred topics from git
original_json = subprocess.check_output(
    ['git', 'show', 'HEAD:data/words.json'],
    cwd=os.path.dirname(data_path)
)
original_data = json.loads(original_json)
transferred = [t for t in original_data['scholar']['topics'] if t['id'] in TRANSFER_IDS]
print(f"Transferred from Scholar: {[t['id'] for t in transferred]}")

with open(data_path, encoding='utf-8') as f:
    data = json.load(f)

# Create master level
data['master'] = {"topics": transferred + NEW_MASTER_TOPICS_PART1}

with open(data_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

master_count = len(data['master']['topics'])
print(f"Master: {master_count} topics so far (8 transferred + {len(NEW_MASTER_TOPICS_PART1)} new)")
for t in data['master']['topics']:
    print(f"  {t['id']}: {len(t['words'])} words")
