# -*- coding: utf-8 -*-
import json, os

NEW_MASTER_TOPICS_PART2 = [
  {
    "id": "media-literacy",
    "name": "Năng Lực Truyền Thông",
    "emoji": "📰",
    "color": "orange",
    "words": [
      {"word": "bias", "meaning": "thành kiến (truyền thông)", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Media bias occurs when news coverage favours a particular political viewpoint.", "vi": "Thành kiến truyền thông xảy ra khi đưa tin thiên về một quan điểm chính trị cụ thể."},
                    {"en": "Readers should be aware of potential bias when consuming news from a single source.", "vi": "Người đọc nên nhận thức về thành kiến tiềm ẩn khi tiêu thụ tin tức từ một nguồn duy nhất."}]},
      {"word": "credibility", "meaning": "độ tin cậy", "emoji": "✅", "class": "n",
       "examples": [{"en": "A news organisation's credibility depends on accuracy, fairness, and transparency.", "vi": "Độ tin cậy của tổ chức tin tức phụ thuộc vào độ chính xác, công bằng và minh bạch."},
                    {"en": "Once credibility is lost, it is very difficult for a media outlet to regain public trust.", "vi": "Một khi mất đi độ tin cậy, rất khó để cơ quan truyền thông lấy lại niềm tin của công chúng."}]},
      {"word": "objectivity", "meaning": "tính khách quan", "emoji": "🎯", "class": "n",
       "examples": [{"en": "Journalists are expected to maintain objectivity by presenting multiple perspectives.", "vi": "Nhà báo được kỳ vọng duy trì tính khách quan bằng cách trình bày nhiều quan điểm."},
                    {"en": "Complete objectivity in journalism is considered by many to be an impossible ideal.", "vi": "Tính khách quan hoàn toàn trong báo chí được nhiều người coi là lý tưởng không thể đạt được."}]},
      {"word": "misinformation", "meaning": "thông tin sai lệch", "emoji": "❌", "class": "n",
       "examples": [{"en": "Misinformation spreads rapidly on social media, often outpacing fact-checking efforts.", "vi": "Thông tin sai lệch lan truyền nhanh chóng trên mạng xã hội, thường vượt xa các nỗ lực kiểm tra thực tế."},
                    {"en": "Health misinformation can cause serious public harm if not addressed promptly.", "vi": "Thông tin sai lệch về sức khỏe có thể gây hại nghiêm trọng cho công chúng nếu không được xử lý kịp thời."}]},
      {"word": "sensationalism", "meaning": "chủ nghĩa giật gân", "emoji": "📣", "class": "n",
       "examples": [{"en": "Sensationalism prioritises shocking headlines over accurate and balanced reporting.", "vi": "Chủ nghĩa giật gân ưu tiên tiêu đề gây sốc hơn là đưa tin chính xác và cân bằng."},
                    {"en": "Tabloid media is often criticised for its reliance on sensationalism to attract readers.", "vi": "Báo lá cải thường bị chỉ trích vì phụ thuộc vào chủ nghĩa giật gân để thu hút độc giả."}]},
      {"word": "censorship", "meaning": "kiểm duyệt", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Government censorship suppresses media freedom and restricts public access to information.", "vi": "Kiểm duyệt của chính phủ đàn áp tự do báo chí và hạn chế tiếp cận thông tin của công chúng."},
                    {"en": "Social media platforms face accusations of political censorship when removing content.", "vi": "Các nền tảng mạng xã hội đối mặt với cáo buộc kiểm duyệt chính trị khi xóa nội dung."}]},
      {"word": "echo chamber", "meaning": "buồng vang", "emoji": "🔄", "class": "phrase",
       "examples": [{"en": "Social media algorithms create echo chambers by showing users only content they already agree with.", "vi": "Thuật toán mạng xã hội tạo ra buồng vang bằng cách chỉ hiển thị nội dung người dùng đã đồng ý."},
                    {"en": "Breaking out of an echo chamber requires actively seeking out opposing views.", "vi": "Thoát ra khỏi buồng vang đòi hỏi tích cực tìm kiếm các quan điểm đối lập."}]},
      {"word": "framing", "meaning": "đóng khung thông tin", "emoji": "🖼️", "class": "n",
       "examples": [{"en": "The framing of a news story influences how the public perceives an issue.", "vi": "Cách đóng khung một câu chuyện tin tức ảnh hưởng đến cách công chúng nhận thức một vấn đề."},
                    {"en": "Different newspapers used contrasting framing to report the same political event.", "vi": "Các tờ báo khác nhau sử dụng cách đóng khung tương phản để đưa tin về cùng một sự kiện chính trị."}]},
      {"word": "propaganda", "meaning": "tuyên truyền", "emoji": "📢", "class": "n",
       "examples": [{"en": "Propaganda uses emotionally charged language and selective facts to manipulate public opinion.", "vi": "Tuyên truyền sử dụng ngôn ngữ nạp cảm xúc và sự kiện chọn lọc để thao túng dư luận."},
                    {"en": "Wartime propaganda historically portrayed the enemy as subhuman to encourage support.", "vi": "Tuyên truyền thời chiến trong lịch sử mô tả kẻ thù như không phải con người để khuyến khích ủng hộ."}]},
      {"word": "fact-check", "meaning": "kiểm tra thực tế", "emoji": "🔍", "class": "v",
       "examples": [{"en": "Responsible journalists fact-check all claims before publishing a story.", "vi": "Các nhà báo có trách nhiệm kiểm tra thực tế tất cả các tuyên bố trước khi đăng bài."},
                    {"en": "Independent fact-checking organisations play a vital role in combating misinformation.", "vi": "Các tổ chức kiểm tra thực tế độc lập đóng vai trò quan trọng trong việc chống lại thông tin sai lệch."}]},
      {"word": "representation", "meaning": "sự đại diện", "emoji": "🪞", "class": "n",
       "examples": [{"en": "Media representation of minority groups has improved but still has significant gaps.", "vi": "Sự đại diện của các nhóm thiểu số trong truyền thông đã cải thiện nhưng vẫn còn nhiều khoảng cách đáng kể."},
                    {"en": "Diverse representation in the media helps all viewers see themselves reflected in society.", "vi": "Sự đại diện đa dạng trong truyền thông giúp tất cả khán giả thấy bản thân được phản ánh trong xã hội."}]},
      {"word": "narrative", "meaning": "tường thuật, câu chuyện", "emoji": "📖", "class": "n",
       "examples": [{"en": "Political leaders often try to control the dominant narrative in the media.", "vi": "Các nhà lãnh đạo chính trị thường cố gắng kiểm soát câu chuyện chủ đạo trên truyền thông."},
                    {"en": "The official narrative about the crisis was challenged by investigative journalists.", "vi": "Câu chuyện chính thức về cuộc khủng hoảng bị thách thức bởi các nhà báo điều tra."}]},
      {"word": "influence", "meaning": "ảnh hưởng", "emoji": "🌀", "class": "n",
       "examples": [{"en": "Media influence on public opinion is profound and often underestimated.", "vi": "Ảnh hưởng của truyền thông đối với dư luận rất sâu sắc và thường bị đánh giá thấp."},
                    {"en": "Foreign governments can use media influence to interfere in another country's elections.", "vi": "Các chính phủ nước ngoài có thể sử dụng ảnh hưởng truyền thông để can thiệp vào bầu cử của quốc gia khác."}]}
    ]
  },
  {
    "id": "rhetoric-debate",
    "name": "Hùng Biện & Tranh Luận",
    "emoji": "🗣️",
    "color": "rose",
    "words": [
      {"word": "argument", "meaning": "lập luận", "emoji": "💬", "class": "n",
       "examples": [{"en": "A well-constructed argument presents a clear claim supported by relevant evidence.", "vi": "Một lập luận được xây dựng tốt trình bày một tuyên bố rõ ràng được hỗ trợ bởi bằng chứng liên quan."},
                    {"en": "The argument fell apart when the key evidence was shown to be inaccurate.", "vi": "Lập luận sụp đổ khi bằng chứng chủ chốt được chứng minh là không chính xác."}]},
      {"word": "persuasion", "meaning": "sự thuyết phục", "emoji": "✨", "class": "n",
       "examples": [{"en": "Effective persuasion relies on logic, emotion, and the credibility of the speaker.", "vi": "Thuyết phục hiệu quả dựa vào logic, cảm xúc và độ tin cậy của người nói."},
                    {"en": "Advertisers are skilled in the art of persuasion through language and imagery.", "vi": "Các nhà quảng cáo có kỹ năng trong nghệ thuật thuyết phục qua ngôn ngữ và hình ảnh."}]},
      {"word": "fallacy", "meaning": "ngụy biện", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "The ad hominem fallacy attacks the person rather than their argument.", "vi": "Ngụy biện công kích cá nhân tấn công người đó thay vì lập luận của họ."},
                    {"en": "Identifying logical fallacies is an essential critical thinking skill.", "vi": "Nhận diện các ngụy biện logic là kỹ năng tư duy phản biện thiết yếu."}]},
      {"word": "rebuttal", "meaning": "phản bác", "emoji": "🔄", "class": "n",
       "examples": [{"en": "Her rebuttal dismantled the opposing team's central argument in two minutes.", "vi": "Phần phản bác của cô đã tháo dỡ lập luận trung tâm của đội đối phương trong hai phút."},
                    {"en": "A strong rebuttal anticipates objections and addresses them directly.", "vi": "Một phản bác mạnh mẽ dự đoán trước các phản đối và giải quyết chúng trực tiếp."}]},
      {"word": "concession", "meaning": "nhượng bộ", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Making a concession shows intellectual honesty and can strengthen your overall argument.", "vi": "Nhượng bộ thể hiện sự trung thực trí tuệ và có thể củng cố toàn bộ lập luận của bạn."},
                    {"en": "He opened with a concession that his opponents had raised valid concerns.", "vi": "Anh mở đầu bằng việc nhượng bộ rằng đối thủ đã nêu ra những lo ngại chính đáng."}]},
      {"word": "premise", "meaning": "tiền đề", "emoji": "🔑", "class": "n",
       "examples": [{"en": "If the premise of an argument is false, the conclusion cannot be valid.", "vi": "Nếu tiền đề của một lập luận sai, kết luận không thể hợp lệ."},
                    {"en": "The debate exposed the faulty premises underlying the government's economic plan.", "vi": "Cuộc tranh luận đã vạch trần những tiền đề sai lầm ẩn sau kế hoạch kinh tế của chính phủ."}]},
      {"word": "coherence", "meaning": "tính mạch lạc", "emoji": "🔗", "class": "n",
       "examples": [{"en": "Coherence in academic writing means all points connect logically to support the thesis.", "vi": "Tính mạch lạc trong văn viết học thuật có nghĩa là tất cả các điểm kết nối logic để hỗ trợ luận điểm."},
                    {"en": "Lack of coherence makes an argument confusing and difficult to follow.", "vi": "Thiếu tính mạch lạc khiến lập luận trở nên khó hiểu và khó theo dõi."}]},
      {"word": "counterargument", "meaning": "phản luận", "emoji": "↩️", "class": "n",
       "examples": [{"en": "Addressing counterarguments directly shows that your position can withstand scrutiny.", "vi": "Giải quyết các phản luận trực tiếp cho thấy quan điểm của bạn có thể chịu đựng sự xem xét kỹ lưỡng."},
                    {"en": "A strong essay acknowledges the most powerful counterarguments before refuting them.", "vi": "Một bài luận mạnh thừa nhận các phản luận mạnh mẽ nhất trước khi bác bỏ chúng."}]},
      {"word": "credibility", "meaning": "độ tin cậy (người nói)", "emoji": "🎓", "class": "n",
       "examples": [{"en": "A speaker's credibility is enhanced by expertise, honesty, and consistent behaviour.", "vi": "Độ tin cậy của người nói được tăng cường bởi chuyên môn, sự trung thực và hành vi nhất quán."},
                    {"en": "Citing respected sources boosts the credibility of an academic argument.", "vi": "Trích dẫn các nguồn đáng kính tăng độ tin cậy của một lập luận học thuật."}]},
      {"word": "claim", "meaning": "tuyên bố, luận điểm", "emoji": "📌", "class": "n",
       "examples": [{"en": "Every claim in a debate must be supported by verifiable evidence.", "vi": "Mỗi tuyên bố trong tranh luận phải được hỗ trợ bởi bằng chứng có thể kiểm chứng."},
                    {"en": "The politician's bold claims were not backed up by any factual data.", "vi": "Các tuyên bố táo bạo của chính trị gia không được hỗ trợ bởi bất kỳ dữ liệu thực tế nào."}]},
      {"word": "discourse", "meaning": "diễn ngôn", "emoji": "🗣️", "class": "n",
       "examples": [{"en": "Public discourse about climate change has become increasingly polarised.", "vi": "Diễn ngôn công cộng về biến đổi khí hậu ngày càng trở nên phân cực."},
                    {"en": "Academic discourse follows established conventions of evidence-based argumentation.", "vi": "Diễn ngôn học thuật tuân theo các quy ước đã được thiết lập của lập luận dựa trên bằng chứng."}]}
    ]
  },
  {
    "id": "global-governance",
    "name": "Quản Trị Toàn Cầu",
    "emoji": "🌐",
    "color": "green",
    "words": [
      {"word": "international law", "meaning": "luật quốc tế", "emoji": "⚖️", "class": "phrase",
       "examples": [{"en": "International law governs relations between states and protects human rights globally.", "vi": "Luật quốc tế điều chỉnh quan hệ giữa các quốc gia và bảo vệ quyền con người toàn cầu."},
                    {"en": "Violations of international law can lead to sanctions or referrals to international courts.", "vi": "Vi phạm luật quốc tế có thể dẫn đến các biện pháp trừng phạt hoặc chuyển đến tòa án quốc tế."}]},
      {"word": "multilateral", "meaning": "đa phương", "emoji": "🌐", "class": "adj",
       "examples": [{"en": "Multilateral institutions like the UN provide a forum for resolving global disputes.", "vi": "Các thể chế đa phương như Liên Hợp Quốc cung cấp diễn đàn để giải quyết các tranh chấp toàn cầu."},
                    {"en": "Addressing climate change requires multilateral cooperation across all nations.", "vi": "Giải quyết biến đổi khí hậu đòi hỏi hợp tác đa phương trên tất cả các quốc gia."}]},
      {"word": "humanitarian", "meaning": "nhân đạo", "emoji": "❤️", "class": "adj",
       "examples": [{"en": "Humanitarian aid was delivered to conflict zones to help civilians affected by war.", "vi": "Viện trợ nhân đạo được chuyển đến các vùng xung đột để giúp đỡ dân thường bị ảnh hưởng bởi chiến tranh."},
                    {"en": "Humanitarian intervention is justified under international law when civilian lives are at risk.", "vi": "Can thiệp nhân đạo được biện minh theo luật quốc tế khi sinh mạng dân thường bị đe dọa."}]},
      {"word": "peacekeeping", "meaning": "gìn giữ hòa bình", "emoji": "🕊️", "class": "n",
       "examples": [{"en": "UN peacekeeping missions help stabilise conflict zones and protect civilians.", "vi": "Các phái bộ gìn giữ hòa bình của Liên Hợp Quốc giúp ổn định các vùng xung đột và bảo vệ dân thường."},
                    {"en": "Peacekeeping operations are most effective when they have clear mandates and resources.", "vi": "Các hoạt động gìn giữ hòa bình hiệu quả nhất khi có nhiệm vụ rõ ràng và nguồn lực đầy đủ."}]},
      {"word": "sovereignty", "meaning": "chủ quyền", "emoji": "🏳️", "class": "n",
       "examples": [{"en": "Respecting national sovereignty is a foundational principle of the international order.", "vi": "Tôn trọng chủ quyền quốc gia là nguyên tắc nền tảng của trật tự quốc tế."},
                    {"en": "The tension between national sovereignty and global governance remains unresolved.", "vi": "Căng thẳng giữa chủ quyền quốc gia và quản trị toàn cầu vẫn chưa được giải quyết."}]},
      {"word": "NGO", "meaning": "tổ chức phi chính phủ", "emoji": "🤝", "class": "n",
       "examples": [{"en": "NGOs provide vital services in areas where governments are unable or unwilling to act.", "vi": "Các tổ chức phi chính phủ cung cấp các dịch vụ thiết yếu ở những nơi chính phủ không thể hoặc không sẵn sàng hành động."},
                    {"en": "International NGOs play a major role in humanitarian relief and development.", "vi": "Các tổ chức phi chính phủ quốc tế đóng vai trò lớn trong cứu trợ nhân đạo và phát triển."}]},
      {"word": "compliance", "meaning": "tuân thủ", "emoji": "✅", "class": "n",
       "examples": [{"en": "Compliance with international agreements requires strong domestic legal frameworks.", "vi": "Tuân thủ các thỏa thuận quốc tế đòi hỏi khung pháp lý trong nước mạnh mẽ."},
                    {"en": "Monitoring mechanisms are essential to verify compliance with arms control treaties.", "vi": "Cơ chế giám sát là thiết yếu để xác minh tuân thủ các hiệp ước kiểm soát vũ khí."}]},
      {"word": "cooperation", "meaning": "hợp tác", "emoji": "🤝", "class": "n",
       "examples": [{"en": "International cooperation is essential for addressing challenges that no country can solve alone.", "vi": "Hợp tác quốc tế là thiết yếu để giải quyết những thách thức mà không quốc gia nào có thể giải quyết một mình."},
                    {"en": "Security cooperation between allied nations deters potential aggressors.", "vi": "Hợp tác an ninh giữa các quốc gia đồng minh ngăn chặn các kẻ xâm lược tiềm năng."}]},
      {"word": "institution", "meaning": "thể chế quốc tế", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "International institutions like the IMF and World Bank shape global economic policy.", "vi": "Các thể chế quốc tế như IMF và Ngân hàng Thế giới định hình chính sách kinh tế toàn cầu."},
                    {"en": "Strengthening global institutions is key to managing an increasingly multipolar world.", "vi": "Củng cố các thể chế toàn cầu là chìa khóa để quản lý thế giới ngày càng đa cực."}]},
      {"word": "sanction", "meaning": "lệnh trừng phạt", "emoji": "🚫", "class": "n",
       "examples": [{"en": "International sanctions were designed to change the government's behaviour without military force.", "vi": "Các lệnh trừng phạt quốc tế được thiết kế để thay đổi hành vi của chính phủ mà không cần vũ lực quân sự."},
                    {"en": "The effectiveness of sanctions depends on broad international support.", "vi": "Hiệu quả của các lệnh trừng phạt phụ thuộc vào sự ủng hộ quốc tế rộng rãi."}]},
      {"word": "diplomacy", "meaning": "ngoại giao", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Diplomacy is the primary tool for managing international conflicts peacefully.", "vi": "Ngoại giao là công cụ chính để quản lý các xung đột quốc tế một cách hòa bình."},
                    {"en": "Economic diplomacy uses trade agreements to advance a nation's foreign policy goals.", "vi": "Ngoại giao kinh tế sử dụng các thỏa thuận thương mại để thúc đẩy các mục tiêu chính sách đối ngoại của quốc gia."}]}
    ]
  },
  {
    "id": "bioethics",
    "name": "Đạo Đức Sinh Học",
    "emoji": "🧬",
    "color": "pink",
    "words": [
      {"word": "genetic engineering", "meaning": "kỹ thuật di truyền", "emoji": "🧬", "class": "phrase",
       "examples": [{"en": "Genetic engineering allows scientists to modify the DNA of living organisms.", "vi": "Kỹ thuật di truyền cho phép các nhà khoa học sửa đổi DNA của sinh vật sống."},
                    {"en": "The ethical implications of human genetic engineering are widely debated.", "vi": "Các hệ quả đạo đức của kỹ thuật di truyền con người được tranh luận rộng rãi."}]},
      {"word": "gene editing", "meaning": "chỉnh sửa gen", "emoji": "✂️", "class": "phrase",
       "examples": [{"en": "CRISPR is a revolutionary gene editing technology with enormous medical potential.", "vi": "CRISPR là công nghệ chỉnh sửa gen cách mạng với tiềm năng y tế to lớn."},
                    {"en": "Gene editing to enhance intelligence or physical traits raises profound ethical questions.", "vi": "Chỉnh sửa gen để nâng cao trí thông minh hay đặc điểm thể chất đặt ra những câu hỏi đạo đức sâu sắc."}]},
      {"word": "human dignity", "meaning": "nhân phẩm", "emoji": "🌟", "class": "phrase",
       "examples": [{"en": "All medical procedures must respect the human dignity of the patient.", "vi": "Tất cả các thủ thuật y tế phải tôn trọng nhân phẩm của bệnh nhân."},
                    {"en": "Human dignity is the foundation of many arguments against reproductive cloning.", "vi": "Nhân phẩm là nền tảng của nhiều lập luận chống lại việc nhân bản sinh sản."}]},
      {"word": "stem cell", "meaning": "tế bào gốc", "emoji": "🔬", "class": "phrase",
       "examples": [{"en": "Stem cell research holds promise for treating diseases like Parkinson's and diabetes.", "vi": "Nghiên cứu tế bào gốc có tiềm năng trong điều trị các bệnh như Parkinson và tiểu đường."},
                    {"en": "Embryonic stem cell research is controversial due to questions about the moral status of embryos.", "vi": "Nghiên cứu tế bào gốc phôi gây tranh cãi do các câu hỏi về địa vị đạo đức của phôi."}]},
      {"word": "consent", "meaning": "sự đồng ý", "emoji": "✅", "class": "n",
       "examples": [{"en": "Obtaining free and informed consent is an ethical requirement in all biomedical research.", "vi": "Có được sự đồng ý tự do và đầy đủ thông tin là yêu cầu đạo đức trong mọi nghiên cứu y sinh."},
                    {"en": "Consent cannot be given on behalf of future generations affected by genetic changes.", "vi": "Sự đồng ý không thể được đưa ra thay mặt cho các thế hệ tương lai bị ảnh hưởng bởi những thay đổi di truyền."}]},
      {"word": "enhancement", "meaning": "tăng cường năng lực con người", "emoji": "⬆️", "class": "n",
       "examples": [{"en": "Cognitive enhancement through drugs raises questions about fairness and authenticity.", "vi": "Tăng cường nhận thức qua thuốc đặt ra câu hỏi về công bằng và tính xác thực."},
                    {"en": "Some bioethicists argue that human enhancement is a natural extension of medicine.", "vi": "Một số nhà đạo đức sinh học cho rằng tăng cường con người là sự mở rộng tự nhiên của y học."}]},
      {"word": "autonomy", "meaning": "quyền tự quyết", "emoji": "🗽", "class": "n",
       "examples": [{"en": "Bioethical debates often centre on balancing individual autonomy with collective welfare.", "vi": "Các cuộc tranh luận đạo đức sinh học thường tập trung vào cân bằng quyền tự quyết cá nhân với phúc lợi tập thể."},
                    {"en": "Reproductive autonomy means individuals have the right to decide whether and how to have children.", "vi": "Quyền tự quyết sinh sản có nghĩa là cá nhân có quyền quyết định có hay không và làm thế nào để có con."}]},
      {"word": "regulation", "meaning": "quy định", "emoji": "📏", "class": "n",
       "examples": [{"en": "International regulation of genetic research is needed to prevent reckless experimentation.", "vi": "Cần quy định quốc tế về nghiên cứu di truyền để ngăn chặn thử nghiệm thiếu cẩn thận."},
                    {"en": "Without strict regulation, advances in biotechnology could be exploited for harmful purposes.", "vi": "Không có quy định nghiêm ngặt, các tiến bộ trong công nghệ sinh học có thể bị lạm dụng cho mục đích có hại."}]},
      {"word": "moral", "meaning": "đạo đức", "emoji": "🧭", "class": "adj",
       "examples": [{"en": "The moral status of embryos is one of the most contested questions in bioethics.", "vi": "Địa vị đạo đức của phôi là một trong những câu hỏi gây tranh cãi nhất trong đạo đức sinh học."},
                    {"en": "Cloning raises profound moral concerns that cross religious and secular boundaries.", "vi": "Nhân bản vô tính đặt ra những lo ngại đạo đức sâu sắc vượt qua ranh giới tôn giáo và thế tục."}]},
      {"word": "research ethics", "meaning": "đạo đức nghiên cứu", "emoji": "🎓", "class": "phrase",
       "examples": [{"en": "Research ethics require that scientific benefits never outweigh unacceptable risks to participants.", "vi": "Đạo đức nghiên cứu yêu cầu rằng lợi ích khoa học không bao giờ vượt qua rủi ro không thể chấp nhận cho người tham gia."},
                    {"en": "Advances in AI are raising new questions in research ethics about data and privacy.", "vi": "Những tiến bộ trong AI đang đặt ra các câu hỏi mới trong đạo đức nghiên cứu về dữ liệu và quyền riêng tư."}]},
      {"word": "impact", "meaning": "tác động", "emoji": "🌊", "class": "n",
       "examples": [{"en": "The long-term impact of gene editing on future generations is still unknown.", "vi": "Tác động lâu dài của chỉnh sửa gen đối với các thế hệ tương lai vẫn chưa được biết."},
                    {"en": "Assessing the societal impact of biotechnology requires input from diverse disciplines.", "vi": "Đánh giá tác động xã hội của công nghệ sinh học đòi hỏi đầu vào từ nhiều lĩnh vực khác nhau."}]}
    ]
  },
  {
    "id": "argumentation",
    "name": "Lập Luận",
    "emoji": "💬",
    "color": "gray",
    "words": [
      {"word": "evidence", "meaning": "bằng chứng", "emoji": "🔍", "class": "n",
       "examples": [{"en": "Strong arguments are grounded in reliable and verifiable evidence.", "vi": "Các lập luận mạnh mẽ được xây dựng trên bằng chứng đáng tin cậy và có thể kiểm chứng."},
                    {"en": "Anecdotal evidence should not be used as the sole basis for a conclusion.", "vi": "Bằng chứng giai thoại không nên được dùng làm cơ sở duy nhất cho một kết luận."}]},
      {"word": "counterargument", "meaning": "phản luận", "emoji": "↩️", "class": "n",
       "examples": [{"en": "Anticipating counterarguments makes your position more robust and persuasive.", "vi": "Dự đoán trước các phản luận làm cho lập trường của bạn vững chắc và thuyết phục hơn."},
                    {"en": "She offered a compelling counterargument that undermined the main thesis.", "vi": "Cô đưa ra một phản luận thuyết phục làm suy yếu luận điểm chính."}]},
      {"word": "fallacy", "meaning": "ngụy biện", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "The straw man fallacy misrepresents the opponent's position to make it easier to attack.", "vi": "Ngụy biện người rơm xuyên tạc lập trường của đối phương để dễ bác bỏ hơn."},
                    {"en": "Pointing out a fallacy in someone's reasoning can discredit their entire argument.", "vi": "Chỉ ra ngụy biện trong lý luận của ai đó có thể làm mất uy tín toàn bộ lập luận của họ."}]},
      {"word": "premise", "meaning": "tiền đề", "emoji": "🔑", "class": "n",
       "examples": [{"en": "A valid argument must begin with a well-supported and true premise.", "vi": "Một lập luận hợp lệ phải bắt đầu bằng một tiền đề được hỗ trợ tốt và đúng sự thật."},
                    {"en": "The entire argument rests on one shaky premise that has not been proven.", "vi": "Toàn bộ lập luận dựa trên một tiền đề lung lay chưa được chứng minh."}]},
      {"word": "assumption", "meaning": "giả định", "emoji": "💭", "class": "n",
       "examples": [{"en": "Challenging an assumption can change the entire direction of an argument.", "vi": "Thách thức một giả định có thể thay đổi toàn bộ hướng đi của một lập luận."},
                    {"en": "The policy was based on the flawed assumption that economic growth would solve inequality.", "vi": "Chính sách dựa trên giả định sai lầm rằng tăng trưởng kinh tế sẽ giải quyết bất bình đẳng."}]},
      {"word": "inference", "meaning": "suy luận", "emoji": "🔗", "class": "n",
       "examples": [{"en": "A logical inference draws a reasonable conclusion from the available evidence.", "vi": "Suy luận logic rút ra kết luận hợp lý từ bằng chứng có sẵn."},
                    {"en": "Be careful not to make inferences that go beyond what the data actually supports.", "vi": "Hãy cẩn thận không đưa ra các suy luận vượt quá những gì dữ liệu thực sự hỗ trợ."}]},
      {"word": "assertion", "meaning": "khẳng định", "emoji": "📌", "class": "n",
       "examples": [{"en": "An assertion without supporting evidence is not a valid academic argument.", "vi": "Một khẳng định không có bằng chứng hỗ trợ không phải là lập luận học thuật hợp lệ."},
                    {"en": "The politician made a series of bold assertions that were not backed by facts.", "vi": "Chính trị gia đưa ra một loạt khẳng định táo bạo không được hỗ trợ bởi sự thật."}]},
      {"word": "evaluate", "meaning": "đánh giá", "emoji": "📊", "class": "v",
       "examples": [{"en": "Students must evaluate the strength and limitations of each source they use.", "vi": "Sinh viên phải đánh giá điểm mạnh và hạn chế của mỗi nguồn họ sử dụng."},
                    {"en": "To evaluate an argument fairly, consider both its strengths and weaknesses.", "vi": "Để đánh giá một lập luận công bằng, hãy xem xét cả điểm mạnh và điểm yếu của nó."}]},
      {"word": "perspective", "meaning": "quan điểm", "emoji": "👁️", "class": "n",
       "examples": [{"en": "A strong argument acknowledges multiple perspectives before advocating for one.", "vi": "Một lập luận mạnh thừa nhận nhiều quan điểm trước khi bảo vệ một quan điểm."},
                    {"en": "Reading from different perspectives enriches your ability to critically evaluate ideas.", "vi": "Đọc từ nhiều quan điểm khác nhau làm phong phú khả năng đánh giá phê phán các ý tưởng của bạn."}]},
      {"word": "coherence", "meaning": "tính mạch lạc", "emoji": "🔗", "class": "n",
       "examples": [{"en": "Coherence means that each part of your argument flows logically from the last.", "vi": "Tính mạch lạc có nghĩa là mỗi phần của lập luận của bạn chảy một cách logic từ phần trước."},
                    {"en": "Use clear transitions to maintain coherence across paragraphs.", "vi": "Sử dụng các từ nối rõ ràng để duy trì tính mạch lạc giữa các đoạn văn."}]},
      {"word": "substantiate", "meaning": "chứng minh, củng cố", "emoji": "✅", "class": "v",
       "examples": [{"en": "You need credible data to substantiate your claim about economic trends.", "vi": "Bạn cần dữ liệu đáng tin cậy để củng cố tuyên bố của mình về xu hướng kinh tế."},
                    {"en": "Failing to substantiate your main point will significantly weaken your argument.", "vi": "Không chứng minh được điểm chính của bạn sẽ làm suy yếu đáng kể lập luận của bạn."}]},
      {"word": "critique", "meaning": "phê bình", "emoji": "🖊️", "class": "n",
       "examples": [{"en": "A rigorous academic critique identifies both strengths and weaknesses in a study.", "vi": "Một phê bình học thuật nghiêm ngặt xác định cả điểm mạnh lẫn điểm yếu trong một nghiên cứu."},
                    {"en": "Her critique of the government's policy was detailed, fair, and evidence-based.", "vi": "Phê bình của cô về chính sách của chính phủ rất chi tiết, công bằng và dựa trên bằng chứng."}]}
    ]
  },
  {
    "id": "globalisation",
    "name": "Toàn Cầu Hóa",
    "emoji": "🌎",
    "color": "lime",
    "words": [
      {"word": "trade", "meaning": "thương mại", "emoji": "📦", "class": "n",
       "examples": [{"en": "International trade has lifted millions of people out of poverty in developing countries.", "vi": "Thương mại quốc tế đã đưa hàng triệu người thoát khỏi đói nghèo ở các nước đang phát triển."},
                    {"en": "Trade barriers such as tariffs reduce the benefits of economic integration.", "vi": "Các rào cản thương mại như thuế quan làm giảm lợi ích của hội nhập kinh tế."}]},
      {"word": "interdependence", "meaning": "sự phụ thuộc lẫn nhau", "emoji": "🔗", "class": "n",
       "examples": [{"en": "Economic interdependence means that a crisis in one country quickly affects others.", "vi": "Sự phụ thuộc lẫn nhau về kinh tế có nghĩa là khủng hoảng ở một quốc gia nhanh chóng ảnh hưởng đến các quốc gia khác."},
                    {"en": "Global supply chains have deepened interdependence between producers and consumers.", "vi": "Chuỗi cung ứng toàn cầu đã làm sâu sắc hơn sự phụ thuộc lẫn nhau giữa người sản xuất và người tiêu dùng."}]},
      {"word": "migration", "meaning": "di cư", "emoji": "✈️", "class": "n",
       "examples": [{"en": "Labour migration allows workers to seek better opportunities in other countries.", "vi": "Di cư lao động cho phép người lao động tìm kiếm cơ hội tốt hơn ở các quốc gia khác."},
                    {"en": "Climate change is expected to trigger large-scale migration in coming decades.", "vi": "Biến đổi khí hậu dự kiến sẽ kích hoạt di cư quy mô lớn trong những thập kỷ tới."}]},
      {"word": "corporation", "meaning": "tập đoàn đa quốc gia", "emoji": "🏢", "class": "n",
       "examples": [{"en": "Multinational corporations can exert significant influence over developing country economies.", "vi": "Các tập đoàn đa quốc gia có thể tác động đáng kể đến nền kinh tế các nước đang phát triển."},
                    {"en": "Some corporations use offshore tax havens to reduce their tax obligations.", "vi": "Một số tập đoàn sử dụng các thiên đường thuế ngoài khơi để giảm nghĩa vụ thuế của họ."}]},
      {"word": "integration", "meaning": "hội nhập", "emoji": "🔗", "class": "n",
       "examples": [{"en": "Regional integration in Europe has created a single market with free movement of goods and people.", "vi": "Hội nhập khu vực ở châu Âu đã tạo ra một thị trường chung với hàng hóa và người tự do di chuyển."},
                    {"en": "Economic integration increases efficiency but can reduce national policy independence.", "vi": "Hội nhập kinh tế tăng hiệu quả nhưng có thể giảm sự độc lập chính sách quốc gia."}]},
      {"word": "dominance", "meaning": "sự thống trị", "emoji": "👑", "class": "n",
       "examples": [{"en": "Cultural dominance occurs when powerful countries' values and products crowd out local cultures.", "vi": "Sự thống trị văn hóa xảy ra khi các giá trị và sản phẩm của các quốc gia quyền lực lấn át các nền văn hóa địa phương."},
                    {"en": "Some nations seek to challenge the economic dominance of existing superpowers.", "vi": "Một số quốc gia tìm cách thách thức sự thống trị kinh tế của các siêu cường hiện tại."}]},
      {"word": "localization", "meaning": "địa phương hóa", "emoji": "📍", "class": "n",
       "examples": [{"en": "Localization means adapting global products to meet local cultural preferences.", "vi": "Địa phương hóa có nghĩa là điều chỉnh sản phẩm toàn cầu để đáp ứng sở thích văn hóa địa phương."},
                    {"en": "The tension between globalisation and localization reflects broader debates about identity.", "vi": "Căng thẳng giữa toàn cầu hóa và địa phương hóa phản ánh các cuộc tranh luận rộng hơn về bản sắc."}]},
      {"word": "inequality", "meaning": "bất bình đẳng", "emoji": "📊", "class": "n",
       "examples": [{"en": "Critics argue that globalisation has increased inequality both within and between countries.", "vi": "Các nhà phê bình cho rằng toàn cầu hóa đã gia tăng bất bình đẳng cả trong và giữa các quốc gia."},
                    {"en": "Addressing global inequality requires both fair trade rules and domestic redistribution policies.", "vi": "Giải quyết bất bình đẳng toàn cầu đòi hỏi cả các quy tắc thương mại công bằng và chính sách phân phối lại trong nước."}]},
      {"word": "competition", "meaning": "cạnh tranh", "emoji": "🏆", "class": "n",
       "examples": [{"en": "Global competition drives innovation but can also lead to a race to the bottom on wages.", "vi": "Cạnh tranh toàn cầu thúc đẩy đổi mới nhưng cũng có thể dẫn đến cuộc đua xuống đáy về tiền lương."},
                    {"en": "Countries compete to attract foreign investment by offering tax incentives and skilled labour.", "vi": "Các quốc gia cạnh tranh để thu hút đầu tư nước ngoài bằng cách cung cấp ưu đãi thuế và lao động có kỹ năng."}]},
      {"word": "influence", "meaning": "ảnh hưởng", "emoji": "🌀", "class": "n",
       "examples": [{"en": "The influence of American popular culture has spread to nearly every corner of the world.", "vi": "Ảnh hưởng của văn hóa đại chúng Mỹ đã lan rộng đến gần như mọi nơi trên thế giới."},
                    {"en": "Soft power refers to the influence a country gains through cultural and educational exchange.", "vi": "Sức mạnh mềm đề cập đến ảnh hưởng mà một quốc gia đạt được qua trao đổi văn hóa và giáo dục."}]},
      {"word": "opportunity", "meaning": "cơ hội", "emoji": "🌟", "class": "n",
       "examples": [{"en": "Globalisation has created enormous opportunity for countries that can compete effectively.", "vi": "Toàn cầu hóa đã tạo ra cơ hội khổng lồ cho các quốc gia có thể cạnh tranh hiệu quả."},
                    {"en": "Digital technologies have opened up new economic opportunities for people in remote areas.", "vi": "Các công nghệ kỹ thuật số đã mở ra các cơ hội kinh tế mới cho người dân ở các khu vực hẻo lánh."}]}
    ]
  },
  {
    "id": "social-change",
    "name": "Biến Đổi Xã Hội",
    "emoji": "✊",
    "color": "fuchsia",
    "words": [
      {"word": "movement", "meaning": "phong trào (xã hội)", "emoji": "✊", "class": "n",
       "examples": [{"en": "The civil rights movement transformed race relations in the United States.", "vi": "Phong trào quyền dân sự đã biến đổi quan hệ chủng tộc ở Hoa Kỳ."},
                    {"en": "Social media has made it easier for grassroots movements to organise and mobilise.", "vi": "Mạng xã hội đã giúp dễ dàng hơn cho các phong trào cơ sở tổ chức và huy động."}]},
      {"word": "protest", "meaning": "biểu tình", "emoji": "📢", "class": "n",
       "examples": [{"en": "Mass protests pressured the government into reconsidering its controversial policy.", "vi": "Các cuộc biểu tình hàng loạt gây áp lực buộc chính phủ xem xét lại chính sách gây tranh cãi."},
                    {"en": "The right to peaceful protest is protected in most democratic constitutions.", "vi": "Quyền biểu tình ôn hòa được bảo vệ trong hầu hết các hiến pháp dân chủ."}]},
      {"word": "advocacy", "meaning": "vận động (xã hội)", "emoji": "📣", "class": "n",
       "examples": [{"en": "Effective advocacy combines public awareness campaigns with direct political lobbying.", "vi": "Vận động hiệu quả kết hợp các chiến dịch nâng cao nhận thức công chúng với vận động chính trị trực tiếp."},
                    {"en": "Human rights advocacy has led to significant legal reforms in many countries.", "vi": "Vận động quyền con người đã dẫn đến các cải cách pháp lý đáng kể ở nhiều quốc gia."}]},
      {"word": "activism", "meaning": "chủ nghĩa hoạt động", "emoji": "🌱", "class": "n",
       "examples": [{"en": "Youth activism on climate change has put pressure on governments to act more urgently.", "vi": "Chủ nghĩa hoạt động của giới trẻ về biến đổi khí hậu đã gây áp lực buộc chính phủ hành động khẩn cấp hơn."},
                    {"en": "Online activism can raise awareness rapidly but may not always lead to lasting change.", "vi": "Hoạt động trực tuyến có thể nâng cao nhận thức nhanh chóng nhưng không phải lúc nào cũng dẫn đến thay đổi lâu dài."}]},
      {"word": "transformation", "meaning": "sự biến đổi", "emoji": "🦋", "class": "n",
       "examples": [{"en": "Social transformation requires changing both laws and deep-seated cultural attitudes.", "vi": "Biến đổi xã hội đòi hỏi thay đổi cả luật pháp và thái độ văn hóa ăn sâu."},
                    {"en": "Economic transformation in many Asian countries lifted hundreds of millions out of poverty.", "vi": "Sự biến đổi kinh tế ở nhiều quốc gia châu Á đã đưa hàng trăm triệu người thoát khỏi đói nghèo."}]},
      {"word": "solidarity", "meaning": "đoàn kết", "emoji": "🤝", "class": "n",
       "examples": [{"en": "Solidarity between workers led to the formation of powerful trade unions.", "vi": "Sự đoàn kết giữa người lao động dẫn đến sự hình thành các công đoàn quyền lực."},
                    {"en": "International solidarity is essential when responding to large-scale humanitarian crises.", "vi": "Đoàn kết quốc tế là thiết yếu khi ứng phó với các cuộc khủng hoảng nhân đạo quy mô lớn."}]},
      {"word": "resistance", "meaning": "kháng cự, phản kháng", "emoji": "✊", "class": "n",
       "examples": [{"en": "Peaceful resistance has historically been an effective tool for challenging unjust systems.", "vi": "Phản kháng ôn hòa trong lịch sử là công cụ hiệu quả để thách thức các hệ thống bất công."},
                    {"en": "Cultural resistance preserves traditions under threat from dominant external influences.", "vi": "Phản kháng văn hóa bảo tồn các truyền thống bị đe dọa từ những ảnh hưởng bên ngoài thống trị."}]},
      {"word": "mobilize", "meaning": "huy động", "emoji": "📣", "class": "v",
       "examples": [{"en": "Social media has transformed how quickly activists can mobilize large numbers of people.", "vi": "Mạng xã hội đã thay đổi tốc độ mà các nhà hoạt động có thể huy động số lượng lớn người."},
                    {"en": "Mobilizing public opinion is the first step in building pressure for policy change.", "vi": "Huy động dư luận là bước đầu tiên trong việc tạo áp lực cho sự thay đổi chính sách."}]},
      {"word": "demonstration", "meaning": "cuộc biểu tình", "emoji": "👥", "class": "n",
       "examples": [{"en": "A peaceful demonstration outside parliament attracted thousands of supporters.", "vi": "Một cuộc biểu tình ôn hòa bên ngoài quốc hội thu hút hàng ngàn người ủng hộ."},
                    {"en": "The demonstration turned violent when police used excessive force against protesters.", "vi": "Cuộc biểu tình trở nên bạo lực khi cảnh sát sử dụng vũ lực quá mức chống lại người biểu tình."}]},
      {"word": "reform", "meaning": "cải cách", "emoji": "🔧", "class": "n",
       "examples": [{"en": "Land reform redistributed wealth and reduced rural inequality in several countries.", "vi": "Cải cách ruộng đất phân phối lại của cải và giảm bất bình đẳng nông thôn ở một số quốc gia."},
                    {"en": "Institutional reform is often resisted by those who benefit from existing arrangements.", "vi": "Cải cách thể chế thường bị những người hưởng lợi từ các sắp xếp hiện tại chống lại."}]},
      {"word": "justice", "meaning": "công lý", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Social justice movements seek equal rights and opportunities for all members of society.", "vi": "Các phong trào công lý xã hội tìm kiếm quyền lợi và cơ hội bình đẳng cho tất cả thành viên xã hội."},
                    {"en": "Climate justice recognises that the most vulnerable populations bear the greatest burden.", "vi": "Công lý khí hậu công nhận rằng các dân số dễ bị tổn thương nhất phải chịu gánh nặng lớn nhất."}]}
    ]
  },
  {
    "id": "immigration-identity",
    "name": "Di Dân & Bản Sắc",
    "emoji": "🏘️",
    "color": "stone",
    "words": [
      {"word": "diaspora", "meaning": "cộng đồng người di cư", "emoji": "🌍", "class": "n",
       "examples": [{"en": "The Vietnamese diaspora has created vibrant communities in countries like the US and Australia.", "vi": "Cộng đồng người Việt di cư đã tạo ra các cộng đồng sôi động ở các quốc gia như Mỹ và Úc."},
                    {"en": "Diaspora communities often maintain strong cultural ties to their countries of origin.", "vi": "Các cộng đồng người di cư thường duy trì mối liên hệ văn hóa mạnh mẽ với quê hương."}]},
      {"word": "integration", "meaning": "hội nhập (xã hội)", "emoji": "🔗", "class": "n",
       "examples": [{"en": "Successful integration requires effort from both the host society and immigrants.", "vi": "Hội nhập thành công đòi hỏi nỗ lực từ cả xã hội tiếp nhận lẫn người nhập cư."},
                    {"en": "Language learning is one of the most important steps towards social integration.", "vi": "Học ngôn ngữ là một trong những bước quan trọng nhất hướng tới hội nhập xã hội."}]},
      {"word": "assimilation", "meaning": "đồng hóa văn hóa", "emoji": "🔄", "class": "n",
       "examples": [{"en": "Forced assimilation erases cultural identity and can cause lasting psychological harm.", "vi": "Đồng hóa cưỡng bức xóa bỏ bản sắc văn hóa và có thể gây hại tâm lý lâu dài."},
                    {"en": "Some argue that assimilation into mainstream culture is necessary for social cohesion.", "vi": "Một số người cho rằng đồng hóa vào văn hóa chính thống là cần thiết cho sự gắn kết xã hội."}]},
      {"word": "belonging", "meaning": "cảm giác thuộc về", "emoji": "💞", "class": "n",
       "examples": [{"en": "A sense of belonging is essential for psychological wellbeing in immigrant communities.", "vi": "Cảm giác thuộc về là thiết yếu cho sức khỏe tâm lý trong cộng đồng người nhập cư."},
                    {"en": "Many second-generation immigrants struggle with a sense of belonging to two different cultures.", "vi": "Nhiều người nhập cư thế hệ thứ hai đấu tranh với cảm giác thuộc về hai nền văn hóa khác nhau."}]},
      {"word": "multiculturalism", "meaning": "chủ nghĩa đa văn hóa", "emoji": "🌈", "class": "n",
       "examples": [{"en": "Multiculturalism celebrates diversity and encourages different cultures to coexist.", "vi": "Chủ nghĩa đa văn hóa tôn vinh sự đa dạng và khuyến khích các nền văn hóa khác nhau cùng tồn tại."},
                    {"en": "Critics of multiculturalism argue it can hinder social cohesion if not managed carefully.", "vi": "Những người chỉ trích chủ nghĩa đa văn hóa cho rằng nó có thể cản trở sự gắn kết xã hội nếu không được quản lý cẩn thận."}]},
      {"word": "minority", "meaning": "thiểu số", "emoji": "👥", "class": "n",
       "examples": [{"en": "Protecting the rights of ethnic and religious minorities is a mark of a democratic society.", "vi": "Bảo vệ quyền của các nhóm dân tộc và tôn giáo thiểu số là dấu hiệu của xã hội dân chủ."},
                    {"en": "Minority communities often face barriers in employment and housing.", "vi": "Các cộng đồng thiểu số thường đối mặt với rào cản trong việc làm và nhà ở."}]},
      {"word": "host country", "meaning": "quốc gia tiếp nhận", "emoji": "🏠", "class": "phrase",
       "examples": [{"en": "The host country has a responsibility to provide basic rights to asylum seekers.", "vi": "Quốc gia tiếp nhận có trách nhiệm cung cấp quyền cơ bản cho người xin tị nạn."},
                    {"en": "Immigrants often contribute significantly to the host country's economy and culture.", "vi": "Người nhập cư thường đóng góp đáng kể vào kinh tế và văn hóa của quốc gia tiếp nhận."}]},
      {"word": "acceptance", "meaning": "sự chấp nhận", "emoji": "🤗", "class": "n",
       "examples": [{"en": "Social acceptance of immigrants is crucial for community harmony and cohesion.", "vi": "Sự chấp nhận xã hội đối với người nhập cư rất quan trọng cho sự hài hòa và gắn kết cộng đồng."},
                    {"en": "Acceptance of cultural differences requires education, empathy, and open-mindedness.", "vi": "Chấp nhận sự khác biệt văn hóa đòi hỏi giáo dục, sự đồng cảm và tư duy cởi mở."}]},
      {"word": "transnational", "meaning": "xuyên quốc gia", "emoji": "🌐", "class": "adj",
       "examples": [{"en": "Transnational identities challenge traditional notions of national belonging.", "vi": "Bản sắc xuyên quốc gia thách thức các khái niệm truyền thống về sự thuộc về quốc gia."},
                    {"en": "Many migrants maintain transnational ties by sending remittances and returning regularly.", "vi": "Nhiều người di cư duy trì mối liên hệ xuyên quốc gia bằng cách gửi kiều hối và trở về thường xuyên."}]},
      {"word": "cultural exchange", "meaning": "trao đổi văn hóa", "emoji": "🌍", "class": "phrase",
       "examples": [{"en": "Cultural exchange through immigration enriches the arts, cuisine, and intellectual life of a society.", "vi": "Trao đổi văn hóa qua di cư làm phong phú nghệ thuật, ẩm thực và đời sống trí tuệ của xã hội."},
                    {"en": "Meaningful cultural exchange requires mutual respect rather than one-sided assimilation.", "vi": "Trao đổi văn hóa có ý nghĩa đòi hỏi sự tôn trọng lẫn nhau hơn là đồng hóa một chiều."}]},
      {"word": "identity", "meaning": "bản sắc", "emoji": "🪞", "class": "n",
       "examples": [{"en": "Immigration often leads people to question and renegotiate their sense of identity.", "vi": "Di cư thường khiến mọi người đặt câu hỏi và đàm phán lại cảm giác bản sắc của họ."},
                    {"en": "Cultural identity is shaped by language, history, shared values, and lived experience.", "vi": "Bản sắc văn hóa được định hình bởi ngôn ngữ, lịch sử, các giá trị chung và trải nghiệm sống."}]}
    ]
  },
  {
    "id": "psychology-society",
    "name": "Tâm Lý Xã Hội",
    "emoji": "🧠",
    "color": "indigo",
    "words": [
      {"word": "bias", "meaning": "thành kiến tâm lý", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Confirmation bias leads people to seek information that supports their existing beliefs.", "vi": "Thành kiến xác nhận khiến mọi người tìm kiếm thông tin ủng hộ niềm tin hiện có của họ."},
                    {"en": "Unconscious bias affects hiring decisions even in organisations committed to equality.", "vi": "Thành kiến vô thức ảnh hưởng đến các quyết định tuyển dụng ngay cả trong các tổ chức cam kết bình đẳng."}]},
      {"word": "prejudice", "meaning": "định kiến", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Racial prejudice can persist even among people who believe they are open-minded.", "vi": "Định kiến chủng tộc có thể tồn tại ngay cả ở những người tin rằng họ có tư duy cởi mở."},
                    {"en": "Education is one of the most powerful tools for combating prejudice and discrimination.", "vi": "Giáo dục là một trong những công cụ mạnh mẽ nhất để chống lại định kiến và phân biệt đối xử."}]},
      {"word": "conformity", "meaning": "tuân thủ theo đám đông", "emoji": "👥", "class": "n",
       "examples": [{"en": "Social conformity pressure means individuals often abandon their own views to fit in.", "vi": "Áp lực tuân thủ xã hội có nghĩa là cá nhân thường từ bỏ quan điểm của mình để hòa nhập."},
                    {"en": "Classic psychology experiments showed the surprising extent of human conformity.", "vi": "Các thí nghiệm tâm lý học kinh điển cho thấy mức độ đáng ngạc nhiên của sự tuân thủ của con người."}]},
      {"word": "motivation", "meaning": "động lực", "emoji": "🚀", "class": "n",
       "examples": [{"en": "Intrinsic motivation, driven by personal interest, leads to greater long-term achievement.", "vi": "Động lực nội tại, được thúc đẩy bởi sở thích cá nhân, dẫn đến thành tựu lâu dài lớn hơn."},
                    {"en": "Understanding what drives employee motivation is key to effective management.", "vi": "Hiểu điều gì thúc đẩy động lực của nhân viên là chìa khóa để quản lý hiệu quả."}]},
      {"word": "perception", "meaning": "nhận thức", "emoji": "👁️", "class": "n",
       "examples": [{"en": "Perception of risk varies widely across individuals and cultures.", "vi": "Nhận thức về rủi ro khác nhau đáng kể giữa các cá nhân và nền văn hóa."},
                    {"en": "Media shapes public perception of social groups through selective representation.", "vi": "Truyền thông định hình nhận thức công chúng về các nhóm xã hội thông qua sự đại diện chọn lọc."}]},
      {"word": "social pressure", "meaning": "áp lực xã hội", "emoji": "⬇️", "class": "phrase",
       "examples": [{"en": "Social pressure can cause individuals to make decisions that go against their values.", "vi": "Áp lực xã hội có thể khiến cá nhân đưa ra các quyết định đi ngược lại giá trị của họ."},
                    {"en": "Peer pressure is a form of social pressure that particularly affects adolescents.", "vi": "Áp lực bạn bè là một hình thức áp lực xã hội đặc biệt ảnh hưởng đến thanh thiếu niên."}]},
      {"word": "manipulation", "meaning": "thao túng", "emoji": "🎭", "class": "n",
       "examples": [{"en": "Propaganda uses psychological manipulation to control how people think and feel.", "vi": "Tuyên truyền sử dụng thao túng tâm lý để kiểm soát cách người ta suy nghĩ và cảm nhận."},
                    {"en": "Emotional manipulation in relationships involves exploiting vulnerabilities to gain control.", "vi": "Thao túng cảm xúc trong các mối quan hệ bao gồm khai thác điểm yếu để giành quyền kiểm soát."}]},
      {"word": "groupthink", "meaning": "tư duy nhóm", "emoji": "🧩", "class": "n",
       "examples": [{"en": "Groupthink led the committee to ignore critical warnings and make a disastrous decision.", "vi": "Tư duy nhóm khiến ủy ban bỏ qua các cảnh báo quan trọng và đưa ra quyết định thảm họa."},
                    {"en": "Encouraging dissent within teams helps prevent groupthink and improves decision quality.", "vi": "Khuyến khích ý kiến bất đồng trong nhóm giúp ngăn ngừa tư duy nhóm và cải thiện chất lượng quyết định."}]},
      {"word": "stereotype", "meaning": "khuôn mẫu", "emoji": "🏷️", "class": "n",
       "examples": [{"en": "Gender stereotypes limit career choices for both men and women.", "vi": "Các khuôn mẫu giới tính hạn chế lựa chọn nghề nghiệp cho cả nam và nữ."},
                    {"en": "Positive stereotypes are also harmful because they reduce individuals to oversimplified categories.", "vi": "Các khuôn mẫu tích cực cũng có hại vì chúng thu hẹp cá nhân thành các danh mục đơn giản hóa quá mức."}]},
      {"word": "attitude", "meaning": "thái độ", "emoji": "🧭", "class": "n",
       "examples": [{"en": "Changing public attitudes towards mental health has reduced stigma significantly.", "vi": "Thay đổi thái độ của công chúng đối với sức khỏe tâm thần đã giảm đáng kể kỳ thị."},
                    {"en": "Attitudes toward authority and hierarchy vary greatly across different cultures.", "vi": "Thái độ đối với quyền lực và hệ thứ bậc khác nhau rất lớn giữa các nền văn hóa khác nhau."}]},
      {"word": "cognitive", "meaning": "nhận thức, thuộc về nhận thức", "emoji": "🧠", "class": "adj",
       "examples": [{"en": "Cognitive distortions are unhelpful thinking patterns that fuel anxiety and depression.", "vi": "Méo mó nhận thức là các kiểu suy nghĩ không hữu ích thúc đẩy lo lắng và trầm cảm."},
                    {"en": "Cognitive development in children is shaped by education, environment, and social interaction.", "vi": "Phát triển nhận thức ở trẻ em được định hình bởi giáo dục, môi trường và tương tác xã hội."}]}
    ]
  },
  {
    "id": "consumer-society",
    "name": "Xã Hội Tiêu Dùng",
    "emoji": "🛒",
    "color": "amber",
    "words": [
      {"word": "consumption", "meaning": "tiêu thụ", "emoji": "📦", "class": "n",
       "examples": [{"en": "Mass consumption of cheap goods has led to enormous environmental waste.", "vi": "Tiêu thụ hàng loạt hàng hóa rẻ đã dẫn đến lãng phí môi trường khổng lồ."},
                    {"en": "Reducing consumption is considered one of the most effective ways to lower carbon emissions.", "vi": "Giảm tiêu thụ được coi là một trong những cách hiệu quả nhất để giảm phát thải carbon."}]},
      {"word": "materialism", "meaning": "chủ nghĩa vật chất", "emoji": "💎", "class": "n",
       "examples": [{"en": "Critics of materialism argue that the pursuit of possessions rarely leads to lasting happiness.", "vi": "Những người chỉ trích chủ nghĩa vật chất cho rằng việc theo đuổi của cải hiếm khi dẫn đến hạnh phúc lâu dài."},
                    {"en": "Consumer materialism is deeply embedded in the values promoted by modern advertising.", "vi": "Chủ nghĩa vật chất tiêu dùng được nhúng sâu vào các giá trị được quảng bá bởi quảng cáo hiện đại."}]},
      {"word": "status", "meaning": "địa vị xã hội", "emoji": "👑", "class": "n",
       "examples": [{"en": "Luxury brands exploit the desire for social status to justify premium pricing.", "vi": "Các thương hiệu xa xỉ khai thác mong muốn địa vị xã hội để biện minh cho giá cao cấp."},
                    {"en": "Status consumption is the purchase of goods primarily to signal wealth or success.", "vi": "Tiêu dùng địa vị là việc mua hàng hóa chủ yếu để thể hiện sự giàu có hay thành công."}]},
      {"word": "waste", "meaning": "lãng phí", "emoji": "🗑️", "class": "n",
       "examples": [{"en": "Fast fashion generates enormous textile waste that ends up in landfills.", "vi": "Thời trang nhanh tạo ra lượng lớn chất thải dệt may kết thúc trong bãi chôn lấp."},
                    {"en": "Reducing food waste is both an environmental and ethical imperative.", "vi": "Giảm lãng phí thực phẩm là cả một mệnh lệnh môi trường và đạo đức."}]},
      {"word": "aspiration", "meaning": "khát vọng", "emoji": "⭐", "class": "n",
       "examples": [{"en": "Advertising exploits social aspirations to make consumers feel inadequate without certain products.", "vi": "Quảng cáo khai thác các khát vọng xã hội để khiến người tiêu dùng cảm thấy thiếu thốn nếu không có sản phẩm nhất định."},
                    {"en": "Consumer aspirations are shaped by the lifestyles portrayed in media and popular culture.", "vi": "Các khát vọng tiêu dùng được định hình bởi các lối sống được miêu tả trong truyền thông và văn hóa đại chúng."}]},
      {"word": "impulse", "meaning": "bốc đồng", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Retailers design store layouts to encourage impulse buying near checkout counters.", "vi": "Các nhà bán lẻ thiết kế bố cục cửa hàng để khuyến khích mua hàng bốc đồng gần quầy thanh toán."},
                    {"en": "Impulse purchases often lead to regret when consumers reflect on unnecessary spending.", "vi": "Mua hàng bốc đồng thường dẫn đến hối tiếc khi người tiêu dùng suy nghĩ về chi tiêu không cần thiết."}]},
      {"word": "sustainability", "meaning": "tính bền vững", "emoji": "♻️", "class": "n",
       "examples": [{"en": "Sustainability in consumer choices means selecting products with lower environmental impact.", "vi": "Tính bền vững trong lựa chọn tiêu dùng có nghĩa là chọn sản phẩm có tác động môi trường thấp hơn."},
                    {"en": "Growing consumer demand for sustainability is pushing companies to reform their supply chains.", "vi": "Nhu cầu ngày càng tăng của người tiêu dùng về tính bền vững đang thúc đẩy các công ty cải cách chuỗi cung ứng."}]},
      {"word": "debt", "meaning": "nợ tiêu dùng", "emoji": "💳", "class": "n",
       "examples": [{"en": "Easy access to credit has led many consumers into unsustainable levels of personal debt.", "vi": "Tiếp cận tín dụng dễ dàng đã khiến nhiều người tiêu dùng rơi vào mức nợ cá nhân không bền vững."},
                    {"en": "Consumer debt fuels economic growth in the short term but creates long-term vulnerability.", "vi": "Nợ tiêu dùng thúc đẩy tăng trưởng kinh tế ngắn hạn nhưng tạo ra dễ bị tổn thương dài hạn."}]},
      {"word": "brand", "meaning": "thương hiệu", "emoji": "🏷️", "class": "n",
       "examples": [{"en": "Brand loyalty can be irrational, with consumers paying more for identical products.", "vi": "Lòng trung thành với thương hiệu có thể phi lý, với người tiêu dùng trả nhiều hơn cho các sản phẩm giống hệt nhau."},
                    {"en": "Global brands shape consumer culture and homogenise tastes across different societies.", "vi": "Các thương hiệu toàn cầu định hình văn hóa tiêu dùng và đồng nhất hóa khẩu vị ở các xã hội khác nhau."}]},
      {"word": "wellbeing", "meaning": "sức khỏe toàn diện", "emoji": "🌟", "class": "n",
       "examples": [{"en": "Research shows that beyond a basic income level, more consumption does not improve wellbeing.", "vi": "Nghiên cứu cho thấy rằng vượt qua mức thu nhập cơ bản, tiêu dùng nhiều hơn không cải thiện sức khỏe toàn diện."},
                    {"en": "A shift from material consumption to experiences is associated with greater wellbeing.", "vi": "Sự chuyển dịch từ tiêu dùng vật chất sang trải nghiệm được liên kết với sức khỏe toàn diện lớn hơn."}]},
      {"word": "inequality", "meaning": "bất bình đẳng", "emoji": "📊", "class": "n",
       "examples": [{"en": "Consumer society can deepen inequality when only the wealthy can afford sustainable products.", "vi": "Xã hội tiêu dùng có thể làm sâu sắc hơn bất bình đẳng khi chỉ người giàu mới có thể mua sản phẩm bền vững."},
                    {"en": "Inequality in consumer societies leads to status anxiety and reduced social cohesion.", "vi": "Bất bình đẳng trong xã hội tiêu dùng dẫn đến lo lắng về địa vị và giảm sự gắn kết xã hội."}]}
    ]
  },
  {
    "id": "language-power",
    "name": "Ngôn Ngữ & Quyền Lực",
    "emoji": "🗣️",
    "color": "violet",
    "words": [
      {"word": "discourse", "meaning": "diễn ngôn", "emoji": "💬", "class": "n",
       "examples": [{"en": "Political discourse shapes how citizens understand social problems and their causes.", "vi": "Diễn ngôn chính trị định hình cách công dân hiểu các vấn đề xã hội và nguyên nhân của chúng."},
                    {"en": "Critical discourse analysis examines how language reflects and reproduces power relations.", "vi": "Phân tích diễn ngôn phê phán xem xét cách ngôn ngữ phản ánh và tái tạo các quan hệ quyền lực."}]},
      {"word": "narrative", "meaning": "tường thuật", "emoji": "📖", "class": "n",
       "examples": [{"en": "Controlling the dominant narrative gives institutions significant power over public opinion.", "vi": "Kiểm soát tường thuật chủ đạo mang lại cho các thể chế quyền lực đáng kể đối với dư luận."},
                    {"en": "Marginalised communities often struggle to have their narratives heard in mainstream media.", "vi": "Các cộng đồng bị ngoại lề hóa thường đấu tranh để câu chuyện của họ được lắng nghe trên phương tiện truyền thông chính thống."}]},
      {"word": "framing", "meaning": "đóng khung ngôn ngữ", "emoji": "🖼️", "class": "n",
       "examples": [{"en": "The framing of immigration as a 'crisis' rather than a 'challenge' affects how solutions are sought.", "vi": "Đóng khung di cư là 'khủng hoảng' thay vì 'thách thức' ảnh hưởng đến cách tìm kiếm giải pháp."},
                    {"en": "Linguistic framing determines which aspects of an issue become visible and which are ignored.", "vi": "Đóng khung ngôn ngữ xác định khía cạnh nào của vấn đề trở nên hiện rõ và khía cạnh nào bị bỏ qua."}]},
      {"word": "censorship", "meaning": "kiểm duyệt", "emoji": "🚫", "class": "n",
       "examples": [{"en": "Censorship of minority languages suppresses cultural identity and restricts freedom of expression.", "vi": "Kiểm duyệt ngôn ngữ thiểu số đàn áp bản sắc văn hóa và hạn chế tự do ngôn luận."},
                    {"en": "Self-censorship occurs when speakers avoid certain topics due to fear of social consequences.", "vi": "Tự kiểm duyệt xảy ra khi người nói tránh một số chủ đề vì sợ hậu quả xã hội."}]},
      {"word": "propaganda", "meaning": "tuyên truyền", "emoji": "📢", "class": "n",
       "examples": [{"en": "Governments use propaganda to manufacture consent for policies that benefit those in power.", "vi": "Chính phủ sử dụng tuyên truyền để tạo ra sự đồng thuận cho các chính sách có lợi cho những người nắm quyền."},
                    {"en": "Propaganda often simplifies complex issues into powerful but misleading slogans.", "vi": "Tuyên truyền thường đơn giản hóa các vấn đề phức tạp thành các khẩu hiệu mạnh mẽ nhưng gây hiểu lầm."}]},
      {"word": "minority language", "meaning": "ngôn ngữ thiểu số", "emoji": "🌐", "class": "phrase",
       "examples": [{"en": "Protecting minority languages preserves cultural diversity and intangible heritage.", "vi": "Bảo vệ ngôn ngữ thiểu số bảo tồn đa dạng văn hóa và di sản phi vật thể."},
                    {"en": "Education in minority languages helps communities maintain their distinct identities.", "vi": "Giáo dục bằng ngôn ngữ thiểu số giúp cộng đồng duy trì bản sắc riêng biệt của họ."}]},
      {"word": "representation", "meaning": "sự đại diện ngôn ngữ", "emoji": "🪞", "class": "n",
       "examples": [{"en": "The under-representation of certain voices in academic language shapes what counts as knowledge.", "vi": "Sự thiếu đại diện của một số giọng nói trong ngôn ngữ học thuật định hình những gì được coi là tri thức."},
                    {"en": "Language representation in law and policy affects who is included or excluded from civic life.", "vi": "Đại diện ngôn ngữ trong luật pháp và chính sách ảnh hưởng đến ai được tham gia hay bị loại trừ khỏi đời sống dân sự."}]},
      {"word": "multilingual", "meaning": "đa ngôn ngữ", "emoji": "🗺️", "class": "adj",
       "examples": [{"en": "A multilingual education system prepares students to communicate across cultural boundaries.", "vi": "Hệ thống giáo dục đa ngôn ngữ chuẩn bị cho học sinh giao tiếp qua các ranh giới văn hóa."},
                    {"en": "Multilingual societies face complex challenges in ensuring equal treatment for all speakers.", "vi": "Các xã hội đa ngôn ngữ đối mặt với những thách thức phức tạp trong việc đảm bảo đối xử bình đẳng cho tất cả người nói."}]},
      {"word": "dominant", "meaning": "thống trị", "emoji": "👑", "class": "adj",
       "examples": [{"en": "The dominant language in a society often reflects and reinforces existing power structures.", "vi": "Ngôn ngữ thống trị trong xã hội thường phản ánh và củng cố các cấu trúc quyền lực hiện có."},
                    {"en": "When a dominant language is imposed on minorities, it can erase cultural heritage.", "vi": "Khi ngôn ngữ thống trị được áp đặt lên thiểu số, nó có thể xóa bỏ di sản văn hóa."}]},
      {"word": "heritage", "meaning": "di sản ngôn ngữ", "emoji": "📜", "class": "n",
       "examples": [{"en": "Language is central to cultural heritage and the transmission of identity across generations.", "vi": "Ngôn ngữ là trung tâm của di sản văn hóa và việc truyền bản sắc qua các thế hệ."},
                    {"en": "Preserving linguistic heritage requires active policy support and community engagement.", "vi": "Bảo tồn di sản ngôn ngữ đòi hỏi sự hỗ trợ chính sách tích cực và sự tham gia của cộng đồng."}]},
      {"word": "power", "meaning": "quyền lực", "emoji": "💪", "class": "n",
       "examples": [{"en": "Language is a tool of power: those who control terminology also control how issues are understood.", "vi": "Ngôn ngữ là công cụ quyền lực: những người kiểm soát thuật ngữ cũng kiểm soát cách hiểu các vấn đề."},
                    {"en": "The power of language to include or exclude is central to all political discourse.", "vi": "Quyền lực của ngôn ngữ để bao gồm hay loại trừ là trung tâm của tất cả diễn ngôn chính trị."}]}
    ]
  }
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'words.json')
with open(data_path, encoding='utf-8') as f:
    data = json.load(f)

data['master']['topics'].extend(NEW_MASTER_TOPICS_PART2)

with open(data_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

master_count = len(data['master']['topics'])
print(f"Master complete: {master_count} topics")
for t in data['master']['topics']:
    print(f"  {t['id']}: {len(t['words'])} words")
total_words = sum(len(t['words']) for t in data['master']['topics'])
print(f"Total Master words: {total_words}")
