# -*- coding: utf-8 -*-
import json, os

REMOVE_IDS = {
    "academic-skills", "law-justice", "science-research", "innovation-startup",
    "language-communication", "philosophy-ethics", "education-system", "food-agriculture"
}

NEW_SCHOLAR_TOPICS = [
  {
    "id": "personal-finance",
    "name": "Tài Chính Cá Nhân",
    "emoji": "💳",
    "color": "emerald",
    "words": [
      {"word": "salary", "meaning": "tiền lương", "emoji": "💵", "class": "n",
       "examples": [{"en": "Her monthly salary is enough to cover rent and daily expenses.", "vi": "Tiền lương hàng tháng của cô đủ để trang trải tiền thuê nhà và chi phí hàng ngày."},
                    {"en": "He asked for a salary increase after two years at the company.", "vi": "Anh xin tăng lương sau hai năm làm việc tại công ty."}]},
      {"word": "income", "meaning": "thu nhập", "emoji": "📈", "class": "n",
       "examples": [{"en": "Their household income doubled after both parents found full-time jobs.", "vi": "Thu nhập hộ gia đình tăng gấp đôi sau khi cả hai cha mẹ tìm được việc làm toàn thời gian."},
                    {"en": "A steady income gives people financial security.", "vi": "Thu nhập ổn định mang lại sự an toàn tài chính cho mọi người."}]},
      {"word": "savings", "meaning": "tiền tiết kiệm", "emoji": "🏦", "class": "n",
       "examples": [{"en": "He put a portion of his earnings into savings every month.", "vi": "Anh để một phần thu nhập vào tiết kiệm mỗi tháng."},
                    {"en": "Having savings helps you handle unexpected emergencies.", "vi": "Có tiền tiết kiệm giúp bạn xử lý các trường hợp khẩn cấp bất ngờ."}]},
      {"word": "loan", "meaning": "khoản vay", "emoji": "🤝", "class": "n",
       "examples": [{"en": "She took out a bank loan to start her small business.", "vi": "Cô vay tiền ngân hàng để bắt đầu doanh nghiệp nhỏ của mình."},
                    {"en": "Repaying a loan on time builds a good credit record.", "vi": "Trả khoản vay đúng hạn xây dựng lịch sử tín dụng tốt."}]},
      {"word": "mortgage", "meaning": "vay thế chấp mua nhà", "emoji": "🏠", "class": "n",
       "examples": [{"en": "They signed a 25-year mortgage to buy their first home.", "vi": "Họ ký hợp đồng vay thế chấp 25 năm để mua ngôi nhà đầu tiên."},
                    {"en": "Rising interest rates made mortgage repayments more expensive.", "vi": "Lãi suất tăng làm cho việc trả nợ thế chấp tốn kém hơn."}]},
      {"word": "insurance", "meaning": "bảo hiểm", "emoji": "🛡️", "class": "n",
       "examples": [{"en": "Health insurance covers most of her medical bills.", "vi": "Bảo hiểm y tế chi trả hầu hết các hóa đơn y tế của cô."},
                    {"en": "Car insurance is required by law in most countries.", "vi": "Bảo hiểm xe hơi được yêu cầu bởi pháp luật ở hầu hết các quốc gia."}]},
      {"word": "pension", "meaning": "lương hưu", "emoji": "👴", "class": "n",
       "examples": [{"en": "He contributes to a pension fund to secure his retirement.", "vi": "Anh đóng góp vào quỹ hưu trí để đảm bảo tuổi về hưu của mình."},
                    {"en": "Many workers rely on a government pension after they retire.", "vi": "Nhiều người lao động phụ thuộc vào lương hưu nhà nước sau khi nghỉ hưu."}]},
      {"word": "budget", "meaning": "ngân sách", "emoji": "📊", "class": "n",
       "examples": [{"en": "She created a monthly budget to track her spending.", "vi": "Cô lập ngân sách hàng tháng để theo dõi chi tiêu của mình."},
                    {"en": "Sticking to a budget helps you avoid unnecessary debt.", "vi": "Tuân theo ngân sách giúp bạn tránh nợ không cần thiết."}]},
      {"word": "expenditure", "meaning": "chi tiêu", "emoji": "💸", "class": "n",
       "examples": [{"en": "The government's expenditure on education increased this year.", "vi": "Chi tiêu của chính phủ cho giáo dục tăng trong năm nay."},
                    {"en": "Reducing unnecessary expenditure is key to saving money.", "vi": "Giảm chi tiêu không cần thiết là chìa khóa để tiết kiệm tiền."}]},
      {"word": "investment", "meaning": "đầu tư", "emoji": "📉", "class": "n",
       "examples": [{"en": "Investing in shares can bring higher returns than a savings account.", "vi": "Đầu tư vào cổ phiếu có thể mang lại lợi nhuận cao hơn tài khoản tiết kiệm."},
                    {"en": "Property investment is popular in many Asian countries.", "vi": "Đầu tư bất động sản rất phổ biến ở nhiều quốc gia châu Á."}]},
      {"word": "debt", "meaning": "nợ", "emoji": "⚠️", "class": "n",
       "examples": [{"en": "He worked hard to pay off his student debt within five years.", "vi": "Anh làm việc chăm chỉ để trả hết nợ sinh viên trong vòng năm năm."},
                    {"en": "Living beyond your means can quickly lead to serious debt.", "vi": "Sống vượt quá khả năng tài chính có thể nhanh chóng dẫn đến nợ nần nghiêm trọng."}]},
      {"word": "afford", "meaning": "đủ khả năng chi trả", "emoji": "💰", "class": "v",
       "examples": [{"en": "They could not afford to buy a house in the city centre.", "vi": "Họ không đủ khả năng mua nhà ở trung tâm thành phố."},
                    {"en": "With careful saving, she could finally afford a holiday abroad.", "vi": "Với việc tiết kiệm cẩn thận, cuối cùng cô có thể đủ khả năng đi du lịch nước ngoài."}]},
      {"word": "credit", "meaning": "tín dụng", "emoji": "💳", "class": "n",
       "examples": [{"en": "A good credit score makes it easier to get a bank loan.", "vi": "Điểm tín dụng tốt giúp việc vay ngân hàng dễ dàng hơn."},
                    {"en": "She paid for the laptop on credit and repaid it in instalments.", "vi": "Cô mua máy tính xách tay bằng tín dụng và trả dần từng kỳ."}]},
      {"word": "tax", "meaning": "thuế", "emoji": "🧾", "class": "n",
       "examples": [{"en": "Citizens are required to pay income tax on their earnings.", "vi": "Công dân phải nộp thuế thu nhập trên thu nhập của họ."},
                    {"en": "The government uses tax revenue to fund public services.", "vi": "Chính phủ sử dụng nguồn thu thuế để tài trợ cho các dịch vụ công."}]}
    ]
  },
  {
    "id": "advertising-consumer",
    "name": "Quảng Cáo & Tiêu Dùng",
    "emoji": "📢",
    "color": "orange",
    "words": [
      {"word": "advertisement", "meaning": "quảng cáo", "emoji": "📺", "class": "n",
       "examples": [{"en": "The advertisement was shown during the most popular TV shows.", "vi": "Quảng cáo được chiếu trong các chương trình truyền hình phổ biến nhất."},
                    {"en": "Online advertisements can be targeted to specific age groups.", "vi": "Quảng cáo trực tuyến có thể nhắm vào các nhóm tuổi cụ thể."}]},
      {"word": "brand", "meaning": "thương hiệu", "emoji": "🏷️", "class": "n",
       "examples": [{"en": "This brand is known worldwide for its quality products.", "vi": "Thương hiệu này nổi tiếng toàn thế giới về chất lượng sản phẩm."},
                    {"en": "Building a strong brand takes years of consistent marketing.", "vi": "Xây dựng thương hiệu mạnh đòi hỏi nhiều năm marketing nhất quán."}]},
      {"word": "consumer", "meaning": "người tiêu dùng", "emoji": "🛒", "class": "n",
       "examples": [{"en": "Consumers today are more aware of product ingredients.", "vi": "Người tiêu dùng ngày nay nhận thức rõ hơn về thành phần sản phẩm."},
                    {"en": "The company surveyed consumers to improve its service.", "vi": "Công ty khảo sát người tiêu dùng để cải thiện dịch vụ."}]},
      {"word": "campaign", "meaning": "chiến dịch (quảng cáo)", "emoji": "📣", "class": "n",
       "examples": [{"en": "The marketing campaign increased sales by thirty per cent.", "vi": "Chiến dịch marketing tăng doanh số bán hàng lên ba mươi phần trăm."},
                    {"en": "They launched a social media campaign to raise brand awareness.", "vi": "Họ tung ra chiến dịch mạng xã hội để nâng cao nhận thức về thương hiệu."}]},
      {"word": "persuade", "meaning": "thuyết phục", "emoji": "💬", "class": "v",
       "examples": [{"en": "Advertisers use emotional stories to persuade people to buy.", "vi": "Các nhà quảng cáo dùng câu chuyện cảm xúc để thuyết phục mọi người mua hàng."},
                    {"en": "She was persuaded to switch to a different mobile provider.", "vi": "Cô được thuyết phục chuyển sang nhà cung cấp di động khác."}]},
      {"word": "promote", "meaning": "quảng bá", "emoji": "📡", "class": "v",
       "examples": [{"en": "Celebrities are often paid to promote new products on social media.", "vi": "Người nổi tiếng thường được trả tiền để quảng bá sản phẩm mới trên mạng xã hội."},
                    {"en": "The company promoted its eco-friendly packaging to attract green consumers.", "vi": "Công ty quảng bá bao bì thân thiện môi trường để thu hút người tiêu dùng xanh."}]},
      {"word": "sponsor", "meaning": "tài trợ", "emoji": "🤝", "class": "v",
       "examples": [{"en": "A sports drink brand sponsors the national football team.", "vi": "Một thương hiệu nước uống thể thao tài trợ cho đội bóng đá quốc gia."},
                    {"en": "The event was sponsored by several local businesses.", "vi": "Sự kiện được tài trợ bởi một số doanh nghiệp địa phương."}]},
      {"word": "slogan", "meaning": "khẩu hiệu", "emoji": "✏️", "class": "n",
       "examples": [{"en": "A catchy slogan helps customers remember a brand easily.", "vi": "Một khẩu hiệu dễ nhớ giúp khách hàng ghi nhớ thương hiệu dễ dàng."},
                    {"en": "Their slogan 'Just Do It' became one of the most famous in history.", "vi": "Khẩu hiệu 'Just Do It' của họ trở thành một trong những khẩu hiệu nổi tiếng nhất trong lịch sử."}]},
      {"word": "target", "meaning": "đối tượng mục tiêu", "emoji": "🎯", "class": "n",
       "examples": [{"en": "The target audience for this product is young professionals.", "vi": "Đối tượng mục tiêu của sản phẩm này là những người đi làm trẻ tuổi."},
                    {"en": "Digital ads allow brands to target users based on their interests.", "vi": "Quảng cáo kỹ thuật số cho phép thương hiệu nhắm mục tiêu người dùng dựa trên sở thích."}]},
      {"word": "influence", "meaning": "ảnh hưởng", "emoji": "🌀", "class": "n",
       "examples": [{"en": "Advertising has a strong influence on consumer behaviour.", "vi": "Quảng cáo có ảnh hưởng mạnh mẽ đến hành vi người tiêu dùng."},
                    {"en": "Social media influencers can influence millions of buying decisions.", "vi": "Người có ảnh hưởng trên mạng xã hội có thể tác động đến hàng triệu quyết định mua hàng."}]},
      {"word": "commercial", "meaning": "mang tính thương mại", "emoji": "📻", "class": "adj",
       "examples": [{"en": "The film was a commercial success despite poor critical reviews.", "vi": "Bộ phim thành công về mặt thương mại dù bị giới phê bình đánh giá kém."},
                    {"en": "Commercial television relies on advertising revenue to operate.", "vi": "Truyền hình thương mại dựa vào doanh thu quảng cáo để hoạt động."}]},
      {"word": "purchase", "meaning": "mua, việc mua hàng", "emoji": "🛍️", "class": "v",
       "examples": [{"en": "She purchased the jacket online at a discounted price.", "vi": "Cô mua chiếc áo khoác trực tuyến với giá giảm."},
                    {"en": "Impulse purchases are often encouraged by attractive displays.", "vi": "Mua hàng bốc đồng thường được khuyến khích bởi các trưng bày hấp dẫn."}]},
      {"word": "demand", "meaning": "nhu cầu", "emoji": "📊", "class": "n",
       "examples": [{"en": "There is high demand for skilled workers in the technology sector.", "vi": "Có nhu cầu cao về lao động có kỹ năng trong lĩnh vực công nghệ."},
                    {"en": "When supply is low and demand is high, prices tend to rise.", "vi": "Khi cung thấp và cầu cao, giá cả có xu hướng tăng."}]},
      {"word": "loyalty", "meaning": "lòng trung thành (với thương hiệu)", "emoji": "❤️", "class": "n",
       "examples": [{"en": "The company rewards customer loyalty with a points system.", "vi": "Công ty thưởng cho lòng trung thành của khách hàng bằng hệ thống điểm."},
                    {"en": "Brand loyalty is harder to maintain in a competitive market.", "vi": "Lòng trung thành với thương hiệu khó duy trì hơn trong thị trường cạnh tranh."}]}
    ]
  },
  {
    "id": "crime-society",
    "name": "Tội Phạm & Xã Hội",
    "emoji": "🚔",
    "color": "slate",
    "words": [
      {"word": "criminal", "meaning": "tội phạm", "emoji": "🦹", "class": "n",
       "examples": [{"en": "The criminal was convicted and sentenced to five years in prison.", "vi": "Tên tội phạm bị kết án và lĩnh án năm năm tù."},
                    {"en": "Criminal activity in the area has decreased due to better policing.", "vi": "Hoạt động tội phạm trong khu vực đã giảm nhờ việc tuần tra tốt hơn."}]},
      {"word": "victim", "meaning": "nạn nhân", "emoji": "🫂", "class": "n",
       "examples": [{"en": "The victim reported the theft to the police immediately.", "vi": "Nạn nhân báo cáo vụ trộm với cảnh sát ngay lập tức."},
                    {"en": "Support services help victims of crime recover emotionally.", "vi": "Các dịch vụ hỗ trợ giúp nạn nhân của tội phạm phục hồi về mặt cảm xúc."}]},
      {"word": "violence", "meaning": "bạo lực", "emoji": "⚡", "class": "n",
       "examples": [{"en": "Domestic violence is a serious problem that affects many families.", "vi": "Bạo lực gia đình là một vấn đề nghiêm trọng ảnh hưởng đến nhiều gia đình."},
                    {"en": "Schools teach conflict resolution to reduce violence among students.", "vi": "Các trường học dạy giải quyết xung đột để giảm bạo lực giữa học sinh."}]},
      {"word": "punishment", "meaning": "hình phạt", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "The punishment for the crime was considered too lenient by many.", "vi": "Hình phạt cho tội ác này bị nhiều người cho là quá nhẹ."},
                    {"en": "Effective punishment should deter others from committing crimes.", "vi": "Hình phạt hiệu quả nên ngăn chặn người khác phạm tội."}]},
      {"word": "sentence", "meaning": "bản án", "emoji": "🔨", "class": "n",
       "examples": [{"en": "The judge handed down a ten-year prison sentence.", "vi": "Thẩm phán tuyên phạt mười năm tù giam."},
                    {"en": "His sentence was reduced for good behaviour in prison.", "vi": "Bản án của anh được giảm vì hành vi tốt trong tù."}]},
      {"word": "arrest", "meaning": "bắt giữ", "emoji": "🚨", "class": "v",
       "examples": [{"en": "Police arrested the suspect near the scene of the crime.", "vi": "Cảnh sát bắt giữ nghi phạm gần hiện trường vụ án."},
                    {"en": "He was arrested on charges of fraud and money laundering.", "vi": "Anh bị bắt với tội danh gian lận và rửa tiền."}]},
      {"word": "guilty", "meaning": "có tội", "emoji": "😔", "class": "adj",
       "examples": [{"en": "The jury found the defendant guilty of robbery.", "vi": "Bồi thẩm đoàn kết luận bị cáo có tội về tội cướp."},
                    {"en": "She pleaded guilty and accepted a reduced sentence.", "vi": "Cô nhận tội và chấp nhận bản án được giảm nhẹ."}]},
      {"word": "evidence", "meaning": "bằng chứng", "emoji": "🔍", "class": "n",
       "examples": [{"en": "The prosecution presented strong evidence linking him to the crime.", "vi": "Bên công tố trình bày bằng chứng mạnh mẽ liên kết anh ta với tội ác."},
                    {"en": "Without sufficient evidence, the case was dismissed.", "vi": "Không có đủ bằng chứng, vụ án đã bị bác bỏ."}]},
      {"word": "prevention", "meaning": "phòng ngừa", "emoji": "🛡️", "class": "n",
       "examples": [{"en": "Crime prevention programmes have helped reduce burglaries.", "vi": "Các chương trình phòng ngừa tội phạm đã giúp giảm số vụ trộm cắp."},
                    {"en": "Prevention is always better than punishment when it comes to crime.", "vi": "Phòng ngừa luôn tốt hơn trừng phạt khi nói đến tội phạm."}]},
      {"word": "illegal", "meaning": "bất hợp pháp", "emoji": "🚫", "class": "adj",
       "examples": [{"en": "It is illegal to drive without a valid licence.", "vi": "Lái xe không có bằng lái hợp lệ là bất hợp pháp."},
                    {"en": "The company was fined for illegal disposal of chemical waste.", "vi": "Công ty bị phạt vì thải hóa chất bất hợp pháp."}]},
      {"word": "consequence", "meaning": "hậu quả", "emoji": "💥", "class": "n",
       "examples": [{"en": "The consequences of drunk driving can be fatal.", "vi": "Hậu quả của việc lái xe khi say rượu có thể gây chết người."},
                    {"en": "Young offenders often fail to consider the consequences of their actions.", "vi": "Những người vi phạm trẻ tuổi thường không suy nghĩ đến hậu quả của hành động."}]},
      {"word": "rehabilitation", "meaning": "cải tạo, phục hồi", "emoji": "🌱", "class": "n",
       "examples": [{"en": "Rehabilitation programmes help prisoners reintegrate into society.", "vi": "Các chương trình cải tạo giúp tù nhân tái hòa nhập xã hội."},
                    {"en": "Drug rehabilitation requires both medical treatment and emotional support.", "vi": "Cai nghiện đòi hỏi cả điều trị y tế và hỗ trợ tinh thần."}]},
      {"word": "fine", "meaning": "phạt tiền", "emoji": "💵", "class": "n",
       "examples": [{"en": "He received a heavy fine for speeding on the motorway.", "vi": "Anh bị phạt tiền nặng vì chạy quá tốc độ trên đường cao tốc."},
                    {"en": "Companies face large fines if they violate environmental regulations.", "vi": "Các công ty đối mặt với khoản phạt lớn nếu vi phạm quy định môi trường."}]},
      {"word": "patrol", "meaning": "tuần tra", "emoji": "👮", "class": "v",
       "examples": [{"en": "Police officers patrol the streets at night to ensure safety.", "vi": "Cảnh sát tuần tra trên đường phố vào ban đêm để đảm bảo an toàn."},
                    {"en": "Security guards patrol the building every two hours.", "vi": "Nhân viên bảo vệ tuần tra tòa nhà mỗi hai tiếng."}]}
    ]
  },
  {
    "id": "family-relationships",
    "name": "Gia Đình & Mối Quan Hệ",
    "emoji": "👨‍👩‍👧‍👦",
    "color": "rose",
    "words": [
      {"word": "marriage", "meaning": "hôn nhân", "emoji": "💍", "class": "n",
       "examples": [{"en": "A successful marriage requires trust, communication, and compromise.", "vi": "Một cuộc hôn nhân thành công đòi hỏi sự tin tưởng, giao tiếp và thỏa hiệp."},
                    {"en": "They celebrated their 25th wedding anniversary this year.", "vi": "Họ kỷ niệm 25 năm ngày cưới trong năm nay."}]},
      {"word": "divorce", "meaning": "ly hôn", "emoji": "💔", "class": "n",
       "examples": [{"en": "The divorce rate has increased in many developed countries.", "vi": "Tỷ lệ ly hôn đã tăng ở nhiều quốc gia phát triển."},
                    {"en": "Going through a divorce can be emotionally difficult for children.", "vi": "Trải qua ly hôn có thể gây khó khăn về mặt cảm xúc cho trẻ em."}]},
      {"word": "generation", "meaning": "thế hệ", "emoji": "👴👶", "class": "n",
       "examples": [{"en": "Each generation faces different social and economic challenges.", "vi": "Mỗi thế hệ đối mặt với những thách thức xã hội và kinh tế khác nhau."},
                    {"en": "This story was passed down through three generations of the family.", "vi": "Câu chuyện này được truyền qua ba thế hệ trong gia đình."}]},
      {"word": "gender", "meaning": "giới tính", "emoji": "♀♂", "class": "n",
       "examples": [{"en": "Gender equality means that men and women have the same opportunities.", "vi": "Bình đẳng giới có nghĩa là nam và nữ có cơ hội như nhau."},
                    {"en": "Society's views on gender roles have changed significantly in recent decades.", "vi": "Quan điểm của xã hội về vai trò giới tính đã thay đổi đáng kể trong những thập kỷ gần đây."}]},
      {"word": "equality", "meaning": "bình đẳng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Equality in the workplace means fair pay regardless of gender.", "vi": "Bình đẳng tại nơi làm việc có nghĩa là trả công bình đẳng bất kể giới tính."},
                    {"en": "Racial equality is a fundamental human right.", "vi": "Bình đẳng chủng tộc là quyền con người cơ bản."}]},
      {"word": "independence", "meaning": "sự độc lập", "emoji": "🦅", "class": "n",
       "examples": [{"en": "Young adults value their independence when they leave home.", "vi": "Những người trẻ tuổi trân trọng sự độc lập khi rời khỏi nhà."},
                    {"en": "Financial independence allows people to make their own life choices.", "vi": "Độc lập tài chính cho phép mọi người tự đưa ra lựa chọn cuộc sống."}]},
      {"word": "commitment", "meaning": "cam kết", "emoji": "🤝", "class": "n",
       "examples": [{"en": "A strong relationship is built on commitment and mutual respect.", "vi": "Một mối quan hệ bền vững được xây dựng trên sự cam kết và tôn trọng lẫn nhau."},
                    {"en": "He showed his commitment by being there through difficult times.", "vi": "Anh thể hiện cam kết bằng cách ở bên trong những lúc khó khăn."}]},
      {"word": "boundary", "meaning": "ranh giới (cá nhân)", "emoji": "🚧", "class": "n",
       "examples": [{"en": "Setting healthy boundaries in relationships is important for wellbeing.", "vi": "Đặt ranh giới lành mạnh trong các mối quan hệ là quan trọng cho sức khỏe tinh thần."},
                    {"en": "She learned to communicate her boundaries clearly and respectfully.", "vi": "Cô học cách truyền đạt ranh giới của mình một cách rõ ràng và tôn trọng."}]},
      {"word": "tradition", "meaning": "truyền thống", "emoji": "🏮", "class": "n",
       "examples": [{"en": "Family traditions help strengthen bonds across generations.", "vi": "Truyền thống gia đình giúp củng cố mối gắn kết qua các thế hệ."},
                    {"en": "Some traditions evolve over time to reflect modern values.", "vi": "Một số truyền thống phát triển theo thời gian để phản ánh các giá trị hiện đại."}]},
      {"word": "responsibility", "meaning": "trách nhiệm", "emoji": "📋", "class": "n",
       "examples": [{"en": "Parents have a responsibility to provide a safe environment for their children.", "vi": "Cha mẹ có trách nhiệm tạo ra môi trường an toàn cho con cái."},
                    {"en": "Taking responsibility for your actions is a sign of maturity.", "vi": "Chịu trách nhiệm về hành động của mình là dấu hiệu của sự trưởng thành."}]},
      {"word": "parental", "meaning": "thuộc về cha mẹ", "emoji": "👨‍👩‍👧", "class": "adj",
       "examples": [{"en": "Parental support is crucial during a child's early years.", "vi": "Sự hỗ trợ của cha mẹ rất quan trọng trong những năm đầu đời của trẻ."},
                    {"en": "The court granted full parental rights to the mother.", "vi": "Tòa án trao toàn quyền làm cha mẹ cho người mẹ."}]},
      {"word": "bond", "meaning": "mối gắn kết", "emoji": "💞", "class": "n",
       "examples": [{"en": "The bond between siblings often lasts a lifetime.", "vi": "Mối gắn kết giữa anh chị em thường kéo dài suốt đời."},
                    {"en": "Shared experiences help build a strong bond between friends.", "vi": "Những trải nghiệm chung giúp xây dựng mối gắn kết mạnh mẽ giữa bạn bè."}]},
      {"word": "value", "meaning": "giá trị (đạo đức)", "emoji": "💎", "class": "n",
       "examples": [{"en": "Family values such as honesty and kindness are taught at home.", "vi": "Các giá trị gia đình như sự trung thực và lòng tốt được dạy ở nhà."},
                    {"en": "Their values guide how they raise their children.", "vi": "Các giá trị của họ hướng dẫn cách họ nuôi dạy con cái."}]},
      {"word": "identity", "meaning": "bản sắc", "emoji": "🪞", "class": "n",
       "examples": [{"en": "Family background plays an important role in shaping personal identity.", "vi": "Nền tảng gia đình đóng vai trò quan trọng trong việc hình thành bản sắc cá nhân."},
                    {"en": "Many young people struggle with identity as they grow up.", "vi": "Nhiều người trẻ gặp khó khăn với bản sắc khi lớn lên."}]}
    ]
  },
  {
    "id": "tourism-hospitality",
    "name": "Du Lịch & Khách Sạn",
    "emoji": "🏨",
    "color": "sky",
    "words": [
      {"word": "tourism", "meaning": "du lịch", "emoji": "✈️", "class": "n",
       "examples": [{"en": "Tourism is one of the most important industries in Thailand.", "vi": "Du lịch là một trong những ngành quan trọng nhất ở Thái Lan."},
                    {"en": "Sustainable tourism aims to protect natural and cultural resources.", "vi": "Du lịch bền vững nhằm bảo vệ tài nguyên tự nhiên và văn hóa."}]},
      {"word": "destination", "meaning": "điểm đến", "emoji": "📍", "class": "n",
       "examples": [{"en": "Japan is one of the most popular tourist destinations in Asia.", "vi": "Nhật Bản là một trong những điểm đến du lịch phổ biến nhất ở châu Á."},
                    {"en": "The travel agent recommended a lesser-known destination for a peaceful holiday.", "vi": "Đại lý du lịch giới thiệu một điểm đến ít người biết để có kỳ nghỉ yên tĩnh."}]},
      {"word": "authentic", "meaning": "chân thực, địa phương", "emoji": "🌿", "class": "adj",
       "examples": [{"en": "Tourists often seek authentic local food rather than international chains.", "vi": "Du khách thường tìm kiếm đồ ăn địa phương chân thực thay vì các chuỗi quốc tế."},
                    {"en": "The village offered an authentic experience of traditional life.", "vi": "Ngôi làng mang lại trải nghiệm chân thực về cuộc sống truyền thống."}]},
      {"word": "accommodation", "meaning": "chỗ ở", "emoji": "🏠", "class": "n",
       "examples": [{"en": "The accommodation included breakfast and free Wi-Fi.", "vi": "Chỗ ở bao gồm bữa sáng và Wi-Fi miễn phí."},
                    {"en": "Finding affordable accommodation near the city centre can be difficult.", "vi": "Tìm chỗ ở giá cả phải chăng gần trung tâm thành phố có thể khó khăn."}]},
      {"word": "cultural exchange", "meaning": "trao đổi văn hóa", "emoji": "🌍", "class": "phrase",
       "examples": [{"en": "Homestay programmes encourage meaningful cultural exchange between visitors and locals.", "vi": "Các chương trình homestay khuyến khích trao đổi văn hóa có ý nghĩa giữa du khách và người địa phương."},
                    {"en": "Cultural exchange helps break down stereotypes and build understanding.", "vi": "Trao đổi văn hóa giúp phá vỡ định kiến và xây dựng sự hiểu biết."}]},
      {"word": "impression", "meaning": "ấn tượng", "emoji": "✨", "class": "n",
       "examples": [{"en": "The ancient temples left a lasting impression on all the visitors.", "vi": "Những ngôi đền cổ để lại ấn tượng lâu dài với tất cả du khách."},
                    {"en": "First impressions of a destination are often formed at the airport.", "vi": "Ấn tượng đầu tiên về một điểm đến thường được hình thành ở sân bay."}]},
      {"word": "heritage", "meaning": "di sản", "emoji": "🏛️", "class": "n",
       "examples": [{"en": "Hoi An is recognised as a UNESCO World Heritage site.", "vi": "Hội An được công nhận là di sản thế giới UNESCO."},
                    {"en": "Preserving cultural heritage is essential for future generations.", "vi": "Bảo tồn di sản văn hóa là điều cần thiết cho các thế hệ tương lai."}]},
      {"word": "custom", "meaning": "phong tục", "emoji": "🎎", "class": "n",
       "examples": [{"en": "Travellers should respect local customs when visiting other countries.", "vi": "Du khách nên tôn trọng phong tục địa phương khi đến thăm các quốc gia khác."},
                    {"en": "Removing shoes before entering a home is a common custom in many Asian cultures.", "vi": "Bỏ giày trước khi vào nhà là phong tục phổ biến ở nhiều nền văn hóa châu Á."}]},
      {"word": "resort", "meaning": "khu nghỉ dưỡng", "emoji": "🏖️", "class": "n",
       "examples": [{"en": "The beach resort offered swimming pools, restaurants, and spa treatments.", "vi": "Khu nghỉ dưỡng biển cung cấp hồ bơi, nhà hàng và dịch vụ spa."},
                    {"en": "All-inclusive resorts are popular for families on holiday.", "vi": "Khu nghỉ dưỡng trọn gói rất phổ biến cho các gia đình đi nghỉ."}]},
      {"word": "hospitality", "meaning": "lòng hiếu khách", "emoji": "🤗", "class": "n",
       "examples": [{"en": "Vietnamese people are known for their warm hospitality.", "vi": "Người Việt Nam nổi tiếng với lòng hiếu khách nồng hậu."},
                    {"en": "The hospitality industry employs millions of people worldwide.", "vi": "Ngành khách sạn thuê hàng triệu người trên toàn thế giới."}]},
      {"word": "eco-tourism", "meaning": "du lịch sinh thái", "emoji": "🌲", "class": "n",
       "examples": [{"en": "Eco-tourism encourages travellers to minimise their environmental impact.", "vi": "Du lịch sinh thái khuyến khích du khách giảm thiểu tác động môi trường."},
                    {"en": "The national park promotes eco-tourism to fund conservation efforts.", "vi": "Vườn quốc gia thúc đẩy du lịch sinh thái để tài trợ cho các nỗ lực bảo tồn."}]},
      {"word": "itinerary", "meaning": "lịch trình du lịch", "emoji": "🗺️", "class": "n",
       "examples": [{"en": "They planned a detailed itinerary for their two-week trip to Europe.", "vi": "Họ lên kế hoạch lịch trình chi tiết cho chuyến đi châu Âu hai tuần."},
                    {"en": "A flexible itinerary allows you to explore spontaneously.", "vi": "Một lịch trình linh hoạt cho phép bạn khám phá một cách tự phát."}]},
      {"word": "diverse", "meaning": "đa dạng", "emoji": "🌈", "class": "adj",
       "examples": [{"en": "Vietnam offers a diverse range of landscapes, from mountains to beaches.", "vi": "Việt Nam cung cấp nhiều cảnh quan đa dạng, từ núi đến biển."},
                    {"en": "The city attracts diverse visitors from all over the world.", "vi": "Thành phố thu hút du khách đa dạng từ khắp nơi trên thế giới."}]}
    ]
  },
  {
    "id": "wellbeing-lifestyle",
    "name": "Sức Khỏe & Lối Sống",
    "emoji": "🧘",
    "color": "teal",
    "words": [
      {"word": "wellbeing", "meaning": "sức khỏe toàn diện", "emoji": "🌟", "class": "n",
       "examples": [{"en": "Physical exercise has a positive impact on mental wellbeing.", "vi": "Tập thể dục thể chất có tác động tích cực đến sức khỏe tinh thần."},
                    {"en": "Employee wellbeing is increasingly a priority for modern companies.", "vi": "Sức khỏe của nhân viên ngày càng trở thành ưu tiên của các công ty hiện đại."}]},
      {"word": "balance", "meaning": "cân bằng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Achieving a work-life balance is challenging in demanding careers.", "vi": "Đạt được sự cân bằng giữa công việc và cuộc sống là thách thức trong những nghề nghiệp đòi hỏi cao."},
                    {"en": "A balanced diet includes proteins, carbohydrates, and healthy fats.", "vi": "Chế độ ăn cân bằng bao gồm protein, carbohydrate và chất béo lành mạnh."}]},
      {"word": "routine", "meaning": "thói quen hàng ngày", "emoji": "📅", "class": "n",
       "examples": [{"en": "A consistent morning routine helps her start the day productively.", "vi": "Thói quen buổi sáng nhất quán giúp cô bắt đầu ngày làm việc hiệu quả."},
                    {"en": "Regular exercise should be part of everyone's daily routine.", "vi": "Tập thể dục thường xuyên nên là một phần trong thói quen hàng ngày của mọi người."}]},
      {"word": "mindfulness", "meaning": "chánh niệm", "emoji": "🧠", "class": "n",
       "examples": [{"en": "Practising mindfulness can reduce stress and improve focus.", "vi": "Thực hành chánh niệm có thể giảm căng thẳng và cải thiện sự tập trung."},
                    {"en": "Mindfulness meditation is widely used in therapy and schools.", "vi": "Thiền chánh niệm được sử dụng rộng rãi trong liệu pháp và trường học."}]},
      {"word": "active", "meaning": "năng động", "emoji": "🏃", "class": "adj",
       "examples": [{"en": "Staying active is important for both physical and mental health.", "vi": "Duy trì lối sống năng động quan trọng cho cả sức khỏe thể chất và tinh thần."},
                    {"en": "She stays active by cycling to work and swimming at weekends.", "vi": "Cô duy trì lối sống năng động bằng cách đạp xe đi làm và bơi lội vào cuối tuần."}]},
      {"word": "fitness", "meaning": "thể lực, sức khoẻ thể chất", "emoji": "💪", "class": "n",
       "examples": [{"en": "Physical fitness is measured by strength, endurance, and flexibility.", "vi": "Thể lực được đo bằng sức mạnh, sức bền và tính linh hoạt."},
                    {"en": "Joining a gym helped him improve his overall fitness level.", "vi": "Tham gia phòng tập thể dục giúp anh cải thiện mức thể lực tổng thể."}]},
      {"word": "lifestyle", "meaning": "lối sống", "emoji": "🌿", "class": "n",
       "examples": [{"en": "A sedentary lifestyle increases the risk of heart disease.", "vi": "Lối sống ít vận động làm tăng nguy cơ mắc bệnh tim."},
                    {"en": "Many people are adopting a plant-based lifestyle for health reasons.", "vi": "Nhiều người đang áp dụng lối sống thuần thực vật vì lý do sức khỏe."}]},
      {"word": "posture", "meaning": "tư thế", "emoji": "🧍", "class": "n",
       "examples": [{"en": "Poor posture from sitting at a desk can cause back pain.", "vi": "Tư thế ngồi bàn kém có thể gây đau lưng."},
                    {"en": "Yoga improves posture and flexibility significantly.", "vi": "Yoga cải thiện đáng kể tư thế và tính linh hoạt."}]},
      {"word": "hydration", "meaning": "bổ sung nước", "emoji": "💧", "class": "n",
       "examples": [{"en": "Proper hydration is essential when exercising in hot weather.", "vi": "Bổ sung nước đầy đủ là điều cần thiết khi tập thể dục trong thời tiết nóng."},
                    {"en": "Drinking eight glasses of water a day supports good hydration.", "vi": "Uống tám ly nước mỗi ngày hỗ trợ bổ sung nước tốt."}]},
      {"word": "self-care", "meaning": "tự chăm sóc bản thân", "emoji": "🛁", "class": "n",
       "examples": [{"en": "Self-care practices like reading and relaxing are important for mental health.", "vi": "Các thói quen tự chăm sóc như đọc sách và thư giãn quan trọng cho sức khỏe tâm thần."},
                    {"en": "Taking time for self-care helps prevent burnout.", "vi": "Dành thời gian tự chăm sóc bản thân giúp ngăn ngừa kiệt sức."}]},
      {"word": "productive", "meaning": "năng suất", "emoji": "✅", "class": "adj",
       "examples": [{"en": "A good night's sleep makes you more productive the next day.", "vi": "Ngủ đêm ngon giúp bạn làm việc năng suất hơn vào ngày hôm sau."},
                    {"en": "She reorganised her workspace to create a more productive environment.", "vi": "Cô sắp xếp lại không gian làm việc để tạo ra môi trường năng suất hơn."}]},
      {"word": "recovery", "meaning": "phục hồi", "emoji": "🔄", "class": "n",
       "examples": [{"en": "Rest days are essential for muscle recovery after intense exercise.", "vi": "Những ngày nghỉ rất cần thiết cho việc phục hồi cơ bắp sau khi tập luyện cường độ cao."},
                    {"en": "Mental recovery after a stressful period takes time and patience.", "vi": "Phục hồi tinh thần sau một giai đoạn căng thẳng cần thời gian và sự kiên nhẫn."}]},
      {"word": "habit", "meaning": "thói quen", "emoji": "🔁", "class": "n",
       "examples": [{"en": "It takes approximately 21 days to form a new habit.", "vi": "Mất khoảng 21 ngày để hình thành một thói quen mới."},
                    {"en": "Replacing unhealthy habits with positive ones improves long-term wellbeing.", "vi": "Thay thế thói quen không lành mạnh bằng thói quen tích cực cải thiện sức khỏe lâu dài."}]},
      {"word": "sustainable", "meaning": "bền vững", "emoji": "♻️", "class": "adj",
       "examples": [{"en": "A sustainable diet reduces environmental impact without sacrificing nutrition.", "vi": "Chế độ ăn bền vững giảm tác động môi trường mà không ảnh hưởng đến dinh dưỡng."},
                    {"en": "Building sustainable habits is more effective than short-term diets.", "vi": "Xây dựng thói quen bền vững hiệu quả hơn là những chế độ ăn kiêng ngắn hạn."}]}
    ]
  },
  {
    "id": "arts-entertainment",
    "name": "Nghệ Thuật & Giải Trí",
    "emoji": "🎭",
    "color": "purple",
    "words": [
      {"word": "novel", "meaning": "tiểu thuyết", "emoji": "📖", "class": "n",
       "examples": [{"en": "Her debut novel won several prestigious literary awards.", "vi": "Tiểu thuyết đầu tay của cô đã giành được nhiều giải thưởng văn học uy tín."},
                    {"en": "The novel explores themes of identity, loss, and redemption.", "vi": "Cuốn tiểu thuyết khám phá các chủ đề về bản sắc, mất mát và cứu chuộc."}]},
      {"word": "film", "meaning": "bộ phim", "emoji": "🎬", "class": "n",
       "examples": [{"en": "The film received critical acclaim for its stunning cinematography.", "vi": "Bộ phim nhận được sự khen ngợi của giới phê bình nhờ kỹ thuật quay phim tuyệt vời."},
                    {"en": "Independent films often tackle challenging social issues.", "vi": "Phim độc lập thường đề cập đến các vấn đề xã hội thách thức."}]},
      {"word": "theatre", "meaning": "nhà hát", "emoji": "🎪", "class": "n",
       "examples": [{"en": "She has been performing at the theatre since she was a teenager.", "vi": "Cô đã biểu diễn tại nhà hát từ khi còn là thiếu niên."},
                    {"en": "Live theatre creates an emotional connection that films cannot replicate.", "vi": "Sân khấu trực tiếp tạo ra sự kết nối cảm xúc mà phim ảnh không thể tái tạo."}]},
      {"word": "concert", "meaning": "buổi hòa nhạc", "emoji": "🎵", "class": "n",
       "examples": [{"en": "Thousands of fans attended the outdoor concert despite the rain.", "vi": "Hàng ngàn fan hâm mộ tham dự buổi hòa nhạc ngoài trời mặc dù trời mưa."},
                    {"en": "The orchestra performed a concert of classical music last evening.", "vi": "Dàn nhạc trình diễn một buổi hòa nhạc nhạc cổ điển vào tối qua."}]},
      {"word": "exhibition", "meaning": "triển lãm", "emoji": "🖼️", "class": "n",
       "examples": [{"en": "The exhibition showcased works by emerging local artists.", "vi": "Triển lãm trưng bày tác phẩm của các nghệ sĩ địa phương mới nổi."},
                    {"en": "Millions visited the exhibition during its three-month run.", "vi": "Hàng triệu người đến thăm triển lãm trong thời gian ba tháng."}]},
      {"word": "audience", "meaning": "khán giả", "emoji": "👏", "class": "n",
       "examples": [{"en": "The audience gave the performers a standing ovation.", "vi": "Khán giả đứng dậy vỗ tay nhiệt liệt cho các diễn viên."},
                    {"en": "Social media has helped artists reach a global audience.", "vi": "Mạng xã hội đã giúp các nghệ sĩ tiếp cận khán giả toàn cầu."}]},
      {"word": "performance", "meaning": "màn trình diễn", "emoji": "🌟", "class": "n",
       "examples": [{"en": "Her performance in the lead role was critically acclaimed.", "vi": "Màn trình diễn của cô trong vai chính được giới phê bình khen ngợi."},
                    {"en": "The band's live performance was far more energetic than their studio recordings.", "vi": "Màn trình diễn trực tiếp của ban nhạc năng động hơn nhiều so với các bản thu âm trong phòng."}]},
      {"word": "genre", "meaning": "thể loại", "emoji": "📂", "class": "n",
       "examples": [{"en": "Science fiction is one of the most popular literary genres.", "vi": "Khoa học viễn tưởng là một trong những thể loại văn học phổ biến nhất."},
                    {"en": "This film blends the horror and comedy genres in an unusual way.", "vi": "Bộ phim này kết hợp thể loại kinh dị và hài hước theo cách bất thường."}]},
      {"word": "award", "meaning": "giải thưởng", "emoji": "🏆", "class": "n",
       "examples": [{"en": "The director won an award for Best Film at the international festival.", "vi": "Đạo diễn giành giải thưởng Phim Hay Nhất tại liên hoan phim quốc tế."},
                    {"en": "Winning a prestigious award can transform an artist's career.", "vi": "Giành được một giải thưởng uy tín có thể thay đổi sự nghiệp của một nghệ sĩ."}]},
      {"word": "adaptation", "meaning": "chuyển thể", "emoji": "🔄", "class": "n",
       "examples": [{"en": "The film is a faithful adaptation of the bestselling novel.", "vi": "Bộ phim là chuyển thể trung thành với cuốn tiểu thuyết bán chạy nhất."},
                    {"en": "Stage adaptations of classic novels often attract large audiences.", "vi": "Chuyển thể sân khấu của các tiểu thuyết kinh điển thường thu hút lượng khán giả lớn."}]},
      {"word": "screenplay", "meaning": "kịch bản phim", "emoji": "📝", "class": "n",
       "examples": [{"en": "She spent two years writing the screenplay before it was accepted.", "vi": "Cô dành hai năm để viết kịch bản trước khi nó được chấp nhận."},
                    {"en": "A well-written screenplay is the foundation of every great film.", "vi": "Một kịch bản được viết tốt là nền tảng của mọi bộ phim xuất sắc."}]},
      {"word": "cast", "meaning": "dàn diễn viên", "emoji": "🎭", "class": "n",
       "examples": [{"en": "The film features an impressive cast of international stars.", "vi": "Bộ phim có dàn diễn viên ấn tượng gồm các ngôi sao quốc tế."},
                    {"en": "The director cast an unknown actor in the leading role.", "vi": "Đạo diễn chọn một diễn viên vô danh vào vai chính."}]},
      {"word": "remake", "meaning": "làm lại (phim/bài hát)", "emoji": "🔁", "class": "n",
       "examples": [{"en": "The remake of the 1980s classic was less successful than the original.", "vi": "Phiên bản làm lại của kiệt tác thập niên 1980 kém thành công hơn bản gốc."},
                    {"en": "Hollywood frequently remakes popular films from other countries.", "vi": "Hollywood thường xuyên làm lại các bộ phim nổi tiếng từ các quốc gia khác."}]},
      {"word": "inspire", "meaning": "truyền cảm hứng", "emoji": "✨", "class": "v",
       "examples": [{"en": "Great art has the power to inspire people across generations.", "vi": "Nghệ thuật vĩ đại có sức mạnh truyền cảm hứng cho mọi người qua nhiều thế hệ."},
                    {"en": "The musician said her travels around the world inspired her best songs.", "vi": "Nhạc sĩ nói những chuyến du lịch vòng quanh thế giới đã truyền cảm hứng cho những ca khúc hay nhất của cô."}]}
    ]
  },
  {
    "id": "ethical-issues",
    "name": "Các Vấn Đề Đạo Đức",
    "emoji": "⚖️",
    "color": "amber",
    "words": [
      {"word": "privacy", "meaning": "quyền riêng tư", "emoji": "🔒", "class": "n",
       "examples": [{"en": "Social media companies have been criticised for invading users' privacy.", "vi": "Các công ty mạng xã hội bị chỉ trích vì xâm phạm quyền riêng tư của người dùng."},
                    {"en": "Everyone has the right to privacy in their personal communications.", "vi": "Mọi người đều có quyền riêng tư trong giao tiếp cá nhân."}]},
      {"word": "fairness", "meaning": "sự công bằng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Fairness in the justice system means equal treatment for all.", "vi": "Sự công bằng trong hệ thống tư pháp có nghĩa là đối xử bình đẳng với tất cả mọi người."},
                    {"en": "Students often complain when they feel grading lacks fairness.", "vi": "Học sinh thường phàn nàn khi cảm thấy việc chấm điểm thiếu công bằng."}]},
      {"word": "responsibility", "meaning": "trách nhiệm", "emoji": "📋", "class": "n",
       "examples": [{"en": "Companies have a social responsibility to treat their workers fairly.", "vi": "Các công ty có trách nhiệm xã hội đối xử công bằng với người lao động."},
                    {"en": "With freedom comes responsibility for the consequences of your choices.", "vi": "Với tự do đến trách nhiệm về hậu quả của những lựa chọn của bạn."}]},
      {"word": "moral", "meaning": "đạo đức", "emoji": "🧭", "class": "adj",
       "examples": [{"en": "It raised serious moral questions about the use of artificial intelligence.", "vi": "Nó đặt ra những câu hỏi đạo đức nghiêm trọng về việc sử dụng trí tuệ nhân tạo."},
                    {"en": "People face moral dilemmas when their values conflict with each other.", "vi": "Mọi người đối mặt với tình huống khó xử về đạo đức khi các giá trị của họ mâu thuẫn nhau."}]},
      {"word": "consequence", "meaning": "hậu quả", "emoji": "💥", "class": "n",
       "examples": [{"en": "Companies must consider the ethical consequences of their business decisions.", "vi": "Các công ty phải xem xét hậu quả đạo đức của các quyết định kinh doanh."},
                    {"en": "Actions without moral consideration can have serious long-term consequences.", "vi": "Hành động thiếu sự xem xét đạo đức có thể có hậu quả nghiêm trọng lâu dài."}]},
      {"word": "impact", "meaning": "tác động", "emoji": "🌊", "class": "n",
       "examples": [{"en": "Technology has a profound impact on how we communicate and work.", "vi": "Công nghệ có tác động sâu sắc đến cách chúng ta giao tiếp và làm việc."},
                    {"en": "The environmental impact of mass production cannot be ignored.", "vi": "Tác động môi trường của sản xuất hàng loạt không thể bị bỏ qua."}]},
      {"word": "justify", "meaning": "biện minh", "emoji": "🗣️", "class": "v",
       "examples": [{"en": "It is difficult to justify using animals in cosmetic testing.", "vi": "Thật khó để biện minh cho việc sử dụng động vật trong thử nghiệm mỹ phẩm."},
                    {"en": "Can higher profits justify cutting employee benefits?", "vi": "Liệu lợi nhuận cao hơn có thể biện minh cho việc cắt giảm phúc lợi nhân viên không?"}]},
      {"word": "controversial", "meaning": "gây tranh cãi", "emoji": "💬", "class": "adj",
       "examples": [{"en": "Capital punishment remains a controversial topic in many societies.", "vi": "Án tử hình vẫn là một chủ đề gây tranh cãi ở nhiều xã hội."},
                    {"en": "The politician's controversial remarks divided public opinion.", "vi": "Những phát ngôn gây tranh cãi của chính trị gia đã chia rẽ ý kiến công chúng."}]},
      {"word": "obligation", "meaning": "nghĩa vụ", "emoji": "📌", "class": "n",
       "examples": [{"en": "Wealthier nations have an obligation to help developing countries.", "vi": "Các quốc gia giàu hơn có nghĩa vụ giúp đỡ các quốc gia đang phát triển."},
                    {"en": "Every citizen has an obligation to obey the law.", "vi": "Mỗi công dân có nghĩa vụ tuân thủ pháp luật."}]},
      {"word": "regulate", "meaning": "điều chỉnh, quản lý", "emoji": "🎛️", "class": "v",
       "examples": [{"en": "Governments must regulate social media to prevent the spread of misinformation.", "vi": "Chính phủ phải quản lý mạng xã hội để ngăn chặn sự lan truyền thông tin sai lệch."},
                    {"en": "The pharmaceutical industry is tightly regulated to protect public health.", "vi": "Ngành dược phẩm được quản lý chặt chẽ để bảo vệ sức khỏe cộng đồng."}]},
      {"word": "protect", "meaning": "bảo vệ", "emoji": "🛡️", "class": "v",
       "examples": [{"en": "Laws exist to protect citizens from exploitation and abuse.", "vi": "Luật pháp tồn tại để bảo vệ công dân khỏi sự bóc lột và lạm dụng."},
                    {"en": "We must act to protect the rights of future generations.", "vi": "Chúng ta phải hành động để bảo vệ quyền của các thế hệ tương lai."}]},
      {"word": "freedom", "meaning": "tự do", "emoji": "🕊️", "class": "n",
       "examples": [{"en": "Freedom of speech is a fundamental right in democratic societies.", "vi": "Tự do ngôn luận là quyền cơ bản trong các xã hội dân chủ."},
                    {"en": "There is ongoing debate about how much freedom individuals should have online.", "vi": "Có cuộc tranh luận liên tục về việc cá nhân nên có bao nhiêu tự do trực tuyến."}]},
      {"word": "dilemma", "meaning": "tình huống khó xử", "emoji": "🤔", "class": "n",
       "examples": [{"en": "The doctor faced an ethical dilemma when two patients needed the same treatment.", "vi": "Bác sĩ đối mặt với tình huống khó xử về đạo đức khi hai bệnh nhân cần cùng một phương pháp điều trị."},
                    {"en": "A classic ethical dilemma is choosing between honesty and kindness.", "vi": "Một tình huống khó xử về đạo đức kinh điển là chọn giữa sự thật thà và lòng tốt."}]},
      {"word": "balance", "meaning": "cân bằng", "emoji": "⚖️", "class": "n",
       "examples": [{"en": "Finding the right balance between security and freedom is a challenge for governments.", "vi": "Tìm sự cân bằng đúng đắn giữa an ninh và tự do là thách thức với chính phủ."},
                    {"en": "Ethics requires balancing individual rights with the good of society.", "vi": "Đạo đức đòi hỏi cân bằng quyền cá nhân với lợi ích của xã hội."}]}
    ]
  }
]

data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'words.json')
with open(data_path, encoding='utf-8') as f:
    data = json.load(f)

# Remove 8 C1 topics from Scholar
before = len(data['scholar']['topics'])
data['scholar']['topics'] = [t for t in data['scholar']['topics'] if t['id'] not in REMOVE_IDS]
after = len(data['scholar']['topics'])
print(f"Scholar: removed {before - after} topics ({before} → {after})")

# Append 8 new B2 topics
data['scholar']['topics'].extend(NEW_SCHOLAR_TOPICS)
final = len(data['scholar']['topics'])
print(f"Scholar: added {len(NEW_SCHOLAR_TOPICS)} new B2 topics ({after} → {final})")

with open(data_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

total_words = sum(len(t['words']) for t in data['scholar']['topics'])
print(f"Scholar final: {final} topics, {total_words} words total")
for t in data['scholar']['topics']:
    print(f"  {t['id']}: {len(t['words'])} words")
